/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.opentrans_2_1;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.lp.server.schema.bmecat_2005.DtCURRENCIES;
import com.lp.server.schema.bmecat_2005.DtMLSTRING;
import com.lp.server.schema.bmecat_2005.TypePARTYID;
import org.w3._2005._05.xmlmime.Base64Binary;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lp.server.schema.opentrans_2_1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FOREIGNCURRENCY_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "FOREIGN_CURRENCY");
    private final static QName _FINALDELIVERYIDREF_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "FINAL_DELIVERY_IDREF");
    private final static QName _PACKAGEORDERUNITQUANTITY_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "PACKAGE_ORDER_UNIT_QUANTITY");
    private final static QName _CREDITAVAILABLE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "CREDIT_AVAILABLE");
    private final static QName _MEANSOFTRANSPORTIDREF_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "MEANS_OF_TRANSPORT_IDREF");
    private final static QName _CARDNUM_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "CARD_NUM");
    private final static QName _QUOTATIONID_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "QUOTATION_ID");
    private final static QName _STOPAUTOMATICPROCESSING_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "STOP_AUTOMATIC_PROCESSING");
    private final static QName _ORDERID_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "ORDER_ID");
    private final static QName _DELIVERYNOTEID_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "DELIVERYNOTE_ID");
    private final static QName _EXCHANGERATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "EXCHANGE_RATE");
    private final static QName _MIMEDATA_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "MIME_DATA");
    private final static QName _AMOUNTOVERCREDITLIMIT_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "AMOUNT_OVER_CREDIT_LIMIT");
    private final static QName _INVOICELISTTYPE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "INVOICELIST_TYPE");
    private final static QName _REPORTUDX_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "REPORT_UDX");
    private final static QName _QUOTATIONDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "QUOTATION_DATE");
    private final static QName _AOCADDITIONALITEMS_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "AOC_ADDITIONAL_ITEMS");
    private final static QName _ORDERCHANGEDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "ORDERCHANGE_DATE");
    private final static QName _REMITTEEIDREF_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "REMITTEE_IDREF");
    private final static QName _CARDAUTHCODE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "CARD_AUTH_CODE");
    private final static QName _SERIALNUMBER_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "SERIAL_NUMBER");
    private final static QName _DEBIT_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "DEBIT");
    private final static QName _PARTYROLE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "PARTY_ROLE");
    private final static QName _DELIVERYIDREF_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "DELIVERY_IDREF");
    private final static QName _DELIVERERIDREF_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "DELIVERER_IDREF");
    private final static QName _ADJUSTEDSUMMARYAMOUNT_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "ADJUSTED_SUMMARY_AMOUNT");
    private final static QName _ALTCUSTOMERORDERID_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "ALT_CUSTOMER_ORDER_ID");
    private final static QName _POSTDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "POST_DATE");
    private final static QName _AOCPERCENTAGEFACTOR_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "AOC_PERCENTAGE_FACTOR");
    private final static QName _ADJUSTMENTREASONDESCR_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "ADJUSTMENT_REASON_DESCR");
    private final static QName _DELIVERYNOTEDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "DELIVERYNOTE_DATE");
    private final static QName _INVOICERECIPIENTIDREF_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "INVOICE_RECIPIENT_IDREF");
    private final static QName _HOLDER_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "HOLDER");
    private final static QName _LINEITEMID_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "LINE_ITEM_ID");
    private final static QName _CONFIGCODEFIX_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "CONFIG_CODE_FIX");
    private final static QName _TAXAMOUNT_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "TAX_AMOUNT");
    private final static QName _DELIVERYSTARTDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "DELIVERY_START_DATE");
    private final static QName _DISPATCHNOTIFICATIONID_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "DISPATCHNOTIFICATION_ID");
    private final static QName _INVOICETYPE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "INVOICE_TYPE");
    private final static QName _FOREIGNAMOUNT_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "FOREIGN_AMOUNT");
    private final static QName _SIGNATUREINORIGINAL_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "SIGNATURE_IN_ORIGINAL");
    private final static QName _DELIVERYENDDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "DELIVERY_END_DATE");
    private final static QName _REWARDSSUMMARY_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "REWARDS_SUMMARY");
    private final static QName _BANKCOUNTRY_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "BANK_COUNTRY");
    private final static QName _NETVALUEGOODS_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "NET_VALUE_GOODS");
    private final static QName _CARDHOLDERNAME_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "CARD_HOLDER_NAME");
    private final static QName _ACCOUNTINGPERIODENDDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "ACCOUNTING_PERIOD_END_DATE");
    private final static QName _ORDERDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "ORDER_DATE");
    private final static QName _PARTIALSHIPMENTALLOWED_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "PARTIAL_SHIPMENT_ALLOWED");
    private final static QName _PACKAGETYPE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "PACKAGE_TYPE");
    private final static QName _INVOICELISTDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "INVOICELIST_DATE");
    private final static QName _RECEIPTACKNOWLEDGEMENTID_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "RECEIPTACKNOWLEDGEMENT_ID");
    private final static QName _REWARDSPOINTS_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "REWARDS_POINTS");
    private final static QName _FILENAME_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "FILE_NAME");
    private final static QName _LOTNUMBER_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "LOT_NUMBER");
    private final static QName _PRICEUNITVALUE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "PRICE_UNIT_VALUE");
    private final static QName _ALLOWORCHARGEBASE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "ALLOW_OR_CHARGE_BASE");
    private final static QName _ADJUSTMENTREASONCODE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "ADJUSTMENT_REASON_CODE");
    private final static QName _PARTIALSHIPMENT_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "PARTIAL_SHIPMENT");
    private final static QName _ALLOWORCHARGESTOTALAMOUNT_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "ALLOW_OR_CHARGES_TOTAL_AMOUNT");
    private final static QName _ORDERRESPONSEDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "ORDERRESPONSE_DATE");
    private final static QName _DAYS_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "DAYS");
    private final static QName _DOCUMENTRECIPIENTIDREF_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "DOCUMENT_RECIPIENT_IDREF");
    private final static QName _BANKNAME_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "BANK_NAME");
    private final static QName _VERIFICATIONRESULT_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "VERIFICATION_RESULT");
    private final static QName _QUANTITY_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "QUANTITY");
    private final static QName _INVOICEISSUERIDREF_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "INVOICE_ISSUER_IDREF");
    private final static QName _GENERATORINFO_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "GENERATOR_INFO");
    private final static QName _TOTALTAXAMOUNT_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "TOTAL_TAX_AMOUNT");
    private final static QName _XMLFORMAT_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "XML_FORMAT");
    private final static QName _OPENINGBALANCE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "OPENING_BALANCE");
    private final static QName _NETVALUEEXTRA_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "NET_VALUE_EXTRA");
    private final static QName _CASH_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "CASH");
    private final static QName _INVOICELISTID_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "INVOICELIST_ID");
    private final static QName _REMITTANCEADVICEDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "REMITTANCEADVICE_DATE");
    private final static QName _INVOICEID_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "INVOICE_ID");
    private final static QName _ALLOWORCHARGESEQUENCE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "ALLOW_OR_CHARGE_SEQUENCE");
    private final static QName _DISCOUNTFACTOR_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "DISCOUNT_FACTOR");
    private final static QName _REMITTANCEADVICEID_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "REMITTANCEADVICE_ID");
    private final static QName _PAYERIDREF_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "PAYER_IDREF");
    private final static QName _DOCUMENTISSUERIDREF_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "DOCUMENT_ISSUER_IDREF");
    private final static QName _RECEIPTDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "RECEIPT_DATE");
    private final static QName _CUSTOMERIDREF_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "CUSTOMER_IDREF");
    private final static QName _FILESIZE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "FILE_SIZE");
    private final static QName _CREDITLIMIT_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "CREDIT_LIMIT");
    private final static QName _CLOSINGBALANCE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "CLOSING_BALANCE");
    private final static QName _REASONFORTRANSFER_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "REASON_FOR_TRANSFER");
    private final static QName _RFQDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "RFQ_DATE");
    private final static QName _TOTALITEMNUM_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "TOTAL_ITEM_NUM");
    private final static QName _CHECK_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "CHECK");
    private final static QName _CENTRALREGULATION_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "CENTRAL_REGULATION");
    private final static QName _TAXNUMBER_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "TAX_NUMBER");
    private final static QName _ITEMUDX_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "ITEM_UDX");
    private final static QName _ALLOWORCHARGETYPE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "ALLOW_OR_CHARGE_TYPE");
    private final static QName _GENERATIONDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "GENERATION_DATE");
    private final static QName _INVOICEDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "INVOICE_DATE");
    private final static QName _SHIPMENTID_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "SHIPMENT_ID");
    private final static QName _INVOICECOVERAGE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "INVOICE_COVERAGE");
    private final static QName _DELIVERYCOMPLETED_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "DELIVERY_COMPLETED");
    private final static QName _RFQID_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "RFQ_ID");
    private final static QName _PACKAGEQUANTITY_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "PACKAGE_QUANTITY");
    private final static QName _ACCOUNTINGPERIODSTARTDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "ACCOUNTING_PERIOD_START_DATE");
    private final static QName _HEADERUDX_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "HEADER_UDX");
    private final static QName _CARDEXPIRATIONDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "CARD_EXPIRATION_DATE");
    private final static QName _TOTALAMOUNT_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "TOTAL_AMOUNT");
    private final static QName _PRICELINEAMOUNT_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "PRICE_LINE_AMOUNT");
    private final static QName _TERMSANDCONDITIONS_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "TERMS_AND_CONDITIONS");
    private final static QName _CARDREFNUM_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "CARD_REF_NUM");
    private final static QName _ALLOWORCHARGEAMOUNT_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "ALLOW_OR_CHARGE_AMOUNT");
    private final static QName _TAXBASE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "TAX_BASE");
    private final static QName _SUPPLIERORDERITEMID_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "SUPPLIER_ORDER_ITEM_ID");
    private final static QName _DIRECTDEBIT_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "DIRECT_DEBIT");
    private final static QName _DISPATCHNOTIFICATIONDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "DISPATCHNOTIFICATION_DATE");
    private final static QName _ORIGINALSUMMARYAMOUNT_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "ORIGINAL_SUMMARY_AMOUNT");
    private final static QName _FINANCECHARGE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "FINANCE_CHARGE");
    private final static QName _VALUEDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "VALUE_DATE");
    private final static QName _VERIFICATIONSUCCESS_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "VERIFICATION_SUCCESS");
    private final static QName _RESULTDESCR_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "RESULT_DESCR");
    private final static QName _RECEIPTACKNOWLEDGEMENTDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "RECEIPTACKNOWLEDGEMENT_DATE");
    private final static QName _SUPPLIERORDERID_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "SUPPLIER_ORDER_ID");
    private final static QName _PAYMENTDATE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "PAYMENT_DATE");
    private final static QName _VERIFICATIONPARTYIDREF_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "VERIFICATION_PARTY_IDREF");
    private final static QName _AOCMONETARYAMOUNT_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "AOC_MONETARY_AMOUNT");
    private final static QName _REMITTANCEADVICETYPE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "REMITTANCEADVICE_TYPE");
    private final static QName _ORDERCHANGESEQUENCEID_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "ORDERCHANGE_SEQUENCE_ID");
    private final static QName _TRACKINGTRACINGURL_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "TRACKING_TRACING_URL");
    private final static QName _RESULTCODE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "RESULT_CODE");
    private final static QName _MIMEPURPOSE_QNAME = new QName("http://www.opentrans.org/XMLSchema/2.1", "MIME_PURPOSE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lp.server.schema.opentrans_2_1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OT2INVOICEORIGINAL }
     * 
     */
    public OT2INVOICEORIGINAL createOT2INVOICEORIGINAL() {
        return new OT2INVOICEORIGINAL();
    }

    /**
     * Create an instance of {@link OT2RECEIPTACKNOWLEDGEMENTITEM }
     * 
     */
    public OT2RECEIPTACKNOWLEDGEMENTITEM createOT2RECEIPTACKNOWLEDGEMENTITEM() {
        return new OT2RECEIPTACKNOWLEDGEMENTITEM();
    }

    /**
     * Create an instance of {@link OT2ORIGINALINVOICESUMMARY }
     * 
     */
    public OT2ORIGINALINVOICESUMMARY createOT2ORIGINALINVOICESUMMARY() {
        return new OT2ORIGINALINVOICESUMMARY();
    }

    /**
     * Create an instance of {@link OT2DISPATCHNOTIFICATION }
     * 
     */
    public OT2DISPATCHNOTIFICATION createOT2DISPATCHNOTIFICATION() {
        return new OT2DISPATCHNOTIFICATION();
    }

    /**
     * Create an instance of {@link OT2FINALDELIVERYPARTY }
     * 
     */
    public OT2FINALDELIVERYPARTY createOT2FINALDELIVERYPARTY() {
        return new OT2FINALDELIVERYPARTY();
    }

    /**
     * Create an instance of {@link OT2XMLSIGNATURE }
     * 
     */
    public OT2XMLSIGNATURE createOT2XMLSIGNATURE() {
        return new OT2XMLSIGNATURE();
    }

    /**
     * Create an instance of {@link OT2RECEIPTACKNOWLEDGEMENT }
     * 
     */
    public OT2RECEIPTACKNOWLEDGEMENT createOT2RECEIPTACKNOWLEDGEMENT() {
        return new OT2RECEIPTACKNOWLEDGEMENT();
    }

    /**
     * Create an instance of {@link OT2PAYMENT }
     * 
     */
    public OT2PAYMENT createOT2PAYMENT() {
        return new OT2PAYMENT();
    }

    /**
     * Create an instance of {@link OT2INVOICEPARTY }
     * 
     */
    public OT2INVOICEPARTY createOT2INVOICEPARTY() {
        return new OT2INVOICEPARTY();
    }

    /**
     * Create an instance of {@link OT2QUOTATIONITEMLIST }
     * 
     */
    public OT2QUOTATIONITEMLIST createOT2QUOTATIONITEMLIST() {
        return new OT2QUOTATIONITEMLIST();
    }

    /**
     * Create an instance of {@link OT2DELIVERYDATE }
     * 
     */
    public OT2DELIVERYDATE createOT2DELIVERYDATE() {
        return new OT2DELIVERYDATE();
    }

    /**
     * Create an instance of {@link OT2DELIVERYREFERENCE }
     * 
     */
    public OT2DELIVERYREFERENCE createOT2DELIVERYREFERENCE() {
        return new OT2DELIVERYREFERENCE();
    }

    /**
     * Create an instance of {@link OT2VERIFICATION }
     * 
     */
    public OT2VERIFICATION createOT2VERIFICATION() {
        return new OT2VERIFICATION();
    }

    /**
     * Create an instance of {@link OT2ORDERSUMMARY }
     * 
     */
    public OT2ORDERSUMMARY createOT2ORDERSUMMARY() {
        return new OT2ORDERSUMMARY();
    }

    /**
     * Create an instance of {@link OT2RFQITEM }
     * 
     */
    public OT2RFQITEM createOT2RFQITEM() {
        return new OT2RFQITEM();
    }

    /**
     * Create an instance of {@link OT2REMITTANCEADVICE }
     * 
     */
    public OT2REMITTANCEADVICE createOT2REMITTANCEADVICE() {
        return new OT2REMITTANCEADVICE();
    }

    /**
     * Create an instance of {@link OT2LOGISTICDETAILSINFO }
     * 
     */
    public OT2LOGISTICDETAILSINFO createOT2LOGISTICDETAILSINFO() {
        return new OT2LOGISTICDETAILSINFO();
    }

    /**
     * Create an instance of {@link OT2ORDER }
     * 
     */
    public OT2ORDER createOT2ORDER() {
        return new OT2ORDER();
    }

    /**
     * Create an instance of {@link OT2VERIFICATIONATTACHMENT }
     * 
     */
    public OT2VERIFICATIONATTACHMENT createOT2VERIFICATIONATTACHMENT() {
        return new OT2VERIFICATIONATTACHMENT();
    }

    /**
     * Create an instance of {@link OT2ORDERPARTIESREFERENCE }
     * 
     */
    public OT2ORDERPARTIESREFERENCE createOT2ORDERPARTIESREFERENCE() {
        return new OT2ORDERPARTIESREFERENCE();
    }

    /**
     * Create an instance of {@link OT2ORDERRESPONSEINFO }
     * 
     */
    public OT2ORDERRESPONSEINFO createOT2ORDERRESPONSEINFO() {
        return new OT2ORDERRESPONSEINFO();
    }

    /**
     * Create an instance of {@link OT2CONTACTDETAILS }
     * 
     */
    public OT2CONTACTDETAILS createOT2CONTACTDETAILS() {
        return new OT2CONTACTDETAILS();
    }

    /**
     * Create an instance of {@link OT2CUSTOMERORDERREFERENCE }
     * 
     */
    public OT2CUSTOMERORDERREFERENCE createOT2CUSTOMERORDERREFERENCE() {
        return new OT2CUSTOMERORDERREFERENCE();
    }

    /**
     * Create an instance of {@link OT2ALLOWORCHARGESFIX }
     * 
     */
    public OT2ALLOWORCHARGESFIX createOT2ALLOWORCHARGESFIX() {
        return new OT2ALLOWORCHARGESFIX();
    }

    /**
     * Create an instance of {@link OT2SHIPMENTPARTIES }
     * 
     */
    public OT2SHIPMENTPARTIES createOT2SHIPMENTPARTIES() {
        return new OT2SHIPMENTPARTIES();
    }

    /**
     * Create an instance of {@link OT2REMITTANCEADVICESUMMARY }
     * 
     */
    public OT2REMITTANCEADVICESUMMARY createOT2REMITTANCEADVICESUMMARY() {
        return new OT2REMITTANCEADVICESUMMARY();
    }

    /**
     * Create an instance of {@link OT2PACKAGEID }
     * 
     */
    public OT2PACKAGEID createOT2PACKAGEID() {
        return new OT2PACKAGEID();
    }

    /**
     * Create an instance of {@link OT2ADDRESS }
     * 
     */
    public OT2ADDRESS createOT2ADDRESS() {
        return new OT2ADDRESS();
    }

    /**
     * Create an instance of {@link OT2TRANSPORTPARTY }
     * 
     */
    public OT2TRANSPORTPARTY createOT2TRANSPORTPARTY() {
        return new OT2TRANSPORTPARTY();
    }

    /**
     * Create an instance of {@link OT2MIMEINFO }
     * 
     */
    public OT2MIMEINFO createOT2MIMEINFO() {
        return new OT2MIMEINFO();
    }

    /**
     * Create an instance of {@link OT2REMITTANCEADVICEHEADER }
     * 
     */
    public OT2REMITTANCEADVICEHEADER createOT2REMITTANCEADVICEHEADER() {
        return new OT2REMITTANCEADVICEHEADER();
    }

    /**
     * Create an instance of {@link OT2PRODUCTID }
     * 
     */
    public OT2PRODUCTID createOT2PRODUCTID() {
        return new OT2PRODUCTID();
    }

    /**
     * Create an instance of {@link OT2ADJUSTEDINVOICESUMMARY }
     * 
     */
    public OT2ADJUSTEDINVOICESUMMARY createOT2ADJUSTEDINVOICESUMMARY() {
        return new OT2ADJUSTEDINVOICESUMMARY();
    }

    /**
     * Create an instance of {@link TypeMLSTRING00050 }
     * 
     */
    public TypeMLSTRING00050 createTypeMLSTRING00050() {
        return new TypeMLSTRING00050();
    }

    /**
     * Create an instance of {@link OT2ORDERPARTIES }
     * 
     */
    public OT2ORDERPARTIES createOT2ORDERPARTIES() {
        return new OT2ORDERPARTIES();
    }

    /**
     * Create an instance of {@link OT2ORDERHEADER }
     * 
     */
    public OT2ORDERHEADER createOT2ORDERHEADER() {
        return new OT2ORDERHEADER();
    }

    /**
     * Create an instance of {@link OT2VERIFICATIONXMLREPORT }
     * 
     */
    public OT2VERIFICATIONXMLREPORT createOT2VERIFICATIONXMLREPORT() {
        return new OT2VERIFICATIONXMLREPORT();
    }

    /**
     * Create an instance of {@link OT2INVOICELISTITEMLIST }
     * 
     */
    public OT2INVOICELISTITEMLIST createOT2INVOICELISTITEMLIST() {
        return new OT2INVOICELISTITEMLIST();
    }

    /**
     * Create an instance of {@link OT2QUOTATIONHEADER }
     * 
     */
    public OT2QUOTATIONHEADER createOT2QUOTATIONHEADER() {
        return new OT2QUOTATIONHEADER();
    }

    /**
     * Create an instance of {@link OT2DISPATCHNOTIFICATIONSUMMARY }
     * 
     */
    public OT2DISPATCHNOTIFICATIONSUMMARY createOT2DISPATCHNOTIFICATIONSUMMARY() {
        return new OT2DISPATCHNOTIFICATIONSUMMARY();
    }

    /**
     * Create an instance of {@link OT2SIGNATUREANDVERIFICATION }
     * 
     */
    public OT2SIGNATUREANDVERIFICATION createOT2SIGNATUREANDVERIFICATION() {
        return new OT2SIGNATUREANDVERIFICATION();
    }

    /**
     * Create an instance of {@link OT2CATALOGREFERENCE }
     * 
     */
    public OT2CATALOGREFERENCE createOT2CATALOGREFERENCE() {
        return new OT2CATALOGREFERENCE();
    }

    /**
     * Create an instance of {@link OT2SUPPLIERORDERREFERENCE }
     * 
     */
    public OT2SUPPLIERORDERREFERENCE createOT2SUPPLIERORDERREFERENCE() {
        return new OT2SUPPLIERORDERREFERENCE();
    }

    /**
     * Create an instance of {@link UdxREPORT }
     * 
     */
    public UdxREPORT createUdxREPORT() {
        return new UdxREPORT();
    }

    /**
     * Create an instance of {@link OT2INVOICEREFERENCE }
     * 
     */
    public OT2INVOICEREFERENCE createOT2INVOICEREFERENCE() {
        return new OT2INVOICEREFERENCE();
    }

    /**
     * Create an instance of {@link OT2MIME }
     * 
     */
    public OT2MIME createOT2MIME() {
        return new OT2MIME();
    }

    /**
     * Create an instance of {@link OT2BUYERPARTY }
     * 
     */
    public OT2BUYERPARTY createOT2BUYERPARTY() {
        return new OT2BUYERPARTY();
    }

    /**
     * Create an instance of {@link OT2REWARDS }
     * 
     */
    public OT2REWARDS createOT2REWARDS() {
        return new OT2REWARDS();
    }

    /**
     * Create an instance of {@link OT2MANUFACTURERINFO }
     * 
     */
    public OT2MANUFACTURERINFO createOT2MANUFACTURERINFO() {
        return new OT2MANUFACTURERINFO();
    }

    /**
     * Create an instance of {@link OT2PRODUCTPRICEDETAILS }
     * 
     */
    public OT2PRODUCTPRICEDETAILS createOT2PRODUCTPRICEDETAILS() {
        return new OT2PRODUCTPRICEDETAILS();
    }

    /**
     * Create an instance of {@link OT2REWARDSDESCR }
     * 
     */
    public OT2REWARDSDESCR createOT2REWARDSDESCR() {
        return new OT2REWARDSDESCR();
    }

    /**
     * Create an instance of {@link OT2INVOICECORRECTION }
     * 
     */
    public OT2INVOICECORRECTION createOT2INVOICECORRECTION() {
        return new OT2INVOICECORRECTION();
    }

    /**
     * Create an instance of {@link OT2PACKAGEDIMENSIONS }
     * 
     */
    public OT2PACKAGEDIMENSIONS createOT2PACKAGEDIMENSIONS() {
        return new OT2PACKAGEDIMENSIONS();
    }

    /**
     * Create an instance of {@link OT2INVOICEINFO }
     * 
     */
    public OT2INVOICEINFO createOT2INVOICEINFO() {
        return new OT2INVOICEINFO();
    }

    /**
     * Create an instance of {@link OT2TAXDETAILSFIX }
     * 
     */
    public OT2TAXDETAILSFIX createOT2TAXDETAILSFIX() {
        return new OT2TAXDETAILSFIX();
    }

    /**
     * Create an instance of {@link OT2REMITTANCEADVICEINFO }
     * 
     */
    public OT2REMITTANCEADVICEINFO createOT2REMITTANCEADVICEINFO() {
        return new OT2REMITTANCEADVICEINFO();
    }

    /**
     * Create an instance of {@link OT2DISPATCHNOTIFICATIONITEMLIST }
     * 
     */
    public OT2DISPATCHNOTIFICATIONITEMLIST createOT2DISPATCHNOTIFICATIONITEMLIST() {
        return new OT2DISPATCHNOTIFICATIONITEMLIST();
    }

    /**
     * Create an instance of {@link OT2AGREEMENTDESCR }
     * 
     */
    public OT2AGREEMENTDESCR createOT2AGREEMENTDESCR() {
        return new OT2AGREEMENTDESCR();
    }

    /**
     * Create an instance of {@link OT2SUBPACKAGES }
     * 
     */
    public OT2SUBPACKAGES createOT2SUBPACKAGES() {
        return new OT2SUBPACKAGES();
    }

    /**
     * Create an instance of {@link OT2ORDERCHANGEHEADER }
     * 
     */
    public OT2ORDERCHANGEHEADER createOT2ORDERCHANGEHEADER() {
        return new OT2ORDERCHANGEHEADER();
    }

    /**
     * Create an instance of {@link OT2INVOICELISTINFO }
     * 
     */
    public OT2INVOICELISTINFO createOT2INVOICELISTINFO() {
        return new OT2INVOICELISTINFO();
    }

    /**
     * Create an instance of {@link OT2PARTIALDELIVERY }
     * 
     */
    public OT2PARTIALDELIVERY createOT2PARTIALDELIVERY() {
        return new OT2PARTIALDELIVERY();
    }

    /**
     * Create an instance of {@link OT2FEATURE }
     * 
     */
    public OT2FEATURE createOT2FEATURE() {
        return new OT2FEATURE();
    }

    /**
     * Create an instance of {@link OT2FILEHASHVALUE }
     * 
     */
    public OT2FILEHASHVALUE createOT2FILEHASHVALUE() {
        return new OT2FILEHASHVALUE();
    }

    /**
     * Create an instance of {@link OT2PACKAGEDESCR }
     * 
     */
    public OT2PACKAGEDESCR createOT2PACKAGEDESCR() {
        return new OT2PACKAGEDESCR();
    }

    /**
     * Create an instance of {@link OT2PARTIES }
     * 
     */
    public OT2PARTIES createOT2PARTIES() {
        return new OT2PARTIES();
    }

    /**
     * Create an instance of {@link UdxITEM }
     * 
     */
    public UdxITEM createUdxITEM() {
        return new UdxITEM();
    }

    /**
     * Create an instance of {@link OT2ALLOWORCHARGENAME }
     * 
     */
    public OT2ALLOWORCHARGENAME createOT2ALLOWORCHARGENAME() {
        return new OT2ALLOWORCHARGENAME();
    }

    /**
     * Create an instance of {@link OT2INVOICE }
     * 
     */
    public OT2INVOICE createOT2INVOICE() {
        return new OT2INVOICE();
    }

    /**
     * Create an instance of {@link OT2ORDERCHANGESUMMARY }
     * 
     */
    public OT2ORDERCHANGESUMMARY createOT2ORDERCHANGESUMMARY() {
        return new OT2ORDERCHANGESUMMARY();
    }

    /**
     * Create an instance of {@link OT2ILINVOICELIST }
     * 
     */
    public OT2ILINVOICELIST createOT2ILINVOICELIST() {
        return new OT2ILINVOICELIST();
    }

    /**
     * Create an instance of {@link OT2DISPATCHNOTIFICATIONINFO }
     * 
     */
    public OT2DISPATCHNOTIFICATIONINFO createOT2DISPATCHNOTIFICATIONINFO() {
        return new OT2DISPATCHNOTIFICATIONINFO();
    }

    /**
     * Create an instance of {@link OT2QUOTATIONSUMMARY }
     * 
     */
    public OT2QUOTATIONSUMMARY createOT2QUOTATIONSUMMARY() {
        return new OT2QUOTATIONSUMMARY();
    }

    /**
     * Create an instance of {@link OT2QUOTATIONINFO }
     * 
     */
    public OT2QUOTATIONINFO createOT2QUOTATIONINFO() {
        return new OT2QUOTATIONINFO();
    }

    /**
     * Create an instance of {@link OT2INVOICEHEADER }
     * 
     */
    public OT2INVOICEHEADER createOT2INVOICEHEADER() {
        return new OT2INVOICEHEADER();
    }

    /**
     * Create an instance of {@link OT2REMARKS }
     * 
     */
    public OT2REMARKS createOT2REMARKS() {
        return new OT2REMARKS();
    }

    /**
     * Create an instance of {@link OT2INVOICELISTITEM }
     * 
     */
    public OT2INVOICELISTITEM createOT2INVOICELISTITEM() {
        return new OT2INVOICELISTITEM();
    }

    /**
     * Create an instance of {@link OT2CARD }
     * 
     */
    public OT2CARD createOT2CARD() {
        return new OT2CARD();
    }

    /**
     * Create an instance of {@link OT2QUOTATIONITEM }
     * 
     */
    public OT2QUOTATIONITEM createOT2QUOTATIONITEM() {
        return new OT2QUOTATIONITEM();
    }

    /**
     * Create an instance of {@link OT2SOURCINGINFO }
     * 
     */
    public OT2SOURCINGINFO createOT2SOURCINGINFO() {
        return new OT2SOURCINGINFO();
    }

    /**
     * Create an instance of {@link OT2PRODUCTPRICEFIX }
     * 
     */
    public OT2PRODUCTPRICEFIX createOT2PRODUCTPRICEFIX() {
        return new OT2PRODUCTPRICEFIX();
    }

    /**
     * Create an instance of {@link OT2ORDERRESPONSEITEM }
     * 
     */
    public OT2ORDERRESPONSEITEM createOT2ORDERRESPONSEITEM() {
        return new OT2ORDERRESPONSEITEM();
    }

    /**
     * Create an instance of {@link OT2INVOICEITEMLIST }
     * 
     */
    public OT2INVOICEITEMLIST createOT2INVOICEITEMLIST() {
        return new OT2INVOICEITEMLIST();
    }

    /**
     * Create an instance of {@link OT2CONTACTROLE }
     * 
     */
    public OT2CONTACTROLE createOT2CONTACTROLE() {
        return new OT2CONTACTROLE();
    }

    /**
     * Create an instance of {@link OT2DOCEXCHANGEPARTIESREFERENCE }
     * 
     */
    public OT2DOCEXCHANGEPARTIESREFERENCE createOT2DOCEXCHANGEPARTIESREFERENCE() {
        return new OT2DOCEXCHANGEPARTIESREFERENCE();
    }

    /**
     * Create an instance of {@link OT2INVOICESUMMARY }
     * 
     */
    public OT2INVOICESUMMARY createOT2INVOICESUMMARY() {
        return new OT2INVOICESUMMARY();
    }

    /**
     * Create an instance of {@link OT2ORDERITEM }
     * 
     */
    public OT2ORDERITEM createOT2ORDERITEM() {
        return new OT2ORDERITEM();
    }

    /**
     * Create an instance of {@link OT2DELIVERYPARTY }
     * 
     */
    public OT2DELIVERYPARTY createOT2DELIVERYPARTY() {
        return new OT2DELIVERYPARTY();
    }

    /**
     * Create an instance of {@link OT2ORDERDESCR }
     * 
     */
    public OT2ORDERDESCR createOT2ORDERDESCR() {
        return new OT2ORDERDESCR();
    }

    /**
     * Create an instance of {@link OT2PARTIALDELIVERYLIST }
     * 
     */
    public OT2PARTIALDELIVERYLIST createOT2PARTIALDELIVERYLIST() {
        return new OT2PARTIALDELIVERYLIST();
    }

    /**
     * Create an instance of {@link OT2INVOICEDESCR }
     * 
     */
    public OT2INVOICEDESCR createOT2INVOICEDESCR() {
        return new OT2INVOICEDESCR();
    }

    /**
     * Create an instance of {@link OT2INVOICELISTHEADER }
     * 
     */
    public OT2INVOICELISTHEADER createOT2INVOICELISTHEADER() {
        return new OT2INVOICELISTHEADER();
    }

    /**
     * Create an instance of {@link OT2VERIFICATIONREPORT }
     * 
     */
    public OT2VERIFICATIONREPORT createOT2VERIFICATIONREPORT() {
        return new OT2VERIFICATIONREPORT();
    }

    /**
     * Create an instance of {@link OT2ORDERRESPONSEHEADER }
     * 
     */
    public OT2ORDERRESPONSEHEADER createOT2ORDERRESPONSEHEADER() {
        return new OT2ORDERRESPONSEHEADER();
    }

    /**
     * Create an instance of {@link OT2ORDERREFERENCE }
     * 
     */
    public OT2ORDERREFERENCE createOT2ORDERREFERENCE() {
        return new OT2ORDERREFERENCE();
    }

    /**
     * Create an instance of {@link OT2EBILLING }
     * 
     */
    public OT2EBILLING createOT2EBILLING() {
        return new OT2EBILLING();
    }

    /**
     * Create an instance of {@link OT2RFQHEADER }
     * 
     */
    public OT2RFQHEADER createOT2RFQHEADER() {
        return new OT2RFQHEADER();
    }

    /**
     * Create an instance of {@link TypeMLSTRING64000 }
     * 
     */
    public TypeMLSTRING64000 createTypeMLSTRING64000() {
        return new TypeMLSTRING64000();
    }

    /**
     * Create an instance of {@link OT2QUOTATION }
     * 
     */
    public OT2QUOTATION createOT2QUOTATION() {
        return new OT2QUOTATION();
    }

    /**
     * Create an instance of {@link OT2CARDTYPE }
     * 
     */
    public OT2CARDTYPE createOT2CARDTYPE() {
        return new OT2CARDTYPE();
    }

    /**
     * Create an instance of {@link OT2PRODUCTFEATURES }
     * 
     */
    public OT2PRODUCTFEATURES createOT2PRODUCTFEATURES() {
        return new OT2PRODUCTFEATURES();
    }

    /**
     * Create an instance of {@link OT2SHIPMENTPARTIESREFERENCE }
     * 
     */
    public OT2SHIPMENTPARTIESREFERENCE createOT2SHIPMENTPARTIESREFERENCE() {
        return new OT2SHIPMENTPARTIESREFERENCE();
    }

    /**
     * Create an instance of {@link OT2VERIFICATIONPROTOCOL }
     * 
     */
    public OT2VERIFICATIONPROTOCOL createOT2VERIFICATIONPROTOCOL() {
        return new OT2VERIFICATIONPROTOCOL();
    }

    /**
     * Create an instance of {@link OT2PACKAGE }
     * 
     */
    public OT2PACKAGE createOT2PACKAGE() {
        return new OT2PACKAGE();
    }

    /**
     * Create an instance of {@link OT2RFQITEMLIST }
     * 
     */
    public OT2RFQITEMLIST createOT2RFQITEMLIST() {
        return new OT2RFQITEMLIST();
    }

    /**
     * Create an instance of {@link OT2ACCOUNTINGPERIOD }
     * 
     */
    public OT2ACCOUNTINGPERIOD createOT2ACCOUNTINGPERIOD() {
        return new OT2ACCOUNTINGPERIOD();
    }

    /**
     * Create an instance of {@link OT2OPENTRANS }
     * 
     */
    public OT2OPENTRANS createOT2OPENTRANS() {
        return new OT2OPENTRANS();
    }

    /**
     * Create an instance of {@link OT2ORDERRESPONSE }
     * 
     */
    public OT2ORDERRESPONSE createOT2ORDERRESPONSE() {
        return new OT2ORDERRESPONSE();
    }

    /**
     * Create an instance of {@link OT2ORDERCHANGEINFO }
     * 
     */
    public OT2ORDERCHANGEINFO createOT2ORDERCHANGEINFO() {
        return new OT2ORDERCHANGEINFO();
    }

    /**
     * Create an instance of {@link OT2ORDERCHANGEITEMLIST }
     * 
     */
    public OT2ORDERCHANGEITEMLIST createOT2ORDERCHANGEITEMLIST() {
        return new OT2ORDERCHANGEITEMLIST();
    }

    /**
     * Create an instance of {@link OT2RAINVOICELISTITEM }
     * 
     */
    public OT2RAINVOICELISTITEM createOT2RAINVOICELISTITEM() {
        return new OT2RAINVOICELISTITEM();
    }

    /**
     * Create an instance of {@link OT2ORDERHISTORY }
     * 
     */
    public OT2ORDERHISTORY createOT2ORDERHISTORY() {
        return new OT2ORDERHISTORY();
    }

    /**
     * Create an instance of {@link OT2INVOICEADJUSTMENT }
     * 
     */
    public OT2INVOICEADJUSTMENT createOT2INVOICEADJUSTMENT() {
        return new OT2INVOICEADJUSTMENT();
    }

    /**
     * Create an instance of {@link OT2BANKCODE }
     * 
     */
    public OT2BANKCODE createOT2BANKCODE() {
        return new OT2BANKCODE();
    }

    /**
     * Create an instance of {@link OT2PACKAGEINFO }
     * 
     */
    public OT2PACKAGEINFO createOT2PACKAGEINFO() {
        return new OT2PACKAGEINFO();
    }

    /**
     * Create an instance of {@link OT2RECEIPTACKNOWLEDGEMENTITEMLIST }
     * 
     */
    public OT2RECEIPTACKNOWLEDGEMENTITEMLIST createOT2RECEIPTACKNOWLEDGEMENTITEMLIST() {
        return new OT2RECEIPTACKNOWLEDGEMENTITEMLIST();
    }

    /**
     * Create an instance of {@link OT2PAYMENTTERMS }
     * 
     */
    public OT2PAYMENTTERMS createOT2PAYMENTTERMS() {
        return new OT2PAYMENTTERMS();
    }

    /**
     * Create an instance of {@link OT2ORDERRESPONSESUMMARY }
     * 
     */
    public OT2ORDERRESPONSESUMMARY createOT2ORDERRESPONSESUMMARY() {
        return new OT2ORDERRESPONSESUMMARY();
    }

    /**
     * Create an instance of {@link OT2BANKACCOUNT }
     * 
     */
    public OT2BANKACCOUNT createOT2BANKACCOUNT() {
        return new OT2BANKACCOUNT();
    }

    /**
     * Create an instance of {@link OT2SIGNATURE }
     * 
     */
    public OT2SIGNATURE createOT2SIGNATURE() {
        return new OT2SIGNATURE();
    }

    /**
     * Create an instance of {@link OT2INVOICEITEM }
     * 
     */
    public OT2INVOICEITEM createOT2INVOICEITEM() {
        return new OT2INVOICEITEM();
    }

    /**
     * Create an instance of {@link OT2PRODUCTCOMPONENT }
     * 
     */
    public OT2PRODUCTCOMPONENT createOT2PRODUCTCOMPONENT() {
        return new OT2PRODUCTCOMPONENT();
    }

    /**
     * Create an instance of {@link OT2DISPATCHNOTIFICATIONHEADER }
     * 
     */
    public OT2DISPATCHNOTIFICATIONHEADER createOT2DISPATCHNOTIFICATIONHEADER() {
        return new OT2DISPATCHNOTIFICATIONHEADER();
    }

    /**
     * Create an instance of {@link OT2TOTALTAX }
     * 
     */
    public OT2TOTALTAX createOT2TOTALTAX() {
        return new OT2TOTALTAX();
    }

    /**
     * Create an instance of {@link OT2REMITTANCEADVICEITEMLIST }
     * 
     */
    public OT2REMITTANCEADVICEITEMLIST createOT2REMITTANCEADVICEITEMLIST() {
        return new OT2REMITTANCEADVICEITEMLIST();
    }

    /**
     * Create an instance of {@link OT2TIMEFORPAYMENT }
     * 
     */
    public OT2TIMEFORPAYMENT createOT2TIMEFORPAYMENT() {
        return new OT2TIMEFORPAYMENT();
    }

    /**
     * Create an instance of {@link OT2ILINVOICELISTITEM }
     * 
     */
    public OT2ILINVOICELISTITEM createOT2ILINVOICELISTITEM() {
        return new OT2ILINVOICELISTITEM();
    }

    /**
     * Create an instance of {@link OT2ACCOUNT }
     * 
     */
    public OT2ACCOUNT createOT2ACCOUNT() {
        return new OT2ACCOUNT();
    }

    /**
     * Create an instance of {@link OT2ORDERITEMLIST }
     * 
     */
    public OT2ORDERITEMLIST createOT2ORDERITEMLIST() {
        return new OT2ORDERITEMLIST();
    }

    /**
     * Create an instance of {@link OT2RECEIPTACKNOWLEDGEMENTINFO }
     * 
     */
    public OT2RECEIPTACKNOWLEDGEMENTINFO createOT2RECEIPTACKNOWLEDGEMENTINFO() {
        return new OT2RECEIPTACKNOWLEDGEMENTINFO();
    }

    /**
     * Create an instance of {@link OT2ALLOWORCHARGEDESCR }
     * 
     */
    public OT2ALLOWORCHARGEDESCR createOT2ALLOWORCHARGEDESCR() {
        return new OT2ALLOWORCHARGEDESCR();
    }

    /**
     * Create an instance of {@link OT2PRICEBASEFIX }
     * 
     */
    public OT2PRICEBASEFIX createOT2PRICEBASEFIX() {
        return new OT2PRICEBASEFIX();
    }

    /**
     * Create an instance of {@link OT2REWARDSSYSTEM }
     * 
     */
    public OT2REWARDSSYSTEM createOT2REWARDSSYSTEM() {
        return new OT2REWARDSSYSTEM();
    }

    /**
     * Create an instance of {@link OT2PARTY }
     * 
     */
    public OT2PARTY createOT2PARTY() {
        return new OT2PARTY();
    }

    /**
     * Create an instance of {@link OT2ALLOWORCHARGEVALUE }
     * 
     */
    public OT2ALLOWORCHARGEVALUE createOT2ALLOWORCHARGEVALUE() {
        return new OT2ALLOWORCHARGEVALUE();
    }

    /**
     * Create an instance of {@link OT2MIMEEMBEDDED }
     * 
     */
    public OT2MIMEEMBEDDED createOT2MIMEEMBEDDED() {
        return new OT2MIMEEMBEDDED();
    }

    /**
     * Create an instance of {@link OT2RAINVOICELIST }
     * 
     */
    public OT2RAINVOICELIST createOT2RAINVOICELIST() {
        return new OT2RAINVOICELIST();
    }

    /**
     * Create an instance of {@link OT2PAYMENTTERM }
     * 
     */
    public OT2PAYMENTTERM createOT2PAYMENTTERM() {
        return new OT2PAYMENTTERM();
    }

    /**
     * Create an instance of {@link OT2AGREEMENT }
     * 
     */
    public OT2AGREEMENT createOT2AGREEMENT() {
        return new OT2AGREEMENT();
    }

    /**
     * Create an instance of {@link OT2ORDERCHANGE }
     * 
     */
    public OT2ORDERCHANGE createOT2ORDERCHANGE() {
        return new OT2ORDERCHANGE();
    }

    /**
     * Create an instance of {@link OT2PRODUCTCOMPONENTS }
     * 
     */
    public OT2PRODUCTCOMPONENTS createOT2PRODUCTCOMPONENTS() {
        return new OT2PRODUCTCOMPONENTS();
    }

    /**
     * Create an instance of {@link OT2ORDERINFO }
     * 
     */
    public OT2ORDERINFO createOT2ORDERINFO() {
        return new OT2ORDERINFO();
    }

    /**
     * Create an instance of {@link OT2INVOICELIST }
     * 
     */
    public OT2INVOICELIST createOT2INVOICELIST() {
        return new OT2INVOICELIST();
    }

    /**
     * Create an instance of {@link OT2ALLOWORCHARGES }
     * 
     */
    public OT2ALLOWORCHARGES createOT2ALLOWORCHARGES() {
        return new OT2ALLOWORCHARGES();
    }

    /**
     * Create an instance of {@link OT2CONTROLINFO }
     * 
     */
    public OT2CONTROLINFO createOT2CONTROLINFO() {
        return new OT2CONTROLINFO();
    }

    /**
     * Create an instance of {@link OT2REMITTANCEADVICEITEM }
     * 
     */
    public OT2REMITTANCEADVICEITEM createOT2REMITTANCEADVICEITEM() {
        return new OT2REMITTANCEADVICEITEM();
    }

    /**
     * Create an instance of {@link OT2ALLOWORCHARGE }
     * 
     */
    public OT2ALLOWORCHARGE createOT2ALLOWORCHARGE() {
        return new OT2ALLOWORCHARGE();
    }

    /**
     * Create an instance of {@link OT2LOGISTICDETAILS }
     * 
     */
    public OT2LOGISTICDETAILS createOT2LOGISTICDETAILS() {
        return new OT2LOGISTICDETAILS();
    }

    /**
     * Create an instance of {@link OT2RFQINFO }
     * 
     */
    public OT2RFQINFO createOT2RFQINFO() {
        return new OT2RFQINFO();
    }

    /**
     * Create an instance of {@link OT2RECEIPTACKNOWLEDGEMENTHEADER }
     * 
     */
    public OT2RECEIPTACKNOWLEDGEMENTHEADER createOT2RECEIPTACKNOWLEDGEMENTHEADER() {
        return new OT2RECEIPTACKNOWLEDGEMENTHEADER();
    }

    /**
     * Create an instance of {@link OT2FINANCECHARGEDESCR }
     * 
     */
    public OT2FINANCECHARGEDESCR createOT2FINANCECHARGEDESCR() {
        return new OT2FINANCECHARGEDESCR();
    }

    /**
     * Create an instance of {@link OT2SUPPLIERPARTY }
     * 
     */
    public OT2SUPPLIERPARTY createOT2SUPPLIERPARTY() {
        return new OT2SUPPLIERPARTY();
    }

    /**
     * Create an instance of {@link OT2AOCORDERUNITSCOUNT }
     * 
     */
    public OT2AOCORDERUNITSCOUNT createOT2AOCORDERUNITSCOUNT() {
        return new OT2AOCORDERUNITSCOUNT();
    }

    /**
     * Create an instance of {@link OT2RFQ }
     * 
     */
    public OT2RFQ createOT2RFQ() {
        return new OT2RFQ();
    }

    /**
     * Create an instance of {@link UdxHEADER }
     * 
     */
    public UdxHEADER createUdxHEADER() {
        return new UdxHEADER();
    }

    /**
     * Create an instance of {@link OT2RFQSUMMARY }
     * 
     */
    public OT2RFQSUMMARY createOT2RFQSUMMARY() {
        return new OT2RFQSUMMARY();
    }

    /**
     * Create an instance of {@link OT2RECEIPTACKNOWLEDGEMENTSUMMARY }
     * 
     */
    public OT2RECEIPTACKNOWLEDGEMENTSUMMARY createOT2RECEIPTACKNOWLEDGEMENTSUMMARY() {
        return new OT2RECEIPTACKNOWLEDGEMENTSUMMARY();
    }

    /**
     * Create an instance of {@link OT2DISPATCHNOTIFICATIONITEM }
     * 
     */
    public OT2DISPATCHNOTIFICATIONITEM createOT2DISPATCHNOTIFICATIONITEM() {
        return new OT2DISPATCHNOTIFICATIONITEM();
    }

    /**
     * Create an instance of {@link OT2INVOICELISTSUMMARY }
     * 
     */
    public OT2INVOICELISTSUMMARY createOT2INVOICELISTSUMMARY() {
        return new OT2INVOICELISTSUMMARY();
    }

    /**
     * Create an instance of {@link OT2ORDERRESPONSEITEMLIST }
     * 
     */
    public OT2ORDERRESPONSEITEMLIST createOT2ORDERRESPONSEITEMLIST() {
        return new OT2ORDERRESPONSEITEMLIST();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DtCURRENCIES }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "FOREIGN_CURRENCY")
    public JAXBElement<DtCURRENCIES> createFOREIGNCURRENCY(DtCURRENCIES value) {
        return new JAXBElement<DtCURRENCIES>(_FOREIGNCURRENCY_QNAME, DtCURRENCIES.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypePARTYID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "FINAL_DELIVERY_IDREF")
    public JAXBElement<TypePARTYID> createFINALDELIVERYIDREF(TypePARTYID value) {
        return new JAXBElement<TypePARTYID>(_FINALDELIVERYIDREF_QNAME, TypePARTYID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "PACKAGE_ORDER_UNIT_QUANTITY")
    public JAXBElement<BigDecimal> createPACKAGEORDERUNITQUANTITY(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PACKAGEORDERUNITQUANTITY_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "CREDIT_AVAILABLE")
    public JAXBElement<BigDecimal> createCREDITAVAILABLE(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_CREDITAVAILABLE_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "MEANS_OF_TRANSPORT_IDREF")
    public JAXBElement<String> createMEANSOFTRANSPORTIDREF(String value) {
        return new JAXBElement<String>(_MEANSOFTRANSPORTIDREF_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "CARD_NUM")
    public JAXBElement<String> createCARDNUM(String value) {
        return new JAXBElement<String>(_CARDNUM_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "QUOTATION_ID")
    public JAXBElement<String> createQUOTATIONID(String value) {
        return new JAXBElement<String>(_QUOTATIONID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "STOP_AUTOMATIC_PROCESSING")
    public JAXBElement<String> createSTOPAUTOMATICPROCESSING(String value) {
        return new JAXBElement<String>(_STOPAUTOMATICPROCESSING_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "ORDER_ID")
    public JAXBElement<String> createORDERID(String value) {
        return new JAXBElement<String>(_ORDERID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "DELIVERYNOTE_ID")
    public JAXBElement<String> createDELIVERYNOTEID(String value) {
        return new JAXBElement<String>(_DELIVERYNOTEID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "EXCHANGE_RATE")
    public JAXBElement<BigDecimal> createEXCHANGERATE(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_EXCHANGERATE_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Base64Binary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "MIME_DATA")
    public JAXBElement<Base64Binary> createMIMEDATA(Base64Binary value) {
        return new JAXBElement<Base64Binary>(_MIMEDATA_QNAME, Base64Binary.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "AMOUNT_OVER_CREDIT_LIMIT")
    public JAXBElement<BigDecimal> createAMOUNTOVERCREDITLIMIT(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_AMOUNTOVERCREDITLIMIT_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "INVOICELIST_TYPE", defaultValue = "collective_invoice")
    public JAXBElement<String> createINVOICELISTTYPE(String value) {
        return new JAXBElement<String>(_INVOICELISTTYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UdxREPORT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "REPORT_UDX")
    public JAXBElement<UdxREPORT> createREPORTUDX(UdxREPORT value) {
        return new JAXBElement<UdxREPORT>(_REPORTUDX_QNAME, UdxREPORT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "QUOTATION_DATE")
    public JAXBElement<String> createQUOTATIONDATE(String value) {
        return new JAXBElement<String>(_QUOTATIONDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "AOC_ADDITIONAL_ITEMS")
    public JAXBElement<String> createAOCADDITIONALITEMS(String value) {
        return new JAXBElement<String>(_AOCADDITIONALITEMS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "ORDERCHANGE_DATE")
    public JAXBElement<String> createORDERCHANGEDATE(String value) {
        return new JAXBElement<String>(_ORDERCHANGEDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypePARTYID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "REMITTEE_IDREF")
    public JAXBElement<TypePARTYID> createREMITTEEIDREF(TypePARTYID value) {
        return new JAXBElement<TypePARTYID>(_REMITTEEIDREF_QNAME, TypePARTYID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "CARD_AUTH_CODE")
    public JAXBElement<String> createCARDAUTHCODE(String value) {
        return new JAXBElement<String>(_CARDAUTHCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "SERIAL_NUMBER")
    public JAXBElement<String> createSERIALNUMBER(String value) {
        return new JAXBElement<String>(_SERIALNUMBER_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "DEBIT")
    public JAXBElement<String> createDEBIT(String value) {
        return new JAXBElement<String>(_DEBIT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "PARTY_ROLE")
    public JAXBElement<String> createPARTYROLE(String value) {
        return new JAXBElement<String>(_PARTYROLE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypePARTYID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "DELIVERY_IDREF")
    public JAXBElement<TypePARTYID> createDELIVERYIDREF(TypePARTYID value) {
        return new JAXBElement<TypePARTYID>(_DELIVERYIDREF_QNAME, TypePARTYID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypePARTYID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "DELIVERER_IDREF")
    public JAXBElement<TypePARTYID> createDELIVERERIDREF(TypePARTYID value) {
        return new JAXBElement<TypePARTYID>(_DELIVERERIDREF_QNAME, TypePARTYID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "ADJUSTED_SUMMARY_AMOUNT")
    public JAXBElement<BigDecimal> createADJUSTEDSUMMARYAMOUNT(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ADJUSTEDSUMMARYAMOUNT_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "ALT_CUSTOMER_ORDER_ID")
    public JAXBElement<String> createALTCUSTOMERORDERID(String value) {
        return new JAXBElement<String>(_ALTCUSTOMERORDERID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "POST_DATE")
    public JAXBElement<String> createPOSTDATE(String value) {
        return new JAXBElement<String>(_POSTDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "AOC_PERCENTAGE_FACTOR")
    public JAXBElement<Float> createAOCPERCENTAGEFACTOR(Float value) {
        return new JAXBElement<Float>(_AOCPERCENTAGEFACTOR_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DtMLSTRING }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "ADJUSTMENT_REASON_DESCR")
    public JAXBElement<DtMLSTRING> createADJUSTMENTREASONDESCR(DtMLSTRING value) {
        return new JAXBElement<DtMLSTRING>(_ADJUSTMENTREASONDESCR_QNAME, DtMLSTRING.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "DELIVERYNOTE_DATE")
    public JAXBElement<String> createDELIVERYNOTEDATE(String value) {
        return new JAXBElement<String>(_DELIVERYNOTEDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypePARTYID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "INVOICE_RECIPIENT_IDREF")
    public JAXBElement<TypePARTYID> createINVOICERECIPIENTIDREF(TypePARTYID value) {
        return new JAXBElement<TypePARTYID>(_INVOICERECIPIENTIDREF_QNAME, TypePARTYID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "HOLDER")
    public JAXBElement<String> createHOLDER(String value) {
        return new JAXBElement<String>(_HOLDER_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "LINE_ITEM_ID")
    public JAXBElement<String> createLINEITEMID(String value) {
        return new JAXBElement<String>(_LINEITEMID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "CONFIG_CODE_FIX")
    public JAXBElement<String> createCONFIGCODEFIX(String value) {
        return new JAXBElement<String>(_CONFIGCODEFIX_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "TAX_AMOUNT")
    public JAXBElement<BigDecimal> createTAXAMOUNT(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TAXAMOUNT_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "DELIVERY_START_DATE")
    public JAXBElement<String> createDELIVERYSTARTDATE(String value) {
        return new JAXBElement<String>(_DELIVERYSTARTDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "DISPATCHNOTIFICATION_ID")
    public JAXBElement<String> createDISPATCHNOTIFICATIONID(String value) {
        return new JAXBElement<String>(_DISPATCHNOTIFICATIONID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "INVOICE_TYPE", defaultValue = "invoice")
    public JAXBElement<String> createINVOICETYPE(String value) {
        return new JAXBElement<String>(_INVOICETYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "FOREIGN_AMOUNT")
    public JAXBElement<BigDecimal> createFOREIGNAMOUNT(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_FOREIGNAMOUNT_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "SIGNATURE_IN_ORIGINAL")
    public JAXBElement<String> createSIGNATUREINORIGINAL(String value) {
        return new JAXBElement<String>(_SIGNATUREINORIGINAL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "DELIVERY_END_DATE")
    public JAXBElement<String> createDELIVERYENDDATE(String value) {
        return new JAXBElement<String>(_DELIVERYENDDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "REWARDS_SUMMARY")
    public JAXBElement<BigDecimal> createREWARDSSUMMARY(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_REWARDSSUMMARY_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "BANK_COUNTRY")
    public JAXBElement<String> createBANKCOUNTRY(String value) {
        return new JAXBElement<String>(_BANKCOUNTRY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "NET_VALUE_GOODS")
    public JAXBElement<BigDecimal> createNETVALUEGOODS(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_NETVALUEGOODS_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "CARD_HOLDER_NAME")
    public JAXBElement<String> createCARDHOLDERNAME(String value) {
        return new JAXBElement<String>(_CARDHOLDERNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "ACCOUNTING_PERIOD_END_DATE")
    public JAXBElement<String> createACCOUNTINGPERIODENDDATE(String value) {
        return new JAXBElement<String>(_ACCOUNTINGPERIODENDDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "ORDER_DATE")
    public JAXBElement<String> createORDERDATE(String value) {
        return new JAXBElement<String>(_ORDERDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "PARTIAL_SHIPMENT_ALLOWED")
    public JAXBElement<String> createPARTIALSHIPMENTALLOWED(String value) {
        return new JAXBElement<String>(_PARTIALSHIPMENTALLOWED_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "PACKAGE_TYPE")
    public JAXBElement<String> createPACKAGETYPE(String value) {
        return new JAXBElement<String>(_PACKAGETYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "INVOICELIST_DATE")
    public JAXBElement<String> createINVOICELISTDATE(String value) {
        return new JAXBElement<String>(_INVOICELISTDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "RECEIPTACKNOWLEDGEMENT_ID")
    public JAXBElement<String> createRECEIPTACKNOWLEDGEMENTID(String value) {
        return new JAXBElement<String>(_RECEIPTACKNOWLEDGEMENTID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "REWARDS_POINTS")
    public JAXBElement<BigDecimal> createREWARDSPOINTS(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_REWARDSPOINTS_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "FILE_NAME")
    public JAXBElement<String> createFILENAME(String value) {
        return new JAXBElement<String>(_FILENAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "LOT_NUMBER")
    public JAXBElement<String> createLOTNUMBER(String value) {
        return new JAXBElement<String>(_LOTNUMBER_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "PRICE_UNIT_VALUE")
    public JAXBElement<Float> createPRICEUNITVALUE(Float value) {
        return new JAXBElement<Float>(_PRICEUNITVALUE_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "ALLOW_OR_CHARGE_BASE")
    public JAXBElement<Float> createALLOWORCHARGEBASE(Float value) {
        return new JAXBElement<Float>(_ALLOWORCHARGEBASE_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "ADJUSTMENT_REASON_CODE")
    public JAXBElement<String> createADJUSTMENTREASONCODE(String value) {
        return new JAXBElement<String>(_ADJUSTMENTREASONCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "PARTIAL_SHIPMENT")
    public JAXBElement<String> createPARTIALSHIPMENT(String value) {
        return new JAXBElement<String>(_PARTIALSHIPMENT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "ALLOW_OR_CHARGES_TOTAL_AMOUNT")
    public JAXBElement<Float> createALLOWORCHARGESTOTALAMOUNT(Float value) {
        return new JAXBElement<Float>(_ALLOWORCHARGESTOTALAMOUNT_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "ORDERRESPONSE_DATE")
    public JAXBElement<String> createORDERRESPONSEDATE(String value) {
        return new JAXBElement<String>(_ORDERRESPONSEDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "DAYS")
    public JAXBElement<BigInteger> createDAYS(BigInteger value) {
        return new JAXBElement<BigInteger>(_DAYS_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypePARTYID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "DOCUMENT_RECIPIENT_IDREF")
    public JAXBElement<TypePARTYID> createDOCUMENTRECIPIENTIDREF(TypePARTYID value) {
        return new JAXBElement<TypePARTYID>(_DOCUMENTRECIPIENTIDREF_QNAME, TypePARTYID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "BANK_NAME")
    public JAXBElement<String> createBANKNAME(String value) {
        return new JAXBElement<String>(_BANKNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "VERIFICATION_RESULT")
    public JAXBElement<String> createVERIFICATIONRESULT(String value) {
        return new JAXBElement<String>(_VERIFICATIONRESULT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "QUANTITY")
    public JAXBElement<BigDecimal> createQUANTITY(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_QUANTITY_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypePARTYID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "INVOICE_ISSUER_IDREF")
    public JAXBElement<TypePARTYID> createINVOICEISSUERIDREF(TypePARTYID value) {
        return new JAXBElement<TypePARTYID>(_INVOICEISSUERIDREF_QNAME, TypePARTYID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "GENERATOR_INFO")
    public JAXBElement<String> createGENERATORINFO(String value) {
        return new JAXBElement<String>(_GENERATORINFO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "TOTAL_TAX_AMOUNT")
    public JAXBElement<BigDecimal> createTOTALTAXAMOUNT(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TOTALTAXAMOUNT_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "XML_FORMAT")
    public JAXBElement<String> createXMLFORMAT(String value) {
        return new JAXBElement<String>(_XMLFORMAT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "OPENING_BALANCE")
    public JAXBElement<BigDecimal> createOPENINGBALANCE(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_OPENINGBALANCE_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "NET_VALUE_EXTRA")
    public JAXBElement<BigDecimal> createNETVALUEEXTRA(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_NETVALUEEXTRA_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "CASH")
    public JAXBElement<String> createCASH(String value) {
        return new JAXBElement<String>(_CASH_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "INVOICELIST_ID")
    public JAXBElement<String> createINVOICELISTID(String value) {
        return new JAXBElement<String>(_INVOICELISTID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "REMITTANCEADVICE_DATE")
    public JAXBElement<String> createREMITTANCEADVICEDATE(String value) {
        return new JAXBElement<String>(_REMITTANCEADVICEDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "INVOICE_ID")
    public JAXBElement<String> createINVOICEID(String value) {
        return new JAXBElement<String>(_INVOICEID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "ALLOW_OR_CHARGE_SEQUENCE")
    public JAXBElement<BigInteger> createALLOWORCHARGESEQUENCE(BigInteger value) {
        return new JAXBElement<BigInteger>(_ALLOWORCHARGESEQUENCE_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "DISCOUNT_FACTOR")
    public JAXBElement<Float> createDISCOUNTFACTOR(Float value) {
        return new JAXBElement<Float>(_DISCOUNTFACTOR_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "REMITTANCEADVICE_ID")
    public JAXBElement<String> createREMITTANCEADVICEID(String value) {
        return new JAXBElement<String>(_REMITTANCEADVICEID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypePARTYID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "PAYER_IDREF")
    public JAXBElement<TypePARTYID> createPAYERIDREF(TypePARTYID value) {
        return new JAXBElement<TypePARTYID>(_PAYERIDREF_QNAME, TypePARTYID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypePARTYID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "DOCUMENT_ISSUER_IDREF")
    public JAXBElement<TypePARTYID> createDOCUMENTISSUERIDREF(TypePARTYID value) {
        return new JAXBElement<TypePARTYID>(_DOCUMENTISSUERIDREF_QNAME, TypePARTYID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "RECEIPT_DATE")
    public JAXBElement<String> createRECEIPTDATE(String value) {
        return new JAXBElement<String>(_RECEIPTDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypePARTYID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "CUSTOMER_IDREF")
    public JAXBElement<TypePARTYID> createCUSTOMERIDREF(TypePARTYID value) {
        return new JAXBElement<TypePARTYID>(_CUSTOMERIDREF_QNAME, TypePARTYID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "FILE_SIZE")
    public JAXBElement<BigInteger> createFILESIZE(BigInteger value) {
        return new JAXBElement<BigInteger>(_FILESIZE_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "CREDIT_LIMIT")
    public JAXBElement<BigDecimal> createCREDITLIMIT(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_CREDITLIMIT_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "CLOSING_BALANCE")
    public JAXBElement<BigDecimal> createCLOSINGBALANCE(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_CLOSINGBALANCE_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "REASON_FOR_TRANSFER")
    public JAXBElement<String> createREASONFORTRANSFER(String value) {
        return new JAXBElement<String>(_REASONFORTRANSFER_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "RFQ_DATE")
    public JAXBElement<String> createRFQDATE(String value) {
        return new JAXBElement<String>(_RFQDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "TOTAL_ITEM_NUM")
    public JAXBElement<BigInteger> createTOTALITEMNUM(BigInteger value) {
        return new JAXBElement<BigInteger>(_TOTALITEMNUM_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "CHECK")
    public JAXBElement<String> createCHECK(String value) {
        return new JAXBElement<String>(_CHECK_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "CENTRAL_REGULATION", defaultValue = "false")
    public JAXBElement<String> createCENTRALREGULATION(String value) {
        return new JAXBElement<String>(_CENTRALREGULATION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "TAX_NUMBER")
    public JAXBElement<String> createTAXNUMBER(String value) {
        return new JAXBElement<String>(_TAXNUMBER_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UdxITEM }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "ITEM_UDX")
    public JAXBElement<UdxITEM> createITEMUDX(UdxITEM value) {
        return new JAXBElement<UdxITEM>(_ITEMUDX_QNAME, UdxITEM.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "ALLOW_OR_CHARGE_TYPE")
    public JAXBElement<String> createALLOWORCHARGETYPE(String value) {
        return new JAXBElement<String>(_ALLOWORCHARGETYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "GENERATION_DATE")
    public JAXBElement<String> createGENERATIONDATE(String value) {
        return new JAXBElement<String>(_GENERATIONDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "INVOICE_DATE")
    public JAXBElement<String> createINVOICEDATE(String value) {
        return new JAXBElement<String>(_INVOICEDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "SHIPMENT_ID")
    public JAXBElement<String> createSHIPMENTID(String value) {
        return new JAXBElement<String>(_SHIPMENTID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "INVOICE_COVERAGE", defaultValue = "single")
    public JAXBElement<String> createINVOICECOVERAGE(String value) {
        return new JAXBElement<String>(_INVOICECOVERAGE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "DELIVERY_COMPLETED")
    public JAXBElement<String> createDELIVERYCOMPLETED(String value) {
        return new JAXBElement<String>(_DELIVERYCOMPLETED_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "RFQ_ID")
    public JAXBElement<String> createRFQID(String value) {
        return new JAXBElement<String>(_RFQID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "PACKAGE_QUANTITY")
    public JAXBElement<BigDecimal> createPACKAGEQUANTITY(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PACKAGEQUANTITY_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "ACCOUNTING_PERIOD_START_DATE")
    public JAXBElement<String> createACCOUNTINGPERIODSTARTDATE(String value) {
        return new JAXBElement<String>(_ACCOUNTINGPERIODSTARTDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UdxHEADER }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "HEADER_UDX")
    public JAXBElement<UdxHEADER> createHEADERUDX(UdxHEADER value) {
        return new JAXBElement<UdxHEADER>(_HEADERUDX_QNAME, UdxHEADER.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "CARD_EXPIRATION_DATE")
    public JAXBElement<String> createCARDEXPIRATIONDATE(String value) {
        return new JAXBElement<String>(_CARDEXPIRATIONDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "TOTAL_AMOUNT")
    public JAXBElement<BigDecimal> createTOTALAMOUNT(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TOTALAMOUNT_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "PRICE_LINE_AMOUNT")
    public JAXBElement<BigDecimal> createPRICELINEAMOUNT(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PRICELINEAMOUNT_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "TERMS_AND_CONDITIONS")
    public JAXBElement<String> createTERMSANDCONDITIONS(String value) {
        return new JAXBElement<String>(_TERMSANDCONDITIONS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "CARD_REF_NUM")
    public JAXBElement<String> createCARDREFNUM(String value) {
        return new JAXBElement<String>(_CARDREFNUM_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "ALLOW_OR_CHARGE_AMOUNT")
    public JAXBElement<Float> createALLOWORCHARGEAMOUNT(Float value) {
        return new JAXBElement<Float>(_ALLOWORCHARGEAMOUNT_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "TAX_BASE")
    public JAXBElement<BigDecimal> createTAXBASE(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TAXBASE_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "SUPPLIER_ORDER_ITEM_ID")
    public JAXBElement<String> createSUPPLIERORDERITEMID(String value) {
        return new JAXBElement<String>(_SUPPLIERORDERITEMID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "DIRECT_DEBIT")
    public JAXBElement<BigDecimal> createDIRECTDEBIT(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_DIRECTDEBIT_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "DISPATCHNOTIFICATION_DATE")
    public JAXBElement<String> createDISPATCHNOTIFICATIONDATE(String value) {
        return new JAXBElement<String>(_DISPATCHNOTIFICATIONDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "ORIGINAL_SUMMARY_AMOUNT")
    public JAXBElement<BigDecimal> createORIGINALSUMMARYAMOUNT(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ORIGINALSUMMARYAMOUNT_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "FINANCE_CHARGE")
    public JAXBElement<BigDecimal> createFINANCECHARGE(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_FINANCECHARGE_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "VALUE_DATE")
    public JAXBElement<String> createVALUEDATE(String value) {
        return new JAXBElement<String>(_VALUEDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "VERIFICATION_SUCCESS")
    public JAXBElement<String> createVERIFICATIONSUCCESS(String value) {
        return new JAXBElement<String>(_VERIFICATIONSUCCESS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DtMLSTRING }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "RESULT_DESCR")
    public JAXBElement<DtMLSTRING> createRESULTDESCR(DtMLSTRING value) {
        return new JAXBElement<DtMLSTRING>(_RESULTDESCR_QNAME, DtMLSTRING.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "RECEIPTACKNOWLEDGEMENT_DATE")
    public JAXBElement<String> createRECEIPTACKNOWLEDGEMENTDATE(String value) {
        return new JAXBElement<String>(_RECEIPTACKNOWLEDGEMENTDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "SUPPLIER_ORDER_ID")
    public JAXBElement<String> createSUPPLIERORDERID(String value) {
        return new JAXBElement<String>(_SUPPLIERORDERID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "PAYMENT_DATE")
    public JAXBElement<String> createPAYMENTDATE(String value) {
        return new JAXBElement<String>(_PAYMENTDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypePARTYID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "VERIFICATION_PARTY_IDREF")
    public JAXBElement<TypePARTYID> createVERIFICATIONPARTYIDREF(TypePARTYID value) {
        return new JAXBElement<TypePARTYID>(_VERIFICATIONPARTYIDREF_QNAME, TypePARTYID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "AOC_MONETARY_AMOUNT")
    public JAXBElement<Float> createAOCMONETARYAMOUNT(Float value) {
        return new JAXBElement<Float>(_AOCMONETARYAMOUNT_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "REMITTANCEADVICE_TYPE")
    public JAXBElement<String> createREMITTANCEADVICETYPE(String value) {
        return new JAXBElement<String>(_REMITTANCEADVICETYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "ORDERCHANGE_SEQUENCE_ID")
    public JAXBElement<BigInteger> createORDERCHANGESEQUENCEID(BigInteger value) {
        return new JAXBElement<BigInteger>(_ORDERCHANGESEQUENCEID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "TRACKING_TRACING_URL")
    public JAXBElement<String> createTRACKINGTRACINGURL(String value) {
        return new JAXBElement<String>(_TRACKINGTRACINGURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "RESULT_CODE")
    public JAXBElement<String> createRESULTCODE(String value) {
        return new JAXBElement<String>(_RESULTCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentrans.org/XMLSchema/2.1", name = "MIME_PURPOSE")
    public JAXBElement<String> createMIMEPURPOSE(String value) {
        return new JAXBElement<String>(_MIMEPURPOSE_QNAME, String.class, null, value);
    }

}
