/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2015 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.opentrans_2_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}AOC_PERCENTAGE_FACTOR"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}AOC_MONETARY_AMOUNT"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}AOC_ORDER_UNITS_COUNT"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}AOC_ADDITIONAL_ITEMS"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aocpercentagefactor",
    "aocmonetaryamount",
    "aocorderunitscount",
    "aocadditionalitems"
})
@XmlRootElement(name = "ALLOW_OR_CHARGE_VALUE")
public class OT2ALLOWORCHARGEVALUE {

    @XmlElement(name = "AOC_PERCENTAGE_FACTOR")
    protected Float aocpercentagefactor;
    @XmlElement(name = "AOC_MONETARY_AMOUNT")
    protected Float aocmonetaryamount;
    @XmlElement(name = "AOC_ORDER_UNITS_COUNT")
    protected OT2AOCORDERUNITSCOUNT aocorderunitscount;
    @XmlElement(name = "AOC_ADDITIONAL_ITEMS")
    protected String aocadditionalitems;

    /**
     * Gets the value of the aocpercentagefactor property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAOCPERCENTAGEFACTOR() {
        return aocpercentagefactor;
    }

    /**
     * Sets the value of the aocpercentagefactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAOCPERCENTAGEFACTOR(Float value) {
        this.aocpercentagefactor = value;
    }

    /**
     * Gets the value of the aocmonetaryamount property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAOCMONETARYAMOUNT() {
        return aocmonetaryamount;
    }

    /**
     * Sets the value of the aocmonetaryamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAOCMONETARYAMOUNT(Float value) {
        this.aocmonetaryamount = value;
    }

    /**
     * Gets the value of the aocorderunitscount property.
     * 
     * @return
     *     possible object is
     *     {@link OT2AOCORDERUNITSCOUNT }
     *     
     */
    public OT2AOCORDERUNITSCOUNT getAOCORDERUNITSCOUNT() {
        return aocorderunitscount;
    }

    /**
     * Sets the value of the aocorderunitscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2AOCORDERUNITSCOUNT }
     *     
     */
    public void setAOCORDERUNITSCOUNT(OT2AOCORDERUNITSCOUNT value) {
        this.aocorderunitscount = value;
    }

    /**
     * Gets the value of the aocadditionalitems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAOCADDITIONALITEMS() {
        return aocadditionalitems;
    }

    /**
     * Sets the value of the aocadditionalitems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAOCADDITIONALITEMS(String value) {
        this.aocadditionalitems = value;
    }

}
