/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.opentrans_2_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.lp.server.schema.bmecat_2005.BCACADEMICTITLE;
import com.lp.server.schema.bmecat_2005.BCAUTHENTIFICATION;
import com.lp.server.schema.bmecat_2005.BCCONTACTDESCR;
import com.lp.server.schema.bmecat_2005.BCCONTACTNAME;
import com.lp.server.schema.bmecat_2005.BCEMAILS;
import com.lp.server.schema.bmecat_2005.BCFAX;
import com.lp.server.schema.bmecat_2005.BCFIRSTNAME;
import com.lp.server.schema.bmecat_2005.BCPHONE;
import com.lp.server.schema.bmecat_2005.BCTITLE;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CONTACT_ID" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CONTACT_NAME" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}FIRST_NAME" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}TITLE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ACADEMIC_TITLE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}CONTACT_ROLE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CONTACT_DESCR" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PHONE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}FAX" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}URL" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}EMAILS" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}AUTHENTIFICATION" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contactid",
    "contactname",
    "firstname",
    "title",
    "academictitle",
    "contactrole",
    "contactdescr",
    "phone",
    "fax",
    "url",
    "emails",
    "authentification"
})
@XmlRootElement(name = "CONTACT_DETAILS")
public class OT2CONTACTDETAILS {

    @XmlElement(name = "CONTACT_ID", namespace = "http://www.bmecat.org/bmecat/2005")
    protected String contactid;
    @XmlElement(name = "CONTACT_NAME", namespace = "http://www.bmecat.org/bmecat/2005", required = true)
    protected List<BCCONTACTNAME> contactname;
    @XmlElement(name = "FIRST_NAME", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<BCFIRSTNAME> firstname;
    @XmlElement(name = "TITLE", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<BCTITLE> title;
    @XmlElement(name = "ACADEMIC_TITLE", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<BCACADEMICTITLE> academictitle;
    @XmlElement(name = "CONTACT_ROLE")
    protected List<OT2CONTACTROLE> contactrole;
    @XmlElement(name = "CONTACT_DESCR", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<BCCONTACTDESCR> contactdescr;
    @XmlElement(name = "PHONE", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<BCPHONE> phone;
    @XmlElement(name = "FAX", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<BCFAX> fax;
    @XmlElement(name = "URL", namespace = "http://www.bmecat.org/bmecat/2005")
    protected String url;
    @XmlElement(name = "EMAILS", namespace = "http://www.bmecat.org/bmecat/2005")
    protected BCEMAILS emails;
    @XmlElement(name = "AUTHENTIFICATION", namespace = "http://www.bmecat.org/bmecat/2005")
    protected BCAUTHENTIFICATION authentification;

    /**
     * Gets the value of the contactid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONTACTID() {
        return contactid;
    }

    /**
     * Sets the value of the contactid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONTACTID(String value) {
        this.contactid = value;
    }

    /**
     * Gets the value of the contactname property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactname property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCONTACTNAME().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCCONTACTNAME }
     * 
     * 
     */
    public List<BCCONTACTNAME> getCONTACTNAME() {
        if (contactname == null) {
            contactname = new ArrayList<BCCONTACTNAME>();
        }
        return this.contactname;
    }

    /**
     * Gets the value of the firstname property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the firstname property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFIRSTNAME().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCFIRSTNAME }
     * 
     * 
     */
    public List<BCFIRSTNAME> getFIRSTNAME() {
        if (firstname == null) {
            firstname = new ArrayList<BCFIRSTNAME>();
        }
        return this.firstname;
    }

    /**
     * Gets the value of the title property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the title property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTITLE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCTITLE }
     * 
     * 
     */
    public List<BCTITLE> getTITLE() {
        if (title == null) {
            title = new ArrayList<BCTITLE>();
        }
        return this.title;
    }

    /**
     * Gets the value of the academictitle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the academictitle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getACADEMICTITLE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCACADEMICTITLE }
     * 
     * 
     */
    public List<BCACADEMICTITLE> getACADEMICTITLE() {
        if (academictitle == null) {
            academictitle = new ArrayList<BCACADEMICTITLE>();
        }
        return this.academictitle;
    }

    /**
     * Gets the value of the contactrole property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactrole property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCONTACTROLE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OT2CONTACTROLE }
     * 
     * 
     */
    public List<OT2CONTACTROLE> getCONTACTROLE() {
        if (contactrole == null) {
            contactrole = new ArrayList<OT2CONTACTROLE>();
        }
        return this.contactrole;
    }

    /**
     * Gets the value of the contactdescr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactdescr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCONTACTDESCR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCCONTACTDESCR }
     * 
     * 
     */
    public List<BCCONTACTDESCR> getCONTACTDESCR() {
        if (contactdescr == null) {
            contactdescr = new ArrayList<BCCONTACTDESCR>();
        }
        return this.contactdescr;
    }

    /**
     * Gets the value of the phone property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phone property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPHONE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCPHONE }
     * 
     * 
     */
    public List<BCPHONE> getPHONE() {
        if (phone == null) {
            phone = new ArrayList<BCPHONE>();
        }
        return this.phone;
    }

    /**
     * Gets the value of the fax property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fax property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFAX().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCFAX }
     * 
     * 
     */
    public List<BCFAX> getFAX() {
        if (fax == null) {
            fax = new ArrayList<BCFAX>();
        }
        return this.fax;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURL(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the emails property.
     * 
     * @return
     *     possible object is
     *     {@link BCEMAILS }
     *     
     */
    public BCEMAILS getEMAILS() {
        return emails;
    }

    /**
     * Sets the value of the emails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCEMAILS }
     *     
     */
    public void setEMAILS(BCEMAILS value) {
        this.emails = value;
    }

    /**
     * Gets the value of the authentification property.
     * 
     * @return
     *     possible object is
     *     {@link BCAUTHENTIFICATION }
     *     
     */
    public BCAUTHENTIFICATION getAUTHENTIFICATION() {
        return authentification;
    }

    /**
     * Sets the value of the authentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCAUTHENTIFICATION }
     *     
     */
    public void setAUTHENTIFICATION(BCAUTHENTIFICATION value) {
        this.authentification = value;
    }

}
