/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2015 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.opentrans_2_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.lp.server.schema.bmecat_2005.BCACCOUNTINGINFO;
import com.lp.server.schema.bmecat_2005.BCLANGUAGE;
import com.lp.server.schema.bmecat_2005.BCMIMEROOT;
import com.lp.server.schema.bmecat_2005.DtCURRENCIES;
import com.lp.server.schema.bmecat_2005.TypePARTYID;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}INVOICELIST_ID"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}INVOICELIST_DATE"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}REASON_FOR_TRANSFER" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}INVOICELIST_TYPE" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ACCOUNTING_PERIOD"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}LANGUAGE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}MIME_ROOT" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PARTIES"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}INVOICE_ISSUER_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}INVOICE_RECIPIENT_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}BUYER_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PAYER_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}REMITTEE_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}DOCEXCHANGE_PARTIES_REFERENCE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CURRENCY"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PAYMENT" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}TERMS_AND_CONDITIONS" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ACCOUNTING_INFO" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}E_BILLING" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}MIME_INFO" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}REMARKS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}HEADER_UDX" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "invoicelistid",
    "invoicelistdate",
    "reasonfortransfer",
    "invoicelisttype",
    "accountingperiod",
    "language",
    "mimeroot",
    "parties",
    "invoiceissueridref",
    "invoicerecipientidref",
    "buyeridref",
    "supplieridref",
    "payeridref",
    "remitteeidref",
    "docexchangepartiesreference",
    "currency",
    "payment",
    "termsandconditions",
    "accountinginfo",
    "ebilling",
    "mimeinfo",
    "remarks",
    "headerudx"
})
@XmlRootElement(name = "INVOICELIST_INFO")
public class OT2INVOICELISTINFO {

    @XmlElement(name = "INVOICELIST_ID", required = true)
    protected String invoicelistid;
    @XmlElement(name = "INVOICELIST_DATE", required = true)
    protected String invoicelistdate;
    @XmlElement(name = "REASON_FOR_TRANSFER")
    protected String reasonfortransfer;
    @XmlElement(name = "INVOICELIST_TYPE", defaultValue = "collective_invoice")
    protected String invoicelisttype;
    @XmlElement(name = "ACCOUNTING_PERIOD", required = true)
    protected OT2ACCOUNTINGPERIOD accountingperiod;
    @XmlElement(name = "LANGUAGE", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<BCLANGUAGE> language;
    @XmlElement(name = "MIME_ROOT", namespace = "http://www.bmecat.org/bmecat/2005")
    protected BCMIMEROOT mimeroot;
    @XmlElement(name = "PARTIES", required = true)
    protected OT2PARTIES parties;
    @XmlElement(name = "INVOICE_ISSUER_IDREF")
    protected TypePARTYID invoiceissueridref;
    @XmlElement(name = "INVOICE_RECIPIENT_IDREF")
    protected TypePARTYID invoicerecipientidref;
    @XmlElement(name = "BUYER_IDREF", namespace = "http://www.bmecat.org/bmecat/2005")
    protected TypePARTYID buyeridref;
    @XmlElement(name = "SUPPLIER_IDREF", namespace = "http://www.bmecat.org/bmecat/2005")
    protected TypePARTYID supplieridref;
    @XmlElement(name = "PAYER_IDREF")
    protected TypePARTYID payeridref;
    @XmlElement(name = "REMITTEE_IDREF")
    protected TypePARTYID remitteeidref;
    @XmlElement(name = "DOCEXCHANGE_PARTIES_REFERENCE")
    protected OT2DOCEXCHANGEPARTIESREFERENCE docexchangepartiesreference;
    @XmlElement(name = "CURRENCY", namespace = "http://www.bmecat.org/bmecat/2005", required = true)
    protected DtCURRENCIES currency;
    @XmlElement(name = "PAYMENT")
    protected OT2PAYMENT payment;
    @XmlElement(name = "TERMS_AND_CONDITIONS")
    protected String termsandconditions;
    @XmlElement(name = "ACCOUNTING_INFO", namespace = "http://www.bmecat.org/bmecat/2005")
    protected BCACCOUNTINGINFO accountinginfo;
    @XmlElement(name = "E_BILLING")
    protected OT2EBILLING ebilling;
    @XmlElement(name = "MIME_INFO")
    protected OT2MIMEINFO mimeinfo;
    @XmlElement(name = "REMARKS")
    protected List<OT2REMARKS> remarks;
    @XmlElement(name = "HEADER_UDX")
    protected UdxHEADER headerudx;

    /**
     * Gets the value of the invoicelistid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVOICELISTID() {
        return invoicelistid;
    }

    /**
     * Sets the value of the invoicelistid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVOICELISTID(String value) {
        this.invoicelistid = value;
    }

    /**
     * Gets the value of the invoicelistdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVOICELISTDATE() {
        return invoicelistdate;
    }

    /**
     * Sets the value of the invoicelistdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVOICELISTDATE(String value) {
        this.invoicelistdate = value;
    }

    /**
     * Gets the value of the reasonfortransfer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREASONFORTRANSFER() {
        return reasonfortransfer;
    }

    /**
     * Sets the value of the reasonfortransfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREASONFORTRANSFER(String value) {
        this.reasonfortransfer = value;
    }

    /**
     * Gets the value of the invoicelisttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVOICELISTTYPE() {
        return invoicelisttype;
    }

    /**
     * Sets the value of the invoicelisttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVOICELISTTYPE(String value) {
        this.invoicelisttype = value;
    }

    /**
     * Gets the value of the accountingperiod property.
     * 
     * @return
     *     possible object is
     *     {@link OT2ACCOUNTINGPERIOD }
     *     
     */
    public OT2ACCOUNTINGPERIOD getACCOUNTINGPERIOD() {
        return accountingperiod;
    }

    /**
     * Sets the value of the accountingperiod property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2ACCOUNTINGPERIOD }
     *     
     */
    public void setACCOUNTINGPERIOD(OT2ACCOUNTINGPERIOD value) {
        this.accountingperiod = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLANGUAGE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCLANGUAGE }
     * 
     * 
     */
    public List<BCLANGUAGE> getLANGUAGE() {
        if (language == null) {
            language = new ArrayList<BCLANGUAGE>();
        }
        return this.language;
    }

    /**
     * Gets the value of the mimeroot property.
     * 
     * @return
     *     possible object is
     *     {@link BCMIMEROOT }
     *     
     */
    public BCMIMEROOT getMIMEROOT() {
        return mimeroot;
    }

    /**
     * Sets the value of the mimeroot property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCMIMEROOT }
     *     
     */
    public void setMIMEROOT(BCMIMEROOT value) {
        this.mimeroot = value;
    }

    /**
     * Gets the value of the parties property.
     * 
     * @return
     *     possible object is
     *     {@link OT2PARTIES }
     *     
     */
    public OT2PARTIES getPARTIES() {
        return parties;
    }

    /**
     * Sets the value of the parties property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2PARTIES }
     *     
     */
    public void setPARTIES(OT2PARTIES value) {
        this.parties = value;
    }

    /**
     * Gets the value of the invoiceissueridref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getINVOICEISSUERIDREF() {
        return invoiceissueridref;
    }

    /**
     * Sets the value of the invoiceissueridref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setINVOICEISSUERIDREF(TypePARTYID value) {
        this.invoiceissueridref = value;
    }

    /**
     * Gets the value of the invoicerecipientidref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getINVOICERECIPIENTIDREF() {
        return invoicerecipientidref;
    }

    /**
     * Sets the value of the invoicerecipientidref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setINVOICERECIPIENTIDREF(TypePARTYID value) {
        this.invoicerecipientidref = value;
    }

    /**
     * Gets the value of the buyeridref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getBUYERIDREF() {
        return buyeridref;
    }

    /**
     * Sets the value of the buyeridref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setBUYERIDREF(TypePARTYID value) {
        this.buyeridref = value;
    }

    /**
     * Gets the value of the supplieridref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getSUPPLIERIDREF() {
        return supplieridref;
    }

    /**
     * Sets the value of the supplieridref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setSUPPLIERIDREF(TypePARTYID value) {
        this.supplieridref = value;
    }

    /**
     * Gets the value of the payeridref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getPAYERIDREF() {
        return payeridref;
    }

    /**
     * Sets the value of the payeridref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setPAYERIDREF(TypePARTYID value) {
        this.payeridref = value;
    }

    /**
     * Gets the value of the remitteeidref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getREMITTEEIDREF() {
        return remitteeidref;
    }

    /**
     * Sets the value of the remitteeidref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setREMITTEEIDREF(TypePARTYID value) {
        this.remitteeidref = value;
    }

    /**
     * Gets the value of the docexchangepartiesreference property.
     * 
     * @return
     *     possible object is
     *     {@link OT2DOCEXCHANGEPARTIESREFERENCE }
     *     
     */
    public OT2DOCEXCHANGEPARTIESREFERENCE getDOCEXCHANGEPARTIESREFERENCE() {
        return docexchangepartiesreference;
    }

    /**
     * Sets the value of the docexchangepartiesreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2DOCEXCHANGEPARTIESREFERENCE }
     *     
     */
    public void setDOCEXCHANGEPARTIESREFERENCE(OT2DOCEXCHANGEPARTIESREFERENCE value) {
        this.docexchangepartiesreference = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link DtCURRENCIES }
     *     
     */
    public DtCURRENCIES getCURRENCY() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link DtCURRENCIES }
     *     
     */
    public void setCURRENCY(DtCURRENCIES value) {
        this.currency = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link OT2PAYMENT }
     *     
     */
    public OT2PAYMENT getPAYMENT() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2PAYMENT }
     *     
     */
    public void setPAYMENT(OT2PAYMENT value) {
        this.payment = value;
    }

    /**
     * Gets the value of the termsandconditions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTERMSANDCONDITIONS() {
        return termsandconditions;
    }

    /**
     * Sets the value of the termsandconditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTERMSANDCONDITIONS(String value) {
        this.termsandconditions = value;
    }

    /**
     * Gets the value of the accountinginfo property.
     * 
     * @return
     *     possible object is
     *     {@link BCACCOUNTINGINFO }
     *     
     */
    public BCACCOUNTINGINFO getACCOUNTINGINFO() {
        return accountinginfo;
    }

    /**
     * Sets the value of the accountinginfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCACCOUNTINGINFO }
     *     
     */
    public void setACCOUNTINGINFO(BCACCOUNTINGINFO value) {
        this.accountinginfo = value;
    }

    /**
     * Gets the value of the ebilling property.
     * 
     * @return
     *     possible object is
     *     {@link OT2EBILLING }
     *     
     */
    public OT2EBILLING getEBILLING() {
        return ebilling;
    }

    /**
     * Sets the value of the ebilling property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2EBILLING }
     *     
     */
    public void setEBILLING(OT2EBILLING value) {
        this.ebilling = value;
    }

    /**
     * Gets the value of the mimeinfo property.
     * 
     * @return
     *     possible object is
     *     {@link OT2MIMEINFO }
     *     
     */
    public OT2MIMEINFO getMIMEINFO() {
        return mimeinfo;
    }

    /**
     * Sets the value of the mimeinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2MIMEINFO }
     *     
     */
    public void setMIMEINFO(OT2MIMEINFO value) {
        this.mimeinfo = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remarks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getREMARKS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OT2REMARKS }
     * 
     * 
     */
    public List<OT2REMARKS> getREMARKS() {
        if (remarks == null) {
            remarks = new ArrayList<OT2REMARKS>();
        }
        return this.remarks;
    }

    /**
     * Gets the value of the headerudx property.
     * 
     * @return
     *     possible object is
     *     {@link UdxHEADER }
     *     
     */
    public UdxHEADER getHEADERUDX() {
        return headerudx;
    }

    /**
     * Sets the value of the headerudx property.
     * 
     * @param value
     *     allowed object is
     *     {@link UdxHEADER }
     *     
     */
    public void setHEADERUDX(UdxHEADER value) {
        this.headerudx = value;
    }

}
