/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.opentrans_2_1;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.lp.server.schema.bmecat_2005.BCACCOUNTINGINFO;
import com.lp.server.schema.bmecat_2005.DtCURRENCIES;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}LINE_ITEM_ID"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PRODUCT_ID"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PRODUCT_FEATURES" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PRODUCT_COMPONENTS" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}QUANTITY"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ORDER_UNIT"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PRODUCT_PRICE_FIX"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PRICE_LINE_AMOUNT"/>
 *         &lt;sequence>
 *           &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}FOREIGN_CURRENCY" minOccurs="0"/>
 *           &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}EXCHANGE_RATE" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}INVOICE_CORRECTION" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ORDER_REFERENCE" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}SUPPLIER_ORDER_REFERENCE" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}CUSTOMER_ORDER_REFERENCE" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}DELIVERY_REFERENCE" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}LOGISTIC_DETAILS" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ACCOUNTING_INFO" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}MIME_INFO" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}REMARKS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ITEM_UDX" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.bmecat.org/bmecat/2005}dtSTRING">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="20"/>
 *             &lt;enumeration value="order_item"/>
 *             &lt;enumeration value="extra_item"/>
 *             &lt;enumeration value="pledge_item"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lineitemid",
    "productid",
    "productfeatures",
    "productcomponents",
    "quantity",
    "orderunit",
    "productpricefix",
    "pricelineamount",
    "foreigncurrency",
    "exchangerate",
    "invoicecorrection",
    "orderreference",
    "supplierorderreference",
    "customerorderreference",
    "deliveryreference",
    "logisticdetails",
    "accountinginfo",
    "mimeinfo",
    "remarks",
    "itemudx"
})
@XmlRootElement(name = "INVOICE_ITEM")
public class OT2INVOICEITEM {

    @XmlElement(name = "LINE_ITEM_ID", required = true)
    protected String lineitemid;
    @XmlElement(name = "PRODUCT_ID", required = true)
    protected OT2PRODUCTID productid;
    @XmlElement(name = "PRODUCT_FEATURES")
    protected List<OT2PRODUCTFEATURES> productfeatures;
    @XmlElement(name = "PRODUCT_COMPONENTS")
    protected OT2PRODUCTCOMPONENTS productcomponents;
    @XmlElement(name = "QUANTITY", required = true)
    protected BigDecimal quantity;
    @XmlElement(name = "ORDER_UNIT", namespace = "http://www.bmecat.org/bmecat/2005", required = true)
    protected String orderunit;
    @XmlElement(name = "PRODUCT_PRICE_FIX", required = true)
    protected OT2PRODUCTPRICEFIX productpricefix;
    @XmlElement(name = "PRICE_LINE_AMOUNT", required = true)
    protected BigDecimal pricelineamount;
    @XmlElement(name = "FOREIGN_CURRENCY")
    protected DtCURRENCIES foreigncurrency;
    @XmlElement(name = "EXCHANGE_RATE")
    protected BigDecimal exchangerate;
    @XmlElement(name = "INVOICE_CORRECTION")
    protected OT2INVOICECORRECTION invoicecorrection;
    @XmlElement(name = "ORDER_REFERENCE")
    protected OT2ORDERREFERENCE orderreference;
    @XmlElement(name = "SUPPLIER_ORDER_REFERENCE")
    protected OT2SUPPLIERORDERREFERENCE supplierorderreference;
    @XmlElement(name = "CUSTOMER_ORDER_REFERENCE")
    protected OT2CUSTOMERORDERREFERENCE customerorderreference;
    @XmlElement(name = "DELIVERY_REFERENCE")
    protected OT2DELIVERYREFERENCE deliveryreference;
    @XmlElement(name = "LOGISTIC_DETAILS")
    protected OT2LOGISTICDETAILS logisticdetails;
    @XmlElement(name = "ACCOUNTING_INFO", namespace = "http://www.bmecat.org/bmecat/2005")
    protected BCACCOUNTINGINFO accountinginfo;
    @XmlElement(name = "MIME_INFO")
    protected OT2MIMEINFO mimeinfo;
    @XmlElement(name = "REMARKS")
    protected List<OT2REMARKS> remarks;
    @XmlElement(name = "ITEM_UDX")
    protected UdxITEM itemudx;
    @XmlAttribute
    protected String type;

    /**
     * Gets the value of the lineitemid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLINEITEMID() {
        return lineitemid;
    }

    /**
     * Sets the value of the lineitemid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLINEITEMID(String value) {
        this.lineitemid = value;
    }

    /**
     * Gets the value of the productid property.
     * 
     * @return
     *     possible object is
     *     {@link OT2PRODUCTID }
     *     
     */
    public OT2PRODUCTID getPRODUCTID() {
        return productid;
    }

    /**
     * Sets the value of the productid property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2PRODUCTID }
     *     
     */
    public void setPRODUCTID(OT2PRODUCTID value) {
        this.productid = value;
    }

    /**
     * Gets the value of the productfeatures property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productfeatures property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPRODUCTFEATURES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OT2PRODUCTFEATURES }
     * 
     * 
     */
    public List<OT2PRODUCTFEATURES> getPRODUCTFEATURES() {
        if (productfeatures == null) {
            productfeatures = new ArrayList<OT2PRODUCTFEATURES>();
        }
        return this.productfeatures;
    }

    /**
     * Gets the value of the productcomponents property.
     * 
     * @return
     *     possible object is
     *     {@link OT2PRODUCTCOMPONENTS }
     *     
     */
    public OT2PRODUCTCOMPONENTS getPRODUCTCOMPONENTS() {
        return productcomponents;
    }

    /**
     * Sets the value of the productcomponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2PRODUCTCOMPONENTS }
     *     
     */
    public void setPRODUCTCOMPONENTS(OT2PRODUCTCOMPONENTS value) {
        this.productcomponents = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQUANTITY() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQUANTITY(BigDecimal value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the orderunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDERUNIT() {
        return orderunit;
    }

    /**
     * Sets the value of the orderunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDERUNIT(String value) {
        this.orderunit = value;
    }

    /**
     * Gets the value of the productpricefix property.
     * 
     * @return
     *     possible object is
     *     {@link OT2PRODUCTPRICEFIX }
     *     
     */
    public OT2PRODUCTPRICEFIX getPRODUCTPRICEFIX() {
        return productpricefix;
    }

    /**
     * Sets the value of the productpricefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2PRODUCTPRICEFIX }
     *     
     */
    public void setPRODUCTPRICEFIX(OT2PRODUCTPRICEFIX value) {
        this.productpricefix = value;
    }

    /**
     * Gets the value of the pricelineamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPRICELINEAMOUNT() {
        return pricelineamount;
    }

    /**
     * Sets the value of the pricelineamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPRICELINEAMOUNT(BigDecimal value) {
        this.pricelineamount = value;
    }

    /**
     * Gets the value of the foreigncurrency property.
     * 
     * @return
     *     possible object is
     *     {@link DtCURRENCIES }
     *     
     */
    public DtCURRENCIES getFOREIGNCURRENCY() {
        return foreigncurrency;
    }

    /**
     * Sets the value of the foreigncurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link DtCURRENCIES }
     *     
     */
    public void setFOREIGNCURRENCY(DtCURRENCIES value) {
        this.foreigncurrency = value;
    }

    /**
     * Gets the value of the exchangerate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEXCHANGERATE() {
        return exchangerate;
    }

    /**
     * Sets the value of the exchangerate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEXCHANGERATE(BigDecimal value) {
        this.exchangerate = value;
    }

    /**
     * Gets the value of the invoicecorrection property.
     * 
     * @return
     *     possible object is
     *     {@link OT2INVOICECORRECTION }
     *     
     */
    public OT2INVOICECORRECTION getINVOICECORRECTION() {
        return invoicecorrection;
    }

    /**
     * Sets the value of the invoicecorrection property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2INVOICECORRECTION }
     *     
     */
    public void setINVOICECORRECTION(OT2INVOICECORRECTION value) {
        this.invoicecorrection = value;
    }

    /**
     * Gets the value of the orderreference property.
     * 
     * @return
     *     possible object is
     *     {@link OT2ORDERREFERENCE }
     *     
     */
    public OT2ORDERREFERENCE getORDERREFERENCE() {
        return orderreference;
    }

    /**
     * Sets the value of the orderreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2ORDERREFERENCE }
     *     
     */
    public void setORDERREFERENCE(OT2ORDERREFERENCE value) {
        this.orderreference = value;
    }

    /**
     * Gets the value of the supplierorderreference property.
     * 
     * @return
     *     possible object is
     *     {@link OT2SUPPLIERORDERREFERENCE }
     *     
     */
    public OT2SUPPLIERORDERREFERENCE getSUPPLIERORDERREFERENCE() {
        return supplierorderreference;
    }

    /**
     * Sets the value of the supplierorderreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2SUPPLIERORDERREFERENCE }
     *     
     */
    public void setSUPPLIERORDERREFERENCE(OT2SUPPLIERORDERREFERENCE value) {
        this.supplierorderreference = value;
    }

    /**
     * Gets the value of the customerorderreference property.
     * 
     * @return
     *     possible object is
     *     {@link OT2CUSTOMERORDERREFERENCE }
     *     
     */
    public OT2CUSTOMERORDERREFERENCE getCUSTOMERORDERREFERENCE() {
        return customerorderreference;
    }

    /**
     * Sets the value of the customerorderreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2CUSTOMERORDERREFERENCE }
     *     
     */
    public void setCUSTOMERORDERREFERENCE(OT2CUSTOMERORDERREFERENCE value) {
        this.customerorderreference = value;
    }

    /**
     * Gets the value of the deliveryreference property.
     * 
     * @return
     *     possible object is
     *     {@link OT2DELIVERYREFERENCE }
     *     
     */
    public OT2DELIVERYREFERENCE getDELIVERYREFERENCE() {
        return deliveryreference;
    }

    /**
     * Sets the value of the deliveryreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2DELIVERYREFERENCE }
     *     
     */
    public void setDELIVERYREFERENCE(OT2DELIVERYREFERENCE value) {
        this.deliveryreference = value;
    }

    /**
     * Gets the value of the logisticdetails property.
     * 
     * @return
     *     possible object is
     *     {@link OT2LOGISTICDETAILS }
     *     
     */
    public OT2LOGISTICDETAILS getLOGISTICDETAILS() {
        return logisticdetails;
    }

    /**
     * Sets the value of the logisticdetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2LOGISTICDETAILS }
     *     
     */
    public void setLOGISTICDETAILS(OT2LOGISTICDETAILS value) {
        this.logisticdetails = value;
    }

    /**
     * Gets the value of the accountinginfo property.
     * 
     * @return
     *     possible object is
     *     {@link BCACCOUNTINGINFO }
     *     
     */
    public BCACCOUNTINGINFO getACCOUNTINGINFO() {
        return accountinginfo;
    }

    /**
     * Sets the value of the accountinginfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCACCOUNTINGINFO }
     *     
     */
    public void setACCOUNTINGINFO(BCACCOUNTINGINFO value) {
        this.accountinginfo = value;
    }

    /**
     * Gets the value of the mimeinfo property.
     * 
     * @return
     *     possible object is
     *     {@link OT2MIMEINFO }
     *     
     */
    public OT2MIMEINFO getMIMEINFO() {
        return mimeinfo;
    }

    /**
     * Sets the value of the mimeinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2MIMEINFO }
     *     
     */
    public void setMIMEINFO(OT2MIMEINFO value) {
        this.mimeinfo = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remarks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getREMARKS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OT2REMARKS }
     * 
     * 
     */
    public List<OT2REMARKS> getREMARKS() {
        if (remarks == null) {
            remarks = new ArrayList<OT2REMARKS>();
        }
        return this.remarks;
    }

    /**
     * Gets the value of the itemudx property.
     * 
     * @return
     *     possible object is
     *     {@link UdxITEM }
     *     
     */
    public UdxITEM getITEMUDX() {
        return itemudx;
    }

    /**
     * Sets the value of the itemudx property.
     * 
     * @param value
     *     allowed object is
     *     {@link UdxITEM }
     *     
     */
    public void setITEMUDX(UdxITEM value) {
        this.itemudx = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
