/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.opentrans_2_1;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.lp.server.schema.bmecat_2005.DtCURRENCIES;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}INVOICE_REFERENCE"/>
 *         &lt;sequence>
 *           &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}FOREIGN_CURRENCY" minOccurs="0"/>
 *           &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}FOREIGN_AMOUNT" minOccurs="0"/>
 *           &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}EXCHANGE_RATE" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}NET_VALUE_GOODS"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}NET_VALUE_EXTRA" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ALLOW_OR_CHARGES_FIX" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}TOTAL_TAX"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}TOTAL_AMOUNT"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}REWARDS" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "invoicereference",
    "foreigncurrency",
    "foreignamount",
    "exchangerate",
    "netvaluegoods",
    "netvalueextra",
    "alloworchargesfix",
    "totaltax",
    "totalamount",
    "rewards"
})
@XmlRootElement(name = "IL_INVOICE_LIST_ITEM")
public class OT2ILINVOICELISTITEM {

    @XmlElement(name = "INVOICE_REFERENCE", required = true)
    protected OT2INVOICEREFERENCE invoicereference;
    @XmlElement(name = "FOREIGN_CURRENCY")
    protected DtCURRENCIES foreigncurrency;
    @XmlElement(name = "FOREIGN_AMOUNT")
    protected BigDecimal foreignamount;
    @XmlElement(name = "EXCHANGE_RATE")
    protected BigDecimal exchangerate;
    @XmlElement(name = "NET_VALUE_GOODS", required = true)
    protected BigDecimal netvaluegoods;
    @XmlElement(name = "NET_VALUE_EXTRA")
    protected BigDecimal netvalueextra;
    @XmlElement(name = "ALLOW_OR_CHARGES_FIX")
    protected OT2ALLOWORCHARGESFIX alloworchargesfix;
    @XmlElement(name = "TOTAL_TAX", required = true)
    protected OT2TOTALTAX totaltax;
    @XmlElement(name = "TOTAL_AMOUNT", required = true)
    protected BigDecimal totalamount;
    @XmlElement(name = "REWARDS")
    protected List<OT2REWARDS> rewards;

    /**
     * Gets the value of the invoicereference property.
     * 
     * @return
     *     possible object is
     *     {@link OT2INVOICEREFERENCE }
     *     
     */
    public OT2INVOICEREFERENCE getINVOICEREFERENCE() {
        return invoicereference;
    }

    /**
     * Sets the value of the invoicereference property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2INVOICEREFERENCE }
     *     
     */
    public void setINVOICEREFERENCE(OT2INVOICEREFERENCE value) {
        this.invoicereference = value;
    }

    /**
     * Gets the value of the foreigncurrency property.
     * 
     * @return
     *     possible object is
     *     {@link DtCURRENCIES }
     *     
     */
    public DtCURRENCIES getFOREIGNCURRENCY() {
        return foreigncurrency;
    }

    /**
     * Sets the value of the foreigncurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link DtCURRENCIES }
     *     
     */
    public void setFOREIGNCURRENCY(DtCURRENCIES value) {
        this.foreigncurrency = value;
    }

    /**
     * Gets the value of the foreignamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFOREIGNAMOUNT() {
        return foreignamount;
    }

    /**
     * Sets the value of the foreignamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFOREIGNAMOUNT(BigDecimal value) {
        this.foreignamount = value;
    }

    /**
     * Gets the value of the exchangerate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEXCHANGERATE() {
        return exchangerate;
    }

    /**
     * Sets the value of the exchangerate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEXCHANGERATE(BigDecimal value) {
        this.exchangerate = value;
    }

    /**
     * Gets the value of the netvaluegoods property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNETVALUEGOODS() {
        return netvaluegoods;
    }

    /**
     * Sets the value of the netvaluegoods property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNETVALUEGOODS(BigDecimal value) {
        this.netvaluegoods = value;
    }

    /**
     * Gets the value of the netvalueextra property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNETVALUEEXTRA() {
        return netvalueextra;
    }

    /**
     * Sets the value of the netvalueextra property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNETVALUEEXTRA(BigDecimal value) {
        this.netvalueextra = value;
    }

    /**
     * Gets the value of the alloworchargesfix property.
     * 
     * @return
     *     possible object is
     *     {@link OT2ALLOWORCHARGESFIX }
     *     
     */
    public OT2ALLOWORCHARGESFIX getALLOWORCHARGESFIX() {
        return alloworchargesfix;
    }

    /**
     * Sets the value of the alloworchargesfix property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2ALLOWORCHARGESFIX }
     *     
     */
    public void setALLOWORCHARGESFIX(OT2ALLOWORCHARGESFIX value) {
        this.alloworchargesfix = value;
    }

    /**
     * Gets the value of the totaltax property.
     * 
     * @return
     *     possible object is
     *     {@link OT2TOTALTAX }
     *     
     */
    public OT2TOTALTAX getTOTALTAX() {
        return totaltax;
    }

    /**
     * Sets the value of the totaltax property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2TOTALTAX }
     *     
     */
    public void setTOTALTAX(OT2TOTALTAX value) {
        this.totaltax = value;
    }

    /**
     * Gets the value of the totalamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTOTALAMOUNT() {
        return totalamount;
    }

    /**
     * Sets the value of the totalamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTOTALAMOUNT(BigDecimal value) {
        this.totalamount = value;
    }

    /**
     * Gets the value of the rewards property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rewards property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getREWARDS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OT2REWARDS }
     * 
     * 
     */
    public List<OT2REWARDS> getREWARDS() {
        if (rewards == null) {
            rewards = new ArrayList<OT2REWARDS>();
        }
        return this.rewards;
    }

}
