/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2015 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.opentrans_2_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}RFQ"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}QUOTATION"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ORDER"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ORDERCHANGE"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ORDERRESPONSE"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}DISPATCHNOTIFICATION"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}RECEIPTACKNOWLEDGEMENT"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}INVOICE"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}INVOICELIST"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}REMITTANCEADVICE"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rfq",
    "quotation",
    "order",
    "orderchange",
    "orderresponse",
    "dispatchnotification",
    "receiptacknowledgement",
    "invoice",
    "invoicelist",
    "remittanceadvice"
})
@XmlRootElement(name = "OPENTRANS")
public class OT2OPENTRANS {

    @XmlElement(name = "RFQ")
    protected OT2RFQ rfq;
    @XmlElement(name = "QUOTATION")
    protected OT2QUOTATION quotation;
    @XmlElement(name = "ORDER")
    protected OT2ORDER order;
    @XmlElement(name = "ORDERCHANGE")
    protected OT2ORDERCHANGE orderchange;
    @XmlElement(name = "ORDERRESPONSE")
    protected OT2ORDERRESPONSE orderresponse;
    @XmlElement(name = "DISPATCHNOTIFICATION")
    protected OT2DISPATCHNOTIFICATION dispatchnotification;
    @XmlElement(name = "RECEIPTACKNOWLEDGEMENT")
    protected OT2RECEIPTACKNOWLEDGEMENT receiptacknowledgement;
    @XmlElement(name = "INVOICE")
    protected OT2INVOICE invoice;
    @XmlElement(name = "INVOICELIST")
    protected OT2INVOICELIST invoicelist;
    @XmlElement(name = "REMITTANCEADVICE")
    protected OT2REMITTANCEADVICE remittanceadvice;

    /**
     * Gets the value of the rfq property.
     * 
     * @return
     *     possible object is
     *     {@link OT2RFQ }
     *     
     */
    public OT2RFQ getRFQ() {
        return rfq;
    }

    /**
     * Sets the value of the rfq property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2RFQ }
     *     
     */
    public void setRFQ(OT2RFQ value) {
        this.rfq = value;
    }

    /**
     * Gets the value of the quotation property.
     * 
     * @return
     *     possible object is
     *     {@link OT2QUOTATION }
     *     
     */
    public OT2QUOTATION getQUOTATION() {
        return quotation;
    }

    /**
     * Sets the value of the quotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2QUOTATION }
     *     
     */
    public void setQUOTATION(OT2QUOTATION value) {
        this.quotation = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link OT2ORDER }
     *     
     */
    public OT2ORDER getORDER() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2ORDER }
     *     
     */
    public void setORDER(OT2ORDER value) {
        this.order = value;
    }

    /**
     * Gets the value of the orderchange property.
     * 
     * @return
     *     possible object is
     *     {@link OT2ORDERCHANGE }
     *     
     */
    public OT2ORDERCHANGE getORDERCHANGE() {
        return orderchange;
    }

    /**
     * Sets the value of the orderchange property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2ORDERCHANGE }
     *     
     */
    public void setORDERCHANGE(OT2ORDERCHANGE value) {
        this.orderchange = value;
    }

    /**
     * Gets the value of the orderresponse property.
     * 
     * @return
     *     possible object is
     *     {@link OT2ORDERRESPONSE }
     *     
     */
    public OT2ORDERRESPONSE getORDERRESPONSE() {
        return orderresponse;
    }

    /**
     * Sets the value of the orderresponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2ORDERRESPONSE }
     *     
     */
    public void setORDERRESPONSE(OT2ORDERRESPONSE value) {
        this.orderresponse = value;
    }

    /**
     * Gets the value of the dispatchnotification property.
     * 
     * @return
     *     possible object is
     *     {@link OT2DISPATCHNOTIFICATION }
     *     
     */
    public OT2DISPATCHNOTIFICATION getDISPATCHNOTIFICATION() {
        return dispatchnotification;
    }

    /**
     * Sets the value of the dispatchnotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2DISPATCHNOTIFICATION }
     *     
     */
    public void setDISPATCHNOTIFICATION(OT2DISPATCHNOTIFICATION value) {
        this.dispatchnotification = value;
    }

    /**
     * Gets the value of the receiptacknowledgement property.
     * 
     * @return
     *     possible object is
     *     {@link OT2RECEIPTACKNOWLEDGEMENT }
     *     
     */
    public OT2RECEIPTACKNOWLEDGEMENT getRECEIPTACKNOWLEDGEMENT() {
        return receiptacknowledgement;
    }

    /**
     * Sets the value of the receiptacknowledgement property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2RECEIPTACKNOWLEDGEMENT }
     *     
     */
    public void setRECEIPTACKNOWLEDGEMENT(OT2RECEIPTACKNOWLEDGEMENT value) {
        this.receiptacknowledgement = value;
    }

    /**
     * Gets the value of the invoice property.
     * 
     * @return
     *     possible object is
     *     {@link OT2INVOICE }
     *     
     */
    public OT2INVOICE getINVOICE() {
        return invoice;
    }

    /**
     * Sets the value of the invoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2INVOICE }
     *     
     */
    public void setINVOICE(OT2INVOICE value) {
        this.invoice = value;
    }

    /**
     * Gets the value of the invoicelist property.
     * 
     * @return
     *     possible object is
     *     {@link OT2INVOICELIST }
     *     
     */
    public OT2INVOICELIST getINVOICELIST() {
        return invoicelist;
    }

    /**
     * Sets the value of the invoicelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2INVOICELIST }
     *     
     */
    public void setINVOICELIST(OT2INVOICELIST value) {
        this.invoicelist = value;
    }

    /**
     * Gets the value of the remittanceadvice property.
     * 
     * @return
     *     possible object is
     *     {@link OT2REMITTANCEADVICE }
     *     
     */
    public OT2REMITTANCEADVICE getREMITTANCEADVICE() {
        return remittanceadvice;
    }

    /**
     * Sets the value of the remittanceadvice property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2REMITTANCEADVICE }
     *     
     */
    public void setREMITTANCEADVICE(OT2REMITTANCEADVICE value) {
        this.remittanceadvice = value;
    }

}
