/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.opentrans_2_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}CARD"/>
 *           &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ACCOUNT" maxOccurs="unbounded"/>
 *           &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}DEBIT"/>
 *           &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}CHECK"/>
 *           &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}CASH"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}CENTRAL_REGULATION" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PAYMENT_TERMS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "card",
    "account",
    "debit",
    "check",
    "cash",
    "centralregulation",
    "paymentterms"
})
@XmlRootElement(name = "PAYMENT")
public class OT2PAYMENT {

    @XmlElement(name = "CARD")
    protected OT2CARD card;
    @XmlElement(name = "ACCOUNT")
    protected List<OT2ACCOUNT> account;
    @XmlElement(name = "DEBIT")
    protected String debit;
    @XmlElement(name = "CHECK")
    protected String check;
    @XmlElement(name = "CASH")
    protected String cash;
    @XmlElement(name = "CENTRAL_REGULATION", defaultValue = "false")
    protected String centralregulation;
    @XmlElement(name = "PAYMENT_TERMS")
    protected OT2PAYMENTTERMS paymentterms;

    /**
     * Gets the value of the card property.
     * 
     * @return
     *     possible object is
     *     {@link OT2CARD }
     *     
     */
    public OT2CARD getCARD() {
        return card;
    }

    /**
     * Sets the value of the card property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2CARD }
     *     
     */
    public void setCARD(OT2CARD value) {
        this.card = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the account property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getACCOUNT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OT2ACCOUNT }
     * 
     * 
     */
    public List<OT2ACCOUNT> getACCOUNT() {
        if (account == null) {
            account = new ArrayList<OT2ACCOUNT>();
        }
        return this.account;
    }

    /**
     * Gets the value of the debit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEBIT() {
        return debit;
    }

    /**
     * Sets the value of the debit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEBIT(String value) {
        this.debit = value;
    }

    /**
     * Gets the value of the check property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHECK() {
        return check;
    }

    /**
     * Sets the value of the check property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHECK(String value) {
        this.check = value;
    }

    /**
     * Gets the value of the cash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCASH() {
        return cash;
    }

    /**
     * Sets the value of the cash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCASH(String value) {
        this.cash = value;
    }

    /**
     * Gets the value of the centralregulation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCENTRALREGULATION() {
        return centralregulation;
    }

    /**
     * Sets the value of the centralregulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCENTRALREGULATION(String value) {
        this.centralregulation = value;
    }

    /**
     * Gets the value of the paymentterms property.
     * 
     * @return
     *     possible object is
     *     {@link OT2PAYMENTTERMS }
     *     
     */
    public OT2PAYMENTTERMS getPAYMENTTERMS() {
        return paymentterms;
    }

    /**
     * Sets the value of the paymentterms property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2PAYMENTTERMS }
     *     
     */
    public void setPAYMENTTERMS(OT2PAYMENTTERMS value) {
        this.paymentterms = value;
    }

}
