/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.opentrans_2_1;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PRODUCT_ID"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PRODUCT_FEATURES" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PRODUCT_COMPONENTS" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}QUANTITY"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ORDER_UNIT"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PRODUCT_PRICE_FIX" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "productid",
    "productfeatures",
    "productcomponents",
    "quantity",
    "orderunit",
    "productpricefix"
})
@XmlRootElement(name = "PRODUCT_COMPONENT")
public class OT2PRODUCTCOMPONENT {

    @XmlElement(name = "PRODUCT_ID", required = true)
    protected OT2PRODUCTID productid;
    @XmlElement(name = "PRODUCT_FEATURES")
    protected OT2PRODUCTFEATURES productfeatures;
    @XmlElement(name = "PRODUCT_COMPONENTS")
    protected OT2PRODUCTCOMPONENTS productcomponents;
    @XmlElement(name = "QUANTITY", required = true)
    protected BigDecimal quantity;
    @XmlElement(name = "ORDER_UNIT", namespace = "http://www.bmecat.org/bmecat/2005", required = true)
    protected String orderunit;
    @XmlElement(name = "PRODUCT_PRICE_FIX")
    protected OT2PRODUCTPRICEFIX productpricefix;

    /**
     * Gets the value of the productid property.
     * 
     * @return
     *     possible object is
     *     {@link OT2PRODUCTID }
     *     
     */
    public OT2PRODUCTID getPRODUCTID() {
        return productid;
    }

    /**
     * Sets the value of the productid property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2PRODUCTID }
     *     
     */
    public void setPRODUCTID(OT2PRODUCTID value) {
        this.productid = value;
    }

    /**
     * Gets the value of the productfeatures property.
     * 
     * @return
     *     possible object is
     *     {@link OT2PRODUCTFEATURES }
     *     
     */
    public OT2PRODUCTFEATURES getPRODUCTFEATURES() {
        return productfeatures;
    }

    /**
     * Sets the value of the productfeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2PRODUCTFEATURES }
     *     
     */
    public void setPRODUCTFEATURES(OT2PRODUCTFEATURES value) {
        this.productfeatures = value;
    }

    /**
     * Gets the value of the productcomponents property.
     * 
     * @return
     *     possible object is
     *     {@link OT2PRODUCTCOMPONENTS }
     *     
     */
    public OT2PRODUCTCOMPONENTS getPRODUCTCOMPONENTS() {
        return productcomponents;
    }

    /**
     * Sets the value of the productcomponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2PRODUCTCOMPONENTS }
     *     
     */
    public void setPRODUCTCOMPONENTS(OT2PRODUCTCOMPONENTS value) {
        this.productcomponents = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQUANTITY() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQUANTITY(BigDecimal value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the orderunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDERUNIT() {
        return orderunit;
    }

    /**
     * Sets the value of the orderunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDERUNIT(String value) {
        this.orderunit = value;
    }

    /**
     * Gets the value of the productpricefix property.
     * 
     * @return
     *     possible object is
     *     {@link OT2PRODUCTPRICEFIX }
     *     
     */
    public OT2PRODUCTPRICEFIX getPRODUCTPRICEFIX() {
        return productpricefix;
    }

    /**
     * Sets the value of the productpricefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2PRODUCTPRICEFIX }
     *     
     */
    public void setPRODUCTPRICEFIX(OT2PRODUCTPRICEFIX value) {
        this.productpricefix = value;
    }

}
