/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.opentrans_2_1;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.lp.server.schema.bmecat_2005.BCPACKINGUNITDESCR;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PACKAGE_ID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PACKAGE_DESCR" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PACKING_UNIT_CODE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PACKING_UNIT_DESCR" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PACKAGE_ORDER_UNIT_QUANTITY" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PACKAGE_QUANTITY" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PACKAGE_DIMENSIONS" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}MEANS_OF_TRANSPORT_IDREF" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}SUB_PACKAGES" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "packageid",
    "packagedescr",
    "packingunitcode",
    "packingunitdescr",
    "packageorderunitquantity",
    "packagequantity",
    "packagedimensions",
    "meansoftransportidref",
    "subpackages"
})
@XmlRootElement(name = "PACKAGE")
public class OT2PACKAGE {

    @XmlElement(name = "PACKAGE_ID")
    protected List<OT2PACKAGEID> packageid;
    @XmlElement(name = "PACKAGE_DESCR")
    protected List<OT2PACKAGEDESCR> packagedescr;
    @XmlElement(name = "PACKING_UNIT_CODE", namespace = "http://www.bmecat.org/bmecat/2005")
    protected String packingunitcode;
    @XmlElement(name = "PACKING_UNIT_DESCR", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<BCPACKINGUNITDESCR> packingunitdescr;
    @XmlElement(name = "PACKAGE_ORDER_UNIT_QUANTITY")
    protected BigDecimal packageorderunitquantity;
    @XmlElement(name = "PACKAGE_QUANTITY")
    protected BigDecimal packagequantity;
    @XmlElement(name = "PACKAGE_DIMENSIONS")
    protected OT2PACKAGEDIMENSIONS packagedimensions;
    @XmlElement(name = "MEANS_OF_TRANSPORT_IDREF")
    protected List<String> meansoftransportidref;
    @XmlElement(name = "SUB_PACKAGES")
    protected OT2SUBPACKAGES subpackages;

    /**
     * Gets the value of the packageid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packageid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPACKAGEID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OT2PACKAGEID }
     * 
     * 
     */
    public List<OT2PACKAGEID> getPACKAGEID() {
        if (packageid == null) {
            packageid = new ArrayList<OT2PACKAGEID>();
        }
        return this.packageid;
    }

    /**
     * Gets the value of the packagedescr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packagedescr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPACKAGEDESCR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OT2PACKAGEDESCR }
     * 
     * 
     */
    public List<OT2PACKAGEDESCR> getPACKAGEDESCR() {
        if (packagedescr == null) {
            packagedescr = new ArrayList<OT2PACKAGEDESCR>();
        }
        return this.packagedescr;
    }

    /**
     * Gets the value of the packingunitcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPACKINGUNITCODE() {
        return packingunitcode;
    }

    /**
     * Sets the value of the packingunitcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPACKINGUNITCODE(String value) {
        this.packingunitcode = value;
    }

    /**
     * Gets the value of the packingunitdescr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packingunitdescr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPACKINGUNITDESCR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCPACKINGUNITDESCR }
     * 
     * 
     */
    public List<BCPACKINGUNITDESCR> getPACKINGUNITDESCR() {
        if (packingunitdescr == null) {
            packingunitdescr = new ArrayList<BCPACKINGUNITDESCR>();
        }
        return this.packingunitdescr;
    }

    /**
     * Gets the value of the packageorderunitquantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPACKAGEORDERUNITQUANTITY() {
        return packageorderunitquantity;
    }

    /**
     * Sets the value of the packageorderunitquantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPACKAGEORDERUNITQUANTITY(BigDecimal value) {
        this.packageorderunitquantity = value;
    }

    /**
     * Gets the value of the packagequantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPACKAGEQUANTITY() {
        return packagequantity;
    }

    /**
     * Sets the value of the packagequantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPACKAGEQUANTITY(BigDecimal value) {
        this.packagequantity = value;
    }

    /**
     * Gets the value of the packagedimensions property.
     * 
     * @return
     *     possible object is
     *     {@link OT2PACKAGEDIMENSIONS }
     *     
     */
    public OT2PACKAGEDIMENSIONS getPACKAGEDIMENSIONS() {
        return packagedimensions;
    }

    /**
     * Sets the value of the packagedimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2PACKAGEDIMENSIONS }
     *     
     */
    public void setPACKAGEDIMENSIONS(OT2PACKAGEDIMENSIONS value) {
        this.packagedimensions = value;
    }

    /**
     * Gets the value of the meansoftransportidref property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meansoftransportidref property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMEANSOFTRANSPORTIDREF().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMEANSOFTRANSPORTIDREF() {
        if (meansoftransportidref == null) {
            meansoftransportidref = new ArrayList<String>();
        }
        return this.meansoftransportidref;
    }

    /**
     * Gets the value of the subpackages property.
     * 
     * @return
     *     possible object is
     *     {@link OT2SUBPACKAGES }
     *     
     */
    public OT2SUBPACKAGES getSUBPACKAGES() {
        return subpackages;
    }

    /**
     * Sets the value of the subpackages property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2SUBPACKAGES }
     *     
     */
    public void setSUBPACKAGES(OT2SUBPACKAGES value) {
        this.subpackages = value;
    }

}
