/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.opentrans_2_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.lp.server.schema.bmecat_2005.BCBUYERPID;
import com.lp.server.schema.bmecat_2005.BCDESCRIPTIONLONG;
import com.lp.server.schema.bmecat_2005.BCDESCRIPTIONSHORT;
import com.lp.server.schema.bmecat_2005.BCINTERNATIONALPID;
import com.lp.server.schema.bmecat_2005.BCSUPPLIERPID;
import com.lp.server.schema.bmecat_2005.TypePARTYID;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_PID" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}CONFIG_CODE_FIX" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}LOT_NUMBER" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}SERIAL_NUMBER" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}INTERNATIONAL_PID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}BUYER_PID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}DESCRIPTION_SHORT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}DESCRIPTION_LONG" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}MANUFACTURER_INFO" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_TYPE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "supplierpid",
    "supplieridref",
    "configcodefix",
    "lotnumber",
    "serialnumber",
    "internationalpid",
    "buyerpid",
    "descriptionshort",
    "descriptionlong",
    "manufacturerinfo",
    "producttype"
})
@XmlRootElement(name = "PRODUCT_ID")
public class OT2PRODUCTID {

    @XmlElement(name = "SUPPLIER_PID", namespace = "http://www.bmecat.org/bmecat/2005")
    protected BCSUPPLIERPID supplierpid;
    @XmlElement(name = "SUPPLIER_IDREF", namespace = "http://www.bmecat.org/bmecat/2005")
    protected TypePARTYID supplieridref;
    @XmlElement(name = "CONFIG_CODE_FIX")
    protected String configcodefix;
    @XmlElement(name = "LOT_NUMBER")
    protected List<String> lotnumber;
    @XmlElement(name = "SERIAL_NUMBER")
    protected List<String> serialnumber;
    @XmlElement(name = "INTERNATIONAL_PID", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<BCINTERNATIONALPID> internationalpid;
    @XmlElement(name = "BUYER_PID", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<BCBUYERPID> buyerpid;
    @XmlElement(name = "DESCRIPTION_SHORT", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<BCDESCRIPTIONSHORT> descriptionshort;
    @XmlElement(name = "DESCRIPTION_LONG", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<BCDESCRIPTIONLONG> descriptionlong;
    @XmlElement(name = "MANUFACTURER_INFO")
    protected OT2MANUFACTURERINFO manufacturerinfo;
    @XmlElement(name = "PRODUCT_TYPE", namespace = "http://www.bmecat.org/bmecat/2005")
    protected String producttype;

    /**
     * Gets the value of the supplierpid property.
     * 
     * @return
     *     possible object is
     *     {@link BCSUPPLIERPID }
     *     
     */
    public BCSUPPLIERPID getSUPPLIERPID() {
        return supplierpid;
    }

    /**
     * Sets the value of the supplierpid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCSUPPLIERPID }
     *     
     */
    public void setSUPPLIERPID(BCSUPPLIERPID value) {
        this.supplierpid = value;
    }

    /**
     * Gets the value of the supplieridref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getSUPPLIERIDREF() {
        return supplieridref;
    }

    /**
     * Sets the value of the supplieridref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setSUPPLIERIDREF(TypePARTYID value) {
        this.supplieridref = value;
    }

    /**
     * Gets the value of the configcodefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONFIGCODEFIX() {
        return configcodefix;
    }

    /**
     * Sets the value of the configcodefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONFIGCODEFIX(String value) {
        this.configcodefix = value;
    }

    /**
     * Gets the value of the lotnumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lotnumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLOTNUMBER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLOTNUMBER() {
        if (lotnumber == null) {
            lotnumber = new ArrayList<String>();
        }
        return this.lotnumber;
    }

    /**
     * Gets the value of the serialnumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serialnumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSERIALNUMBER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSERIALNUMBER() {
        if (serialnumber == null) {
            serialnumber = new ArrayList<String>();
        }
        return this.serialnumber;
    }

    /**
     * Gets the value of the internationalpid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the internationalpid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getINTERNATIONALPID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCINTERNATIONALPID }
     * 
     * 
     */
    public List<BCINTERNATIONALPID> getINTERNATIONALPID() {
        if (internationalpid == null) {
            internationalpid = new ArrayList<BCINTERNATIONALPID>();
        }
        return this.internationalpid;
    }

    /**
     * Gets the value of the buyerpid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the buyerpid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBUYERPID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCBUYERPID }
     * 
     * 
     */
    public List<BCBUYERPID> getBUYERPID() {
        if (buyerpid == null) {
            buyerpid = new ArrayList<BCBUYERPID>();
        }
        return this.buyerpid;
    }

    /**
     * Gets the value of the descriptionshort property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descriptionshort property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDESCRIPTIONSHORT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCDESCRIPTIONSHORT }
     * 
     * 
     */
    public List<BCDESCRIPTIONSHORT> getDESCRIPTIONSHORT() {
        if (descriptionshort == null) {
            descriptionshort = new ArrayList<BCDESCRIPTIONSHORT>();
        }
        return this.descriptionshort;
    }

    /**
     * Gets the value of the descriptionlong property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descriptionlong property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDESCRIPTIONLONG().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCDESCRIPTIONLONG }
     * 
     * 
     */
    public List<BCDESCRIPTIONLONG> getDESCRIPTIONLONG() {
        if (descriptionlong == null) {
            descriptionlong = new ArrayList<BCDESCRIPTIONLONG>();
        }
        return this.descriptionlong;
    }

    /**
     * Gets the value of the manufacturerinfo property.
     * 
     * @return
     *     possible object is
     *     {@link OT2MANUFACTURERINFO }
     *     
     */
    public OT2MANUFACTURERINFO getMANUFACTURERINFO() {
        return manufacturerinfo;
    }

    /**
     * Sets the value of the manufacturerinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2MANUFACTURERINFO }
     *     
     */
    public void setMANUFACTURERINFO(OT2MANUFACTURERINFO value) {
        this.manufacturerinfo = value;
    }

    /**
     * Gets the value of the producttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODUCTTYPE() {
        return producttype;
    }

    /**
     * Sets the value of the producttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODUCTTYPE(String value) {
        this.producttype = value;
    }

}
