/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.opentrans_2_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.lp.server.schema.bmecat_2005.BCINTERNATIONALRESTRICTIONS;
import com.lp.server.schema.bmecat_2005.BCLANGUAGE;
import com.lp.server.schema.bmecat_2005.BCMIMEROOT;
import com.lp.server.schema.bmecat_2005.BCTRANSPORT;
import com.lp.server.schema.bmecat_2005.DtCURRENCIES;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}QUOTATION_ID"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}QUOTATION_DATE"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}VALID_START_DATE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}VALID_END_DATE" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}DELIVERY_DATE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}LANGUAGE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}MIME_ROOT" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PARTIES"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ORDER_PARTIES_REFERENCE"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}DOCEXCHANGE_PARTIES_REFERENCE" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}AGREEMENT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}CATALOG_REFERENCE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CURRENCY"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PAYMENT" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}TERMS_AND_CONDITIONS" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}TRANSPORT" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}INTERNATIONAL_RESTRICTIONS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}TERRITORY" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}MIME_INFO" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}REMARKS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}HEADER_UDX" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "quotationid",
    "quotationdate",
    "validstartdate",
    "validenddate",
    "deliverydate",
    "language",
    "mimeroot",
    "parties",
    "orderpartiesreference",
    "docexchangepartiesreference",
    "agreement",
    "catalogreference",
    "currency",
    "payment",
    "termsandconditions",
    "transport",
    "internationalrestrictions",
    "territory",
    "mimeinfo",
    "remarks",
    "headerudx"
})
@XmlRootElement(name = "QUOTATION_INFO")
public class OT2QUOTATIONINFO {

    @XmlElement(name = "QUOTATION_ID", required = true)
    protected String quotationid;
    @XmlElement(name = "QUOTATION_DATE", required = true)
    protected String quotationdate;
    @XmlElement(name = "VALID_START_DATE", namespace = "http://www.bmecat.org/bmecat/2005")
    protected String validstartdate;
    @XmlElement(name = "VALID_END_DATE", namespace = "http://www.bmecat.org/bmecat/2005")
    protected String validenddate;
    @XmlElement(name = "DELIVERY_DATE")
    protected OT2DELIVERYDATE deliverydate;
    @XmlElement(name = "LANGUAGE", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<BCLANGUAGE> language;
    @XmlElement(name = "MIME_ROOT", namespace = "http://www.bmecat.org/bmecat/2005")
    protected BCMIMEROOT mimeroot;
    @XmlElement(name = "PARTIES", required = true)
    protected OT2PARTIES parties;
    @XmlElement(name = "ORDER_PARTIES_REFERENCE", required = true)
    protected OT2ORDERPARTIESREFERENCE orderpartiesreference;
    @XmlElement(name = "DOCEXCHANGE_PARTIES_REFERENCE")
    protected OT2DOCEXCHANGEPARTIESREFERENCE docexchangepartiesreference;
    @XmlElement(name = "AGREEMENT")
    protected List<OT2AGREEMENT> agreement;
    @XmlElement(name = "CATALOG_REFERENCE")
    protected OT2CATALOGREFERENCE catalogreference;
    @XmlElement(name = "CURRENCY", namespace = "http://www.bmecat.org/bmecat/2005", required = true)
    protected DtCURRENCIES currency;
    @XmlElement(name = "PAYMENT")
    protected OT2PAYMENT payment;
    @XmlElement(name = "TERMS_AND_CONDITIONS")
    protected String termsandconditions;
    @XmlElement(name = "TRANSPORT", namespace = "http://www.bmecat.org/bmecat/2005")
    protected BCTRANSPORT transport;
    @XmlElement(name = "INTERNATIONAL_RESTRICTIONS", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<BCINTERNATIONALRESTRICTIONS> internationalrestrictions;
    @XmlElement(name = "TERRITORY", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<String> territory;
    @XmlElement(name = "MIME_INFO")
    protected OT2MIMEINFO mimeinfo;
    @XmlElement(name = "REMARKS")
    protected List<OT2REMARKS> remarks;
    @XmlElement(name = "HEADER_UDX")
    protected UdxHEADER headerudx;

    /**
     * Gets the value of the quotationid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQUOTATIONID() {
        return quotationid;
    }

    /**
     * Sets the value of the quotationid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQUOTATIONID(String value) {
        this.quotationid = value;
    }

    /**
     * Gets the value of the quotationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQUOTATIONDATE() {
        return quotationdate;
    }

    /**
     * Sets the value of the quotationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQUOTATIONDATE(String value) {
        this.quotationdate = value;
    }

    /**
     * Gets the value of the validstartdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALIDSTARTDATE() {
        return validstartdate;
    }

    /**
     * Sets the value of the validstartdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALIDSTARTDATE(String value) {
        this.validstartdate = value;
    }

    /**
     * Gets the value of the validenddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALIDENDDATE() {
        return validenddate;
    }

    /**
     * Sets the value of the validenddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALIDENDDATE(String value) {
        this.validenddate = value;
    }

    /**
     * Gets the value of the deliverydate property.
     * 
     * @return
     *     possible object is
     *     {@link OT2DELIVERYDATE }
     *     
     */
    public OT2DELIVERYDATE getDELIVERYDATE() {
        return deliverydate;
    }

    /**
     * Sets the value of the deliverydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2DELIVERYDATE }
     *     
     */
    public void setDELIVERYDATE(OT2DELIVERYDATE value) {
        this.deliverydate = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLANGUAGE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCLANGUAGE }
     * 
     * 
     */
    public List<BCLANGUAGE> getLANGUAGE() {
        if (language == null) {
            language = new ArrayList<BCLANGUAGE>();
        }
        return this.language;
    }

    /**
     * Gets the value of the mimeroot property.
     * 
     * @return
     *     possible object is
     *     {@link BCMIMEROOT }
     *     
     */
    public BCMIMEROOT getMIMEROOT() {
        return mimeroot;
    }

    /**
     * Sets the value of the mimeroot property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCMIMEROOT }
     *     
     */
    public void setMIMEROOT(BCMIMEROOT value) {
        this.mimeroot = value;
    }

    /**
     * Gets the value of the parties property.
     * 
     * @return
     *     possible object is
     *     {@link OT2PARTIES }
     *     
     */
    public OT2PARTIES getPARTIES() {
        return parties;
    }

    /**
     * Sets the value of the parties property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2PARTIES }
     *     
     */
    public void setPARTIES(OT2PARTIES value) {
        this.parties = value;
    }

    /**
     * Gets the value of the orderpartiesreference property.
     * 
     * @return
     *     possible object is
     *     {@link OT2ORDERPARTIESREFERENCE }
     *     
     */
    public OT2ORDERPARTIESREFERENCE getORDERPARTIESREFERENCE() {
        return orderpartiesreference;
    }

    /**
     * Sets the value of the orderpartiesreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2ORDERPARTIESREFERENCE }
     *     
     */
    public void setORDERPARTIESREFERENCE(OT2ORDERPARTIESREFERENCE value) {
        this.orderpartiesreference = value;
    }

    /**
     * Gets the value of the docexchangepartiesreference property.
     * 
     * @return
     *     possible object is
     *     {@link OT2DOCEXCHANGEPARTIESREFERENCE }
     *     
     */
    public OT2DOCEXCHANGEPARTIESREFERENCE getDOCEXCHANGEPARTIESREFERENCE() {
        return docexchangepartiesreference;
    }

    /**
     * Sets the value of the docexchangepartiesreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2DOCEXCHANGEPARTIESREFERENCE }
     *     
     */
    public void setDOCEXCHANGEPARTIESREFERENCE(OT2DOCEXCHANGEPARTIESREFERENCE value) {
        this.docexchangepartiesreference = value;
    }

    /**
     * Gets the value of the agreement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agreement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAGREEMENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OT2AGREEMENT }
     * 
     * 
     */
    public List<OT2AGREEMENT> getAGREEMENT() {
        if (agreement == null) {
            agreement = new ArrayList<OT2AGREEMENT>();
        }
        return this.agreement;
    }

    /**
     * Gets the value of the catalogreference property.
     * 
     * @return
     *     possible object is
     *     {@link OT2CATALOGREFERENCE }
     *     
     */
    public OT2CATALOGREFERENCE getCATALOGREFERENCE() {
        return catalogreference;
    }

    /**
     * Sets the value of the catalogreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2CATALOGREFERENCE }
     *     
     */
    public void setCATALOGREFERENCE(OT2CATALOGREFERENCE value) {
        this.catalogreference = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link DtCURRENCIES }
     *     
     */
    public DtCURRENCIES getCURRENCY() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link DtCURRENCIES }
     *     
     */
    public void setCURRENCY(DtCURRENCIES value) {
        this.currency = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link OT2PAYMENT }
     *     
     */
    public OT2PAYMENT getPAYMENT() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2PAYMENT }
     *     
     */
    public void setPAYMENT(OT2PAYMENT value) {
        this.payment = value;
    }

    /**
     * Gets the value of the termsandconditions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTERMSANDCONDITIONS() {
        return termsandconditions;
    }

    /**
     * Sets the value of the termsandconditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTERMSANDCONDITIONS(String value) {
        this.termsandconditions = value;
    }

    /**
     * Gets the value of the transport property.
     * 
     * @return
     *     possible object is
     *     {@link BCTRANSPORT }
     *     
     */
    public BCTRANSPORT getTRANSPORT() {
        return transport;
    }

    /**
     * Sets the value of the transport property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCTRANSPORT }
     *     
     */
    public void setTRANSPORT(BCTRANSPORT value) {
        this.transport = value;
    }

    /**
     * Gets the value of the internationalrestrictions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the internationalrestrictions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getINTERNATIONALRESTRICTIONS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCINTERNATIONALRESTRICTIONS }
     * 
     * 
     */
    public List<BCINTERNATIONALRESTRICTIONS> getINTERNATIONALRESTRICTIONS() {
        if (internationalrestrictions == null) {
            internationalrestrictions = new ArrayList<BCINTERNATIONALRESTRICTIONS>();
        }
        return this.internationalrestrictions;
    }

    /**
     * Gets the value of the territory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the territory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTERRITORY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTERRITORY() {
        if (territory == null) {
            territory = new ArrayList<String>();
        }
        return this.territory;
    }

    /**
     * Gets the value of the mimeinfo property.
     * 
     * @return
     *     possible object is
     *     {@link OT2MIMEINFO }
     *     
     */
    public OT2MIMEINFO getMIMEINFO() {
        return mimeinfo;
    }

    /**
     * Sets the value of the mimeinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2MIMEINFO }
     *     
     */
    public void setMIMEINFO(OT2MIMEINFO value) {
        this.mimeinfo = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remarks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getREMARKS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OT2REMARKS }
     * 
     * 
     */
    public List<OT2REMARKS> getREMARKS() {
        if (remarks == null) {
            remarks = new ArrayList<OT2REMARKS>();
        }
        return this.remarks;
    }

    /**
     * Gets the value of the headerudx property.
     * 
     * @return
     *     possible object is
     *     {@link UdxHEADER }
     *     
     */
    public UdxHEADER getHEADERUDX() {
        return headerudx;
    }

    /**
     * Sets the value of the headerudx property.
     * 
     * @param value
     *     allowed object is
     *     {@link UdxHEADER }
     *     
     */
    public void setHEADERUDX(UdxHEADER value) {
        this.headerudx = value;
    }

}
