/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2015 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.opentrans_2_1;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.lp.server.schema.bmecat_2005.TypePARTYID;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}LINE_ITEM_ID"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PRODUCT_ID"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}QUANTITY"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ORDER_UNIT"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}DELIVERY_COMPLETED" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}RECEIPT_DATE" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ORDER_REFERENCE"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}SUPPLIER_ORDER_REFERENCE" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}CUSTOMER_ORDER_REFERENCE" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}DELIVERY_REFERENCE"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}DELIVERY_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}FINAL_DELIVERY_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}MIME_INFO" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}REMARKS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ITEM_UDX" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lineitemid",
    "productid",
    "quantity",
    "orderunit",
    "deliverycompleted",
    "receiptdate",
    "orderreference",
    "supplierorderreference",
    "customerorderreference",
    "deliveryreference",
    "supplieridref",
    "deliveryidref",
    "finaldeliveryidref",
    "mimeinfo",
    "remarks",
    "itemudx"
})
@XmlRootElement(name = "RECEIPTACKNOWLEDGEMENT_ITEM")
public class OT2RECEIPTACKNOWLEDGEMENTITEM {

    @XmlElement(name = "LINE_ITEM_ID", required = true)
    protected String lineitemid;
    @XmlElement(name = "PRODUCT_ID", required = true)
    protected OT2PRODUCTID productid;
    @XmlElement(name = "QUANTITY", required = true)
    protected BigDecimal quantity;
    @XmlElement(name = "ORDER_UNIT", namespace = "http://www.bmecat.org/bmecat/2005", required = true)
    protected String orderunit;
    @XmlElement(name = "DELIVERY_COMPLETED")
    protected String deliverycompleted;
    @XmlElement(name = "RECEIPT_DATE")
    protected String receiptdate;
    @XmlElement(name = "ORDER_REFERENCE", required = true)
    protected OT2ORDERREFERENCE orderreference;
    @XmlElement(name = "SUPPLIER_ORDER_REFERENCE")
    protected OT2SUPPLIERORDERREFERENCE supplierorderreference;
    @XmlElement(name = "CUSTOMER_ORDER_REFERENCE")
    protected OT2CUSTOMERORDERREFERENCE customerorderreference;
    @XmlElement(name = "DELIVERY_REFERENCE", required = true)
    protected OT2DELIVERYREFERENCE deliveryreference;
    @XmlElement(name = "SUPPLIER_IDREF", namespace = "http://www.bmecat.org/bmecat/2005")
    protected TypePARTYID supplieridref;
    @XmlElement(name = "DELIVERY_IDREF")
    protected TypePARTYID deliveryidref;
    @XmlElement(name = "FINAL_DELIVERY_IDREF")
    protected TypePARTYID finaldeliveryidref;
    @XmlElement(name = "MIME_INFO")
    protected OT2MIMEINFO mimeinfo;
    @XmlElement(name = "REMARKS")
    protected List<OT2REMARKS> remarks;
    @XmlElement(name = "ITEM_UDX")
    protected UdxITEM itemudx;

    /**
     * Gets the value of the lineitemid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLINEITEMID() {
        return lineitemid;
    }

    /**
     * Sets the value of the lineitemid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLINEITEMID(String value) {
        this.lineitemid = value;
    }

    /**
     * Gets the value of the productid property.
     * 
     * @return
     *     possible object is
     *     {@link OT2PRODUCTID }
     *     
     */
    public OT2PRODUCTID getPRODUCTID() {
        return productid;
    }

    /**
     * Sets the value of the productid property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2PRODUCTID }
     *     
     */
    public void setPRODUCTID(OT2PRODUCTID value) {
        this.productid = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQUANTITY() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQUANTITY(BigDecimal value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the orderunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDERUNIT() {
        return orderunit;
    }

    /**
     * Sets the value of the orderunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDERUNIT(String value) {
        this.orderunit = value;
    }

    /**
     * Gets the value of the deliverycompleted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDELIVERYCOMPLETED() {
        return deliverycompleted;
    }

    /**
     * Sets the value of the deliverycompleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDELIVERYCOMPLETED(String value) {
        this.deliverycompleted = value;
    }

    /**
     * Gets the value of the receiptdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECEIPTDATE() {
        return receiptdate;
    }

    /**
     * Sets the value of the receiptdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECEIPTDATE(String value) {
        this.receiptdate = value;
    }

    /**
     * Gets the value of the orderreference property.
     * 
     * @return
     *     possible object is
     *     {@link OT2ORDERREFERENCE }
     *     
     */
    public OT2ORDERREFERENCE getORDERREFERENCE() {
        return orderreference;
    }

    /**
     * Sets the value of the orderreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2ORDERREFERENCE }
     *     
     */
    public void setORDERREFERENCE(OT2ORDERREFERENCE value) {
        this.orderreference = value;
    }

    /**
     * Gets the value of the supplierorderreference property.
     * 
     * @return
     *     possible object is
     *     {@link OT2SUPPLIERORDERREFERENCE }
     *     
     */
    public OT2SUPPLIERORDERREFERENCE getSUPPLIERORDERREFERENCE() {
        return supplierorderreference;
    }

    /**
     * Sets the value of the supplierorderreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2SUPPLIERORDERREFERENCE }
     *     
     */
    public void setSUPPLIERORDERREFERENCE(OT2SUPPLIERORDERREFERENCE value) {
        this.supplierorderreference = value;
    }

    /**
     * Gets the value of the customerorderreference property.
     * 
     * @return
     *     possible object is
     *     {@link OT2CUSTOMERORDERREFERENCE }
     *     
     */
    public OT2CUSTOMERORDERREFERENCE getCUSTOMERORDERREFERENCE() {
        return customerorderreference;
    }

    /**
     * Sets the value of the customerorderreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2CUSTOMERORDERREFERENCE }
     *     
     */
    public void setCUSTOMERORDERREFERENCE(OT2CUSTOMERORDERREFERENCE value) {
        this.customerorderreference = value;
    }

    /**
     * Gets the value of the deliveryreference property.
     * 
     * @return
     *     possible object is
     *     {@link OT2DELIVERYREFERENCE }
     *     
     */
    public OT2DELIVERYREFERENCE getDELIVERYREFERENCE() {
        return deliveryreference;
    }

    /**
     * Sets the value of the deliveryreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2DELIVERYREFERENCE }
     *     
     */
    public void setDELIVERYREFERENCE(OT2DELIVERYREFERENCE value) {
        this.deliveryreference = value;
    }

    /**
     * Gets the value of the supplieridref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getSUPPLIERIDREF() {
        return supplieridref;
    }

    /**
     * Sets the value of the supplieridref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setSUPPLIERIDREF(TypePARTYID value) {
        this.supplieridref = value;
    }

    /**
     * Gets the value of the deliveryidref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getDELIVERYIDREF() {
        return deliveryidref;
    }

    /**
     * Sets the value of the deliveryidref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setDELIVERYIDREF(TypePARTYID value) {
        this.deliveryidref = value;
    }

    /**
     * Gets the value of the finaldeliveryidref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getFINALDELIVERYIDREF() {
        return finaldeliveryidref;
    }

    /**
     * Sets the value of the finaldeliveryidref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setFINALDELIVERYIDREF(TypePARTYID value) {
        this.finaldeliveryidref = value;
    }

    /**
     * Gets the value of the mimeinfo property.
     * 
     * @return
     *     possible object is
     *     {@link OT2MIMEINFO }
     *     
     */
    public OT2MIMEINFO getMIMEINFO() {
        return mimeinfo;
    }

    /**
     * Sets the value of the mimeinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2MIMEINFO }
     *     
     */
    public void setMIMEINFO(OT2MIMEINFO value) {
        this.mimeinfo = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remarks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getREMARKS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OT2REMARKS }
     * 
     * 
     */
    public List<OT2REMARKS> getREMARKS() {
        if (remarks == null) {
            remarks = new ArrayList<OT2REMARKS>();
        }
        return this.remarks;
    }

    /**
     * Gets the value of the itemudx property.
     * 
     * @return
     *     possible object is
     *     {@link UdxITEM }
     *     
     */
    public UdxITEM getITEMUDX() {
        return itemudx;
    }

    /**
     * Sets the value of the itemudx property.
     * 
     * @param value
     *     allowed object is
     *     {@link UdxITEM }
     *     
     */
    public void setITEMUDX(UdxITEM value) {
        this.itemudx = value;
    }

}
