/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2015 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.opentrans_2_1;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.lp.server.schema.bmecat_2005.TypePARTYID;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}LINE_ITEM_ID"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}INVOICE_ISSUER_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}INVOICE_RECIPIENT_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}RA_INVOICE_LIST"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}TOTAL_ITEM_NUM" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}TOTAL_AMOUNT"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ORIGINAL_SUMMARY_AMOUNT" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}MIME_INFO" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}REMARKS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ITEM_UDX" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lineitemid",
    "invoiceissueridref",
    "invoicerecipientidref",
    "rainvoicelist",
    "totalitemnum",
    "totalamount",
    "originalsummaryamount",
    "mimeinfo",
    "remarks",
    "itemudx"
})
@XmlRootElement(name = "REMITTANCEADVICE_ITEM")
public class OT2REMITTANCEADVICEITEM {

    @XmlElement(name = "LINE_ITEM_ID", required = true)
    protected String lineitemid;
    @XmlElement(name = "INVOICE_ISSUER_IDREF")
    protected TypePARTYID invoiceissueridref;
    @XmlElement(name = "INVOICE_RECIPIENT_IDREF")
    protected TypePARTYID invoicerecipientidref;
    @XmlElement(name = "RA_INVOICE_LIST", required = true)
    protected OT2RAINVOICELIST rainvoicelist;
    @XmlElement(name = "TOTAL_ITEM_NUM")
    protected BigInteger totalitemnum;
    @XmlElement(name = "TOTAL_AMOUNT", required = true)
    protected BigDecimal totalamount;
    @XmlElement(name = "ORIGINAL_SUMMARY_AMOUNT")
    protected BigDecimal originalsummaryamount;
    @XmlElement(name = "MIME_INFO")
    protected OT2MIMEINFO mimeinfo;
    @XmlElement(name = "REMARKS")
    protected List<OT2REMARKS> remarks;
    @XmlElement(name = "ITEM_UDX")
    protected UdxITEM itemudx;

    /**
     * Gets the value of the lineitemid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLINEITEMID() {
        return lineitemid;
    }

    /**
     * Sets the value of the lineitemid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLINEITEMID(String value) {
        this.lineitemid = value;
    }

    /**
     * Gets the value of the invoiceissueridref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getINVOICEISSUERIDREF() {
        return invoiceissueridref;
    }

    /**
     * Sets the value of the invoiceissueridref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setINVOICEISSUERIDREF(TypePARTYID value) {
        this.invoiceissueridref = value;
    }

    /**
     * Gets the value of the invoicerecipientidref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getINVOICERECIPIENTIDREF() {
        return invoicerecipientidref;
    }

    /**
     * Sets the value of the invoicerecipientidref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setINVOICERECIPIENTIDREF(TypePARTYID value) {
        this.invoicerecipientidref = value;
    }

    /**
     * Gets the value of the rainvoicelist property.
     * 
     * @return
     *     possible object is
     *     {@link OT2RAINVOICELIST }
     *     
     */
    public OT2RAINVOICELIST getRAINVOICELIST() {
        return rainvoicelist;
    }

    /**
     * Sets the value of the rainvoicelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2RAINVOICELIST }
     *     
     */
    public void setRAINVOICELIST(OT2RAINVOICELIST value) {
        this.rainvoicelist = value;
    }

    /**
     * Gets the value of the totalitemnum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTOTALITEMNUM() {
        return totalitemnum;
    }

    /**
     * Sets the value of the totalitemnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTOTALITEMNUM(BigInteger value) {
        this.totalitemnum = value;
    }

    /**
     * Gets the value of the totalamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTOTALAMOUNT() {
        return totalamount;
    }

    /**
     * Sets the value of the totalamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTOTALAMOUNT(BigDecimal value) {
        this.totalamount = value;
    }

    /**
     * Gets the value of the originalsummaryamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getORIGINALSUMMARYAMOUNT() {
        return originalsummaryamount;
    }

    /**
     * Sets the value of the originalsummaryamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setORIGINALSUMMARYAMOUNT(BigDecimal value) {
        this.originalsummaryamount = value;
    }

    /**
     * Gets the value of the mimeinfo property.
     * 
     * @return
     *     possible object is
     *     {@link OT2MIMEINFO }
     *     
     */
    public OT2MIMEINFO getMIMEINFO() {
        return mimeinfo;
    }

    /**
     * Sets the value of the mimeinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OT2MIMEINFO }
     *     
     */
    public void setMIMEINFO(OT2MIMEINFO value) {
        this.mimeinfo = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remarks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getREMARKS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OT2REMARKS }
     * 
     * 
     */
    public List<OT2REMARKS> getREMARKS() {
        if (remarks == null) {
            remarks = new ArrayList<OT2REMARKS>();
        }
        return this.remarks;
    }

    /**
     * Gets the value of the itemudx property.
     * 
     * @return
     *     possible object is
     *     {@link UdxITEM }
     *     
     */
    public UdxITEM getITEMUDX() {
        return itemudx;
    }

    /**
     * Sets the value of the itemudx property.
     * 
     * @param value
     *     allowed object is
     *     {@link UdxITEM }
     *     
     */
    public void setITEMUDX(UdxITEM value) {
        this.itemudx = value;
    }

}
