/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2015 HELIUM V IT-Solutions GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of theLicense, or
 * (at your option) any later version.
 *
 * According to sec. 7 of the GNU Affero General Public License, version 3,
 * the terms of the AGPL are supplemented with the following terms:
 *
 * "HELIUM V" and "HELIUM 5" are registered trademarks of
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Contact: developers@heliumv.com
 ******************************************************************************/
package com.lp.server.eingangsrechnung.bl;

import javax.xml.bind.JAXBException;

import org.xml.sax.SAXException;

import com.lp.server.schema.iso20022.pain001V06.PADocument;

/**
 * Marshaller der Pain-Version pain.001.001.006
 * 
 * @author andi
 *
 */
public class SepaXmlMarshallerPain001V06 extends SepaXmlMarshaller {
	
	String xsdSchemaV06ISO = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n" + 
			"<!--Generated by Standards Editor (build:R1.6.5.2_DEV) on 2015 Feb 24 14:08:25, ISO 20022 version : 2013-->\r\n" + 
			"<xs:schema xmlns=\"urn:iso:std:iso:20022:tech:xsd:pain.001.001.06\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" elementFormDefault=\"qualified\" targetNamespace=\"urn:iso:std:iso:20022:tech:xsd:pain.001.001.06\">\r\n" + 
			"    <xs:element name=\"Document\" type=\"Document\"/>\r\n" + 
			"    <xs:complexType name=\"AccountIdentification4Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"IBAN\" type=\"IBAN2007Identifier\"/>\r\n" + 
			"            <xs:element name=\"Othr\" type=\"GenericAccountIdentification1\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"AccountSchemeName1Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"ExternalAccountIdentification1Code\"/>\r\n" + 
			"            <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"ActiveOrHistoricCurrencyAndAmount_SimpleType\">\r\n" + 
			"        <xs:restriction base=\"xs:decimal\">\r\n" + 
			"            <xs:fractionDigits value=\"5\"/>\r\n" + 
			"            <xs:totalDigits value=\"18\"/>\r\n" + 
			"            <xs:minInclusive value=\"0\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"ActiveOrHistoricCurrencyAndAmount\">\r\n" + 
			"        <xs:simpleContent>\r\n" + 
			"            <xs:extension base=\"ActiveOrHistoricCurrencyAndAmount_SimpleType\">\r\n" + 
			"                <xs:attribute name=\"Ccy\" type=\"ActiveOrHistoricCurrencyCode\" use=\"required\"/>\r\n" + 
			"            </xs:extension>\r\n" + 
			"        </xs:simpleContent>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"ActiveOrHistoricCurrencyCode\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:pattern value=\"[A-Z]{3,3}\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"AddressType2Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"ADDR\"/>\r\n" + 
			"            <xs:enumeration value=\"PBOX\"/>\r\n" + 
			"            <xs:enumeration value=\"HOME\"/>\r\n" + 
			"            <xs:enumeration value=\"BIZZ\"/>\r\n" + 
			"            <xs:enumeration value=\"MLTO\"/>\r\n" + 
			"            <xs:enumeration value=\"DLVY\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"AmountType4Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"InstdAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element name=\"EqvtAmt\" type=\"EquivalentAmount2\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"AnyBICIdentifier\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:pattern value=\"[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"Authorisation1Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"Authorisation1Code\"/>\r\n" + 
			"            <xs:element name=\"Prtry\" type=\"Max128Text\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"Authorisation1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"AUTH\"/>\r\n" + 
			"            <xs:enumeration value=\"FDET\"/>\r\n" + 
			"            <xs:enumeration value=\"FSUM\"/>\r\n" + 
			"            <xs:enumeration value=\"ILEV\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"BICFIIdentifier\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:pattern value=\"[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"BaseOneRate\">\r\n" + 
			"        <xs:restriction base=\"xs:decimal\">\r\n" + 
			"            <xs:fractionDigits value=\"10\"/>\r\n" + 
			"            <xs:totalDigits value=\"11\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"BatchBookingIndicator\">\r\n" + 
			"        <xs:restriction base=\"xs:boolean\"/>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"BranchAndFinancialInstitutionIdentification5\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"FinInstnId\" type=\"FinancialInstitutionIdentification8\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"BrnchId\" type=\"BranchData2\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"BranchData2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Id\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Nm\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PstlAdr\" type=\"PostalAddress6\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"CashAccount24\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Id\" type=\"AccountIdentification4Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tp\" type=\"CashAccountType2Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Ccy\" type=\"ActiveOrHistoricCurrencyCode\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Nm\" type=\"Max70Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"CashAccountType2Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"ExternalCashAccountType1Code\"/>\r\n" + 
			"            <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"CategoryPurpose1Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"ExternalCategoryPurpose1Code\"/>\r\n" + 
			"            <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"ChargeBearerType1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"DEBT\"/>\r\n" + 
			"            <xs:enumeration value=\"CRED\"/>\r\n" + 
			"            <xs:enumeration value=\"SHAR\"/>\r\n" + 
			"            <xs:enumeration value=\"SLEV\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"Cheque7\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ChqTp\" type=\"ChequeType2Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ChqNb\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ChqFr\" type=\"NameAndAddress10\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"DlvryMtd\" type=\"ChequeDeliveryMethod1Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"DlvrTo\" type=\"NameAndAddress10\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"InstrPrty\" type=\"Priority2Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ChqMtrtyDt\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"FrmsCd\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"2\" minOccurs=\"0\" name=\"MemoFld\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RgnlClrZone\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PrtLctn\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"5\" minOccurs=\"0\" name=\"Sgntr\" type=\"Max70Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"ChequeDelivery1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"MLDB\"/>\r\n" + 
			"            <xs:enumeration value=\"MLCD\"/>\r\n" + 
			"            <xs:enumeration value=\"MLFA\"/>\r\n" + 
			"            <xs:enumeration value=\"CRDB\"/>\r\n" + 
			"            <xs:enumeration value=\"CRCD\"/>\r\n" + 
			"            <xs:enumeration value=\"CRFA\"/>\r\n" + 
			"            <xs:enumeration value=\"PUDB\"/>\r\n" + 
			"            <xs:enumeration value=\"PUCD\"/>\r\n" + 
			"            <xs:enumeration value=\"PUFA\"/>\r\n" + 
			"            <xs:enumeration value=\"RGDB\"/>\r\n" + 
			"            <xs:enumeration value=\"RGCD\"/>\r\n" + 
			"            <xs:enumeration value=\"RGFA\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"ChequeDeliveryMethod1Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"ChequeDelivery1Code\"/>\r\n" + 
			"            <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"ChequeType2Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"CCHQ\"/>\r\n" + 
			"            <xs:enumeration value=\"CCCH\"/>\r\n" + 
			"            <xs:enumeration value=\"BCHQ\"/>\r\n" + 
			"            <xs:enumeration value=\"DRFT\"/>\r\n" + 
			"            <xs:enumeration value=\"ELDR\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"ClearingSystemIdentification2Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"ExternalClearingSystemIdentification1Code\"/>\r\n" + 
			"            <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ClearingSystemMemberIdentification2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ClrSysId\" type=\"ClearingSystemIdentification2Choice\"/>\r\n" + 
			"            <xs:element name=\"MmbId\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ContactDetails2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"NmPrfx\" type=\"NamePrefix1Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Nm\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PhneNb\" type=\"PhoneNumber\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"MobNb\" type=\"PhoneNumber\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"FaxNb\" type=\"PhoneNumber\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"EmailAdr\" type=\"Max2048Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Othr\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"CountryCode\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:pattern value=\"[A-Z]{2,2}\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"CreditDebitCode\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"CRDT\"/>\r\n" + 
			"            <xs:enumeration value=\"DBIT\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"CreditTransferTransaction20\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"PmtId\" type=\"PaymentIdentification1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PmtTpInf\" type=\"PaymentTypeInformation19\"/>\r\n" + 
			"            <xs:element name=\"Amt\" type=\"AmountType4Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"XchgRateInf\" type=\"ExchangeRate1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ChrgBr\" type=\"ChargeBearerType1Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ChqInstr\" type=\"Cheque7\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"UltmtDbtr\" type=\"PartyIdentification43\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"IntrmyAgt1\" type=\"BranchAndFinancialInstitutionIdentification5\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"IntrmyAgt1Acct\" type=\"CashAccount24\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"IntrmyAgt2\" type=\"BranchAndFinancialInstitutionIdentification5\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"IntrmyAgt2Acct\" type=\"CashAccount24\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"IntrmyAgt3\" type=\"BranchAndFinancialInstitutionIdentification5\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"IntrmyAgt3Acct\" type=\"CashAccount24\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CdtrAgt\" type=\"BranchAndFinancialInstitutionIdentification5\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CdtrAgtAcct\" type=\"CashAccount24\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Cdtr\" type=\"PartyIdentification43\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CdtrAcct\" type=\"CashAccount24\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"UltmtCdtr\" type=\"PartyIdentification43\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"InstrForCdtrAgt\" type=\"InstructionForCreditorAgent1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"InstrForDbtrAgt\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Purp\" type=\"Purpose2Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"10\" minOccurs=\"0\" name=\"RgltryRptg\" type=\"RegulatoryReporting3\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tax\" type=\"TaxInformation3\"/>\r\n" + 
			"            <xs:element maxOccurs=\"10\" minOccurs=\"0\" name=\"RltdRmtInf\" type=\"RemittanceLocation4\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RmtInf\" type=\"RemittanceInformation10\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"SplmtryData\" type=\"SupplementaryData1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"CreditorReferenceInformation2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tp\" type=\"CreditorReferenceType2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Ref\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"CreditorReferenceType1Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"DocumentType3Code\"/>\r\n" + 
			"            <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"CreditorReferenceType2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"CdOrPrtry\" type=\"CreditorReferenceType1Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Issr\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"CustomerCreditTransferInitiationV06\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"GrpHdr\" type=\"GroupHeader48\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"1\" name=\"PmtInf\" type=\"PaymentInstruction16\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"SplmtryData\" type=\"SupplementaryData1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"DateAndPlaceOfBirth\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"BirthDt\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PrvcOfBirth\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element name=\"CityOfBirth\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element name=\"CtryOfBirth\" type=\"CountryCode\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"DatePeriodDetails\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"FrDt\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element name=\"ToDt\" type=\"ISODate\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"DecimalNumber\">\r\n" + 
			"        <xs:restriction base=\"xs:decimal\">\r\n" + 
			"            <xs:fractionDigits value=\"17\"/>\r\n" + 
			"            <xs:totalDigits value=\"18\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"DiscountAmountAndType1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tp\" type=\"DiscountAmountType1Choice\"/>\r\n" + 
			"            <xs:element name=\"Amt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"DiscountAmountType1Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"ExternalDiscountAmountType1Code\"/>\r\n" + 
			"            <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"Document\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"CstmrCdtTrfInitn\" type=\"CustomerCreditTransferInitiationV06\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"DocumentAdjustment1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Amt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CdtDbtInd\" type=\"CreditDebitCode\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Rsn\" type=\"Max4Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AddtlInf\" type=\"Max140Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"DocumentType3Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"RADM\"/>\r\n" + 
			"            <xs:enumeration value=\"RPIN\"/>\r\n" + 
			"            <xs:enumeration value=\"FXDR\"/>\r\n" + 
			"            <xs:enumeration value=\"DISP\"/>\r\n" + 
			"            <xs:enumeration value=\"PUOR\"/>\r\n" + 
			"            <xs:enumeration value=\"SCOR\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"DocumentType6Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"MSIN\"/>\r\n" + 
			"            <xs:enumeration value=\"CNFA\"/>\r\n" + 
			"            <xs:enumeration value=\"DNFA\"/>\r\n" + 
			"            <xs:enumeration value=\"CINV\"/>\r\n" + 
			"            <xs:enumeration value=\"CREN\"/>\r\n" + 
			"            <xs:enumeration value=\"DEBN\"/>\r\n" + 
			"            <xs:enumeration value=\"HIRI\"/>\r\n" + 
			"            <xs:enumeration value=\"SBIN\"/>\r\n" + 
			"            <xs:enumeration value=\"CMCN\"/>\r\n" + 
			"            <xs:enumeration value=\"SOAC\"/>\r\n" + 
			"            <xs:enumeration value=\"DISP\"/>\r\n" + 
			"            <xs:enumeration value=\"BOLD\"/>\r\n" + 
			"            <xs:enumeration value=\"VCHR\"/>\r\n" + 
			"            <xs:enumeration value=\"AROI\"/>\r\n" + 
			"            <xs:enumeration value=\"TSUT\"/>\r\n" + 
			"            <xs:enumeration value=\"PUOR\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"EquivalentAmount2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Amt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element name=\"CcyOfTrf\" type=\"ActiveOrHistoricCurrencyCode\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ExchangeRate1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"UnitCcy\" type=\"ActiveOrHistoricCurrencyCode\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"XchgRate\" type=\"BaseOneRate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RateTp\" type=\"ExchangeRateType1Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CtrctId\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"ExchangeRateType1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"SPOT\"/>\r\n" + 
			"            <xs:enumeration value=\"SALE\"/>\r\n" + 
			"            <xs:enumeration value=\"AGRD\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalAccountIdentification1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalCashAccountType1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalCategoryPurpose1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalClearingSystemIdentification1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"5\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalDiscountAmountType1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalFinancialInstitutionIdentification1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalGarnishmentType1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalLocalInstrument1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"35\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalOrganisationIdentification1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalPersonIdentification1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalPurpose1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalServiceLevel1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalTaxAmountType1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"FinancialIdentificationSchemeName1Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"ExternalFinancialInstitutionIdentification1Code\"/>\r\n" + 
			"            <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"FinancialInstitutionIdentification8\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"BICFI\" type=\"BICFIIdentifier\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ClrSysMmbId\" type=\"ClearingSystemMemberIdentification2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Nm\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PstlAdr\" type=\"PostalAddress6\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Othr\" type=\"GenericFinancialIdentification1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"Garnishment1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Tp\" type=\"GarnishmentType1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Grnshee\" type=\"PartyIdentification43\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"GrnshmtAdmstr\" type=\"PartyIdentification43\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RefNb\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Dt\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RmtdAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"FmlyMdclInsrncInd\" type=\"TrueFalseIndicator\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"MplyeeTermntnInd\" type=\"TrueFalseIndicator\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"GarnishmentType1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"CdOrPrtry\" type=\"GarnishmentType1Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Issr\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"GarnishmentType1Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"ExternalGarnishmentType1Code\"/>\r\n" + 
			"            <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"GenericAccountIdentification1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Id\" type=\"Max34Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SchmeNm\" type=\"AccountSchemeName1Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Issr\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"GenericFinancialIdentification1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Id\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SchmeNm\" type=\"FinancialIdentificationSchemeName1Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Issr\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"GenericOrganisationIdentification1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Id\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SchmeNm\" type=\"OrganisationIdentificationSchemeName1Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Issr\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"GenericPersonIdentification1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Id\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SchmeNm\" type=\"PersonIdentificationSchemeName1Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Issr\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"GroupHeader48\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"MsgId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element name=\"CreDtTm\" type=\"ISODateTime\"/>\r\n" + 
			"            <xs:element maxOccurs=\"2\" minOccurs=\"0\" name=\"Authstn\" type=\"Authorisation1Choice\"/>\r\n" + 
			"            <xs:element name=\"NbOfTxs\" type=\"Max15NumericText\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CtrlSum\" type=\"DecimalNumber\"/>\r\n" + 
			"            <xs:element name=\"InitgPty\" type=\"PartyIdentification43\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"FwdgAgt\" type=\"BranchAndFinancialInstitutionIdentification5\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"IBAN2007Identifier\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:pattern value=\"[A-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ISODate\">\r\n" + 
			"        <xs:restriction base=\"xs:date\"/>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ISODateTime\">\r\n" + 
			"        <xs:restriction base=\"xs:dateTime\"/>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Instruction3Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"CHQB\"/>\r\n" + 
			"            <xs:enumeration value=\"HOLD\"/>\r\n" + 
			"            <xs:enumeration value=\"PHOB\"/>\r\n" + 
			"            <xs:enumeration value=\"TELB\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"InstructionForCreditorAgent1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Cd\" type=\"Instruction3Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"InstrInf\" type=\"Max140Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"LocalInstrument2Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"ExternalLocalInstrument1Code\"/>\r\n" + 
			"            <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"Max10Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"10\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max128Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"128\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max140Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"140\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max15NumericText\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:pattern value=\"[0-9]{1,15}\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max16Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"16\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max2048Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"2048\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max34Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"34\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max350Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"350\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max35Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"35\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max4Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max70Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"70\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"NameAndAddress10\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Nm\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element name=\"Adr\" type=\"PostalAddress6\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"NamePrefix1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"DOCT\"/>\r\n" + 
			"            <xs:enumeration value=\"MIST\"/>\r\n" + 
			"            <xs:enumeration value=\"MISS\"/>\r\n" + 
			"            <xs:enumeration value=\"MADM\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Number\">\r\n" + 
			"        <xs:restriction base=\"xs:decimal\">\r\n" + 
			"            <xs:fractionDigits value=\"0\"/>\r\n" + 
			"            <xs:totalDigits value=\"18\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"OrganisationIdentification8\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AnyBIC\" type=\"AnyBICIdentifier\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Othr\" type=\"GenericOrganisationIdentification1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"OrganisationIdentificationSchemeName1Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"ExternalOrganisationIdentification1Code\"/>\r\n" + 
			"            <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"Party11Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"OrgId\" type=\"OrganisationIdentification8\"/>\r\n" + 
			"            <xs:element name=\"PrvtId\" type=\"PersonIdentification5\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"PartyIdentification43\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Nm\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PstlAdr\" type=\"PostalAddress6\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Id\" type=\"Party11Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CtryOfRes\" type=\"CountryCode\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CtctDtls\" type=\"ContactDetails2\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"PaymentIdentification1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"InstrId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element name=\"EndToEndId\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"PaymentInstruction16\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"PmtInfId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element name=\"PmtMtd\" type=\"PaymentMethod3Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"BtchBookg\" type=\"BatchBookingIndicator\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"NbOfTxs\" type=\"Max15NumericText\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CtrlSum\" type=\"DecimalNumber\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PmtTpInf\" type=\"PaymentTypeInformation19\"/>\r\n" + 
			"            <xs:element name=\"ReqdExctnDt\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PoolgAdjstmntDt\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element name=\"Dbtr\" type=\"PartyIdentification43\"/>\r\n" + 
			"            <xs:element name=\"DbtrAcct\" type=\"CashAccount24\"/>\r\n" + 
			"            <xs:element name=\"DbtrAgt\" type=\"BranchAndFinancialInstitutionIdentification5\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"DbtrAgtAcct\" type=\"CashAccount24\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"InstrForDbtrAgt\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"UltmtDbtr\" type=\"PartyIdentification43\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ChrgBr\" type=\"ChargeBearerType1Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ChrgsAcct\" type=\"CashAccount24\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ChrgsAcctAgt\" type=\"BranchAndFinancialInstitutionIdentification5\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"1\" name=\"CdtTrfTxInf\" type=\"CreditTransferTransaction20\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"PaymentMethod3Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"CHK\"/>\r\n" + 
			"            <xs:enumeration value=\"TRF\"/>\r\n" + 
			"            <xs:enumeration value=\"TRA\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"PaymentTypeInformation19\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"InstrPrty\" type=\"Priority2Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SvcLvl\" type=\"ServiceLevel8Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"LclInstrm\" type=\"LocalInstrument2Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CtgyPurp\" type=\"CategoryPurpose1Choice\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"PercentageRate\">\r\n" + 
			"        <xs:restriction base=\"xs:decimal\">\r\n" + 
			"            <xs:fractionDigits value=\"10\"/>\r\n" + 
			"            <xs:totalDigits value=\"11\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"PersonIdentification5\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"DtAndPlcOfBirth\" type=\"DateAndPlaceOfBirth\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Othr\" type=\"GenericPersonIdentification1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"PersonIdentificationSchemeName1Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"ExternalPersonIdentification1Code\"/>\r\n" + 
			"            <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"PhoneNumber\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:pattern value=\"\\+[0-9]{1,3}-[0-9()+\\-]{1,30}\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"PostalAddress6\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AdrTp\" type=\"AddressType2Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Dept\" type=\"Max70Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SubDept\" type=\"Max70Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"StrtNm\" type=\"Max70Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"BldgNb\" type=\"Max16Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PstCd\" type=\"Max16Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TwnNm\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CtrySubDvsn\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Ctry\" type=\"CountryCode\"/>\r\n" + 
			"            <xs:element maxOccurs=\"7\" minOccurs=\"0\" name=\"AdrLine\" type=\"Max70Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"Priority2Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"HIGH\"/>\r\n" + 
			"            <xs:enumeration value=\"NORM\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"Purpose2Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"ExternalPurpose1Code\"/>\r\n" + 
			"            <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ReferredDocumentInformation6\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tp\" type=\"ReferredDocumentType4\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Nb\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RltdDt\" type=\"ISODate\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ReferredDocumentType3Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"DocumentType6Code\"/>\r\n" + 
			"            <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ReferredDocumentType4\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"CdOrPrtry\" type=\"ReferredDocumentType3Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Issr\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"RegulatoryAuthority2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Nm\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Ctry\" type=\"CountryCode\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"RegulatoryReporting3\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"DbtCdtRptgInd\" type=\"RegulatoryReportingType1Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Authrty\" type=\"RegulatoryAuthority2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Dtls\" type=\"StructuredRegulatoryReporting3\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"RegulatoryReportingType1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"CRED\"/>\r\n" + 
			"            <xs:enumeration value=\"DEBT\"/>\r\n" + 
			"            <xs:enumeration value=\"BOTH\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"RemittanceAmount2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"DuePyblAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"DscntApldAmt\" type=\"DiscountAmountAndType1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CdtNoteAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"TaxAmt\" type=\"TaxAmountAndType1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"AdjstmntAmtAndRsn\" type=\"DocumentAdjustment1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RmtdAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"RemittanceInformation10\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Ustrd\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Strd\" type=\"StructuredRemittanceInformation12\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"RemittanceLocation4\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RmtId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"RmtLctnDtls\" type=\"RemittanceLocationDetails1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"RemittanceLocationDetails1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Mtd\" type=\"RemittanceLocationMethod2Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ElctrncAdr\" type=\"Max2048Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PstlAdr\" type=\"NameAndAddress10\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"RemittanceLocationMethod2Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"FAXI\"/>\r\n" + 
			"            <xs:enumeration value=\"EDIC\"/>\r\n" + 
			"            <xs:enumeration value=\"URID\"/>\r\n" + 
			"            <xs:enumeration value=\"EMAL\"/>\r\n" + 
			"            <xs:enumeration value=\"POST\"/>\r\n" + 
			"            <xs:enumeration value=\"SMSM\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"ServiceLevel8Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"ExternalServiceLevel1Code\"/>\r\n" + 
			"            <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"StructuredRegulatoryReporting3\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tp\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Dt\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Ctry\" type=\"CountryCode\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Cd\" type=\"Max10Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Amt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Inf\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"StructuredRemittanceInformation12\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"RfrdDocInf\" type=\"ReferredDocumentInformation6\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RfrdDocAmt\" type=\"RemittanceAmount2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CdtrRefInf\" type=\"CreditorReferenceInformation2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Invcr\" type=\"PartyIdentification43\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Invcee\" type=\"PartyIdentification43\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TaxRmt\" type=\"TaxInformation4\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"GrnshmtRmt\" type=\"Garnishment1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"3\" minOccurs=\"0\" name=\"AddtlRmtInf\" type=\"Max140Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"SupplementaryData1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PlcAndNm\" type=\"Max350Text\"/>\r\n" + 
			"            <xs:element name=\"Envlp\" type=\"SupplementaryDataEnvelope1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"SupplementaryDataEnvelope1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:any namespace=\"##any\" processContents=\"lax\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxAmount1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Rate\" type=\"PercentageRate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TaxblBaseAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TtlAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Dtls\" type=\"TaxRecordDetails1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxAmountAndType1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tp\" type=\"TaxAmountType1Choice\"/>\r\n" + 
			"            <xs:element name=\"Amt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxAmountType1Choice\">\r\n" + 
			"        <xs:choice>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"ExternalTaxAmountType1Code\"/>\r\n" + 
			"            <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:choice>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxAuthorisation1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Titl\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Nm\" type=\"Max140Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxInformation3\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Cdtr\" type=\"TaxParty1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Dbtr\" type=\"TaxParty2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AdmstnZn\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RefNb\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Mtd\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TtlTaxblBaseAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TtlTaxAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Dt\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SeqNb\" type=\"Number\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Rcrd\" type=\"TaxRecord1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxInformation4\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Cdtr\" type=\"TaxParty1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Dbtr\" type=\"TaxParty2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"UltmtDbtr\" type=\"TaxParty2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AdmstnZone\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RefNb\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Mtd\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TtlTaxblBaseAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TtlTaxAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Dt\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SeqNb\" type=\"Number\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Rcrd\" type=\"TaxRecord1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxParty1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TaxId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RegnId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TaxTp\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxParty2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TaxId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RegnId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TaxTp\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Authstn\" type=\"TaxAuthorisation1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxPeriod1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Yr\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tp\" type=\"TaxRecordPeriod1Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"FrToDt\" type=\"DatePeriodDetails\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxRecord1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tp\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Ctgy\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CtgyDtls\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"DbtrSts\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CertId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"FrmsCd\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Prd\" type=\"TaxPeriod1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TaxAmt\" type=\"TaxAmount1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AddtlInf\" type=\"Max140Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxRecordDetails1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Prd\" type=\"TaxPeriod1\"/>\r\n" + 
			"            <xs:element name=\"Amt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"TaxRecordPeriod1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"MM01\"/>\r\n" + 
			"            <xs:enumeration value=\"MM02\"/>\r\n" + 
			"            <xs:enumeration value=\"MM03\"/>\r\n" + 
			"            <xs:enumeration value=\"MM04\"/>\r\n" + 
			"            <xs:enumeration value=\"MM05\"/>\r\n" + 
			"            <xs:enumeration value=\"MM06\"/>\r\n" + 
			"            <xs:enumeration value=\"MM07\"/>\r\n" + 
			"            <xs:enumeration value=\"MM08\"/>\r\n" + 
			"            <xs:enumeration value=\"MM09\"/>\r\n" + 
			"            <xs:enumeration value=\"MM10\"/>\r\n" + 
			"            <xs:enumeration value=\"MM11\"/>\r\n" + 
			"            <xs:enumeration value=\"MM12\"/>\r\n" + 
			"            <xs:enumeration value=\"QTR1\"/>\r\n" + 
			"            <xs:enumeration value=\"QTR2\"/>\r\n" + 
			"            <xs:enumeration value=\"QTR3\"/>\r\n" + 
			"            <xs:enumeration value=\"QTR4\"/>\r\n" + 
			"            <xs:enumeration value=\"HLF1\"/>\r\n" + 
			"            <xs:enumeration value=\"HLF2\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"TrueFalseIndicator\">\r\n" + 
			"        <xs:restriction base=\"xs:boolean\"/>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"</xs:schema>\r\n" + 
			"";

	public SepaXmlMarshallerPain001V06() {
	}

	@Override
	public String marshal(Object sepaDoc) throws JAXBException, SAXException {

		return marshal(xsdSchemaV06ISO, (PADocument)sepaDoc);
	}

}
