/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2015 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CUSTOMS_TARIFF_NUMBER" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}STATISTICS_FACTOR" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}COUNTRY_OF_ORIGIN" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_DIMENSIONS" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}DELIVERY_TIMES" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}TRANSPORT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}MEANS_OF_TRANSPORT" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customstariffnumber",
    "statisticsfactor",
    "countryoforigin",
    "productdimensions",
    "deliverytimes",
    "transport",
    "meansoftransport"
})
@XmlRootElement(name = "ARTICLE_LOGISTIC_DETAILS")
public class BCARTICLELOGISTICDETAILS {

    @XmlElement(name = "CUSTOMS_TARIFF_NUMBER")
    protected List<BCCUSTOMSTARIFFNUMBER> customstariffnumber;
    @XmlElement(name = "STATISTICS_FACTOR")
    protected BigDecimal statisticsfactor;
    @XmlElement(name = "COUNTRY_OF_ORIGIN")
    protected List<String> countryoforigin;
    @XmlElement(name = "PRODUCT_DIMENSIONS")
    protected BCPRODUCTDIMENSIONS productdimensions;
    @XmlElement(name = "DELIVERY_TIMES")
    protected List<BCDELIVERYTIMES> deliverytimes;
    @XmlElement(name = "TRANSPORT")
    protected List<BCTRANSPORT> transport;
    @XmlElement(name = "MEANS_OF_TRANSPORT")
    protected List<BCMEANSOFTRANSPORT> meansoftransport;

    /**
     * Gets the value of the customstariffnumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customstariffnumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCUSTOMSTARIFFNUMBER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCCUSTOMSTARIFFNUMBER }
     * 
     * 
     */
    public List<BCCUSTOMSTARIFFNUMBER> getCUSTOMSTARIFFNUMBER() {
        if (customstariffnumber == null) {
            customstariffnumber = new ArrayList<BCCUSTOMSTARIFFNUMBER>();
        }
        return this.customstariffnumber;
    }

    /**
     * Gets the value of the statisticsfactor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSTATISTICSFACTOR() {
        return statisticsfactor;
    }

    /**
     * Sets the value of the statisticsfactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSTATISTICSFACTOR(BigDecimal value) {
        this.statisticsfactor = value;
    }

    /**
     * Gets the value of the countryoforigin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the countryoforigin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCOUNTRYOFORIGIN().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCOUNTRYOFORIGIN() {
        if (countryoforigin == null) {
            countryoforigin = new ArrayList<String>();
        }
        return this.countryoforigin;
    }

    /**
     * Gets the value of the productdimensions property.
     * 
     * @return
     *     possible object is
     *     {@link BCPRODUCTDIMENSIONS }
     *     
     */
    public BCPRODUCTDIMENSIONS getPRODUCTDIMENSIONS() {
        return productdimensions;
    }

    /**
     * Sets the value of the productdimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCPRODUCTDIMENSIONS }
     *     
     */
    public void setPRODUCTDIMENSIONS(BCPRODUCTDIMENSIONS value) {
        this.productdimensions = value;
    }

    /**
     * Gets the value of the deliverytimes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deliverytimes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDELIVERYTIMES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCDELIVERYTIMES }
     * 
     * 
     */
    public List<BCDELIVERYTIMES> getDELIVERYTIMES() {
        if (deliverytimes == null) {
            deliverytimes = new ArrayList<BCDELIVERYTIMES>();
        }
        return this.deliverytimes;
    }

    /**
     * Gets the value of the transport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTRANSPORT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCTRANSPORT }
     * 
     * 
     */
    public List<BCTRANSPORT> getTRANSPORT() {
        if (transport == null) {
            transport = new ArrayList<BCTRANSPORT>();
        }
        return this.transport;
    }

    /**
     * Gets the value of the meansoftransport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meansoftransport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMEANSOFTRANSPORT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCMEANSOFTRANSPORT }
     * 
     * 
     */
    public List<BCMEANSOFTRANSPORT> getMEANSOFTRANSPORT() {
        if (meansoftransport == null) {
            meansoftransport = new ArrayList<BCMEANSOFTRANSPORT>();
        }
        return this.meansoftransport;
    }

}
