/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2015 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}LANGUAGE" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CATALOG_ID"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CATALOG_VERSION"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CATALOG_NAME" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}GENERATION_DATE" minOccurs="0"/>
 *           &lt;element name="DATETIME" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;extension base="{http://www.bmecat.org/bmecat/2005}typeDATETIME">
 *                   &lt;attribute name="type" use="required" fixed="generation_date">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.bmecat.org/bmecat/2005}dtSTRING">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="20"/>
 *                         &lt;enumeration value="generation_date"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                 &lt;/extension>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}TERRITORY" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}AREA_REFS" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CURRENCY" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}MIME_ROOT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRICE_FLAG" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRICE_FACTOR" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}VALID_START_DATE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}VALID_END_DATE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_TYPE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}COUNTRY_OF_ORIGIN" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}DELIVERY_TIMES" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}TRANSPORT" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_IDREF" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "language",
    "catalogid",
    "catalogversion",
    "catalogname",
    "generationdate",
    "datetime",
    "territory",
    "arearefs",
    "currency",
    "mimeroot",
    "priceflag",
    "pricefactor",
    "validstartdate",
    "validenddate",
    "producttype",
    "countryoforigin",
    "deliverytimes",
    "transport",
    "supplieridref"
})
@XmlRootElement(name = "CATALOG")
public class BCCATALOG {

    @XmlElement(name = "LANGUAGE", required = true)
    protected List<BCLANGUAGE> language;
    @XmlElement(name = "CATALOG_ID", required = true)
    protected String catalogid;
    @XmlElement(name = "CATALOG_VERSION", required = true)
    protected String catalogversion;
    @XmlElement(name = "CATALOG_NAME")
    protected List<BCCATALOGNAME> catalogname;
    @XmlElement(name = "GENERATION_DATE")
    protected String generationdate;
    @XmlElement(name = "DATETIME")
    protected BCCATALOG.DATETIME datetime;
    @XmlElement(name = "TERRITORY")
    protected List<String> territory;
    @XmlElement(name = "AREA_REFS")
    protected BCAREAREFS arearefs;
    @XmlElement(name = "CURRENCY")
    protected DtCURRENCIES currency;
    @XmlElement(name = "MIME_ROOT")
    protected List<BCMIMEROOT> mimeroot;
    @XmlElement(name = "PRICE_FLAG")
    protected List<BCPRICEFLAG> priceflag;
    @XmlElement(name = "PRICE_FACTOR", defaultValue = "1")
    protected BigDecimal pricefactor;
    @XmlElement(name = "VALID_START_DATE")
    protected String validstartdate;
    @XmlElement(name = "VALID_END_DATE")
    protected String validenddate;
    @XmlElement(name = "PRODUCT_TYPE")
    protected String producttype;
    @XmlElement(name = "COUNTRY_OF_ORIGIN")
    protected String countryoforigin;
    @XmlElement(name = "DELIVERY_TIMES")
    protected List<BCDELIVERYTIMES> deliverytimes;
    @XmlElement(name = "TRANSPORT")
    protected BCTRANSPORT transport;
    @XmlElement(name = "SUPPLIER_IDREF")
    protected TypePARTYID supplieridref;

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLANGUAGE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCLANGUAGE }
     * 
     * 
     */
    public List<BCLANGUAGE> getLANGUAGE() {
        if (language == null) {
            language = new ArrayList<BCLANGUAGE>();
        }
        return this.language;
    }

    /**
     * Gets the value of the catalogid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCATALOGID() {
        return catalogid;
    }

    /**
     * Sets the value of the catalogid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCATALOGID(String value) {
        this.catalogid = value;
    }

    /**
     * Gets the value of the catalogversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCATALOGVERSION() {
        return catalogversion;
    }

    /**
     * Sets the value of the catalogversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCATALOGVERSION(String value) {
        this.catalogversion = value;
    }

    /**
     * Gets the value of the catalogname property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the catalogname property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCATALOGNAME().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCCATALOGNAME }
     * 
     * 
     */
    public List<BCCATALOGNAME> getCATALOGNAME() {
        if (catalogname == null) {
            catalogname = new ArrayList<BCCATALOGNAME>();
        }
        return this.catalogname;
    }

    /**
     * Gets the value of the generationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGENERATIONDATE() {
        return generationdate;
    }

    /**
     * Sets the value of the generationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGENERATIONDATE(String value) {
        this.generationdate = value;
    }

    /**
     * Gets the value of the datetime property.
     * 
     * @return
     *     possible object is
     *     {@link BCCATALOG.DATETIME }
     *     
     */
    public BCCATALOG.DATETIME getDATETIME() {
        return datetime;
    }

    /**
     * Sets the value of the datetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCCATALOG.DATETIME }
     *     
     */
    public void setDATETIME(BCCATALOG.DATETIME value) {
        this.datetime = value;
    }

    /**
     * Gets the value of the territory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the territory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTERRITORY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTERRITORY() {
        if (territory == null) {
            territory = new ArrayList<String>();
        }
        return this.territory;
    }

    /**
     * Gets the value of the arearefs property.
     * 
     * @return
     *     possible object is
     *     {@link BCAREAREFS }
     *     
     */
    public BCAREAREFS getAREAREFS() {
        return arearefs;
    }

    /**
     * Sets the value of the arearefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCAREAREFS }
     *     
     */
    public void setAREAREFS(BCAREAREFS value) {
        this.arearefs = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link DtCURRENCIES }
     *     
     */
    public DtCURRENCIES getCURRENCY() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link DtCURRENCIES }
     *     
     */
    public void setCURRENCY(DtCURRENCIES value) {
        this.currency = value;
    }

    /**
     * Gets the value of the mimeroot property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mimeroot property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMIMEROOT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCMIMEROOT }
     * 
     * 
     */
    public List<BCMIMEROOT> getMIMEROOT() {
        if (mimeroot == null) {
            mimeroot = new ArrayList<BCMIMEROOT>();
        }
        return this.mimeroot;
    }

    /**
     * Gets the value of the priceflag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the priceflag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPRICEFLAG().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCPRICEFLAG }
     * 
     * 
     */
    public List<BCPRICEFLAG> getPRICEFLAG() {
        if (priceflag == null) {
            priceflag = new ArrayList<BCPRICEFLAG>();
        }
        return this.priceflag;
    }

    /**
     * Gets the value of the pricefactor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPRICEFACTOR() {
        return pricefactor;
    }

    /**
     * Sets the value of the pricefactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPRICEFACTOR(BigDecimal value) {
        this.pricefactor = value;
    }

    /**
     * Gets the value of the validstartdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALIDSTARTDATE() {
        return validstartdate;
    }

    /**
     * Sets the value of the validstartdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALIDSTARTDATE(String value) {
        this.validstartdate = value;
    }

    /**
     * Gets the value of the validenddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALIDENDDATE() {
        return validenddate;
    }

    /**
     * Sets the value of the validenddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALIDENDDATE(String value) {
        this.validenddate = value;
    }

    /**
     * Gets the value of the producttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODUCTTYPE() {
        return producttype;
    }

    /**
     * Sets the value of the producttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODUCTTYPE(String value) {
        this.producttype = value;
    }

    /**
     * Gets the value of the countryoforigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOUNTRYOFORIGIN() {
        return countryoforigin;
    }

    /**
     * Sets the value of the countryoforigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOUNTRYOFORIGIN(String value) {
        this.countryoforigin = value;
    }

    /**
     * Gets the value of the deliverytimes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deliverytimes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDELIVERYTIMES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCDELIVERYTIMES }
     * 
     * 
     */
    public List<BCDELIVERYTIMES> getDELIVERYTIMES() {
        if (deliverytimes == null) {
            deliverytimes = new ArrayList<BCDELIVERYTIMES>();
        }
        return this.deliverytimes;
    }

    /**
     * Gets the value of the transport property.
     * 
     * @return
     *     possible object is
     *     {@link BCTRANSPORT }
     *     
     */
    public BCTRANSPORT getTRANSPORT() {
        return transport;
    }

    /**
     * Sets the value of the transport property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCTRANSPORT }
     *     
     */
    public void setTRANSPORT(BCTRANSPORT value) {
        this.transport = value;
    }

    /**
     * Gets the value of the supplieridref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getSUPPLIERIDREF() {
        return supplieridref;
    }

    /**
     * Sets the value of the supplieridref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setSUPPLIERIDREF(TypePARTYID value) {
        this.supplieridref = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.bmecat.org/bmecat/2005}typeDATETIME">
     *       &lt;attribute name="type" use="required" fixed="generation_date">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.bmecat.org/bmecat/2005}dtSTRING">
     *             &lt;minLength value="1"/>
     *             &lt;maxLength value="20"/>
     *             &lt;enumeration value="generation_date"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DATETIME
        extends TypeDATETIME
    {

        @XmlAttribute(required = true)
        protected String type;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            if (type == null) {
                return "generation_date";
            } else {
                return type;
            }
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }

}
