/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2015 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}GROUP_SYSTEM_ID" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}GROUP_SYSTEM_NAME" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CATALOG_STRUCTURE" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}GROUP_SYSTEM_DESCRIPTION" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "groupsystemid",
    "groupsystemname",
    "catalogstructure",
    "groupsystemdescription"
})
@XmlRootElement(name = "CATALOG_GROUP_SYSTEM")
public class BCCATALOGGROUPSYSTEM {

    @XmlElement(name = "GROUP_SYSTEM_ID")
    protected String groupsystemid;
    @XmlElement(name = "GROUP_SYSTEM_NAME")
    protected List<BCGROUPSYSTEMNAME> groupsystemname;
    @XmlElement(name = "CATALOG_STRUCTURE", required = true)
    protected List<BCCATALOGSTRUCTURE> catalogstructure;
    @XmlElement(name = "GROUP_SYSTEM_DESCRIPTION")
    protected List<BCGROUPSYSTEMDESCRIPTION> groupsystemdescription;

    /**
     * Gets the value of the groupsystemid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGROUPSYSTEMID() {
        return groupsystemid;
    }

    /**
     * Sets the value of the groupsystemid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGROUPSYSTEMID(String value) {
        this.groupsystemid = value;
    }

    /**
     * Gets the value of the groupsystemname property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupsystemname property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGROUPSYSTEMNAME().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCGROUPSYSTEMNAME }
     * 
     * 
     */
    public List<BCGROUPSYSTEMNAME> getGROUPSYSTEMNAME() {
        if (groupsystemname == null) {
            groupsystemname = new ArrayList<BCGROUPSYSTEMNAME>();
        }
        return this.groupsystemname;
    }

    /**
     * Gets the value of the catalogstructure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the catalogstructure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCATALOGSTRUCTURE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCCATALOGSTRUCTURE }
     * 
     * 
     */
    public List<BCCATALOGSTRUCTURE> getCATALOGSTRUCTURE() {
        if (catalogstructure == null) {
            catalogstructure = new ArrayList<BCCATALOGSTRUCTURE>();
        }
        return this.catalogstructure;
    }

    /**
     * Gets the value of the groupsystemdescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupsystemdescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGROUPSYSTEMDESCRIPTION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCGROUPSYSTEMDESCRIPTION }
     * 
     * 
     */
    public List<BCGROUPSYSTEMDESCRIPTION> getGROUPSYSTEMDESCRIPTION() {
        if (groupsystemdescription == null) {
            groupsystemdescription = new ArrayList<BCGROUPSYSTEMDESCRIPTION>();
        }
        return this.groupsystemdescription;
    }

}
