/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2015 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CLASSIFICATION_SYSTEM_NAME"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CLASSIFICATION_SYSTEM_FULLNAME" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}CLASSIFICATION_SYSTEM_VERSION_DETAILS" minOccurs="0"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}CLASSIFICATION_SYSTEM_VERSION" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CLASSIFICATION_SYSTEM_DESCR" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CLASSIFICATION_SYSTEM_PARTY_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CLASSIFICATION_SYSTEM_LEVELS" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CLASSIFICATION_SYSTEM_LEVEL_NAMES" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CLASSIFICATION_SYSTEM_TYPE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ALLOWED_VALUES" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}UNITS" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}FT_GROUPS" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CLASSIFICATION_SYSTEM_FEATURE_TEMPLATES" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CLASSIFICATION_GROUPS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "classificationsystemname",
    "classificationsystemfullname",
    "classificationsystemversiondetails",
    "classificationsystemversion",
    "classificationsystemdescr",
    "classificationsystempartyidref",
    "classificationsystemlevels",
    "classificationsystemlevelnames",
    "classificationsystemtype",
    "allowedvalues",
    "units",
    "ftgroups",
    "classificationsystemfeaturetemplates",
    "classificationgroups"
})
@XmlRootElement(name = "CLASSIFICATION_SYSTEM")
public class BCCLASSIFICATIONSYSTEM {

    @XmlElement(name = "CLASSIFICATION_SYSTEM_NAME", required = true)
    protected String classificationsystemname;
    @XmlElement(name = "CLASSIFICATION_SYSTEM_FULLNAME")
    protected List<BCCLASSIFICATIONSYSTEMFULLNAME> classificationsystemfullname;
    @XmlElement(name = "CLASSIFICATION_SYSTEM_VERSION_DETAILS")
    protected TypeVERSION classificationsystemversiondetails;
    @XmlElement(name = "CLASSIFICATION_SYSTEM_VERSION")
    protected String classificationsystemversion;
    @XmlElement(name = "CLASSIFICATION_SYSTEM_DESCR")
    protected List<BCCLASSIFICATIONSYSTEMDESCR> classificationsystemdescr;
    @XmlElement(name = "CLASSIFICATION_SYSTEM_PARTY_IDREF")
    protected TypePARTYID classificationsystempartyidref;
    @XmlElement(name = "CLASSIFICATION_SYSTEM_LEVELS")
    protected BigInteger classificationsystemlevels;
    @XmlElement(name = "CLASSIFICATION_SYSTEM_LEVEL_NAMES")
    protected BCCLASSIFICATIONSYSTEMLEVELNAMES classificationsystemlevelnames;
    @XmlElement(name = "CLASSIFICATION_SYSTEM_TYPE")
    protected BCCLASSIFICATIONSYSTEMTYPE classificationsystemtype;
    @XmlElement(name = "ALLOWED_VALUES")
    protected BCALLOWEDVALUES allowedvalues;
    @XmlElement(name = "UNITS")
    protected BCUNITS units;
    @XmlElement(name = "FT_GROUPS")
    protected BCFTGROUPS ftgroups;
    @XmlElement(name = "CLASSIFICATION_SYSTEM_FEATURE_TEMPLATES")
    protected BCCLASSIFICATIONSYSTEMFEATURETEMPLATES classificationsystemfeaturetemplates;
    @XmlElement(name = "CLASSIFICATION_GROUPS")
    protected BCCLASSIFICATIONGROUPS classificationgroups;

    /**
     * Gets the value of the classificationsystemname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLASSIFICATIONSYSTEMNAME() {
        return classificationsystemname;
    }

    /**
     * Sets the value of the classificationsystemname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLASSIFICATIONSYSTEMNAME(String value) {
        this.classificationsystemname = value;
    }

    /**
     * Gets the value of the classificationsystemfullname property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classificationsystemfullname property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCLASSIFICATIONSYSTEMFULLNAME().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCCLASSIFICATIONSYSTEMFULLNAME }
     * 
     * 
     */
    public List<BCCLASSIFICATIONSYSTEMFULLNAME> getCLASSIFICATIONSYSTEMFULLNAME() {
        if (classificationsystemfullname == null) {
            classificationsystemfullname = new ArrayList<BCCLASSIFICATIONSYSTEMFULLNAME>();
        }
        return this.classificationsystemfullname;
    }

    /**
     * Gets the value of the classificationsystemversiondetails property.
     * 
     * @return
     *     possible object is
     *     {@link TypeVERSION }
     *     
     */
    public TypeVERSION getCLASSIFICATIONSYSTEMVERSIONDETAILS() {
        return classificationsystemversiondetails;
    }

    /**
     * Sets the value of the classificationsystemversiondetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeVERSION }
     *     
     */
    public void setCLASSIFICATIONSYSTEMVERSIONDETAILS(TypeVERSION value) {
        this.classificationsystemversiondetails = value;
    }

    /**
     * Gets the value of the classificationsystemversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLASSIFICATIONSYSTEMVERSION() {
        return classificationsystemversion;
    }

    /**
     * Sets the value of the classificationsystemversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLASSIFICATIONSYSTEMVERSION(String value) {
        this.classificationsystemversion = value;
    }

    /**
     * Gets the value of the classificationsystemdescr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classificationsystemdescr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCLASSIFICATIONSYSTEMDESCR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCCLASSIFICATIONSYSTEMDESCR }
     * 
     * 
     */
    public List<BCCLASSIFICATIONSYSTEMDESCR> getCLASSIFICATIONSYSTEMDESCR() {
        if (classificationsystemdescr == null) {
            classificationsystemdescr = new ArrayList<BCCLASSIFICATIONSYSTEMDESCR>();
        }
        return this.classificationsystemdescr;
    }

    /**
     * Gets the value of the classificationsystempartyidref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getCLASSIFICATIONSYSTEMPARTYIDREF() {
        return classificationsystempartyidref;
    }

    /**
     * Sets the value of the classificationsystempartyidref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setCLASSIFICATIONSYSTEMPARTYIDREF(TypePARTYID value) {
        this.classificationsystempartyidref = value;
    }

    /**
     * Gets the value of the classificationsystemlevels property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCLASSIFICATIONSYSTEMLEVELS() {
        return classificationsystemlevels;
    }

    /**
     * Sets the value of the classificationsystemlevels property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCLASSIFICATIONSYSTEMLEVELS(BigInteger value) {
        this.classificationsystemlevels = value;
    }

    /**
     * Gets the value of the classificationsystemlevelnames property.
     * 
     * @return
     *     possible object is
     *     {@link BCCLASSIFICATIONSYSTEMLEVELNAMES }
     *     
     */
    public BCCLASSIFICATIONSYSTEMLEVELNAMES getCLASSIFICATIONSYSTEMLEVELNAMES() {
        return classificationsystemlevelnames;
    }

    /**
     * Sets the value of the classificationsystemlevelnames property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCCLASSIFICATIONSYSTEMLEVELNAMES }
     *     
     */
    public void setCLASSIFICATIONSYSTEMLEVELNAMES(BCCLASSIFICATIONSYSTEMLEVELNAMES value) {
        this.classificationsystemlevelnames = value;
    }

    /**
     * Gets the value of the classificationsystemtype property.
     * 
     * @return
     *     possible object is
     *     {@link BCCLASSIFICATIONSYSTEMTYPE }
     *     
     */
    public BCCLASSIFICATIONSYSTEMTYPE getCLASSIFICATIONSYSTEMTYPE() {
        return classificationsystemtype;
    }

    /**
     * Sets the value of the classificationsystemtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCCLASSIFICATIONSYSTEMTYPE }
     *     
     */
    public void setCLASSIFICATIONSYSTEMTYPE(BCCLASSIFICATIONSYSTEMTYPE value) {
        this.classificationsystemtype = value;
    }

    /**
     * Gets the value of the allowedvalues property.
     * 
     * @return
     *     possible object is
     *     {@link BCALLOWEDVALUES }
     *     
     */
    public BCALLOWEDVALUES getALLOWEDVALUES() {
        return allowedvalues;
    }

    /**
     * Sets the value of the allowedvalues property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCALLOWEDVALUES }
     *     
     */
    public void setALLOWEDVALUES(BCALLOWEDVALUES value) {
        this.allowedvalues = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link BCUNITS }
     *     
     */
    public BCUNITS getUNITS() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCUNITS }
     *     
     */
    public void setUNITS(BCUNITS value) {
        this.units = value;
    }

    /**
     * Gets the value of the ftgroups property.
     * 
     * @return
     *     possible object is
     *     {@link BCFTGROUPS }
     *     
     */
    public BCFTGROUPS getFTGROUPS() {
        return ftgroups;
    }

    /**
     * Sets the value of the ftgroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCFTGROUPS }
     *     
     */
    public void setFTGROUPS(BCFTGROUPS value) {
        this.ftgroups = value;
    }

    /**
     * Gets the value of the classificationsystemfeaturetemplates property.
     * 
     * @return
     *     possible object is
     *     {@link BCCLASSIFICATIONSYSTEMFEATURETEMPLATES }
     *     
     */
    public BCCLASSIFICATIONSYSTEMFEATURETEMPLATES getCLASSIFICATIONSYSTEMFEATURETEMPLATES() {
        return classificationsystemfeaturetemplates;
    }

    /**
     * Sets the value of the classificationsystemfeaturetemplates property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCCLASSIFICATIONSYSTEMFEATURETEMPLATES }
     *     
     */
    public void setCLASSIFICATIONSYSTEMFEATURETEMPLATES(BCCLASSIFICATIONSYSTEMFEATURETEMPLATES value) {
        this.classificationsystemfeaturetemplates = value;
    }

    /**
     * Gets the value of the classificationgroups property.
     * 
     * @return
     *     possible object is
     *     {@link BCCLASSIFICATIONGROUPS }
     *     
     */
    public BCCLASSIFICATIONGROUPS getCLASSIFICATIONGROUPS() {
        return classificationgroups;
    }

    /**
     * Sets the value of the classificationgroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCCLASSIFICATIONGROUPS }
     *     
     */
    public void setCLASSIFICATIONGROUPS(BCCLASSIFICATIONGROUPS value) {
        this.classificationgroups = value;
    }

}
