/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}FNAME" maxOccurs="unbounded"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}FT_IDREF"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}FTEMPLATE"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;choice>
 *             &lt;element ref="{http://www.bmecat.org/bmecat/2005}FVALUE" maxOccurs="unbounded"/>
 *             &lt;element ref="{http://www.bmecat.org/bmecat/2005}VALUE_IDREF" maxOccurs="unbounded"/>
 *           &lt;/choice>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}VARIANTS"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}FUNIT" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}FORDER" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}FDESCR" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}FVALUE_DETAILS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}FVALUE_TYPE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fname",
    "ftidref",
    "ftemplate",
    "fvalue",
    "valueidref",
    "variants",
    "funit",
    "forder",
    "fdescr",
    "fvaluedetails",
    "fvaluetype"
})
@XmlRootElement(name = "FEATURE")
public class BCFEATURE {

    @XmlElement(name = "FNAME")
    protected List<BCFNAME> fname;
    @XmlElement(name = "FT_IDREF")
    protected String ftidref;
    @XmlElement(name = "FTEMPLATE")
    protected TypeFTEMPLATE ftemplate;
    @XmlElement(name = "FVALUE")
    protected List<BCFVALUE> fvalue;
    @XmlElement(name = "VALUE_IDREF")
    protected List<String> valueidref;
    @XmlElement(name = "VARIANTS")
    protected BCVARIANTS variants;
    @XmlElement(name = "FUNIT")
    protected String funit;
    @XmlElement(name = "FORDER")
    protected BigInteger forder;
    @XmlElement(name = "FDESCR")
    protected List<BCFDESCR> fdescr;
    @XmlElement(name = "FVALUE_DETAILS")
    protected List<BCFVALUEDETAILS> fvaluedetails;
    @XmlElement(name = "FVALUE_TYPE")
    protected String fvaluetype;

    /**
     * Gets the value of the fname property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fname property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFNAME().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCFNAME }
     * 
     * 
     */
    public List<BCFNAME> getFNAME() {
        if (fname == null) {
            fname = new ArrayList<BCFNAME>();
        }
        return this.fname;
    }

    /**
     * Gets the value of the ftidref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFTIDREF() {
        return ftidref;
    }

    /**
     * Sets the value of the ftidref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFTIDREF(String value) {
        this.ftidref = value;
    }

    /**
     * Gets the value of the ftemplate property.
     * 
     * @return
     *     possible object is
     *     {@link TypeFTEMPLATE }
     *     
     */
    public TypeFTEMPLATE getFTEMPLATE() {
        return ftemplate;
    }

    /**
     * Sets the value of the ftemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeFTEMPLATE }
     *     
     */
    public void setFTEMPLATE(TypeFTEMPLATE value) {
        this.ftemplate = value;
    }

    /**
     * Gets the value of the fvalue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fvalue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFVALUE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCFVALUE }
     * 
     * 
     */
    public List<BCFVALUE> getFVALUE() {
        if (fvalue == null) {
            fvalue = new ArrayList<BCFVALUE>();
        }
        return this.fvalue;
    }

    /**
     * Gets the value of the valueidref property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valueidref property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVALUEIDREF().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getVALUEIDREF() {
        if (valueidref == null) {
            valueidref = new ArrayList<String>();
        }
        return this.valueidref;
    }

    /**
     * Gets the value of the variants property.
     * 
     * @return
     *     possible object is
     *     {@link BCVARIANTS }
     *     
     */
    public BCVARIANTS getVARIANTS() {
        return variants;
    }

    /**
     * Sets the value of the variants property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCVARIANTS }
     *     
     */
    public void setVARIANTS(BCVARIANTS value) {
        this.variants = value;
    }

    /**
     * Gets the value of the funit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFUNIT() {
        return funit;
    }

    /**
     * Sets the value of the funit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFUNIT(String value) {
        this.funit = value;
    }

    /**
     * Gets the value of the forder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFORDER() {
        return forder;
    }

    /**
     * Sets the value of the forder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFORDER(BigInteger value) {
        this.forder = value;
    }

    /**
     * Gets the value of the fdescr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fdescr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFDESCR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCFDESCR }
     * 
     * 
     */
    public List<BCFDESCR> getFDESCR() {
        if (fdescr == null) {
            fdescr = new ArrayList<BCFDESCR>();
        }
        return this.fdescr;
    }

    /**
     * Gets the value of the fvaluedetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fvaluedetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFVALUEDETAILS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCFVALUEDETAILS }
     * 
     * 
     */
    public List<BCFVALUEDETAILS> getFVALUEDETAILS() {
        if (fvaluedetails == null) {
            fvaluedetails = new ArrayList<BCFVALUEDETAILS>();
        }
        return this.fvaluedetails;
    }

    /**
     * Gets the value of the fvaluetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFVALUETYPE() {
        return fvaluetype;
    }

    /**
     * Sets the value of the fvaluetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFVALUETYPE(String value) {
        this.fvaluetype = value;
    }

}
