/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}FORMULA_ID"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}FORMULA_VERSION" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}FORMULA_NAME" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}FORMULA_DESCR" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}FORMULA_SOURCE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}MIME_INFO" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}FORMULA_FUNCTION" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PARAMETER_DEFINITIONS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "formulaid",
    "formulaversion",
    "formulaname",
    "formuladescr",
    "formulasource",
    "mimeinfo",
    "formulafunction",
    "parameterdefinitions"
})
@XmlRootElement(name = "FORMULA")
public class BCFORMULA {

    @XmlElement(name = "FORMULA_ID", required = true)
    protected String formulaid;
    @XmlElement(name = "FORMULA_VERSION")
    protected TypeVERSION formulaversion;
    @XmlElement(name = "FORMULA_NAME")
    protected List<BCFORMULANAME> formulaname;
    @XmlElement(name = "FORMULA_DESCR")
    protected List<BCFORMULADESCR> formuladescr;
    @XmlElement(name = "FORMULA_SOURCE")
    protected TypeSOURCE formulasource;
    @XmlElement(name = "MIME_INFO")
    protected BCMIMEINFO mimeinfo;
    @XmlElement(name = "FORMULA_FUNCTION")
    protected BCFORMULAFUNCTION formulafunction;
    @XmlElement(name = "PARAMETER_DEFINITIONS", required = true)
    protected BCPARAMETERDEFINITIONS parameterdefinitions;

    /**
     * Gets the value of the formulaid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFORMULAID() {
        return formulaid;
    }

    /**
     * Sets the value of the formulaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFORMULAID(String value) {
        this.formulaid = value;
    }

    /**
     * Gets the value of the formulaversion property.
     * 
     * @return
     *     possible object is
     *     {@link TypeVERSION }
     *     
     */
    public TypeVERSION getFORMULAVERSION() {
        return formulaversion;
    }

    /**
     * Sets the value of the formulaversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeVERSION }
     *     
     */
    public void setFORMULAVERSION(TypeVERSION value) {
        this.formulaversion = value;
    }

    /**
     * Gets the value of the formulaname property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formulaname property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFORMULANAME().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCFORMULANAME }
     * 
     * 
     */
    public List<BCFORMULANAME> getFORMULANAME() {
        if (formulaname == null) {
            formulaname = new ArrayList<BCFORMULANAME>();
        }
        return this.formulaname;
    }

    /**
     * Gets the value of the formuladescr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formuladescr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFORMULADESCR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCFORMULADESCR }
     * 
     * 
     */
    public List<BCFORMULADESCR> getFORMULADESCR() {
        if (formuladescr == null) {
            formuladescr = new ArrayList<BCFORMULADESCR>();
        }
        return this.formuladescr;
    }

    /**
     * Gets the value of the formulasource property.
     * 
     * @return
     *     possible object is
     *     {@link TypeSOURCE }
     *     
     */
    public TypeSOURCE getFORMULASOURCE() {
        return formulasource;
    }

    /**
     * Sets the value of the formulasource property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeSOURCE }
     *     
     */
    public void setFORMULASOURCE(TypeSOURCE value) {
        this.formulasource = value;
    }

    /**
     * Gets the value of the mimeinfo property.
     * 
     * @return
     *     possible object is
     *     {@link BCMIMEINFO }
     *     
     */
    public BCMIMEINFO getMIMEINFO() {
        return mimeinfo;
    }

    /**
     * Sets the value of the mimeinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCMIMEINFO }
     *     
     */
    public void setMIMEINFO(BCMIMEINFO value) {
        this.mimeinfo = value;
    }

    /**
     * Gets the value of the formulafunction property.
     * 
     * @return
     *     possible object is
     *     {@link BCFORMULAFUNCTION }
     *     
     */
    public BCFORMULAFUNCTION getFORMULAFUNCTION() {
        return formulafunction;
    }

    /**
     * Sets the value of the formulafunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCFORMULAFUNCTION }
     *     
     */
    public void setFORMULAFUNCTION(BCFORMULAFUNCTION value) {
        this.formulafunction = value;
    }

    /**
     * Gets the value of the parameterdefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link BCPARAMETERDEFINITIONS }
     *     
     */
    public BCPARAMETERDEFINITIONS getPARAMETERDEFINITIONS() {
        return parameterdefinitions;
    }

    /**
     * Sets the value of the parameterdefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCPARAMETERDEFINITIONS }
     *     
     */
    public void setPARAMETERDEFINITIONS(BCPARAMETERDEFINITIONS value) {
        this.parameterdefinitions = value;
    }

}
