/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}VALUE_IDREF"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}VALUE_SIMPLE"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}VALUE_TEXT"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}VALUE_RANGE"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}MIME_INFO" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CONFIG_INFO" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}VALUE_ORDER" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}DEFAULT_FLAG" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "valueidref",
    "valuesimple",
    "valuetext",
    "valuerange",
    "mimeinfo",
    "configinfo",
    "valueorder",
    "defaultflag"
})
@XmlRootElement(name = "FT_VALUE")
public class BCFTVALUE {

    @XmlElement(name = "VALUE_IDREF")
    protected String valueidref;
    @XmlElement(name = "VALUE_SIMPLE")
    protected String valuesimple;
    @XmlElement(name = "VALUE_TEXT")
    protected BCVALUETEXT valuetext;
    @XmlElement(name = "VALUE_RANGE")
    protected BCVALUERANGE valuerange;
    @XmlElement(name = "MIME_INFO")
    protected BCMIMEINFO mimeinfo;
    @XmlElement(name = "CONFIG_INFO")
    protected BCCONFIGINFO configinfo;
    @XmlElement(name = "VALUE_ORDER")
    protected BigInteger valueorder;
    @XmlElement(name = "DEFAULT_FLAG")
    protected String defaultflag;

    /**
     * Gets the value of the valueidref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALUEIDREF() {
        return valueidref;
    }

    /**
     * Sets the value of the valueidref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALUEIDREF(String value) {
        this.valueidref = value;
    }

    /**
     * Gets the value of the valuesimple property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALUESIMPLE() {
        return valuesimple;
    }

    /**
     * Sets the value of the valuesimple property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALUESIMPLE(String value) {
        this.valuesimple = value;
    }

    /**
     * Gets the value of the valuetext property.
     * 
     * @return
     *     possible object is
     *     {@link BCVALUETEXT }
     *     
     */
    public BCVALUETEXT getVALUETEXT() {
        return valuetext;
    }

    /**
     * Sets the value of the valuetext property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCVALUETEXT }
     *     
     */
    public void setVALUETEXT(BCVALUETEXT value) {
        this.valuetext = value;
    }

    /**
     * Gets the value of the valuerange property.
     * 
     * @return
     *     possible object is
     *     {@link BCVALUERANGE }
     *     
     */
    public BCVALUERANGE getVALUERANGE() {
        return valuerange;
    }

    /**
     * Sets the value of the valuerange property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCVALUERANGE }
     *     
     */
    public void setVALUERANGE(BCVALUERANGE value) {
        this.valuerange = value;
    }

    /**
     * Gets the value of the mimeinfo property.
     * 
     * @return
     *     possible object is
     *     {@link BCMIMEINFO }
     *     
     */
    public BCMIMEINFO getMIMEINFO() {
        return mimeinfo;
    }

    /**
     * Sets the value of the mimeinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCMIMEINFO }
     *     
     */
    public void setMIMEINFO(BCMIMEINFO value) {
        this.mimeinfo = value;
    }

    /**
     * Gets the value of the configinfo property.
     * 
     * @return
     *     possible object is
     *     {@link BCCONFIGINFO }
     *     
     */
    public BCCONFIGINFO getCONFIGINFO() {
        return configinfo;
    }

    /**
     * Sets the value of the configinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCCONFIGINFO }
     *     
     */
    public void setCONFIGINFO(BCCONFIGINFO value) {
        this.configinfo = value;
    }

    /**
     * Gets the value of the valueorder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVALUEORDER() {
        return valueorder;
    }

    /**
     * Sets the value of the valueorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVALUEORDER(BigInteger value) {
        this.valueorder = value;
    }

    /**
     * Gets the value of the defaultflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEFAULTFLAG() {
        return defaultflag;
    }

    /**
     * Sets the value of the defaultflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEFAULTFLAG(String value) {
        this.defaultflag = value;
    }

}
