/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}GENERATOR_INFO" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CATALOG"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}BUYER_IDREF" minOccurs="0"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}BUYER" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}AGREEMENT" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}LEGAL_INFO" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_IDREF"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}DOCUMENT_CREATOR_IDREF"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PARTIES" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}AREAS" minOccurs="0"/>
 *         &lt;element name="USER_DEFINED_EXTENSIONS" type="{http://www.bmecat.org/bmecat/2005}udxHEADER" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "generatorinfo",
    "catalog",
    "buyeridref",
    "buyer",
    "agreement",
    "legalinfo",
    "supplieridref",
    "supplier",
    "documentcreatoridref",
    "parties",
    "areas",
    "userdefinedextensions"
})
@XmlRootElement(name = "HEADER")
public class BCHEADER {

    @XmlElement(name = "GENERATOR_INFO")
    protected String generatorinfo;
    @XmlElement(name = "CATALOG", required = true)
    protected BCCATALOG catalog;
    @XmlElement(name = "BUYER_IDREF")
    protected TypePARTYID buyeridref;
    @XmlElement(name = "BUYER")
    protected BCBUYER buyer;
    @XmlElement(name = "AGREEMENT")
    protected List<BCAGREEMENT> agreement;
    @XmlElement(name = "LEGAL_INFO")
    protected BCLEGALINFO legalinfo;
    @XmlElement(name = "SUPPLIER_IDREF")
    protected TypePARTYID supplieridref;
    @XmlElement(name = "SUPPLIER")
    protected BCSUPPLIER supplier;
    @XmlElement(name = "DOCUMENT_CREATOR_IDREF")
    protected TypePARTYID documentcreatoridref;
    @XmlElement(name = "PARTIES")
    protected BCPARTIES parties;
    @XmlElement(name = "AREAS")
    protected BCAREAS areas;
    @XmlElement(name = "USER_DEFINED_EXTENSIONS")
    protected UdxHEADER userdefinedextensions;

    /**
     * Gets the value of the generatorinfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGENERATORINFO() {
        return generatorinfo;
    }

    /**
     * Sets the value of the generatorinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGENERATORINFO(String value) {
        this.generatorinfo = value;
    }

    /**
     * Gets the value of the catalog property.
     * 
     * @return
     *     possible object is
     *     {@link BCCATALOG }
     *     
     */
    public BCCATALOG getCATALOG() {
        return catalog;
    }

    /**
     * Sets the value of the catalog property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCCATALOG }
     *     
     */
    public void setCATALOG(BCCATALOG value) {
        this.catalog = value;
    }

    /**
     * Gets the value of the buyeridref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getBUYERIDREF() {
        return buyeridref;
    }

    /**
     * Sets the value of the buyeridref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setBUYERIDREF(TypePARTYID value) {
        this.buyeridref = value;
    }

    /**
     * Gets the value of the buyer property.
     * 
     * @return
     *     possible object is
     *     {@link BCBUYER }
     *     
     */
    public BCBUYER getBUYER() {
        return buyer;
    }

    /**
     * Sets the value of the buyer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCBUYER }
     *     
     */
    public void setBUYER(BCBUYER value) {
        this.buyer = value;
    }

    /**
     * Gets the value of the agreement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agreement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAGREEMENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCAGREEMENT }
     * 
     * 
     */
    public List<BCAGREEMENT> getAGREEMENT() {
        if (agreement == null) {
            agreement = new ArrayList<BCAGREEMENT>();
        }
        return this.agreement;
    }

    /**
     * Gets the value of the legalinfo property.
     * 
     * @return
     *     possible object is
     *     {@link BCLEGALINFO }
     *     
     */
    public BCLEGALINFO getLEGALINFO() {
        return legalinfo;
    }

    /**
     * Sets the value of the legalinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCLEGALINFO }
     *     
     */
    public void setLEGALINFO(BCLEGALINFO value) {
        this.legalinfo = value;
    }

    /**
     * Gets the value of the supplieridref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getSUPPLIERIDREF() {
        return supplieridref;
    }

    /**
     * Sets the value of the supplieridref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setSUPPLIERIDREF(TypePARTYID value) {
        this.supplieridref = value;
    }

    /**
     * Gets the value of the supplier property.
     * 
     * @return
     *     possible object is
     *     {@link BCSUPPLIER }
     *     
     */
    public BCSUPPLIER getSUPPLIER() {
        return supplier;
    }

    /**
     * Sets the value of the supplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCSUPPLIER }
     *     
     */
    public void setSUPPLIER(BCSUPPLIER value) {
        this.supplier = value;
    }

    /**
     * Gets the value of the documentcreatoridref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getDOCUMENTCREATORIDREF() {
        return documentcreatoridref;
    }

    /**
     * Sets the value of the documentcreatoridref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setDOCUMENTCREATORIDREF(TypePARTYID value) {
        this.documentcreatoridref = value;
    }

    /**
     * Gets the value of the parties property.
     * 
     * @return
     *     possible object is
     *     {@link BCPARTIES }
     *     
     */
    public BCPARTIES getPARTIES() {
        return parties;
    }

    /**
     * Sets the value of the parties property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCPARTIES }
     *     
     */
    public void setPARTIES(BCPARTIES value) {
        this.parties = value;
    }

    /**
     * Gets the value of the areas property.
     * 
     * @return
     *     possible object is
     *     {@link BCAREAS }
     *     
     */
    public BCAREAS getAREAS() {
        return areas;
    }

    /**
     * Sets the value of the areas property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCAREAS }
     *     
     */
    public void setAREAS(BCAREAS value) {
        this.areas = value;
    }

    /**
     * Gets the value of the userdefinedextensions property.
     * 
     * @return
     *     possible object is
     *     {@link UdxHEADER }
     *     
     */
    public UdxHEADER getUSERDEFINEDEXTENSIONS() {
        return userdefinedextensions;
    }

    /**
     * Sets the value of the userdefinedextensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link UdxHEADER }
     *     
     */
    public void setUSERDEFINEDEXTENSIONS(UdxHEADER value) {
        this.userdefinedextensions = value;
    }

}
