/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_LANGUAGES" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_TERRITORIES" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_PRICE_CURRENCIES" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_PRICE_TYPES" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_SUPPLIER_PID" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_PRODUCTCONFIG_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_PRODUCTLIST_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_USER_INFO" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_AUTHENTIFICATION_INFO" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_PARAM_DEFINITION" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ipplanguages",
    "ippterritories",
    "ipppricecurrencies",
    "ipppricetypes",
    "ippsupplierpid",
    "ippproductconfigidref",
    "ippproductlistidref",
    "ippuserinfo",
    "ippauthentificationinfo",
    "ippparamdefinition"
})
@XmlRootElement(name = "IPP_OUTBOUND_PARAMS")
public class BCIPPOUTBOUNDPARAMS {

    @XmlElement(name = "IPP_LANGUAGES")
    protected BCIPPLANGUAGES ipplanguages;
    @XmlElement(name = "IPP_TERRITORIES")
    protected BCIPPTERRITORIES ippterritories;
    @XmlElement(name = "IPP_PRICE_CURRENCIES")
    protected BCIPPPRICECURRENCIES ipppricecurrencies;
    @XmlElement(name = "IPP_PRICE_TYPES")
    protected BCIPPPRICETYPES ipppricetypes;
    @XmlElement(name = "IPP_SUPPLIER_PID")
    protected BCIPPSUPPLIERPID ippsupplierpid;
    @XmlElement(name = "IPP_PRODUCTCONFIG_IDREF")
    protected BCIPPPRODUCTCONFIGIDREF ippproductconfigidref;
    @XmlElement(name = "IPP_PRODUCTLIST_IDREF")
    protected BCIPPPRODUCTLISTIDREF ippproductlistidref;
    @XmlElement(name = "IPP_USER_INFO")
    protected BCIPPUSERINFO ippuserinfo;
    @XmlElement(name = "IPP_AUTHENTIFICATION_INFO")
    protected BCIPPAUTHENTIFICATIONINFO ippauthentificationinfo;
    @XmlElement(name = "IPP_PARAM_DEFINITION")
    protected List<BCIPPPARAMDEFINITION> ippparamdefinition;

    /**
     * Gets the value of the ipplanguages property.
     * 
     * @return
     *     possible object is
     *     {@link BCIPPLANGUAGES }
     *     
     */
    public BCIPPLANGUAGES getIPPLANGUAGES() {
        return ipplanguages;
    }

    /**
     * Sets the value of the ipplanguages property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCIPPLANGUAGES }
     *     
     */
    public void setIPPLANGUAGES(BCIPPLANGUAGES value) {
        this.ipplanguages = value;
    }

    /**
     * Gets the value of the ippterritories property.
     * 
     * @return
     *     possible object is
     *     {@link BCIPPTERRITORIES }
     *     
     */
    public BCIPPTERRITORIES getIPPTERRITORIES() {
        return ippterritories;
    }

    /**
     * Sets the value of the ippterritories property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCIPPTERRITORIES }
     *     
     */
    public void setIPPTERRITORIES(BCIPPTERRITORIES value) {
        this.ippterritories = value;
    }

    /**
     * Gets the value of the ipppricecurrencies property.
     * 
     * @return
     *     possible object is
     *     {@link BCIPPPRICECURRENCIES }
     *     
     */
    public BCIPPPRICECURRENCIES getIPPPRICECURRENCIES() {
        return ipppricecurrencies;
    }

    /**
     * Sets the value of the ipppricecurrencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCIPPPRICECURRENCIES }
     *     
     */
    public void setIPPPRICECURRENCIES(BCIPPPRICECURRENCIES value) {
        this.ipppricecurrencies = value;
    }

    /**
     * Gets the value of the ipppricetypes property.
     * 
     * @return
     *     possible object is
     *     {@link BCIPPPRICETYPES }
     *     
     */
    public BCIPPPRICETYPES getIPPPRICETYPES() {
        return ipppricetypes;
    }

    /**
     * Sets the value of the ipppricetypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCIPPPRICETYPES }
     *     
     */
    public void setIPPPRICETYPES(BCIPPPRICETYPES value) {
        this.ipppricetypes = value;
    }

    /**
     * Gets the value of the ippsupplierpid property.
     * 
     * @return
     *     possible object is
     *     {@link BCIPPSUPPLIERPID }
     *     
     */
    public BCIPPSUPPLIERPID getIPPSUPPLIERPID() {
        return ippsupplierpid;
    }

    /**
     * Sets the value of the ippsupplierpid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCIPPSUPPLIERPID }
     *     
     */
    public void setIPPSUPPLIERPID(BCIPPSUPPLIERPID value) {
        this.ippsupplierpid = value;
    }

    /**
     * Gets the value of the ippproductconfigidref property.
     * 
     * @return
     *     possible object is
     *     {@link BCIPPPRODUCTCONFIGIDREF }
     *     
     */
    public BCIPPPRODUCTCONFIGIDREF getIPPPRODUCTCONFIGIDREF() {
        return ippproductconfigidref;
    }

    /**
     * Sets the value of the ippproductconfigidref property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCIPPPRODUCTCONFIGIDREF }
     *     
     */
    public void setIPPPRODUCTCONFIGIDREF(BCIPPPRODUCTCONFIGIDREF value) {
        this.ippproductconfigidref = value;
    }

    /**
     * Gets the value of the ippproductlistidref property.
     * 
     * @return
     *     possible object is
     *     {@link BCIPPPRODUCTLISTIDREF }
     *     
     */
    public BCIPPPRODUCTLISTIDREF getIPPPRODUCTLISTIDREF() {
        return ippproductlistidref;
    }

    /**
     * Sets the value of the ippproductlistidref property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCIPPPRODUCTLISTIDREF }
     *     
     */
    public void setIPPPRODUCTLISTIDREF(BCIPPPRODUCTLISTIDREF value) {
        this.ippproductlistidref = value;
    }

    /**
     * Gets the value of the ippuserinfo property.
     * 
     * @return
     *     possible object is
     *     {@link BCIPPUSERINFO }
     *     
     */
    public BCIPPUSERINFO getIPPUSERINFO() {
        return ippuserinfo;
    }

    /**
     * Sets the value of the ippuserinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCIPPUSERINFO }
     *     
     */
    public void setIPPUSERINFO(BCIPPUSERINFO value) {
        this.ippuserinfo = value;
    }

    /**
     * Gets the value of the ippauthentificationinfo property.
     * 
     * @return
     *     possible object is
     *     {@link BCIPPAUTHENTIFICATIONINFO }
     *     
     */
    public BCIPPAUTHENTIFICATIONINFO getIPPAUTHENTIFICATIONINFO() {
        return ippauthentificationinfo;
    }

    /**
     * Sets the value of the ippauthentificationinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCIPPAUTHENTIFICATIONINFO }
     *     
     */
    public void setIPPAUTHENTIFICATIONINFO(BCIPPAUTHENTIFICATIONINFO value) {
        this.ippauthentificationinfo = value;
    }

    /**
     * Gets the value of the ippparamdefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ippparamdefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIPPPARAMDEFINITION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCIPPPARAMDEFINITION }
     * 
     * 
     */
    public List<BCIPPPARAMDEFINITION> getIPPPARAMDEFINITION() {
        if (ippparamdefinition == null) {
            ippparamdefinition = new ArrayList<BCIPPPARAMDEFINITION>();
        }
        return this.ippparamdefinition;
    }

}
