/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_IDREF"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_OPERATION_IDREF" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_RESPONSE_TIME" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_URI" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_PARAM" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ippidref",
    "ippoperationidref",
    "ippresponsetime",
    "ippuri",
    "ippparam"
})
@XmlRootElement(name = "IPP")
public class BCIPP {

    @XmlElement(name = "IPP_IDREF", required = true)
    protected String ippidref;
    @XmlElement(name = "IPP_OPERATION_IDREF", required = true)
    protected List<String> ippoperationidref;
    @XmlElement(name = "IPP_RESPONSE_TIME")
    protected Duration ippresponsetime;
    @XmlElement(name = "IPP_URI")
    protected List<BCIPPURI> ippuri;
    @XmlElement(name = "IPP_PARAM")
    protected List<BCIPPPARAM> ippparam;

    /**
     * Gets the value of the ippidref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPPIDREF() {
        return ippidref;
    }

    /**
     * Sets the value of the ippidref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPPIDREF(String value) {
        this.ippidref = value;
    }

    /**
     * Gets the value of the ippoperationidref property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ippoperationidref property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIPPOPERATIONIDREF().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIPPOPERATIONIDREF() {
        if (ippoperationidref == null) {
            ippoperationidref = new ArrayList<String>();
        }
        return this.ippoperationidref;
    }

    /**
     * Gets the value of the ippresponsetime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getIPPRESPONSETIME() {
        return ippresponsetime;
    }

    /**
     * Sets the value of the ippresponsetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setIPPRESPONSETIME(Duration value) {
        this.ippresponsetime = value;
    }

    /**
     * Gets the value of the ippuri property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ippuri property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIPPURI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCIPPURI }
     * 
     * 
     */
    public List<BCIPPURI> getIPPURI() {
        if (ippuri == null) {
            ippuri = new ArrayList<BCIPPURI>();
        }
        return this.ippuri;
    }

    /**
     * Gets the value of the ippparam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ippparam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIPPPARAM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCIPPPARAM }
     * 
     * 
     */
    public List<BCIPPPARAM> getIPPPARAM() {
        if (ippparam == null) {
            ippparam = new ArrayList<BCIPPPARAM>();
        }
        return this.ippparam;
    }

}
