/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}QUANTITY_MIN"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}QUANTITY_MAX"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PACKING_UNIT_CODE"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PACKING_UNIT_DESCR" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_PID"/>
 *           &lt;sequence minOccurs="0">
 *             &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_PIDREF"/>
 *             &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_IDREF" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "quantitymin",
    "quantitymax",
    "packingunitcode",
    "packingunitdescr",
    "supplierpid",
    "supplierpidref",
    "supplieridref"
})
@XmlRootElement(name = "PACKING_UNIT")
public class BCPACKINGUNIT {

    @XmlElement(name = "QUANTITY_MIN", defaultValue = "1")
    protected float quantitymin;
    @XmlElement(name = "QUANTITY_MAX")
    protected float quantitymax;
    @XmlElement(name = "PACKING_UNIT_CODE", required = true)
    protected String packingunitcode;
    @XmlElement(name = "PACKING_UNIT_DESCR")
    protected List<BCPACKINGUNITDESCR> packingunitdescr;
    @XmlElement(name = "SUPPLIER_PID")
    protected BCSUPPLIERPID supplierpid;
    @XmlElement(name = "SUPPLIER_PIDREF")
    protected String supplierpidref;
    @XmlElement(name = "SUPPLIER_IDREF")
    protected TypePARTYID supplieridref;

    /**
     * Gets the value of the quantitymin property.
     * 
     */
    public float getQUANTITYMIN() {
        return quantitymin;
    }

    /**
     * Sets the value of the quantitymin property.
     * 
     */
    public void setQUANTITYMIN(float value) {
        this.quantitymin = value;
    }

    /**
     * Gets the value of the quantitymax property.
     * 
     */
    public float getQUANTITYMAX() {
        return quantitymax;
    }

    /**
     * Sets the value of the quantitymax property.
     * 
     */
    public void setQUANTITYMAX(float value) {
        this.quantitymax = value;
    }

    /**
     * Gets the value of the packingunitcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPACKINGUNITCODE() {
        return packingunitcode;
    }

    /**
     * Sets the value of the packingunitcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPACKINGUNITCODE(String value) {
        this.packingunitcode = value;
    }

    /**
     * Gets the value of the packingunitdescr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packingunitdescr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPACKINGUNITDESCR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCPACKINGUNITDESCR }
     * 
     * 
     */
    public List<BCPACKINGUNITDESCR> getPACKINGUNITDESCR() {
        if (packingunitdescr == null) {
            packingunitdescr = new ArrayList<BCPACKINGUNITDESCR>();
        }
        return this.packingunitdescr;
    }

    /**
     * Gets the value of the supplierpid property.
     * 
     * @return
     *     possible object is
     *     {@link BCSUPPLIERPID }
     *     
     */
    public BCSUPPLIERPID getSUPPLIERPID() {
        return supplierpid;
    }

    /**
     * Sets the value of the supplierpid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCSUPPLIERPID }
     *     
     */
    public void setSUPPLIERPID(BCSUPPLIERPID value) {
        this.supplierpid = value;
    }

    /**
     * Gets the value of the supplierpidref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUPPLIERPIDREF() {
        return supplierpidref;
    }

    /**
     * Sets the value of the supplierpidref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUPPLIERPIDREF(String value) {
        this.supplierpidref = value;
    }

    /**
     * Gets the value of the supplieridref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getSUPPLIERIDREF() {
        return supplieridref;
    }

    /**
     * Sets the value of the supplieridref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setSUPPLIERIDREF(TypePARTYID value) {
        this.supplieridref = value;
    }

}
