/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PARAMETER_SYMBOL"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}PARAMETER_BASICS"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}FREF"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PARAMETER_ORIGIN" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PARAMETER_DEFAULT_VALUE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PARAMETER_MEANING" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PARAMETER_ORDER" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parametersymbol",
    "parameterbasics",
    "fref",
    "parameterorigin",
    "parameterdefaultvalue",
    "parametermeaning",
    "parameterorder"
})
@XmlRootElement(name = "PARAMETER_DEFINITION")
public class BCPARAMETERDEFINITION {

    @XmlElement(name = "PARAMETER_SYMBOL", required = true)
    protected String parametersymbol;
    @XmlElement(name = "PARAMETER_BASICS")
    protected BCPARAMETERBASICS parameterbasics;
    @XmlElement(name = "FREF")
    protected BCFREF fref;
    @XmlElement(name = "PARAMETER_ORIGIN")
    protected BCPARAMETERORIGIN parameterorigin;
    @XmlElement(name = "PARAMETER_DEFAULT_VALUE")
    protected String parameterdefaultvalue;
    @XmlElement(name = "PARAMETER_MEANING")
    protected String parametermeaning;
    @XmlElement(name = "PARAMETER_ORDER")
    protected BigInteger parameterorder;

    /**
     * Gets the value of the parametersymbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARAMETERSYMBOL() {
        return parametersymbol;
    }

    /**
     * Sets the value of the parametersymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARAMETERSYMBOL(String value) {
        this.parametersymbol = value;
    }

    /**
     * Gets the value of the parameterbasics property.
     * 
     * @return
     *     possible object is
     *     {@link BCPARAMETERBASICS }
     *     
     */
    public BCPARAMETERBASICS getPARAMETERBASICS() {
        return parameterbasics;
    }

    /**
     * Sets the value of the parameterbasics property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCPARAMETERBASICS }
     *     
     */
    public void setPARAMETERBASICS(BCPARAMETERBASICS value) {
        this.parameterbasics = value;
    }

    /**
     * Gets the value of the fref property.
     * 
     * @return
     *     possible object is
     *     {@link BCFREF }
     *     
     */
    public BCFREF getFREF() {
        return fref;
    }

    /**
     * Sets the value of the fref property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCFREF }
     *     
     */
    public void setFREF(BCFREF value) {
        this.fref = value;
    }

    /**
     * Gets the value of the parameterorigin property.
     * 
     * @return
     *     possible object is
     *     {@link BCPARAMETERORIGIN }
     *     
     */
    public BCPARAMETERORIGIN getPARAMETERORIGIN() {
        return parameterorigin;
    }

    /**
     * Sets the value of the parameterorigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCPARAMETERORIGIN }
     *     
     */
    public void setPARAMETERORIGIN(BCPARAMETERORIGIN value) {
        this.parameterorigin = value;
    }

    /**
     * Gets the value of the parameterdefaultvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARAMETERDEFAULTVALUE() {
        return parameterdefaultvalue;
    }

    /**
     * Sets the value of the parameterdefaultvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARAMETERDEFAULTVALUE(String value) {
        this.parameterdefaultvalue = value;
    }

    /**
     * Gets the value of the parametermeaning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARAMETERMEANING() {
        return parametermeaning;
    }

    /**
     * Sets the value of the parametermeaning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARAMETERMEANING(String value) {
        this.parametermeaning = value;
    }

    /**
     * Gets the value of the parameterorder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPARAMETERORDER() {
        return parameterorder;
    }

    /**
     * Sets the value of the parameterorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPARAMETERORDER(BigInteger value) {
        this.parameterorder = value;
    }

}
