/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_PIDREF"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_ORDER" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}DEFAULT_FLAG" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CONFIG_CODE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_PRICE_DETAILS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "supplierpidref",
    "supplieridref",
    "productorder",
    "defaultflag",
    "configcode",
    "productpricedetails"
})
@XmlRootElement(name = "PART_ALTERNATIVE")
public class BCPARTALTERNATIVE {

    @XmlElement(name = "SUPPLIER_PIDREF", required = true)
    protected String supplierpidref;
    @XmlElement(name = "SUPPLIER_IDREF")
    protected TypePARTYID supplieridref;
    @XmlElement(name = "PRODUCT_ORDER")
    protected BigInteger productorder;
    @XmlElement(name = "DEFAULT_FLAG")
    protected String defaultflag;
    @XmlElement(name = "CONFIG_CODE")
    protected String configcode;
    @XmlElement(name = "PRODUCT_PRICE_DETAILS")
    protected BCPRODUCTPRICEDETAILS productpricedetails;

    /**
     * Gets the value of the supplierpidref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUPPLIERPIDREF() {
        return supplierpidref;
    }

    /**
     * Sets the value of the supplierpidref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUPPLIERPIDREF(String value) {
        this.supplierpidref = value;
    }

    /**
     * Gets the value of the supplieridref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getSUPPLIERIDREF() {
        return supplieridref;
    }

    /**
     * Sets the value of the supplieridref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setSUPPLIERIDREF(TypePARTYID value) {
        this.supplieridref = value;
    }

    /**
     * Gets the value of the productorder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPRODUCTORDER() {
        return productorder;
    }

    /**
     * Sets the value of the productorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPRODUCTORDER(BigInteger value) {
        this.productorder = value;
    }

    /**
     * Gets the value of the defaultflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEFAULTFLAG() {
        return defaultflag;
    }

    /**
     * Sets the value of the defaultflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEFAULTFLAG(String value) {
        this.defaultflag = value;
    }

    /**
     * Gets the value of the configcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONFIGCODE() {
        return configcode;
    }

    /**
     * Sets the value of the configcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONFIGCODE(String value) {
        this.configcode = value;
    }

    /**
     * Gets the value of the productpricedetails property.
     * 
     * @return
     *     possible object is
     *     {@link BCPRODUCTPRICEDETAILS }
     *     
     */
    public BCPRODUCTPRICEDETAILS getPRODUCTPRICEDETAILS() {
        return productpricedetails;
    }

    /**
     * Sets the value of the productpricedetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCPRODUCTPRICEDETAILS }
     *     
     */
    public void setPRODUCTPRICEDETAILS(BCPRODUCTPRICEDETAILS value) {
        this.productpricedetails = value;
    }

}
