/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PREDEFINED_CONFIG_CODE"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PREDEFINED_CONFIG_NAME" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PREDEFINED_CONFIG_DESCR" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PREDEFINED_CONFIG_ORDER" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_PRICE_DETAILS" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_PID" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}INTERNATIONAL_PID" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "predefinedconfigcode",
    "predefinedconfigname",
    "predefinedconfigdescr",
    "predefinedconfigorder",
    "productpricedetails",
    "supplierpid",
    "internationalpid"
})
@XmlRootElement(name = "PREDEFINED_CONFIG")
public class BCPREDEFINEDCONFIG {

    @XmlElement(name = "PREDEFINED_CONFIG_CODE", required = true)
    protected String predefinedconfigcode;
    @XmlElement(name = "PREDEFINED_CONFIG_NAME")
    protected List<BCPREDEFINEDCONFIGNAME> predefinedconfigname;
    @XmlElement(name = "PREDEFINED_CONFIG_DESCR")
    protected List<BCPREDEFINEDCONFIGDESCR> predefinedconfigdescr;
    @XmlElement(name = "PREDEFINED_CONFIG_ORDER")
    protected BigInteger predefinedconfigorder;
    @XmlElement(name = "PRODUCT_PRICE_DETAILS")
    protected BCPRODUCTPRICEDETAILS productpricedetails;
    @XmlElement(name = "SUPPLIER_PID")
    protected BCSUPPLIERPID supplierpid;
    @XmlElement(name = "INTERNATIONAL_PID")
    protected List<BCINTERNATIONALPID> internationalpid;

    /**
     * Gets the value of the predefinedconfigcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPREDEFINEDCONFIGCODE() {
        return predefinedconfigcode;
    }

    /**
     * Sets the value of the predefinedconfigcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPREDEFINEDCONFIGCODE(String value) {
        this.predefinedconfigcode = value;
    }

    /**
     * Gets the value of the predefinedconfigname property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the predefinedconfigname property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPREDEFINEDCONFIGNAME().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCPREDEFINEDCONFIGNAME }
     * 
     * 
     */
    public List<BCPREDEFINEDCONFIGNAME> getPREDEFINEDCONFIGNAME() {
        if (predefinedconfigname == null) {
            predefinedconfigname = new ArrayList<BCPREDEFINEDCONFIGNAME>();
        }
        return this.predefinedconfigname;
    }

    /**
     * Gets the value of the predefinedconfigdescr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the predefinedconfigdescr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPREDEFINEDCONFIGDESCR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCPREDEFINEDCONFIGDESCR }
     * 
     * 
     */
    public List<BCPREDEFINEDCONFIGDESCR> getPREDEFINEDCONFIGDESCR() {
        if (predefinedconfigdescr == null) {
            predefinedconfigdescr = new ArrayList<BCPREDEFINEDCONFIGDESCR>();
        }
        return this.predefinedconfigdescr;
    }

    /**
     * Gets the value of the predefinedconfigorder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPREDEFINEDCONFIGORDER() {
        return predefinedconfigorder;
    }

    /**
     * Sets the value of the predefinedconfigorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPREDEFINEDCONFIGORDER(BigInteger value) {
        this.predefinedconfigorder = value;
    }

    /**
     * Gets the value of the productpricedetails property.
     * 
     * @return
     *     possible object is
     *     {@link BCPRODUCTPRICEDETAILS }
     *     
     */
    public BCPRODUCTPRICEDETAILS getPRODUCTPRICEDETAILS() {
        return productpricedetails;
    }

    /**
     * Sets the value of the productpricedetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCPRODUCTPRICEDETAILS }
     *     
     */
    public void setPRODUCTPRICEDETAILS(BCPRODUCTPRICEDETAILS value) {
        this.productpricedetails = value;
    }

    /**
     * Gets the value of the supplierpid property.
     * 
     * @return
     *     possible object is
     *     {@link BCSUPPLIERPID }
     *     
     */
    public BCSUPPLIERPID getSUPPLIERPID() {
        return supplierpid;
    }

    /**
     * Sets the value of the supplierpid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCSUPPLIERPID }
     *     
     */
    public void setSUPPLIERPID(BCSUPPLIERPID value) {
        this.supplierpid = value;
    }

    /**
     * Gets the value of the internationalpid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the internationalpid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getINTERNATIONALPID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCINTERNATIONALPID }
     * 
     * 
     */
    public List<BCINTERNATIONALPID> getINTERNATIONALPID() {
        if (internationalpid == null) {
            internationalpid = new ArrayList<BCINTERNATIONALPID>();
        }
        return this.internationalpid;
    }

}
