/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2015 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence minOccurs="0">
 *             &lt;element ref="{http://www.bmecat.org/bmecat/2005}VALID_START_DATE" minOccurs="0"/>
 *             &lt;element ref="{http://www.bmecat.org/bmecat/2005}VALID_END_DATE" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element name="DATETIME" maxOccurs="2" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;extension base="{http://www.bmecat.org/bmecat/2005}typeDATETIME">
 *                   &lt;attribute name="type" use="required">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.bmecat.org/bmecat/2005}dtSTRING">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="20"/>
 *                         &lt;enumeration value="valid_start_date"/>
 *                         &lt;enumeration value="valid_end_date"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                 &lt;/extension>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}DAILY_PRICE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_PRICE" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validstartdate",
    "validenddate",
    "datetime",
    "dailyprice",
    "productprice"
})
@XmlRootElement(name = "PRODUCT_PRICE_DETAILS")
public class BCPRODUCTPRICEDETAILS {

    @XmlElement(name = "VALID_START_DATE")
    protected String validstartdate;
    @XmlElement(name = "VALID_END_DATE")
    protected String validenddate;
    @XmlElement(name = "DATETIME")
    protected List<BCPRODUCTPRICEDETAILS.DATETIME> datetime;
    @XmlElement(name = "DAILY_PRICE")
    protected String dailyprice;
    @XmlElement(name = "PRODUCT_PRICE", required = true)
    protected List<BCPRODUCTPRICE> productprice;

    /**
     * Gets the value of the validstartdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALIDSTARTDATE() {
        return validstartdate;
    }

    /**
     * Sets the value of the validstartdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALIDSTARTDATE(String value) {
        this.validstartdate = value;
    }

    /**
     * Gets the value of the validenddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALIDENDDATE() {
        return validenddate;
    }

    /**
     * Sets the value of the validenddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALIDENDDATE(String value) {
        this.validenddate = value;
    }

    /**
     * Gets the value of the datetime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datetime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDATETIME().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCPRODUCTPRICEDETAILS.DATETIME }
     * 
     * 
     */
    public List<BCPRODUCTPRICEDETAILS.DATETIME> getDATETIME() {
        if (datetime == null) {
            datetime = new ArrayList<BCPRODUCTPRICEDETAILS.DATETIME>();
        }
        return this.datetime;
    }

    /**
     * Gets the value of the dailyprice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDAILYPRICE() {
        return dailyprice;
    }

    /**
     * Sets the value of the dailyprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDAILYPRICE(String value) {
        this.dailyprice = value;
    }

    /**
     * Gets the value of the productprice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productprice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPRODUCTPRICE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCPRODUCTPRICE }
     * 
     * 
     */
    public List<BCPRODUCTPRICE> getPRODUCTPRICE() {
        if (productprice == null) {
            productprice = new ArrayList<BCPRODUCTPRICE>();
        }
        return this.productprice;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.bmecat.org/bmecat/2005}typeDATETIME">
     *       &lt;attribute name="type" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.bmecat.org/bmecat/2005}dtSTRING">
     *             &lt;minLength value="1"/>
     *             &lt;maxLength value="20"/>
     *             &lt;enumeration value="valid_start_date"/>
     *             &lt;enumeration value="valid_end_date"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DATETIME
        extends TypeDATETIME
    {

        @XmlAttribute(required = true)
        protected String type;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }

}
