/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRICE_AMOUNT" minOccurs="0"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRICE_FORMULA" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRICE_CURRENCY" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}TAX_DETAILS" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}TAX" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRICE_FACTOR" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}LOWER_BOUND" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}TERRITORY" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}AREA_REFS" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRICE_BASE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRICE_FLAG" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="price_type" use="required" type="{http://www.bmecat.org/bmecat/2005}typePRICE_TYPE" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "priceamount",
    "priceformula",
    "pricecurrency",
    "taxdetails",
    "tax",
    "pricefactor",
    "lowerbound",
    "territory",
    "arearefs",
    "pricebase",
    "priceflag"
})
@XmlRootElement(name = "PRODUCT_PRICE")
public class BCPRODUCTPRICE {

    @XmlElement(name = "PRICE_AMOUNT")
    protected BigDecimal priceamount;
    @XmlElement(name = "PRICE_FORMULA")
    protected BCPRICEFORMULA priceformula;
    @XmlElement(name = "PRICE_CURRENCY")
    protected DtCURRENCIES pricecurrency;
    @XmlElement(name = "TAX_DETAILS")
    protected List<BCTAXDETAILS> taxdetails;
    @XmlElement(name = "TAX")
    protected BigDecimal tax;
    @XmlElement(name = "PRICE_FACTOR", defaultValue = "1")
    protected BigDecimal pricefactor;
    @XmlElement(name = "LOWER_BOUND")
    protected BigDecimal lowerbound;
    @XmlElement(name = "TERRITORY")
    protected List<String> territory;
    @XmlElement(name = "AREA_REFS")
    protected BCAREAREFS arearefs;
    @XmlElement(name = "PRICE_BASE")
    protected BCPRICEBASE pricebase;
    @XmlElement(name = "PRICE_FLAG")
    protected List<BCPRICEFLAG> priceflag;
    @XmlAttribute(name = "price_type", required = true)
    protected String priceType;

    /**
     * Gets the value of the priceamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPRICEAMOUNT() {
        return priceamount;
    }

    /**
     * Sets the value of the priceamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPRICEAMOUNT(BigDecimal value) {
        this.priceamount = value;
    }

    /**
     * Gets the value of the priceformula property.
     * 
     * @return
     *     possible object is
     *     {@link BCPRICEFORMULA }
     *     
     */
    public BCPRICEFORMULA getPRICEFORMULA() {
        return priceformula;
    }

    /**
     * Sets the value of the priceformula property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCPRICEFORMULA }
     *     
     */
    public void setPRICEFORMULA(BCPRICEFORMULA value) {
        this.priceformula = value;
    }

    /**
     * Gets the value of the pricecurrency property.
     * 
     * @return
     *     possible object is
     *     {@link DtCURRENCIES }
     *     
     */
    public DtCURRENCIES getPRICECURRENCY() {
        return pricecurrency;
    }

    /**
     * Sets the value of the pricecurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link DtCURRENCIES }
     *     
     */
    public void setPRICECURRENCY(DtCURRENCIES value) {
        this.pricecurrency = value;
    }

    /**
     * Gets the value of the taxdetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxdetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTAXDETAILS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCTAXDETAILS }
     * 
     * 
     */
    public List<BCTAXDETAILS> getTAXDETAILS() {
        if (taxdetails == null) {
            taxdetails = new ArrayList<BCTAXDETAILS>();
        }
        return this.taxdetails;
    }

    /**
     * Gets the value of the tax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTAX() {
        return tax;
    }

    /**
     * Sets the value of the tax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTAX(BigDecimal value) {
        this.tax = value;
    }

    /**
     * Gets the value of the pricefactor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPRICEFACTOR() {
        return pricefactor;
    }

    /**
     * Sets the value of the pricefactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPRICEFACTOR(BigDecimal value) {
        this.pricefactor = value;
    }

    /**
     * Gets the value of the lowerbound property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLOWERBOUND() {
        return lowerbound;
    }

    /**
     * Sets the value of the lowerbound property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLOWERBOUND(BigDecimal value) {
        this.lowerbound = value;
    }

    /**
     * Gets the value of the territory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the territory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTERRITORY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTERRITORY() {
        if (territory == null) {
            territory = new ArrayList<String>();
        }
        return this.territory;
    }

    /**
     * Gets the value of the arearefs property.
     * 
     * @return
     *     possible object is
     *     {@link BCAREAREFS }
     *     
     */
    public BCAREAREFS getAREAREFS() {
        return arearefs;
    }

    /**
     * Sets the value of the arearefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCAREAREFS }
     *     
     */
    public void setAREAREFS(BCAREAREFS value) {
        this.arearefs = value;
    }

    /**
     * Gets the value of the pricebase property.
     * 
     * @return
     *     possible object is
     *     {@link BCPRICEBASE }
     *     
     */
    public BCPRICEBASE getPRICEBASE() {
        return pricebase;
    }

    /**
     * Sets the value of the pricebase property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCPRICEBASE }
     *     
     */
    public void setPRICEBASE(BCPRICEBASE value) {
        this.pricebase = value;
    }

    /**
     * Gets the value of the priceflag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the priceflag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPRICEFLAG().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCPRICEFLAG }
     * 
     * 
     */
    public List<BCPRICEFLAG> getPRICEFLAG() {
        if (priceflag == null) {
            priceflag = new ArrayList<BCPRICEFLAG>();
        }
        return this.priceflag;
    }

    /**
     * Gets the value of the priceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceType() {
        return priceType;
    }

    /**
     * Sets the value of the priceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceType(String value) {
        this.priceType = value;
    }

}
