/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2015 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CONFIG_STEP" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PREDEFINED_CONFIGS" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CONFIG_RULES" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CONFIG_FORMULAS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "configstep",
    "predefinedconfigs",
    "configrules",
    "configformulas"
})
@XmlRootElement(name = "PRODUCT_CONFIG_DETAILS")
public class BCPRODUCTCONFIGDETAILS {

    @XmlElement(name = "CONFIG_STEP", required = true)
    protected List<BCCONFIGSTEP> configstep;
    @XmlElement(name = "PREDEFINED_CONFIGS")
    protected BCPREDEFINEDCONFIGS predefinedconfigs;
    @XmlElement(name = "CONFIG_RULES")
    protected BCCONFIGRULES configrules;
    @XmlElement(name = "CONFIG_FORMULAS")
    protected BCCONFIGFORMULAS configformulas;

    /**
     * Gets the value of the configstep property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the configstep property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCONFIGSTEP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCCONFIGSTEP }
     * 
     * 
     */
    public List<BCCONFIGSTEP> getCONFIGSTEP() {
        if (configstep == null) {
            configstep = new ArrayList<BCCONFIGSTEP>();
        }
        return this.configstep;
    }

    /**
     * Gets the value of the predefinedconfigs property.
     * 
     * @return
     *     possible object is
     *     {@link BCPREDEFINEDCONFIGS }
     *     
     */
    public BCPREDEFINEDCONFIGS getPREDEFINEDCONFIGS() {
        return predefinedconfigs;
    }

    /**
     * Sets the value of the predefinedconfigs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCPREDEFINEDCONFIGS }
     *     
     */
    public void setPREDEFINEDCONFIGS(BCPREDEFINEDCONFIGS value) {
        this.predefinedconfigs = value;
    }

    /**
     * Gets the value of the configrules property.
     * 
     * @return
     *     possible object is
     *     {@link BCCONFIGRULES }
     *     
     */
    public BCCONFIGRULES getCONFIGRULES() {
        return configrules;
    }

    /**
     * Sets the value of the configrules property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCCONFIGRULES }
     *     
     */
    public void setCONFIGRULES(BCCONFIGRULES value) {
        this.configrules = value;
    }

    /**
     * Gets the value of the configformulas property.
     * 
     * @return
     *     possible object is
     *     {@link BCCONFIGFORMULAS }
     *     
     */
    public BCCONFIGFORMULAS getCONFIGFORMULAS() {
        return configformulas;
    }

    /**
     * Sets the value of the configformulas property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCCONFIGFORMULAS }
     *     
     */
    public void setCONFIGFORMULAS(BCCONFIGFORMULAS value) {
        this.configformulas = value;
    }

}
