/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2015 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}FORMULAS" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="PRODUCT" maxOccurs="unbounded">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                     &lt;sequence>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_PID"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_IDREF" minOccurs="0"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_DETAILS"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_FEATURES" maxOccurs="unbounded" minOccurs="0"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_ORDER_DETAILS"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_PRICE_DETAILS" maxOccurs="unbounded"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}MIME_INFO" minOccurs="0"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}USER_DEFINED_EXTENSIONS" minOccurs="0"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_REFERENCE" maxOccurs="unbounded" minOccurs="0"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_CONTACTS" minOccurs="0"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_IPP_DETAILS" minOccurs="0"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_LOGISTIC_DETAILS" minOccurs="0"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_CONFIG_DETAILS" minOccurs="0"/>
 *                     &lt;/sequence>
 *                     &lt;attribute name="mode" use="required">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.bmecat.org/bmecat/2005}dtSTRING">
 *                           &lt;minLength value="1"/>
 *                           &lt;maxLength value="20"/>
 *                           &lt;enumeration value="delete"/>
 *                           &lt;enumeration value="new"/>
 *                           &lt;enumeration value="update"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/attribute>
 *                   &lt;/restriction>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *             &lt;element name="PRODUCT_TO_CATALOGGROUP_MAP" maxOccurs="unbounded" minOccurs="0">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                     &lt;sequence>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}PROD_ID"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_IDREF" minOccurs="0"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}CATALOG_GROUP_ID"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_TO_CATALOGGROUP_MAP_ORDER" minOccurs="0"/>
 *                     &lt;/sequence>
 *                     &lt;attribute name="mode" use="required">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.bmecat.org/bmecat/2005}dtSTRING">
 *                           &lt;minLength value="1"/>
 *                           &lt;maxLength value="20"/>
 *                           &lt;enumeration value="delete"/>
 *                           &lt;enumeration value="new"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/attribute>
 *                   &lt;/restriction>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="ARTICLE" maxOccurs="unbounded">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                     &lt;sequence>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_AID"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_IDREF" minOccurs="0"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}ARTICLE_DETAILS"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}ARTICLE_FEATURES" maxOccurs="unbounded" minOccurs="0"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}ARTICLE_ORDER_DETAILS"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}ARTICLE_PRICE_DETAILS" maxOccurs="unbounded"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}MIME_INFO" minOccurs="0"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}USER_DEFINED_EXTENSIONS" minOccurs="0"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}ARTICLE_REFERENCE" maxOccurs="unbounded" minOccurs="0"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}ARTICLE_CONTACTS" minOccurs="0"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}ARTICLE_LOGISTIC_DETAILS" minOccurs="0"/>
 *                     &lt;/sequence>
 *                     &lt;attribute name="mode" use="required">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.bmecat.org/bmecat/2005}dtSTRING">
 *                           &lt;minLength value="1"/>
 *                           &lt;maxLength value="20"/>
 *                           &lt;enumeration value="delete"/>
 *                           &lt;enumeration value="new"/>
 *                           &lt;enumeration value="update"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/attribute>
 *                   &lt;/restriction>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *             &lt;element name="ARTICLE_TO_CATALOGGROUP_MAP" maxOccurs="unbounded" minOccurs="0">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                     &lt;sequence>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}ART_ID"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_IDREF" minOccurs="0"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}CATALOG_GROUP_ID"/>
 *                       &lt;element ref="{http://www.bmecat.org/bmecat/2005}ARTICLE_TO_CATALOGGROUP_MAP_ORDER" minOccurs="0"/>
 *                     &lt;/sequence>
 *                     &lt;attribute name="mode" use="required">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.bmecat.org/bmecat/2005}dtSTRING">
 *                           &lt;minLength value="1"/>
 *                           &lt;maxLength value="20"/>
 *                           &lt;enumeration value="delete"/>
 *                           &lt;enumeration value="new"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/attribute>
 *                   &lt;/restriction>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="prev_version" use="required" type="{http://www.bmecat.org/bmecat/2005}dtINTEGER" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "formulas",
    "product",
    "producttocataloggroupmap",
    "article",
    "articletocataloggroupmap"
})
@XmlRootElement(name = "T_UPDATE_PRODUCTS")
public class BCTUPDATEPRODUCTS {

    @XmlElement(name = "FORMULAS")
    protected BCFORMULAS formulas;
    @XmlElement(name = "PRODUCT")
    protected List<BCTUPDATEPRODUCTS.PRODUCT> product;
    @XmlElement(name = "PRODUCT_TO_CATALOGGROUP_MAP")
    protected List<BCTUPDATEPRODUCTS.PRODUCTTOCATALOGGROUPMAP> producttocataloggroupmap;
    @XmlElement(name = "ARTICLE")
    protected List<BCTUPDATEPRODUCTS.ARTICLE> article;
    @XmlElement(name = "ARTICLE_TO_CATALOGGROUP_MAP")
    protected List<BCTUPDATEPRODUCTS.ARTICLETOCATALOGGROUPMAP> articletocataloggroupmap;
    @XmlAttribute(name = "prev_version", required = true)
    protected BigInteger prevVersion;

    /**
     * Gets the value of the formulas property.
     * 
     * @return
     *     possible object is
     *     {@link BCFORMULAS }
     *     
     */
    public BCFORMULAS getFORMULAS() {
        return formulas;
    }

    /**
     * Sets the value of the formulas property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCFORMULAS }
     *     
     */
    public void setFORMULAS(BCFORMULAS value) {
        this.formulas = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the product property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPRODUCT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCTUPDATEPRODUCTS.PRODUCT }
     * 
     * 
     */
    public List<BCTUPDATEPRODUCTS.PRODUCT> getPRODUCT() {
        if (product == null) {
            product = new ArrayList<BCTUPDATEPRODUCTS.PRODUCT>();
        }
        return this.product;
    }

    /**
     * Gets the value of the producttocataloggroupmap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the producttocataloggroupmap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPRODUCTTOCATALOGGROUPMAP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCTUPDATEPRODUCTS.PRODUCTTOCATALOGGROUPMAP }
     * 
     * 
     */
    public List<BCTUPDATEPRODUCTS.PRODUCTTOCATALOGGROUPMAP> getPRODUCTTOCATALOGGROUPMAP() {
        if (producttocataloggroupmap == null) {
            producttocataloggroupmap = new ArrayList<BCTUPDATEPRODUCTS.PRODUCTTOCATALOGGROUPMAP>();
        }
        return this.producttocataloggroupmap;
    }

    /**
     * Gets the value of the article property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the article property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getARTICLE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCTUPDATEPRODUCTS.ARTICLE }
     * 
     * 
     */
    public List<BCTUPDATEPRODUCTS.ARTICLE> getARTICLE() {
        if (article == null) {
            article = new ArrayList<BCTUPDATEPRODUCTS.ARTICLE>();
        }
        return this.article;
    }

    /**
     * Gets the value of the articletocataloggroupmap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the articletocataloggroupmap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getARTICLETOCATALOGGROUPMAP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BCTUPDATEPRODUCTS.ARTICLETOCATALOGGROUPMAP }
     * 
     * 
     */
    public List<BCTUPDATEPRODUCTS.ARTICLETOCATALOGGROUPMAP> getARTICLETOCATALOGGROUPMAP() {
        if (articletocataloggroupmap == null) {
            articletocataloggroupmap = new ArrayList<BCTUPDATEPRODUCTS.ARTICLETOCATALOGGROUPMAP>();
        }
        return this.articletocataloggroupmap;
    }

    /**
     * Gets the value of the prevVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrevVersion() {
        return prevVersion;
    }

    /**
     * Sets the value of the prevVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrevVersion(BigInteger value) {
        this.prevVersion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_AID"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_IDREF" minOccurs="0"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ARTICLE_DETAILS"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ARTICLE_FEATURES" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ARTICLE_ORDER_DETAILS"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ARTICLE_PRICE_DETAILS" maxOccurs="unbounded"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}MIME_INFO" minOccurs="0"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}USER_DEFINED_EXTENSIONS" minOccurs="0"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ARTICLE_REFERENCE" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ARTICLE_CONTACTS" minOccurs="0"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ARTICLE_LOGISTIC_DETAILS" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="mode" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.bmecat.org/bmecat/2005}dtSTRING">
     *             &lt;minLength value="1"/>
     *             &lt;maxLength value="20"/>
     *             &lt;enumeration value="delete"/>
     *             &lt;enumeration value="new"/>
     *             &lt;enumeration value="update"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supplieraid",
        "supplieridref",
        "articledetails",
        "articlefeatures",
        "articleorderdetails",
        "articlepricedetails",
        "mimeinfo",
        "userdefinedextensions",
        "articlereference",
        "articlecontacts",
        "articlelogisticdetails"
    })
    public static class ARTICLE {

        @XmlElement(name = "SUPPLIER_AID", required = true)
        protected String supplieraid;
        @XmlElement(name = "SUPPLIER_IDREF")
        protected TypePARTYID supplieridref;
        @XmlElement(name = "ARTICLE_DETAILS", required = true)
        protected BCARTICLEDETAILS articledetails;
        @XmlElement(name = "ARTICLE_FEATURES")
        protected List<BCARTICLEFEATURES> articlefeatures;
        @XmlElement(name = "ARTICLE_ORDER_DETAILS", required = true)
        protected BCARTICLEORDERDETAILS articleorderdetails;
        @XmlElement(name = "ARTICLE_PRICE_DETAILS", required = true)
        protected List<BCARTICLEPRICEDETAILS> articlepricedetails;
        @XmlElement(name = "MIME_INFO")
        protected BCMIMEINFO mimeinfo;
        @XmlElement(name = "USER_DEFINED_EXTENSIONS")
        protected UdxPRODUCT userdefinedextensions;
        @XmlElement(name = "ARTICLE_REFERENCE")
        protected List<BCARTICLEREFERENCE> articlereference;
        @XmlElement(name = "ARTICLE_CONTACTS")
        protected TypeCONTACTREF articlecontacts;
        @XmlElement(name = "ARTICLE_LOGISTIC_DETAILS")
        protected BCARTICLELOGISTICDETAILS articlelogisticdetails;
        @XmlAttribute(required = true)
        protected String mode;

        /**
         * Gets the value of the supplieraid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSUPPLIERAID() {
            return supplieraid;
        }

        /**
         * Sets the value of the supplieraid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSUPPLIERAID(String value) {
            this.supplieraid = value;
        }

        /**
         * Gets the value of the supplieridref property.
         * 
         * @return
         *     possible object is
         *     {@link TypePARTYID }
         *     
         */
        public TypePARTYID getSUPPLIERIDREF() {
            return supplieridref;
        }

        /**
         * Sets the value of the supplieridref property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypePARTYID }
         *     
         */
        public void setSUPPLIERIDREF(TypePARTYID value) {
            this.supplieridref = value;
        }

        /**
         * Gets the value of the articledetails property.
         * 
         * @return
         *     possible object is
         *     {@link BCARTICLEDETAILS }
         *     
         */
        public BCARTICLEDETAILS getARTICLEDETAILS() {
            return articledetails;
        }

        /**
         * Sets the value of the articledetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link BCARTICLEDETAILS }
         *     
         */
        public void setARTICLEDETAILS(BCARTICLEDETAILS value) {
            this.articledetails = value;
        }

        /**
         * Gets the value of the articlefeatures property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the articlefeatures property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getARTICLEFEATURES().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BCARTICLEFEATURES }
         * 
         * 
         */
        public List<BCARTICLEFEATURES> getARTICLEFEATURES() {
            if (articlefeatures == null) {
                articlefeatures = new ArrayList<BCARTICLEFEATURES>();
            }
            return this.articlefeatures;
        }

        /**
         * Gets the value of the articleorderdetails property.
         * 
         * @return
         *     possible object is
         *     {@link BCARTICLEORDERDETAILS }
         *     
         */
        public BCARTICLEORDERDETAILS getARTICLEORDERDETAILS() {
            return articleorderdetails;
        }

        /**
         * Sets the value of the articleorderdetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link BCARTICLEORDERDETAILS }
         *     
         */
        public void setARTICLEORDERDETAILS(BCARTICLEORDERDETAILS value) {
            this.articleorderdetails = value;
        }

        /**
         * Gets the value of the articlepricedetails property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the articlepricedetails property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getARTICLEPRICEDETAILS().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BCARTICLEPRICEDETAILS }
         * 
         * 
         */
        public List<BCARTICLEPRICEDETAILS> getARTICLEPRICEDETAILS() {
            if (articlepricedetails == null) {
                articlepricedetails = new ArrayList<BCARTICLEPRICEDETAILS>();
            }
            return this.articlepricedetails;
        }

        /**
         * Gets the value of the mimeinfo property.
         * 
         * @return
         *     possible object is
         *     {@link BCMIMEINFO }
         *     
         */
        public BCMIMEINFO getMIMEINFO() {
            return mimeinfo;
        }

        /**
         * Sets the value of the mimeinfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link BCMIMEINFO }
         *     
         */
        public void setMIMEINFO(BCMIMEINFO value) {
            this.mimeinfo = value;
        }

        /**
         * Gets the value of the userdefinedextensions property.
         * 
         * @return
         *     possible object is
         *     {@link UdxPRODUCT }
         *     
         */
        public UdxPRODUCT getUSERDEFINEDEXTENSIONS() {
            return userdefinedextensions;
        }

        /**
         * Sets the value of the userdefinedextensions property.
         * 
         * @param value
         *     allowed object is
         *     {@link UdxPRODUCT }
         *     
         */
        public void setUSERDEFINEDEXTENSIONS(UdxPRODUCT value) {
            this.userdefinedextensions = value;
        }

        /**
         * Gets the value of the articlereference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the articlereference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getARTICLEREFERENCE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BCARTICLEREFERENCE }
         * 
         * 
         */
        public List<BCARTICLEREFERENCE> getARTICLEREFERENCE() {
            if (articlereference == null) {
                articlereference = new ArrayList<BCARTICLEREFERENCE>();
            }
            return this.articlereference;
        }

        /**
         * Gets the value of the articlecontacts property.
         * 
         * @return
         *     possible object is
         *     {@link TypeCONTACTREF }
         *     
         */
        public TypeCONTACTREF getARTICLECONTACTS() {
            return articlecontacts;
        }

        /**
         * Sets the value of the articlecontacts property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeCONTACTREF }
         *     
         */
        public void setARTICLECONTACTS(TypeCONTACTREF value) {
            this.articlecontacts = value;
        }

        /**
         * Gets the value of the articlelogisticdetails property.
         * 
         * @return
         *     possible object is
         *     {@link BCARTICLELOGISTICDETAILS }
         *     
         */
        public BCARTICLELOGISTICDETAILS getARTICLELOGISTICDETAILS() {
            return articlelogisticdetails;
        }

        /**
         * Sets the value of the articlelogisticdetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link BCARTICLELOGISTICDETAILS }
         *     
         */
        public void setARTICLELOGISTICDETAILS(BCARTICLELOGISTICDETAILS value) {
            this.articlelogisticdetails = value;
        }

        /**
         * Gets the value of the mode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMode(String value) {
            this.mode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ART_ID"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_IDREF" minOccurs="0"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CATALOG_GROUP_ID"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ARTICLE_TO_CATALOGGROUP_MAP_ORDER" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="mode" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.bmecat.org/bmecat/2005}dtSTRING">
     *             &lt;minLength value="1"/>
     *             &lt;maxLength value="20"/>
     *             &lt;enumeration value="delete"/>
     *             &lt;enumeration value="new"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "artid",
        "supplieridref",
        "cataloggroupid",
        "articletocataloggroupmaporder"
    })
    public static class ARTICLETOCATALOGGROUPMAP {

        @XmlElement(name = "ART_ID", required = true)
        protected String artid;
        @XmlElement(name = "SUPPLIER_IDREF")
        protected TypePARTYID supplieridref;
        @XmlElement(name = "CATALOG_GROUP_ID", required = true)
        protected String cataloggroupid;
        @XmlElement(name = "ARTICLE_TO_CATALOGGROUP_MAP_ORDER")
        protected BigInteger articletocataloggroupmaporder;
        @XmlAttribute(required = true)
        protected String mode;

        /**
         * Gets the value of the artid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getARTID() {
            return artid;
        }

        /**
         * Sets the value of the artid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setARTID(String value) {
            this.artid = value;
        }

        /**
         * Gets the value of the supplieridref property.
         * 
         * @return
         *     possible object is
         *     {@link TypePARTYID }
         *     
         */
        public TypePARTYID getSUPPLIERIDREF() {
            return supplieridref;
        }

        /**
         * Sets the value of the supplieridref property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypePARTYID }
         *     
         */
        public void setSUPPLIERIDREF(TypePARTYID value) {
            this.supplieridref = value;
        }

        /**
         * Gets the value of the cataloggroupid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCATALOGGROUPID() {
            return cataloggroupid;
        }

        /**
         * Sets the value of the cataloggroupid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCATALOGGROUPID(String value) {
            this.cataloggroupid = value;
        }

        /**
         * Gets the value of the articletocataloggroupmaporder property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getARTICLETOCATALOGGROUPMAPORDER() {
            return articletocataloggroupmaporder;
        }

        /**
         * Sets the value of the articletocataloggroupmaporder property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setARTICLETOCATALOGGROUPMAPORDER(BigInteger value) {
            this.articletocataloggroupmaporder = value;
        }

        /**
         * Gets the value of the mode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMode(String value) {
            this.mode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_PID"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_IDREF" minOccurs="0"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_DETAILS"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_FEATURES" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_ORDER_DETAILS"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_PRICE_DETAILS" maxOccurs="unbounded"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}MIME_INFO" minOccurs="0"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}USER_DEFINED_EXTENSIONS" minOccurs="0"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_REFERENCE" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_CONTACTS" minOccurs="0"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_IPP_DETAILS" minOccurs="0"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_LOGISTIC_DETAILS" minOccurs="0"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_CONFIG_DETAILS" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="mode" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.bmecat.org/bmecat/2005}dtSTRING">
     *             &lt;minLength value="1"/>
     *             &lt;maxLength value="20"/>
     *             &lt;enumeration value="delete"/>
     *             &lt;enumeration value="new"/>
     *             &lt;enumeration value="update"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supplierpid",
        "supplieridref",
        "productdetails",
        "productfeatures",
        "productorderdetails",
        "productpricedetails",
        "mimeinfo",
        "userdefinedextensions",
        "productreference",
        "productcontacts",
        "productippdetails",
        "productlogisticdetails",
        "productconfigdetails"
    })
    public static class PRODUCT {

        @XmlElement(name = "SUPPLIER_PID", required = true)
        protected BCSUPPLIERPID supplierpid;
        @XmlElement(name = "SUPPLIER_IDREF")
        protected TypePARTYID supplieridref;
        @XmlElement(name = "PRODUCT_DETAILS", required = true)
        protected BCPRODUCTDETAILS productdetails;
        @XmlElement(name = "PRODUCT_FEATURES")
        protected List<BCPRODUCTFEATURES> productfeatures;
        @XmlElement(name = "PRODUCT_ORDER_DETAILS", required = true)
        protected BCPRODUCTORDERDETAILS productorderdetails;
        @XmlElement(name = "PRODUCT_PRICE_DETAILS", required = true)
        protected List<BCPRODUCTPRICEDETAILS> productpricedetails;
        @XmlElement(name = "MIME_INFO")
        protected BCMIMEINFO mimeinfo;
        @XmlElement(name = "USER_DEFINED_EXTENSIONS")
        protected UdxPRODUCT userdefinedextensions;
        @XmlElement(name = "PRODUCT_REFERENCE")
        protected List<BCPRODUCTREFERENCE> productreference;
        @XmlElement(name = "PRODUCT_CONTACTS")
        protected TypeCONTACTREF productcontacts;
        @XmlElement(name = "PRODUCT_IPP_DETAILS")
        protected BCPRODUCTIPPDETAILS productippdetails;
        @XmlElement(name = "PRODUCT_LOGISTIC_DETAILS")
        protected BCPRODUCTLOGISTICDETAILS productlogisticdetails;
        @XmlElement(name = "PRODUCT_CONFIG_DETAILS")
        protected BCPRODUCTCONFIGDETAILS productconfigdetails;
        @XmlAttribute(required = true)
        protected String mode;

        /**
         * Gets the value of the supplierpid property.
         * 
         * @return
         *     possible object is
         *     {@link BCSUPPLIERPID }
         *     
         */
        public BCSUPPLIERPID getSUPPLIERPID() {
            return supplierpid;
        }

        /**
         * Sets the value of the supplierpid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BCSUPPLIERPID }
         *     
         */
        public void setSUPPLIERPID(BCSUPPLIERPID value) {
            this.supplierpid = value;
        }

        /**
         * Gets the value of the supplieridref property.
         * 
         * @return
         *     possible object is
         *     {@link TypePARTYID }
         *     
         */
        public TypePARTYID getSUPPLIERIDREF() {
            return supplieridref;
        }

        /**
         * Sets the value of the supplieridref property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypePARTYID }
         *     
         */
        public void setSUPPLIERIDREF(TypePARTYID value) {
            this.supplieridref = value;
        }

        /**
         * Gets the value of the productdetails property.
         * 
         * @return
         *     possible object is
         *     {@link BCPRODUCTDETAILS }
         *     
         */
        public BCPRODUCTDETAILS getPRODUCTDETAILS() {
            return productdetails;
        }

        /**
         * Sets the value of the productdetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link BCPRODUCTDETAILS }
         *     
         */
        public void setPRODUCTDETAILS(BCPRODUCTDETAILS value) {
            this.productdetails = value;
        }

        /**
         * Gets the value of the productfeatures property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the productfeatures property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPRODUCTFEATURES().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BCPRODUCTFEATURES }
         * 
         * 
         */
        public List<BCPRODUCTFEATURES> getPRODUCTFEATURES() {
            if (productfeatures == null) {
                productfeatures = new ArrayList<BCPRODUCTFEATURES>();
            }
            return this.productfeatures;
        }

        /**
         * Gets the value of the productorderdetails property.
         * 
         * @return
         *     possible object is
         *     {@link BCPRODUCTORDERDETAILS }
         *     
         */
        public BCPRODUCTORDERDETAILS getPRODUCTORDERDETAILS() {
            return productorderdetails;
        }

        /**
         * Sets the value of the productorderdetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link BCPRODUCTORDERDETAILS }
         *     
         */
        public void setPRODUCTORDERDETAILS(BCPRODUCTORDERDETAILS value) {
            this.productorderdetails = value;
        }

        /**
         * Gets the value of the productpricedetails property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the productpricedetails property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPRODUCTPRICEDETAILS().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BCPRODUCTPRICEDETAILS }
         * 
         * 
         */
        public List<BCPRODUCTPRICEDETAILS> getPRODUCTPRICEDETAILS() {
            if (productpricedetails == null) {
                productpricedetails = new ArrayList<BCPRODUCTPRICEDETAILS>();
            }
            return this.productpricedetails;
        }

        /**
         * Gets the value of the mimeinfo property.
         * 
         * @return
         *     possible object is
         *     {@link BCMIMEINFO }
         *     
         */
        public BCMIMEINFO getMIMEINFO() {
            return mimeinfo;
        }

        /**
         * Sets the value of the mimeinfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link BCMIMEINFO }
         *     
         */
        public void setMIMEINFO(BCMIMEINFO value) {
            this.mimeinfo = value;
        }

        /**
         * Gets the value of the userdefinedextensions property.
         * 
         * @return
         *     possible object is
         *     {@link UdxPRODUCT }
         *     
         */
        public UdxPRODUCT getUSERDEFINEDEXTENSIONS() {
            return userdefinedextensions;
        }

        /**
         * Sets the value of the userdefinedextensions property.
         * 
         * @param value
         *     allowed object is
         *     {@link UdxPRODUCT }
         *     
         */
        public void setUSERDEFINEDEXTENSIONS(UdxPRODUCT value) {
            this.userdefinedextensions = value;
        }

        /**
         * Gets the value of the productreference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the productreference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPRODUCTREFERENCE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BCPRODUCTREFERENCE }
         * 
         * 
         */
        public List<BCPRODUCTREFERENCE> getPRODUCTREFERENCE() {
            if (productreference == null) {
                productreference = new ArrayList<BCPRODUCTREFERENCE>();
            }
            return this.productreference;
        }

        /**
         * Gets the value of the productcontacts property.
         * 
         * @return
         *     possible object is
         *     {@link TypeCONTACTREF }
         *     
         */
        public TypeCONTACTREF getPRODUCTCONTACTS() {
            return productcontacts;
        }

        /**
         * Sets the value of the productcontacts property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeCONTACTREF }
         *     
         */
        public void setPRODUCTCONTACTS(TypeCONTACTREF value) {
            this.productcontacts = value;
        }

        /**
         * Gets the value of the productippdetails property.
         * 
         * @return
         *     possible object is
         *     {@link BCPRODUCTIPPDETAILS }
         *     
         */
        public BCPRODUCTIPPDETAILS getPRODUCTIPPDETAILS() {
            return productippdetails;
        }

        /**
         * Sets the value of the productippdetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link BCPRODUCTIPPDETAILS }
         *     
         */
        public void setPRODUCTIPPDETAILS(BCPRODUCTIPPDETAILS value) {
            this.productippdetails = value;
        }

        /**
         * Gets the value of the productlogisticdetails property.
         * 
         * @return
         *     possible object is
         *     {@link BCPRODUCTLOGISTICDETAILS }
         *     
         */
        public BCPRODUCTLOGISTICDETAILS getPRODUCTLOGISTICDETAILS() {
            return productlogisticdetails;
        }

        /**
         * Sets the value of the productlogisticdetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link BCPRODUCTLOGISTICDETAILS }
         *     
         */
        public void setPRODUCTLOGISTICDETAILS(BCPRODUCTLOGISTICDETAILS value) {
            this.productlogisticdetails = value;
        }

        /**
         * Gets the value of the productconfigdetails property.
         * 
         * @return
         *     possible object is
         *     {@link BCPRODUCTCONFIGDETAILS }
         *     
         */
        public BCPRODUCTCONFIGDETAILS getPRODUCTCONFIGDETAILS() {
            return productconfigdetails;
        }

        /**
         * Sets the value of the productconfigdetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link BCPRODUCTCONFIGDETAILS }
         *     
         */
        public void setPRODUCTCONFIGDETAILS(BCPRODUCTCONFIGDETAILS value) {
            this.productconfigdetails = value;
        }

        /**
         * Gets the value of the mode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMode(String value) {
            this.mode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PROD_ID"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_IDREF" minOccurs="0"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CATALOG_GROUP_ID"/>
     *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_TO_CATALOGGROUP_MAP_ORDER" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="mode" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.bmecat.org/bmecat/2005}dtSTRING">
     *             &lt;minLength value="1"/>
     *             &lt;maxLength value="20"/>
     *             &lt;enumeration value="delete"/>
     *             &lt;enumeration value="new"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "prodid",
        "supplieridref",
        "cataloggroupid",
        "producttocataloggroupmaporder"
    })
    public static class PRODUCTTOCATALOGGROUPMAP {

        @XmlElement(name = "PROD_ID", required = true)
        protected String prodid;
        @XmlElement(name = "SUPPLIER_IDREF")
        protected TypePARTYID supplieridref;
        @XmlElement(name = "CATALOG_GROUP_ID", required = true)
        protected String cataloggroupid;
        @XmlElement(name = "PRODUCT_TO_CATALOGGROUP_MAP_ORDER")
        protected BigInteger producttocataloggroupmaporder;
        @XmlAttribute(required = true)
        protected String mode;

        /**
         * Gets the value of the prodid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPRODID() {
            return prodid;
        }

        /**
         * Sets the value of the prodid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPRODID(String value) {
            this.prodid = value;
        }

        /**
         * Gets the value of the supplieridref property.
         * 
         * @return
         *     possible object is
         *     {@link TypePARTYID }
         *     
         */
        public TypePARTYID getSUPPLIERIDREF() {
            return supplieridref;
        }

        /**
         * Sets the value of the supplieridref property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypePARTYID }
         *     
         */
        public void setSUPPLIERIDREF(TypePARTYID value) {
            this.supplieridref = value;
        }

        /**
         * Gets the value of the cataloggroupid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCATALOGGROUPID() {
            return cataloggroupid;
        }

        /**
         * Sets the value of the cataloggroupid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCATALOGGROUPID(String value) {
            this.cataloggroupid = value;
        }

        /**
         * Gets the value of the producttocataloggroupmaporder property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPRODUCTTOCATALOGGROUPMAPORDER() {
            return producttocataloggroupmaporder;
        }

        /**
         * Sets the value of the producttocataloggroupmaporder property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPRODUCTTOCATALOGGROUPMAPORDER(BigInteger value) {
            this.producttocataloggroupmaporder = value;
        }

        /**
         * Gets the value of the mode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMode(String value) {
            this.mode = value;
        }

    }

}
