/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 04:44:14 PM MEZ 
//


package com.lp.server.schema.bmecat_2005;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}STARTVALUE"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ENDVALUE"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}INTERVALVALUE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startvalue",
    "endvalue",
    "intervalvalue"
})
@XmlRootElement(name = "VALUE_RANGE")
public class BCVALUERANGE {

    @XmlElement(name = "STARTVALUE", required = true)
    protected BCSTARTVALUE startvalue;
    @XmlElement(name = "ENDVALUE", required = true)
    protected BCENDVALUE endvalue;
    @XmlElement(name = "INTERVALVALUE")
    protected BigDecimal intervalvalue;

    /**
     * Gets the value of the startvalue property.
     * 
     * @return
     *     possible object is
     *     {@link BCSTARTVALUE }
     *     
     */
    public BCSTARTVALUE getSTARTVALUE() {
        return startvalue;
    }

    /**
     * Sets the value of the startvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCSTARTVALUE }
     *     
     */
    public void setSTARTVALUE(BCSTARTVALUE value) {
        this.startvalue = value;
    }

    /**
     * Gets the value of the endvalue property.
     * 
     * @return
     *     possible object is
     *     {@link BCENDVALUE }
     *     
     */
    public BCENDVALUE getENDVALUE() {
        return endvalue;
    }

    /**
     * Sets the value of the endvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCENDVALUE }
     *     
     */
    public void setENDVALUE(BCENDVALUE value) {
        this.endvalue = value;
    }

    /**
     * Gets the value of the intervalvalue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getINTERVALVALUE() {
        return intervalvalue;
    }

    /**
     * Sets the value of the intervalvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setINTERVALVALUE(BigDecimal value) {
        this.intervalvalue = value;
    }

}
