//
// Diese Datei wurde mit der JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 generiert 
// Siehe <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Aendrungen an dieser Datei gehen bei einer Neukompilierung des Quellschemas verloren. 
// Generiert: 2015.11.02 um 01:30:28 PM CET 
//


package com.lp.server.schema.vendidata.discounts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.lp.server.schema.vendidata.commonobjects.XMLCustomer;


/**
 * Single payments generated by a discount model directly assigned to a customer
 * 
 * <p>Java-Klasse fuer CustomerSettledPaymentInfo complex type.
 * 
 * <p>Das folgende Schemafragment gibt den erwarteten Content an, der in dieser Klasse enthalten ist.
 * 
 * <pre>
 * &lt;complexType name="CustomerSettledPaymentInfo">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.vendidata.com/XML/Schema/Discounts}SettledPaymentInfo">
 *       &lt;sequence>
 *         &lt;element name="OriginatingCustomer" type="{http://www.vendidata.com/XML/Schema/CommonObjects}Customer"/>
 *         &lt;element name="OriginatingCustomerInfoText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerSettledPaymentInfo", propOrder = {
    "originatingCustomer",
    "originatingCustomerInfoText"
})
public class XMLCustomerSettledPaymentInfo
    extends XMLSettledPaymentInfo
{

    @XmlElement(name = "OriginatingCustomer", required = true)
    protected XMLCustomer originatingCustomer;
    @XmlElement(name = "OriginatingCustomerInfoText", required = true)
    protected String originatingCustomerInfoText;

    /**
     * Ruft den Wert der originatingCustomer-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link XMLCustomer }
     *     
     */
    public XMLCustomer getOriginatingCustomer() {
        return originatingCustomer;
    }

    /**
     * Legt den Wert der originatingCustomer-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLCustomer }
     *     
     */
    public void setOriginatingCustomer(XMLCustomer value) {
        this.originatingCustomer = value;
    }

    /**
     * Ruft den Wert der originatingCustomerInfoText-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatingCustomerInfoText() {
        return originatingCustomerInfoText;
    }

    /**
     * Legt den Wert der originatingCustomerInfoText-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatingCustomerInfoText(String value) {
        this.originatingCustomerInfoText = value;
    }

}
