//
// Diese Datei wurde mit der JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 generiert 
// Siehe <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Aendrungen an dieser Datei gehen bei einer Neukompilierung des Quellschemas verloren. 
// Generiert: 2015.11.02 um 01:30:28 PM CET 
//


package com.lp.server.schema.vendidata.discounts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Variable payment generated by a payout formula
 * 
 * <p>Java-Klasse fuer FormulaPaymentInfo complex type.
 * 
 * <p>Das folgende Schemafragment gibt den erwarteten Content an, der in dieser Klasse enthalten ist.
 * 
 * <pre>
 * &lt;complexType name="FormulaPaymentInfo">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.vendidata.com/XML/Schema/Discounts}PaymentInfo">
 *       &lt;sequence>
 *         &lt;element name="PaymentStatus" type="{http://www.vendidata.com/XML/Schema/Discounts}PaymentStatusType"/>
 *         &lt;element name="PeriodType" type="{http://www.vendidata.com/XML/Schema/Discounts}PeriodicType"/>
 *         &lt;element name="PaymentPeriod" type="{http://www.vendidata.com/XML/Schema/Discounts}FormulaPaymentPeriod"/>
 *         &lt;element name="DiscountFormulaDetails" type="{http://www.vendidata.com/XML/Schema/Discounts}DiscountFormulaDetails"/>
 *         &lt;element name="PaymentRemark" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="isForPrematurePayment" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormulaPaymentInfo", propOrder = {
    "paymentStatus",
    "periodType",
    "paymentPeriod",
    "discountFormulaDetails",
    "paymentRemark"
})
public class XMLFormulaPaymentInfo
    extends XMLPaymentInfo
{

    @XmlElement(name = "PaymentStatus", required = true)
    @XmlSchemaType(name = "string")
    protected XMLPaymentStatusType paymentStatus;
    @XmlElement(name = "PeriodType", required = true)
    @XmlSchemaType(name = "string")
    protected XMLPeriodicType periodType;
    @XmlElement(name = "PaymentPeriod", required = true)
    protected XMLFormulaPaymentPeriod paymentPeriod;
    @XmlElement(name = "DiscountFormulaDetails", required = true)
    protected XMLDiscountFormulaDetails discountFormulaDetails;
    @XmlElement(name = "PaymentRemark")
    protected String paymentRemark;
    @XmlAttribute(name = "isForPrematurePayment", required = true)
    protected boolean isForPrematurePayment;

    /**
     * Ruft den Wert der paymentStatus-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link XMLPaymentStatusType }
     *     
     */
    public XMLPaymentStatusType getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * Legt den Wert der paymentStatus-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLPaymentStatusType }
     *     
     */
    public void setPaymentStatus(XMLPaymentStatusType value) {
        this.paymentStatus = value;
    }

    /**
     * Ruft den Wert der periodType-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link XMLPeriodicType }
     *     
     */
    public XMLPeriodicType getPeriodType() {
        return periodType;
    }

    /**
     * Legt den Wert der periodType-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLPeriodicType }
     *     
     */
    public void setPeriodType(XMLPeriodicType value) {
        this.periodType = value;
    }

    /**
     * Ruft den Wert der paymentPeriod-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link XMLFormulaPaymentPeriod }
     *     
     */
    public XMLFormulaPaymentPeriod getPaymentPeriod() {
        return paymentPeriod;
    }

    /**
     * Legt den Wert der paymentPeriod-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLFormulaPaymentPeriod }
     *     
     */
    public void setPaymentPeriod(XMLFormulaPaymentPeriod value) {
        this.paymentPeriod = value;
    }

    /**
     * Ruft den Wert der discountFormulaDetails-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link XMLDiscountFormulaDetails }
     *     
     */
    public XMLDiscountFormulaDetails getDiscountFormulaDetails() {
        return discountFormulaDetails;
    }

    /**
     * Legt den Wert der discountFormulaDetails-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLDiscountFormulaDetails }
     *     
     */
    public void setDiscountFormulaDetails(XMLDiscountFormulaDetails value) {
        this.discountFormulaDetails = value;
    }

    /**
     * Ruft den Wert der paymentRemark-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentRemark() {
        return paymentRemark;
    }

    /**
     * Legt den Wert der paymentRemark-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentRemark(String value) {
        this.paymentRemark = value;
    }

    /**
     * Ruft den Wert der isForPrematurePayment-Eigenschaft ab.
     * 
     */
    public boolean isIsForPrematurePayment() {
        return isForPrematurePayment;
    }

    /**
     * Legt den Wert der isForPrematurePayment-Eigenschaft fest.
     * 
     */
    public void setIsForPrematurePayment(boolean value) {
        this.isForPrematurePayment = value;
    }

}
