//
// Diese Datei wurde mit der JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 generiert 
// Siehe <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Aendrungen an dieser Datei gehen bei einer Neukompilierung des Quellschemas verloren. 
// Generiert: 2015.11.02 um 01:30:28 PM CET 
//


package com.lp.server.schema.vendidata.discounts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Payment generated by a discount model having single (one-time) or flat-charge payments with a pre-determined (settled) amount
 * 
 * <p>Java-Klasse fuer SettledPaymentInfo complex type.
 * 
 * <p>Das folgende Schemafragment gibt den erwarteten Content an, der in dieser Klasse enthalten ist.
 * 
 * <pre>
 * &lt;complexType name="SettledPaymentInfo">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.vendidata.com/XML/Schema/Discounts}PaymentInfo">
 *       &lt;sequence>
 *         &lt;element name="TotalFlatchargePayments" type="{http://www.vendidata.com/XML/Schema/Discounts}AliquotAmount"/>
 *         &lt;element name="TotalSinglePayments" type="{http://www.vendidata.com/XML/Schema/Discounts}Amount"/>
 *         &lt;element name="PaymentStatus" type="{http://www.vendidata.com/XML/Schema/Discounts}PaymentStatusType"/>
 *         &lt;element name="PeriodType" type="{http://www.vendidata.com/XML/Schema/Discounts}PeriodicType" minOccurs="0"/>
 *         &lt;element name="PaymentPeriod" type="{http://www.vendidata.com/XML/Schema/Discounts}PaymentPeriod" minOccurs="0"/>
 *         &lt;element name="PaymentRemark" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="isPaymentInAdvance" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="paymentType" use="required" type="{http://www.vendidata.com/XML/Schema/Discounts}SettledPaymentType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SettledPaymentInfo", propOrder = {
    "totalFlatchargePayments",
    "totalSinglePayments",
    "paymentStatus",
    "periodType",
    "paymentPeriod",
    "paymentRemark"
})
@XmlSeeAlso({
    XMLCustomerSettledPaymentInfo.class
})
public class XMLSettledPaymentInfo
    extends XMLPaymentInfo
{

    @XmlElement(name = "TotalFlatchargePayments", required = true)
    protected XMLAliquotAmount totalFlatchargePayments;
    @XmlElement(name = "TotalSinglePayments", required = true)
    protected XMLAmount totalSinglePayments;
    @XmlElement(name = "PaymentStatus", required = true)
    @XmlSchemaType(name = "string")
    protected XMLPaymentStatusType paymentStatus;
    @XmlElement(name = "PeriodType")
    @XmlSchemaType(name = "string")
    protected XMLPeriodicType periodType;
    @XmlElement(name = "PaymentPeriod")
    protected XMLPaymentPeriod paymentPeriod;
    @XmlElement(name = "PaymentRemark")
    protected String paymentRemark;
    @XmlAttribute(name = "isPaymentInAdvance", required = true)
    protected boolean isPaymentInAdvance;
    @XmlAttribute(name = "paymentType", required = true)
    protected XMLSettledPaymentType paymentType;

    /**
     * Ruft den Wert der totalFlatchargePayments-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link XMLAliquotAmount }
     *     
     */
    public XMLAliquotAmount getTotalFlatchargePayments() {
        return totalFlatchargePayments;
    }

    /**
     * Legt den Wert der totalFlatchargePayments-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLAliquotAmount }
     *     
     */
    public void setTotalFlatchargePayments(XMLAliquotAmount value) {
        this.totalFlatchargePayments = value;
    }

    /**
     * Ruft den Wert der totalSinglePayments-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link XMLAmount }
     *     
     */
    public XMLAmount getTotalSinglePayments() {
        return totalSinglePayments;
    }

    /**
     * Legt den Wert der totalSinglePayments-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLAmount }
     *     
     */
    public void setTotalSinglePayments(XMLAmount value) {
        this.totalSinglePayments = value;
    }

    /**
     * Ruft den Wert der paymentStatus-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link XMLPaymentStatusType }
     *     
     */
    public XMLPaymentStatusType getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * Legt den Wert der paymentStatus-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLPaymentStatusType }
     *     
     */
    public void setPaymentStatus(XMLPaymentStatusType value) {
        this.paymentStatus = value;
    }

    /**
     * Ruft den Wert der periodType-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link XMLPeriodicType }
     *     
     */
    public XMLPeriodicType getPeriodType() {
        return periodType;
    }

    /**
     * Legt den Wert der periodType-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLPeriodicType }
     *     
     */
    public void setPeriodType(XMLPeriodicType value) {
        this.periodType = value;
    }

    /**
     * Ruft den Wert der paymentPeriod-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link XMLPaymentPeriod }
     *     
     */
    public XMLPaymentPeriod getPaymentPeriod() {
        return paymentPeriod;
    }

    /**
     * Legt den Wert der paymentPeriod-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLPaymentPeriod }
     *     
     */
    public void setPaymentPeriod(XMLPaymentPeriod value) {
        this.paymentPeriod = value;
    }

    /**
     * Ruft den Wert der isPaymentInAdvance-Eigenschaft ab.
     * 
     */
    public boolean isIsPaymentInAdvance() {
        return isPaymentInAdvance;
    }

    /**
     * Ruft den Wert der paymentRemark-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentRemark() {
        return paymentRemark;
    }

    /**
     * Legt den Wert der paymentRemark-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentRemark(String value) {
        this.paymentRemark = value;
    }

    /**
     * Legt den Wert der isPaymentInAdvance-Eigenschaft fest.
     * 
     */
    public void setIsPaymentInAdvance(boolean value) {
        this.isPaymentInAdvance = value;
    }

    /**
     * Ruft den Wert der paymentType-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link XMLSettledPaymentType }
     *     
     */
    public XMLSettledPaymentType getPaymentType() {
        return paymentType;
    }

    /**
     * Legt den Wert der paymentType-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSettledPaymentType }
     *     
     */
    public void setPaymentType(XMLSettledPaymentType value) {
        this.paymentType = value;
    }

}
