//
// Diese Datei wurde mit der JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 generiert 
// Siehe <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Aendrungen an dieser Datei gehen bei einer Neukompilierung des Quellschemas verloren. 
// Generiert: 2015.11.02 um 01:30:28 PM CET 
//


package com.lp.server.schema.vendidata.discounts;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.lp.server.schema.vendidata.commonobjects.XMLCustomer;
import com.lp.server.schema.vendidata.commonobjects.XMLVirtualVendingmachine;


/**
 * Payments generated by a payment model attributed to a virtual vendingmachine
 * 
 * <p>Java-Klasse fuer VirtualVendingmachinePaymentInfo complex type.
 * 
 * <p>Das folgende Schemafragment gibt den erwarteten Content an, der in dieser Klasse enthalten ist.
 * 
 * <pre>
 * &lt;complexType name="VirtualVendingmachinePaymentInfo">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.vendidata.com/XML/Schema/Discounts}CombinedPaymentInfo">
 *       &lt;sequence>
 *         &lt;element name="VirtualVendingmachine" type="{http://www.vendidata.com/XML/Schema/CommonObjects}VirtualVendingmachine"/>
 *         &lt;element name="VirtualVendingmachineInfoText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OriginatingCustomer" type="{http://www.vendidata.com/XML/Schema/CommonObjects}Customer"/>
 *         &lt;element name="OriginatingCustomerInfoText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SettledPaymentInfo" type="{http://www.vendidata.com/XML/Schema/Discounts}SettledPaymentInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FormulaPaymentInfo" type="{http://www.vendidata.com/XML/Schema/Discounts}FormulaPaymentInfo" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VirtualVendingmachinePaymentInfo", propOrder = {
    "virtualVendingmachine",
    "virtualVendingmachineInfoText",
    "originatingCustomer",
    "originatingCustomerInfoText",
    "settledPaymentInfo",
    "formulaPaymentInfo"
})
public class XMLVirtualVendingmachinePaymentInfo
    extends XMLCombinedPaymentInfo
{

    @XmlElement(name = "VirtualVendingmachine", required = true)
    protected XMLVirtualVendingmachine virtualVendingmachine;
    @XmlElement(name = "VirtualVendingmachineInfoText", required = true)
    protected String virtualVendingmachineInfoText;
    @XmlElement(name = "OriginatingCustomer", required = true)
    protected XMLCustomer originatingCustomer;
    @XmlElement(name = "OriginatingCustomerInfoText", required = true)
    protected String originatingCustomerInfoText;
    @XmlElement(name = "SettledPaymentInfo")
    protected List<XMLSettledPaymentInfo> settledPaymentInfo;
    @XmlElement(name = "FormulaPaymentInfo")
    protected List<XMLFormulaPaymentInfo> formulaPaymentInfo;

    /**
     * Ruft den Wert der virtualVendingmachine-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link XMLVirtualVendingmachine }
     *     
     */
    public XMLVirtualVendingmachine getVirtualVendingmachine() {
        return virtualVendingmachine;
    }

    /**
     * Legt den Wert der virtualVendingmachine-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLVirtualVendingmachine }
     *     
     */
    public void setVirtualVendingmachine(XMLVirtualVendingmachine value) {
        this.virtualVendingmachine = value;
    }

    /**
     * Ruft den Wert der virtualVendingmachineInfoText-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVirtualVendingmachineInfoText() {
        return virtualVendingmachineInfoText;
    }

    /**
     * Legt den Wert der virtualVendingmachineInfoText-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVirtualVendingmachineInfoText(String value) {
        this.virtualVendingmachineInfoText = value;
    }

    /**
     * Ruft den Wert der originatingCustomer-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link XMLCustomer }
     *     
     */
    public XMLCustomer getOriginatingCustomer() {
        return originatingCustomer;
    }

    /**
     * Legt den Wert der originatingCustomer-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLCustomer }
     *     
     */
    public void setOriginatingCustomer(XMLCustomer value) {
        this.originatingCustomer = value;
    }

    /**
     * Ruft den Wert der originatingCustomerInfoText-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatingCustomerInfoText() {
        return originatingCustomerInfoText;
    }

    /**
     * Legt den Wert der originatingCustomerInfoText-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatingCustomerInfoText(String value) {
        this.originatingCustomerInfoText = value;
    }

    /**
     * Gets the value of the settledPaymentInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the settledPaymentInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSettledPaymentInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLSettledPaymentInfo }
     * 
     * 
     */
    public List<XMLSettledPaymentInfo> getSettledPaymentInfo() {
        if (settledPaymentInfo == null) {
            settledPaymentInfo = new ArrayList<XMLSettledPaymentInfo>();
        }
        return this.settledPaymentInfo;
    }

    /**
     * Gets the value of the formulaPaymentInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formulaPaymentInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormulaPaymentInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLFormulaPaymentInfo }
     * 
     * 
     */
    public List<XMLFormulaPaymentInfo> getFormulaPaymentInfo() {
        if (formulaPaymentInfo == null) {
            formulaPaymentInfo = new ArrayList<XMLFormulaPaymentInfo>();
        }
        return this.formulaPaymentInfo;
    }

}
