/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.03 at 10:12:07 AM MEZ 
//


package com.lp.server.schema.opentrans.cc.orderresponse;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for _XML_XML_ORDER_ITEM_VARCOND complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_XML_XML_ORDER_ITEM_VARCOND">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}LINE_ITEM_ID" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_VARCOND_VAL" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_VARCOND_NET_PRICE" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_VARCOND_CUR" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_VARCOND_QTY" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_VARCOND_UNIT" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_VARCOND_TOTAL_PRICE" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.opentrans.org/XMLSchema/1.0}ComIbmMrmNamespaceInfo154"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_XML_XML_ORDER_ITEM_VARCOND", propOrder = {
    "lineitemid",
    "ccvarcondval",
    "ccvarcondnetprice",
    "ccvarcondcur",
    "ccvarcondqty",
    "ccvarcondunit",
    "ccvarcondtotalprice"
})
public class XMLXMLORDERITEMVARCOND {

    @XmlElement(name = "LINE_ITEM_ID")
    protected String lineitemid;
    @XmlElement(name = "CC_VARCOND_VAL")
    protected String ccvarcondval;
    @XmlElement(name = "CC_VARCOND_NET_PRICE")
    protected BigDecimal ccvarcondnetprice;
    @XmlElement(name = "CC_VARCOND_CUR")
    protected String ccvarcondcur;
    @XmlElement(name = "CC_VARCOND_QTY")
    protected BigDecimal ccvarcondqty;
    @XmlElement(name = "CC_VARCOND_UNIT")
    protected String ccvarcondunit;
    @XmlElement(name = "CC_VARCOND_TOTAL_PRICE")
    protected BigDecimal ccvarcondtotalprice;
    @XmlAttribute(name = "xsi_schemaLocation")
    protected String xsiSchemaLocation;
    @XmlAttribute(name = "xmlns_xsd")
    protected String xmlnsXsd;

    /**
     * Gets the value of the lineitemid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLINEITEMID() {
        return lineitemid;
    }

    /**
     * Sets the value of the lineitemid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLINEITEMID(String value) {
        this.lineitemid = value;
    }

    /**
     * Gets the value of the ccvarcondval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCVARCONDVAL() {
        return ccvarcondval;
    }

    /**
     * Sets the value of the ccvarcondval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCVARCONDVAL(String value) {
        this.ccvarcondval = value;
    }

    /**
     * Gets the value of the ccvarcondnetprice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCCVARCONDNETPRICE() {
        return ccvarcondnetprice;
    }

    /**
     * Sets the value of the ccvarcondnetprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCCVARCONDNETPRICE(BigDecimal value) {
        this.ccvarcondnetprice = value;
    }

    /**
     * Gets the value of the ccvarcondcur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCVARCONDCUR() {
        return ccvarcondcur;
    }

    /**
     * Sets the value of the ccvarcondcur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCVARCONDCUR(String value) {
        this.ccvarcondcur = value;
    }

    /**
     * Gets the value of the ccvarcondqty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCCVARCONDQTY() {
        return ccvarcondqty;
    }

    /**
     * Sets the value of the ccvarcondqty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCCVARCONDQTY(BigDecimal value) {
        this.ccvarcondqty = value;
    }

    /**
     * Gets the value of the ccvarcondunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCVARCONDUNIT() {
        return ccvarcondunit;
    }

    /**
     * Sets the value of the ccvarcondunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCVARCONDUNIT(String value) {
        this.ccvarcondunit = value;
    }

    /**
     * Gets the value of the ccvarcondtotalprice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCCVARCONDTOTALPRICE() {
        return ccvarcondtotalprice;
    }

    /**
     * Sets the value of the ccvarcondtotalprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCCVARCONDTOTALPRICE(BigDecimal value) {
        this.ccvarcondtotalprice = value;
    }

    /**
     * Gets the value of the xsiSchemaLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsiSchemaLocation() {
        if (xsiSchemaLocation == null) {
            return "openbase_1_0.mxsd";
        } else {
            return xsiSchemaLocation;
        }
    }

    /**
     * Sets the value of the xsiSchemaLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsiSchemaLocation(String value) {
        this.xsiSchemaLocation = value;
    }

    /**
     * Gets the value of the xmlnsXsd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsXsd() {
        if (xmlnsXsd == null) {
            return "http://www.w3.org/2001/XMLSchema";
        } else {
            return xmlnsXsd;
        }
    }

    /**
     * Sets the value of the xmlnsXsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsXsd(String value) {
        this.xmlnsXsd = value;
    }

}
