/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2015 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.03 at 10:12:07 AM MEZ 
//


package com.lp.server.schema.opentrans.cc.orderresponse;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for _XML_XML_ARTICLE_ID complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_XML_XML_ARTICLE_ID">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}SUPPLIER_AID" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}BUYER_AID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}DESCRIPTION_SHORT" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}DESCRIPTION_LONG" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_SKELETON_ORDER_ID" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_SKELETON_ORDER_ITEM_ID" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_SKELETON_ORDER_OPEN_QTY" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_SKELETON_ORDER_V_ID" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_SKELETON_ORDER_OPEN_V_VAL" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_PACKSIZE" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.opentrans.org/XMLSchema/1.0}ComIbmMrmNamespaceInfo154"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_XML_XML_ARTICLE_ID", propOrder = {
    "supplieraid",
    "buyeraid",
    "descriptionshort",
    "descriptionlong",
    "ccskeletonorderid",
    "ccskeletonorderitemid",
    "ccskeletonorderopenqty",
    "ccskeletonordervid",
    "ccskeletonorderopenvval",
    "ccpacksize"
})
public class XMLXMLARTICLEID {

    @XmlElement(name = "SUPPLIER_AID")
    protected String supplieraid;
    @XmlElement(name = "BUYER_AID")
    protected List<XMLXMLBUYERAID> buyeraid;
    @XmlElement(name = "DESCRIPTION_SHORT")
    protected String descriptionshort;
    @XmlElement(name = "DESCRIPTION_LONG")
    protected String descriptionlong;
    @XmlElement(name = "CC_SKELETON_ORDER_ID")
    protected String ccskeletonorderid;
    @XmlElement(name = "CC_SKELETON_ORDER_ITEM_ID")
    protected String ccskeletonorderitemid;
    @XmlElement(name = "CC_SKELETON_ORDER_OPEN_QTY")
    protected BigDecimal ccskeletonorderopenqty;
    @XmlElement(name = "CC_SKELETON_ORDER_V_ID")
    protected String ccskeletonordervid;
    @XmlElement(name = "CC_SKELETON_ORDER_OPEN_V_VAL")
    protected BigDecimal ccskeletonorderopenvval;
    @XmlElement(name = "CC_PACKSIZE")
    protected BigDecimal ccpacksize;
    @XmlAttribute(name = "xsi_schemaLocation")
    protected String xsiSchemaLocation;
    @XmlAttribute(name = "xmlns_xsd")
    protected String xmlnsXsd;

    /**
     * Gets the value of the supplieraid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUPPLIERAID() {
        return supplieraid;
    }

    /**
     * Sets the value of the supplieraid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUPPLIERAID(String value) {
        this.supplieraid = value;
    }

    /**
     * Gets the value of the buyeraid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the buyeraid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBUYERAID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLXMLBUYERAID }
     * 
     * 
     */
    public List<XMLXMLBUYERAID> getBUYERAID() {
        if (buyeraid == null) {
            buyeraid = new ArrayList<XMLXMLBUYERAID>();
        }
        return this.buyeraid;
    }

    /**
     * Gets the value of the descriptionshort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTIONSHORT() {
        return descriptionshort;
    }

    /**
     * Sets the value of the descriptionshort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTIONSHORT(String value) {
        this.descriptionshort = value;
    }

    /**
     * Gets the value of the descriptionlong property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTIONLONG() {
        return descriptionlong;
    }

    /**
     * Sets the value of the descriptionlong property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTIONLONG(String value) {
        this.descriptionlong = value;
    }

    /**
     * Gets the value of the ccskeletonorderid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCSKELETONORDERID() {
        return ccskeletonorderid;
    }

    /**
     * Sets the value of the ccskeletonorderid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCSKELETONORDERID(String value) {
        this.ccskeletonorderid = value;
    }

    /**
     * Gets the value of the ccskeletonorderitemid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCSKELETONORDERITEMID() {
        return ccskeletonorderitemid;
    }

    /**
     * Sets the value of the ccskeletonorderitemid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCSKELETONORDERITEMID(String value) {
        this.ccskeletonorderitemid = value;
    }

    /**
     * Gets the value of the ccskeletonorderopenqty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCCSKELETONORDEROPENQTY() {
        return ccskeletonorderopenqty;
    }

    /**
     * Sets the value of the ccskeletonorderopenqty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCCSKELETONORDEROPENQTY(BigDecimal value) {
        this.ccskeletonorderopenqty = value;
    }

    /**
     * Gets the value of the ccskeletonordervid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCSKELETONORDERVID() {
        return ccskeletonordervid;
    }

    /**
     * Sets the value of the ccskeletonordervid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCSKELETONORDERVID(String value) {
        this.ccskeletonordervid = value;
    }

    /**
     * Gets the value of the ccskeletonorderopenvval property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCCSKELETONORDEROPENVVAL() {
        return ccskeletonorderopenvval;
    }

    /**
     * Sets the value of the ccskeletonorderopenvval property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCCSKELETONORDEROPENVVAL(BigDecimal value) {
        this.ccskeletonorderopenvval = value;
    }

    /**
     * Gets the value of the ccpacksize property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCCPACKSIZE() {
        return ccpacksize;
    }

    /**
     * Sets the value of the ccpacksize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCCPACKSIZE(BigDecimal value) {
        this.ccpacksize = value;
    }

    /**
     * Gets the value of the xsiSchemaLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsiSchemaLocation() {
        if (xsiSchemaLocation == null) {
            return "openbase_1_0.mxsd";
        } else {
            return xsiSchemaLocation;
        }
    }

    /**
     * Sets the value of the xsiSchemaLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsiSchemaLocation(String value) {
        this.xsiSchemaLocation = value;
    }

    /**
     * Gets the value of the xmlnsXsd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsXsd() {
        if (xmlnsXsd == null) {
            return "http://www.w3.org/2001/XMLSchema";
        } else {
            return xmlnsXsd;
        }
    }

    /**
     * Sets the value of the xmlnsXsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsXsd(String value) {
        this.xmlnsXsd = value;
    }

}
