/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.03 at 10:12:07 AM MEZ 
//


package com.lp.server.schema.opentrans.cc.orderresponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for _XML_XML_ORDERRESPONSE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_XML_XML_ORDERRESPONSE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}ORDERRESPONSE_HEADER"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}ORDERRESPONSE_ITEM_LIST"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}ORDERRESPONSE_ITEM_CONF_LIST"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}ORDERRESPONSE_ITEM_VARCOND_LIST"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}ORDERRESPONSE_HEAD_TEXT_LIST"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}ORDERRESPONSE_SUMMARY"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.opentrans.org/XMLSchema/1.0}ComIbmMrmNamespaceInfo181"/>
 *       &lt;attribute name="version" type="{http://www.opentrans.org/XMLSchema/1.0}dtSTRING" fixed="1.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_XML_XML_ORDERRESPONSE", propOrder = {
    "orderresponseheader",
    "orderresponseitemlist",
    "orderresponseitemconflist",
    "orderresponseitemvarcondlist",
    "orderresponseheadtextlist",
    "orderresponsesummary"
})
@XmlRootElement(name="ORDERRESPONSE")
public class XMLXMLORDERRESPONSE {

    @XmlElement(name = "ORDERRESPONSE_HEADER", required = true)
    protected XMLXMLORDERRESPONSEHEADER orderresponseheader;
    @XmlElement(name = "ORDERRESPONSE_ITEM_LIST", required = true)
    protected XMLXMLORDERRESPONSEITEMLIST orderresponseitemlist;
    @XmlElement(name = "ORDERRESPONSE_ITEM_CONF_LIST", required = true)
    protected XMLXMLORDERRESPONSEITEMCONFLIST orderresponseitemconflist;
    @XmlElement(name = "ORDERRESPONSE_ITEM_VARCOND_LIST", required = true)
    protected XMLXMLORDERRESPONSEITEMVARCONDLIST orderresponseitemvarcondlist;
    @XmlElement(name = "ORDERRESPONSE_HEAD_TEXT_LIST", required = true)
    protected XMLXMLORDERRESPONSEHEADTEXTLIST orderresponseheadtextlist;
    @XmlElement(name = "ORDERRESPONSE_SUMMARY", required = true)
    protected XMLXMLORDERRESPONSESUMMARY orderresponsesummary;
    @XmlAttribute
    protected String version;
    @XmlAttribute(name = "xsi_schemaLocation")
    protected String xsiSchemaLocation;
    @XmlAttribute(name = "xmlns_xsd")
    protected String xmlnsXsd;

    /**
     * Gets the value of the orderresponseheader property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLORDERRESPONSEHEADER }
     *     
     */
    public XMLXMLORDERRESPONSEHEADER getORDERRESPONSEHEADER() {
        return orderresponseheader;
    }

    /**
     * Sets the value of the orderresponseheader property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLORDERRESPONSEHEADER }
     *     
     */
    public void setORDERRESPONSEHEADER(XMLXMLORDERRESPONSEHEADER value) {
        this.orderresponseheader = value;
    }

    /**
     * Gets the value of the orderresponseitemlist property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLORDERRESPONSEITEMLIST }
     *     
     */
    public XMLXMLORDERRESPONSEITEMLIST getORDERRESPONSEITEMLIST() {
        return orderresponseitemlist;
    }

    /**
     * Sets the value of the orderresponseitemlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLORDERRESPONSEITEMLIST }
     *     
     */
    public void setORDERRESPONSEITEMLIST(XMLXMLORDERRESPONSEITEMLIST value) {
        this.orderresponseitemlist = value;
    }

    /**
     * Gets the value of the orderresponseitemconflist property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLORDERRESPONSEITEMCONFLIST }
     *     
     */
    public XMLXMLORDERRESPONSEITEMCONFLIST getORDERRESPONSEITEMCONFLIST() {
        return orderresponseitemconflist;
    }

    /**
     * Sets the value of the orderresponseitemconflist property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLORDERRESPONSEITEMCONFLIST }
     *     
     */
    public void setORDERRESPONSEITEMCONFLIST(XMLXMLORDERRESPONSEITEMCONFLIST value) {
        this.orderresponseitemconflist = value;
    }

    /**
     * Gets the value of the orderresponseitemvarcondlist property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLORDERRESPONSEITEMVARCONDLIST }
     *     
     */
    public XMLXMLORDERRESPONSEITEMVARCONDLIST getORDERRESPONSEITEMVARCONDLIST() {
        return orderresponseitemvarcondlist;
    }

    /**
     * Sets the value of the orderresponseitemvarcondlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLORDERRESPONSEITEMVARCONDLIST }
     *     
     */
    public void setORDERRESPONSEITEMVARCONDLIST(XMLXMLORDERRESPONSEITEMVARCONDLIST value) {
        this.orderresponseitemvarcondlist = value;
    }

    /**
     * Gets the value of the orderresponseheadtextlist property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLORDERRESPONSEHEADTEXTLIST }
     *     
     */
    public XMLXMLORDERRESPONSEHEADTEXTLIST getORDERRESPONSEHEADTEXTLIST() {
        return orderresponseheadtextlist;
    }

    /**
     * Sets the value of the orderresponseheadtextlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLORDERRESPONSEHEADTEXTLIST }
     *     
     */
    public void setORDERRESPONSEHEADTEXTLIST(XMLXMLORDERRESPONSEHEADTEXTLIST value) {
        this.orderresponseheadtextlist = value;
    }

    /**
     * Gets the value of the orderresponsesummary property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLORDERRESPONSESUMMARY }
     *     
     */
    public XMLXMLORDERRESPONSESUMMARY getORDERRESPONSESUMMARY() {
        return orderresponsesummary;
    }

    /**
     * Sets the value of the orderresponsesummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLORDERRESPONSESUMMARY }
     *     
     */
    public void setORDERRESPONSESUMMARY(XMLXMLORDERRESPONSESUMMARY value) {
        this.orderresponsesummary = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the xsiSchemaLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsiSchemaLocation() {
        if (xsiSchemaLocation == null) {
            return "openTRANS_ORDERRESPONSE_1_0.mxsd";
        } else {
            return xsiSchemaLocation;
        }
    }

    /**
     * Sets the value of the xsiSchemaLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsiSchemaLocation(String value) {
        this.xsiSchemaLocation = value;
    }

    /**
     * Gets the value of the xmlnsXsd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsXsd() {
        if (xmlnsXsd == null) {
            return "http://www.w3.org/2001/XMLSchema";
        } else {
            return xmlnsXsd;
        }
    }

    /**
     * Sets the value of the xmlnsXsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsXsd(String value) {
        this.xmlnsXsd = value;
    }

}
