/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2015 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.03 at 10:12:07 AM MEZ 
//


package com.lp.server.schema.opentrans.cc.orderresponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for _XML_XML_ORDER_PARTIES complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_XML_XML_ORDER_PARTIES">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}BUYER_PARTY"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}SUPPLIER_PARTY"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}INVOICE_PARTY" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}SHIPMENT_PARTIES" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.opentrans.org/XMLSchema/1.0}ComIbmMrmNamespaceInfo154"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_XML_XML_ORDER_PARTIES", propOrder = {
    "buyerparty",
    "supplierparty",
    "invoiceparty",
    "shipmentparties"
})
public class XMLXMLORDERPARTIES {

    @XmlElement(name = "BUYER_PARTY", required = true)
    protected XMLXMLBUYERPARTY buyerparty;
    @XmlElement(name = "SUPPLIER_PARTY", required = true)
    protected XMLXMLSUPPLIERPARTY supplierparty;
    @XmlElement(name = "INVOICE_PARTY")
    protected XMLXMLINVOICEPARTY invoiceparty;
    @XmlElement(name = "SHIPMENT_PARTIES")
    protected XMLXMLSHIPMENTPARTIES shipmentparties;
    @XmlAttribute(name = "xsi_schemaLocation")
    protected String xsiSchemaLocation;
    @XmlAttribute(name = "xmlns_xsd")
    protected String xmlnsXsd;

    /**
     * Gets the value of the buyerparty property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLBUYERPARTY }
     *     
     */
    public XMLXMLBUYERPARTY getBUYERPARTY() {
        return buyerparty;
    }

    /**
     * Sets the value of the buyerparty property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLBUYERPARTY }
     *     
     */
    public void setBUYERPARTY(XMLXMLBUYERPARTY value) {
        this.buyerparty = value;
    }

    /**
     * Gets the value of the supplierparty property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLSUPPLIERPARTY }
     *     
     */
    public XMLXMLSUPPLIERPARTY getSUPPLIERPARTY() {
        return supplierparty;
    }

    /**
     * Sets the value of the supplierparty property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLSUPPLIERPARTY }
     *     
     */
    public void setSUPPLIERPARTY(XMLXMLSUPPLIERPARTY value) {
        this.supplierparty = value;
    }

    /**
     * Gets the value of the invoiceparty property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLINVOICEPARTY }
     *     
     */
    public XMLXMLINVOICEPARTY getINVOICEPARTY() {
        return invoiceparty;
    }

    /**
     * Sets the value of the invoiceparty property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLINVOICEPARTY }
     *     
     */
    public void setINVOICEPARTY(XMLXMLINVOICEPARTY value) {
        this.invoiceparty = value;
    }

    /**
     * Gets the value of the shipmentparties property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLSHIPMENTPARTIES }
     *     
     */
    public XMLXMLSHIPMENTPARTIES getSHIPMENTPARTIES() {
        return shipmentparties;
    }

    /**
     * Sets the value of the shipmentparties property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLSHIPMENTPARTIES }
     *     
     */
    public void setSHIPMENTPARTIES(XMLXMLSHIPMENTPARTIES value) {
        this.shipmentparties = value;
    }

    /**
     * Gets the value of the xsiSchemaLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsiSchemaLocation() {
        if (xsiSchemaLocation == null) {
            return "openbase_1_0.mxsd";
        } else {
            return xsiSchemaLocation;
        }
    }

    /**
     * Sets the value of the xsiSchemaLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsiSchemaLocation(String value) {
        this.xsiSchemaLocation = value;
    }

    /**
     * Gets the value of the xmlnsXsd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsXsd() {
        if (xmlnsXsd == null) {
            return "http://www.w3.org/2001/XMLSchema";
        } else {
            return xmlnsXsd;
        }
    }

    /**
     * Sets the value of the xmlnsXsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsXsd(String value) {
        this.xmlnsXsd = value;
    }

}
