/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2015 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.03 at 10:12:07 AM MEZ 
//


package com.lp.server.schema.opentrans.cc.orderresponse;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for _XML_XML_ORDERRESPONSE_INFO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_XML_XML_ORDERRESPONSE_INFO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}ORDER_ID"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}ALT_CUSTOMER_ORDER_ID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}SUPPLIER_ORDER_ID" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}ORDER_DATE" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}ORDERCHANGE_SEQUENCE_ID" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}ORDERRESPONSE_DATE"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}ORDER_PARTIES"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}PRICE_CURRENCY" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}REMARK" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_ORDER_TYPE" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_BUYER_NR_SUP" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}TRANSPORT" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_WERKS" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_SENDER_CODE" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_RECEIV_CODE" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}USR_ERP_CODE" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_PRINT_ABLAD" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_OFFER_NR" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_EKORG" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_BUYER_GROUP_NR" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.opentrans.org/XMLSchema/1.0}ComIbmMrmNamespaceInfo181"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_XML_XML_ORDERRESPONSE_INFO", propOrder = {
    "orderid",
    "altcustomerorderid",
    "supplierorderid",
    "orderdate",
    "orderchangesequenceid",
    "orderresponsedate",
    "orderparties",
    "pricecurrency",
    "remark",
    "ccordertype",
    "ccbuyernrsup",
    "transport",
    "ccwerks",
    "ccsendercode",
    "ccreceivcode",
    "usrerpcode",
    "ccprintablad",
    "ccoffernr",
    "ccekorg",
    "ccbuyergroupnr"
})
public class XMLXMLORDERRESPONSEINFO {

    @XmlElement(name = "ORDER_ID", required = true)
    protected String orderid;
    @XmlElement(name = "ALT_CUSTOMER_ORDER_ID")
    protected List<String> altcustomerorderid;
    @XmlElement(name = "SUPPLIER_ORDER_ID")
    protected String supplierorderid;
    @XmlElement(name = "ORDER_DATE")
    protected String orderdate;
    @XmlElement(name = "ORDERCHANGE_SEQUENCE_ID")
    protected BigInteger orderchangesequenceid;
    @XmlElement(name = "ORDERRESPONSE_DATE", required = true)
    protected String orderresponsedate;
    @XmlElement(name = "ORDER_PARTIES", required = true)
    protected XMLXMLORDERPARTIES orderparties;
    @XmlElement(name = "PRICE_CURRENCY")
    protected DtCURRENCIES pricecurrency;
    @XmlElement(name = "REMARK")
    protected List<XMLXMLREMARK> remark;
    @XmlElement(name = "CC_ORDER_TYPE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ccordertype;
    @XmlElement(name = "CC_BUYER_NR_SUP")
    protected String ccbuyernrsup;
    @XmlElement(name = "TRANSPORT")
    protected XMLXMLTRANSPORT transport;
    @XmlElement(name = "CC_WERKS")
    protected String ccwerks;
    @XmlElement(name = "CC_SENDER_CODE")
    protected String ccsendercode;
    @XmlElement(name = "CC_RECEIV_CODE")
    protected String ccreceivcode;
    @XmlElement(name = "USR_ERP_CODE")
    protected String usrerpcode;
    @XmlElement(name = "CC_PRINT_ABLAD")
    protected String ccprintablad;
    @XmlElement(name = "CC_OFFER_NR")
    protected String ccoffernr;
    @XmlElement(name = "CC_EKORG")
    protected String ccekorg;
    @XmlElement(name = "CC_BUYER_GROUP_NR")
    protected String ccbuyergroupnr;
    @XmlAttribute(name = "xsi_schemaLocation")
    protected String xsiSchemaLocation;
    @XmlAttribute(name = "xmlns_xsd")
    protected String xmlnsXsd;

    /**
     * Gets the value of the orderid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDERID() {
        return orderid;
    }

    /**
     * Sets the value of the orderid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDERID(String value) {
        this.orderid = value;
    }

    /**
     * Gets the value of the altcustomerorderid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the altcustomerorderid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getALTCUSTOMERORDERID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getALTCUSTOMERORDERID() {
        if (altcustomerorderid == null) {
            altcustomerorderid = new ArrayList<String>();
        }
        return this.altcustomerorderid;
    }

    /**
     * Gets the value of the supplierorderid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUPPLIERORDERID() {
        return supplierorderid;
    }

    /**
     * Sets the value of the supplierorderid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUPPLIERORDERID(String value) {
        this.supplierorderid = value;
    }

    /**
     * Gets the value of the orderdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDERDATE() {
        return orderdate;
    }

    /**
     * Sets the value of the orderdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDERDATE(String value) {
        this.orderdate = value;
    }

    /**
     * Gets the value of the orderchangesequenceid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getORDERCHANGESEQUENCEID() {
        return orderchangesequenceid;
    }

    /**
     * Sets the value of the orderchangesequenceid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setORDERCHANGESEQUENCEID(BigInteger value) {
        this.orderchangesequenceid = value;
    }

    /**
     * Gets the value of the orderresponsedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDERRESPONSEDATE() {
        return orderresponsedate;
    }

    /**
     * Sets the value of the orderresponsedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDERRESPONSEDATE(String value) {
        this.orderresponsedate = value;
    }

    /**
     * Gets the value of the orderparties property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLORDERPARTIES }
     *     
     */
    public XMLXMLORDERPARTIES getORDERPARTIES() {
        return orderparties;
    }

    /**
     * Sets the value of the orderparties property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLORDERPARTIES }
     *     
     */
    public void setORDERPARTIES(XMLXMLORDERPARTIES value) {
        this.orderparties = value;
    }

    /**
     * Gets the value of the pricecurrency property.
     * 
     * @return
     *     possible object is
     *     {@link DtCURRENCIES }
     *     
     */
    public DtCURRENCIES getPRICECURRENCY() {
        return pricecurrency;
    }

    /**
     * Sets the value of the pricecurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link DtCURRENCIES }
     *     
     */
    public void setPRICECURRENCY(DtCURRENCIES value) {
        this.pricecurrency = value;
    }

    /**
     * Gets the value of the remark property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remark property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getREMARK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLXMLREMARK }
     * 
     * 
     */
    public List<XMLXMLREMARK> getREMARK() {
        if (remark == null) {
            remark = new ArrayList<XMLXMLREMARK>();
        }
        return this.remark;
    }

    /**
     * Gets the value of the ccordertype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCORDERTYPE() {
        return ccordertype;
    }

    /**
     * Sets the value of the ccordertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCORDERTYPE(String value) {
        this.ccordertype = value;
    }

    /**
     * Gets the value of the ccbuyernrsup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCBUYERNRSUP() {
        return ccbuyernrsup;
    }

    /**
     * Sets the value of the ccbuyernrsup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCBUYERNRSUP(String value) {
        this.ccbuyernrsup = value;
    }

    /**
     * Gets the value of the transport property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLTRANSPORT }
     *     
     */
    public XMLXMLTRANSPORT getTRANSPORT() {
        return transport;
    }

    /**
     * Sets the value of the transport property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLTRANSPORT }
     *     
     */
    public void setTRANSPORT(XMLXMLTRANSPORT value) {
        this.transport = value;
    }

    /**
     * Gets the value of the ccwerks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCWERKS() {
        return ccwerks;
    }

    /**
     * Sets the value of the ccwerks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCWERKS(String value) {
        this.ccwerks = value;
    }

    /**
     * Gets the value of the ccsendercode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCSENDERCODE() {
        return ccsendercode;
    }

    /**
     * Sets the value of the ccsendercode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCSENDERCODE(String value) {
        this.ccsendercode = value;
    }

    /**
     * Gets the value of the ccreceivcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCRECEIVCODE() {
        return ccreceivcode;
    }

    /**
     * Sets the value of the ccreceivcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCRECEIVCODE(String value) {
        this.ccreceivcode = value;
    }

    /**
     * Gets the value of the usrerpcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSRERPCODE() {
        return usrerpcode;
    }

    /**
     * Sets the value of the usrerpcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSRERPCODE(String value) {
        this.usrerpcode = value;
    }

    /**
     * Gets the value of the ccprintablad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCPRINTABLAD() {
        return ccprintablad;
    }

    /**
     * Sets the value of the ccprintablad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCPRINTABLAD(String value) {
        this.ccprintablad = value;
    }

    /**
     * Gets the value of the ccoffernr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCOFFERNR() {
        return ccoffernr;
    }

    /**
     * Sets the value of the ccoffernr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCOFFERNR(String value) {
        this.ccoffernr = value;
    }

    /**
     * Gets the value of the ccekorg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCEKORG() {
        return ccekorg;
    }

    /**
     * Sets the value of the ccekorg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCEKORG(String value) {
        this.ccekorg = value;
    }

    /**
     * Gets the value of the ccbuyergroupnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCBUYERGROUPNR() {
        return ccbuyergroupnr;
    }

    /**
     * Sets the value of the ccbuyergroupnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCBUYERGROUPNR(String value) {
        this.ccbuyergroupnr = value;
    }

    /**
     * Gets the value of the xsiSchemaLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsiSchemaLocation() {
        if (xsiSchemaLocation == null) {
            return "openTRANS_ORDERRESPONSE_1_0.mxsd";
        } else {
            return xsiSchemaLocation;
        }
    }

    /**
     * Sets the value of the xsiSchemaLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsiSchemaLocation(String value) {
        this.xsiSchemaLocation = value;
    }

    /**
     * Gets the value of the xmlnsXsd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsXsd() {
        if (xmlnsXsd == null) {
            return "http://www.w3.org/2001/XMLSchema";
        } else {
            return xmlnsXsd;
        }
    }

    /**
     * Sets the value of the xmlnsXsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsXsd(String value) {
        this.xmlnsXsd = value;
    }

}
