/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.03 at 10:12:07 AM MEZ 
//


package com.lp.server.schema.opentrans.cc.orderresponse;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for _XML_XML_ARTICLE_PRICE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_XML_XML_ARTICLE_PRICE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}PRICE_AMOUNT"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}PRICE_LINE_AMOUNT" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}TAX" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}TAX_AMOUNT" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}TAX_RATE_EXT" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}TAX_MARK" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}PRICE_QUANTITY" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_DISCOUNT" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}ORDER_UNIT" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_ORDER_UNIT" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_PRICE_CONVERSION_RATIO" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_PRICEINFO1" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_PRICEINFO2" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/1.0}CC_PRICE_ADD_INFO" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.opentrans.org/XMLSchema/1.0}ComIbmMrmNamespaceInfo154"/>
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="net_list"/>
 *             &lt;enumeration value="gros_list"/>
 *             &lt;enumeration value="net_customer"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_XML_XML_ARTICLE_PRICE", propOrder = {
    "priceamount",
    "pricelineamount",
    "tax",
    "taxamount",
    "taxrateext",
    "taxmark",
    "pricequantity",
    "ccdiscount",
    "orderunit",
    "ccorderunit",
    "ccpriceconversionratio",
    "ccpriceinfo1",
    "ccpriceinfo2",
    "ccpriceaddinfo"
})
public class XMLXMLARTICLEPRICE {

    @XmlElement(name = "PRICE_AMOUNT", required = true)
    protected BigDecimal priceamount;
    @XmlElement(name = "PRICE_LINE_AMOUNT")
    protected BigDecimal pricelineamount;
    @XmlElement(name = "TAX")
    protected BigDecimal tax;
    @XmlElement(name = "TAX_AMOUNT")
    protected BigDecimal taxamount;
    @XmlElement(name = "TAX_RATE_EXT")
    protected BigDecimal taxrateext;
    @XmlElement(name = "TAX_MARK")
    protected String taxmark;
    @XmlElement(name = "PRICE_QUANTITY")
    protected BigDecimal pricequantity;
    @XmlElement(name = "CC_DISCOUNT")
    protected BigDecimal ccdiscount;
    @XmlElement(name = "ORDER_UNIT")
    protected String orderunit;
    @XmlElement(name = "CC_ORDER_UNIT")
    protected String ccorderunit;
    @XmlElement(name = "CC_PRICE_CONVERSION_RATIO")
    protected BigDecimal ccpriceconversionratio;
    @XmlElement(name = "CC_PRICEINFO1")
    protected BigDecimal ccpriceinfo1;
    @XmlElement(name = "CC_PRICEINFO2")
    protected BigDecimal ccpriceinfo2;
    @XmlElement(name = "CC_PRICE_ADD_INFO")
    protected String ccpriceaddinfo;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "xsi_schemaLocation")
    protected String xsiSchemaLocation;
    @XmlAttribute(name = "xmlns_xsd")
    protected String xmlnsXsd;

    /**
     * Gets the value of the priceamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPRICEAMOUNT() {
        return priceamount;
    }

    /**
     * Sets the value of the priceamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPRICEAMOUNT(BigDecimal value) {
        this.priceamount = value;
    }

    /**
     * Gets the value of the pricelineamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPRICELINEAMOUNT() {
        return pricelineamount;
    }

    /**
     * Sets the value of the pricelineamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPRICELINEAMOUNT(BigDecimal value) {
        this.pricelineamount = value;
    }

    /**
     * Gets the value of the tax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTAX() {
        return tax;
    }

    /**
     * Sets the value of the tax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTAX(BigDecimal value) {
        this.tax = value;
    }

    /**
     * Gets the value of the taxamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTAXAMOUNT() {
        return taxamount;
    }

    /**
     * Sets the value of the taxamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTAXAMOUNT(BigDecimal value) {
        this.taxamount = value;
    }

    /**
     * Gets the value of the taxrateext property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTAXRATEEXT() {
        return taxrateext;
    }

    /**
     * Sets the value of the taxrateext property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTAXRATEEXT(BigDecimal value) {
        this.taxrateext = value;
    }

    /**
     * Gets the value of the taxmark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAXMARK() {
        return taxmark;
    }

    /**
     * Sets the value of the taxmark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAXMARK(String value) {
        this.taxmark = value;
    }

    /**
     * Gets the value of the pricequantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPRICEQUANTITY() {
        return pricequantity;
    }

    /**
     * Sets the value of the pricequantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPRICEQUANTITY(BigDecimal value) {
        this.pricequantity = value;
    }

    /**
     * Gets the value of the ccdiscount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCCDISCOUNT() {
        return ccdiscount;
    }

    /**
     * Sets the value of the ccdiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCCDISCOUNT(BigDecimal value) {
        this.ccdiscount = value;
    }

    /**
     * Gets the value of the orderunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDERUNIT() {
        return orderunit;
    }

    /**
     * Sets the value of the orderunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDERUNIT(String value) {
        this.orderunit = value;
    }

    /**
     * Gets the value of the ccorderunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCORDERUNIT() {
        return ccorderunit;
    }

    /**
     * Sets the value of the ccorderunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCORDERUNIT(String value) {
        this.ccorderunit = value;
    }

    /**
     * Gets the value of the ccpriceconversionratio property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCCPRICECONVERSIONRATIO() {
        return ccpriceconversionratio;
    }

    /**
     * Sets the value of the ccpriceconversionratio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCCPRICECONVERSIONRATIO(BigDecimal value) {
        this.ccpriceconversionratio = value;
    }

    /**
     * Gets the value of the ccpriceinfo1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCCPRICEINFO1() {
        return ccpriceinfo1;
    }

    /**
     * Sets the value of the ccpriceinfo1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCCPRICEINFO1(BigDecimal value) {
        this.ccpriceinfo1 = value;
    }

    /**
     * Gets the value of the ccpriceinfo2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCCPRICEINFO2() {
        return ccpriceinfo2;
    }

    /**
     * Sets the value of the ccpriceinfo2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCCPRICEINFO2(BigDecimal value) {
        this.ccpriceinfo2 = value;
    }

    /**
     * Gets the value of the ccpriceaddinfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCPRICEADDINFO() {
        return ccpriceaddinfo;
    }

    /**
     * Sets the value of the ccpriceaddinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCPRICEADDINFO(String value) {
        this.ccpriceaddinfo = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the xsiSchemaLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsiSchemaLocation() {
        if (xsiSchemaLocation == null) {
            return "openbase_1_0.mxsd";
        } else {
            return xsiSchemaLocation;
        }
    }

    /**
     * Sets the value of the xsiSchemaLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsiSchemaLocation(String value) {
        this.xsiSchemaLocation = value;
    }

    /**
     * Gets the value of the xmlnsXsd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsXsd() {
        if (xmlnsXsd == null) {
            return "http://www.w3.org/2001/XMLSchema";
        } else {
            return xmlnsXsd;
        }
    }

    /**
     * Sets the value of the xmlnsXsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsXsd(String value) {
        this.xmlnsXsd = value;
    }

}
