package com.lp.server.partner.bl;

import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;

import org.xml.sax.SAXException;

import com.lp.server.schema.vendidata.customers.ObjectFactory;
import com.lp.server.schema.vendidata.customers.XMLCustomers;
import com.lp.server.util.XMLMarshaller;

public class VendidataCustomersMarshaller extends XMLMarshaller<XMLCustomers> {

	String xsdCustomers = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n" + 
			"<xsd:schema xmlns=\"http://www.vendidata.com/XML/Schema/Customers\"\r\n" + 
			"    targetNamespace=\"http://www.vendidata.com/XML/Schema/Customers\" version=\"1.2.2\"\r\n" + 
			"    xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n" + 
			"    <xsd:element name=\"Customers\" type=\"Customers\">\r\n" + 
			"        <xsd:annotation>\r\n" + 
			"            <xsd:documentation>The element \"Customers\" is the root element of any Customers XML instance. It must be present and it should have at least one child-element of type \"Customer\" or \"CustomerClsuter\" or a combination of multiples of both.\r\n" + 
			"\r\n" + 
			"There are two different ways to import customers:\r\n" + 
			"They can either be unstructured or they can be in a special structure named CustomerCluster. In each XML-File each single customer must not be in both variants (Customer A may only be represented as either \"Customer\" or as \"CustomerCluster\")\r\n" + 
			"\r\n" + 
			"Variant A: Using elements of type \"CustomerCluster\"\r\n" + 
			"A CustomerCluster is intended to group an arbitrary number of customers. Each CustomerCluster has to have exactly one master customer. Existing customers can moved between clusters as required. If the importer should maintain the cluster masters and members, you have to use the \"CustomerCluster\" elements.\r\n" + 
			"\r\n" + 
			"Variant B: Using elements of type \"Customer\"\r\n" + 
			"On the other hand it is also possible to ignore the CustomerCluster structure in the application and just create each customer in it's own cluster. In this case the grouping of customers to clusters can still be done manually by the user within 4Vending. If a existing customers has to be updated it's cluster membership is ignored entirely. If a new customers is set to be created from the XML-file it will be created in a new cluster with this customer as it's sole member.\r\n" + 
			"\r\n" + 
			"Variant A and Variant B can be mixed as desired in one XML-file. The only requirement is, that each unique customer only exists once throughout the whole file.</xsd:documentation>\r\n" + 
			"        </xsd:annotation>\r\n" + 
			"    </xsd:element>\r\n" + 
			"    <xsd:complexType name=\"Customer\">\r\n" + 
			"        <xsd:sequence>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Matchcode\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                        <xsd:whiteSpace value=\"preserve\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:choice>\r\n" + 
			"                <xsd:element name=\"CustomerId\">\r\n" + 
			"                    <xsd:annotation>\r\n" + 
			"                        <xsd:documentation>This ID is used to identify customers and determine if they should be created as new customer or if this is an update for an existing customer. It must not be modified after the creation (=first time import) of the customer.\r\n" + 
			"The customer ID must be unique throughout the whole file.</xsd:documentation>\r\n" + 
			"                    </xsd:annotation>\r\n" + 
			"                    <xsd:simpleType>\r\n" + 
			"                        <xsd:restriction base=\"xsd:int\">\r\n" + 
			"                            <xsd:minInclusive value=\"1\"/>\r\n" + 
			"                            <xsd:maxInclusive value=\"2147483646\"/>\r\n" + 
			"                        </xsd:restriction>\r\n" + 
			"                    </xsd:simpleType>\r\n" + 
			"                </xsd:element>\r\n" + 
			"                <xsd:element name=\"AutoGenerateCustomerId\" type=\"AutoGenerateId\">\r\n" + 
			"                    <xsd:annotation>\r\n" + 
			"                        <xsd:documentation>If this element is present, the CustomerID will be generated by the importer, otherwise the specified CustomerID will be used.\r\n" + 
			"\r\n" + 
			"Only use an autogenerated CustomerID if you are certain, that this customer should be created from scratch. If you intention is to update an existing customer, you have to specify a CustomerID.</xsd:documentation>\r\n" + 
			"                    </xsd:annotation>\r\n" + 
			"                </xsd:element>\r\n" + 
			"            </xsd:choice>\r\n" + 
			"            <xsd:choice>\r\n" + 
			"                <xsd:element name=\"AccountingId\">\r\n" + 
			"                    <xsd:simpleType>\r\n" + 
			"                        <xsd:restriction base=\"xsd:int\">\r\n" + 
			"                            <xsd:minInclusive value=\"1\"/>\r\n" + 
			"                            <xsd:maxInclusive value=\"2147483646\"/>\r\n" + 
			"                        </xsd:restriction>\r\n" + 
			"                    </xsd:simpleType>\r\n" + 
			"                </xsd:element>\r\n" + 
			"                <xsd:element name=\"AutoGenerateAccountingId\">\r\n" + 
			"                    <xsd:annotation>\r\n" + 
			"                        <xsd:documentation>If this element is present, the AccountingID will be generated by the importer, otherwise the specified AccountingID will be used.</xsd:documentation>\r\n" + 
			"                    </xsd:annotation>\r\n" + 
			"                    <xsd:complexType>\r\n" + 
			"                        <xsd:simpleContent>\r\n" + 
			"                            <xsd:extension base=\"AutoGenerateId\">\r\n" + 
			"                                <xsd:attribute default=\"false\" name=\"updateIfExists\"\r\n" + 
			"                                    type=\"xsd:boolean\"/>\r\n" + 
			"                            </xsd:extension>\r\n" + 
			"                        </xsd:simpleContent>\r\n" + 
			"                    </xsd:complexType>\r\n" + 
			"                </xsd:element>\r\n" + 
			"            </xsd:choice>\r\n" + 
			"            <xsd:element name=\"Name1\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"1\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Name2\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Name3\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Street\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Postalcode\" type=\"Postalcode\"/>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Group\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"1\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Language\" type=\"Language\"/>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"VatIdNumber\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"PhoneNumber\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"MobilePhoneNumber\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"FaxNumber\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"EMailAddress\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"WebsiteAddress\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Notes\" type=\"xsd:string\"/>\r\n" + 
			"            <xsd:sequence maxOccurs=\"unbounded\" minOccurs=\"0\">\r\n" + 
			"                <xsd:element name=\"Stand\" type=\"Stand\"/>\r\n" + 
			"            </xsd:sequence>\r\n" + 
			"            <xsd:sequence maxOccurs=\"unbounded\" minOccurs=\"0\">\r\n" + 
			"                <xsd:element name=\"Contact\" type=\"Contact\"/>\r\n" + 
			"            </xsd:sequence>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"AdditionalFields\" type=\"AdditionalFields\"/>\r\n" + 
			"        </xsd:sequence>\r\n" + 
			"        <xsd:attribute name=\"isOperating\" type=\"xsd:boolean\" use=\"required\"/>\r\n" + 
			"        <xsd:attribute name=\"isCustomer\" type=\"xsd:boolean\" use=\"required\"/>\r\n" + 
			"        <xsd:attribute name=\"creationDate\" type=\"xsd:dateTime\"/>\r\n" + 
			"        <xsd:attribute default=\"ACTIVE\" name=\"status\" type=\"Status\" use=\"optional\"/>\r\n" + 
			"    </xsd:complexType>\r\n" + 
			"    <xsd:complexType name=\"Customers\">\r\n" + 
			"        <xsd:sequence>\r\n" + 
			"            <xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"UpdateLegacyId\"\r\n" + 
			"                type=\"UpdateLegacyId\"/>\r\n" + 
			"            <xsd:element maxOccurs=\"unbounded\" name=\"Customer\" type=\"Customer\" minOccurs=\"0\"/>\r\n" + 
			"            <xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"CustomerCluster\"\r\n" + 
			"                type=\"CustomerCluster\"/>\r\n" + 
			"        </xsd:sequence>\r\n" + 
			"    </xsd:complexType>\r\n" + 
			"    <xsd:complexType name=\"Postalcode\">\r\n" + 
			"        <xsd:sequence>\r\n" + 
			"            <xsd:element name=\"Country\" type=\"Country\"/>\r\n" + 
			"            <xsd:element name=\"Province\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"1\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element name=\"County\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"1\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element name=\"ZipCode\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"1\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element name=\"City\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"1\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"        </xsd:sequence>\r\n" + 
			"    </xsd:complexType>\r\n" + 
			"    <xsd:complexType name=\"Country\">\r\n" + 
			"        <xsd:sequence>\r\n" + 
			"            <xsd:element name=\"Fullname\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"1\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element name=\"Shortname\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"1\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"        </xsd:sequence>\r\n" + 
			"    </xsd:complexType>\r\n" + 
			"    <xsd:complexType name=\"Language\">\r\n" + 
			"        <xsd:sequence>\r\n" + 
			"            <xsd:element name=\"Language\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"1\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element name=\"ISO3166\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"1\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"        </xsd:sequence>\r\n" + 
			"    </xsd:complexType>\r\n" + 
			"    <xsd:complexType name=\"Stand\">\r\n" + 
			"        <xsd:sequence>\r\n" + 
			"            <xsd:element name=\"Name\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"1\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:sequence>\r\n" + 
			"                <xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"VirtualVendingmachine\"\r\n" + 
			"                    type=\"VirtualVendingmachine\">\r\n" + 
			"                    <xsd:annotation>\r\n" + 
			"                        <xsd:documentation>If a Stand has one or more VirtualVendingmachines attached, they must be referenced by there LegacyId. Therefore the LegacyId must not be null in the XML File. It also must not be modified in the 4Vending Application.</xsd:documentation>\r\n" + 
			"                    </xsd:annotation>\r\n" + 
			"                </xsd:element>\r\n" + 
			"            </xsd:sequence>\r\n" + 
			"        </xsd:sequence>\r\n" + 
			"        <xsd:attribute form=\"unqualified\" name=\"waterSupplyExists\" type=\"xsd:boolean\" use=\"required\"\r\n" + 
			"        />\r\n" + 
			"    </xsd:complexType>\r\n" + 
			"    <xsd:complexType name=\"Contact\">\r\n" + 
			"        <xsd:sequence>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Salutation\" type=\"Salutation\"/>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Title\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Firstname\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"1\" name=\"Lastname\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"1\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Street\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Postalcode\" type=\"Postalcode\"/>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"PhoneNumber\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"MobilePhoneNumber\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"FaxNumber\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"EMailAddress\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"PrivatePhoneNumber\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"PrivateMobilePhoneNumber\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"DateOfBirth\" type=\"xsd:date\"/>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"PrivateEMailAddress\">\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"0\"/>\r\n" + 
			"                        <xsd:maxLength value=\"50\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element name=\"Notes\" type=\"xsd:string\" minOccurs=\"0\"/>\r\n" + 
			"        </xsd:sequence>\r\n" + 
			"        <xsd:attribute name=\"receiveMailings\" type=\"xsd:boolean\" use=\"required\"/>\r\n" + 
			"        <xsd:attribute name=\"receiveGifts\" type=\"xsd:boolean\" use=\"required\"/>\r\n" + 
			"    </xsd:complexType>\r\n" + 
			"    <xsd:simpleType name=\"Salutation\">\r\n" + 
			"        <xsd:restriction base=\"xsd:string\">\r\n" + 
			"            <xsd:enumeration value=\"MISTER\"/>\r\n" + 
			"            <xsd:enumeration value=\"MISS\"/>\r\n" + 
			"            <xsd:enumeration value=\"MISSES\"/>\r\n" + 
			"        </xsd:restriction>\r\n" + 
			"    </xsd:simpleType>\r\n" + 
			"    <xsd:simpleType name=\"Status\">\r\n" + 
			"        <xsd:restriction base=\"xsd:string\">\r\n" + 
			"            <xsd:enumeration value=\"ACTIVE\"/>\r\n" + 
			"            <xsd:enumeration value=\"DELETED\"/>\r\n" + 
			"            <xsd:enumeration value=\"BLOCKED\"/>\r\n" + 
			"        </xsd:restriction>\r\n" + 
			"    </xsd:simpleType>\r\n" + 
			"    <xsd:complexType name=\"VirtualVendingmachine\">\r\n" + 
			"        <xsd:sequence>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Rowid\">\r\n" + 
			"                <xsd:annotation>\r\n" + 
			"                    <xsd:documentation>Don't use this field for imports! It is only used while exporting CustomerData. It is entirely ignored by the CustomerImporter.</xsd:documentation>\r\n" + 
			"                </xsd:annotation>\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:int\">\r\n" + 
			"                        <xsd:minInclusive value=\"1\"/>\r\n" + 
			"                        <xsd:maxInclusive value=\"999999999\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"1\" name=\"LegacyId\">\r\n" + 
			"                <xsd:annotation>\r\n" + 
			"                    <xsd:documentation>Used to identify and create or update the VVM.</xsd:documentation>\r\n" + 
			"                </xsd:annotation>\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"1\"/>\r\n" + 
			"                        <xsd:maxLength value=\"255\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element name=\"OperationVariant\" type=\"OperationVariant\">\r\n" + 
			"                <xsd:annotation>\r\n" + 
			"                    <xsd:documentation>Can only be set on the first time this VVM is imported (=created). Modifications on existing VVMs are only supported within the 4Vending Application. This element will be ignored if the containing VirtualVendingmachine is already existing in the datababase.</xsd:documentation>\r\n" + 
			"                </xsd:annotation>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element name=\"AllocationType\" type=\"AllocationType\">\r\n" + 
			"                <xsd:annotation>\r\n" + 
			"                    <xsd:documentation>Can only be set on the first time this VVM is imported (=created). Modifications on existing VVMs are only supported within the 4Vending Application. This element will be ignored if the containing VirtualVendingmachine is already existing in the datababase.</xsd:documentation>\r\n" + 
			"                </xsd:annotation>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"AdditionalFields\" type=\"AdditionalFields\"/>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"SalesPriceList\" type=\"SalesPriceList\"/>\r\n" + 
			"        </xsd:sequence>\r\n" + 
			"        <xsd:attribute default=\"false\" name=\"hasLocker\" type=\"xsd:boolean\"/>\r\n" + 
			"    </xsd:complexType>\r\n" + 
			"    <xsd:simpleType name=\"AllocationType\">\r\n" + 
			"        <xsd:restriction base=\"xsd:string\">\r\n" + 
			"            <xsd:enumeration value=\"EASYDATA\"/>\r\n" + 
			"            <xsd:enumeration value=\"QUICK_ONLY\"/>\r\n" + 
			"            <xsd:enumeration value=\"CASH_ONLY\"/>\r\n" + 
			"            <xsd:enumeration value=\"CASHLESS_ONLY\"/>\r\n" + 
			"            <xsd:enumeration value=\"EVA_DTS\"/>\r\n" + 
			"        </xsd:restriction>\r\n" + 
			"    </xsd:simpleType>\r\n" + 
			"    <xsd:simpleType name=\"OperationVariant\">\r\n" + 
			"        <xsd:restriction base=\"xsd:string\">\r\n" + 
			"            <xsd:enumeration value=\"FULL_OPERATING\"/>\r\n" + 
			"            <xsd:enumeration value=\"PARTIAL_OPERATING\"/>\r\n" + 
			"            <xsd:enumeration value=\"CUSTOMER\"/>\r\n" + 
			"            <xsd:enumeration value=\"CLEARING\"/>\r\n" + 
			"        </xsd:restriction>\r\n" + 
			"    </xsd:simpleType>\r\n" + 
			"    <xsd:complexType name=\"CustomerCluster\">\r\n" + 
			"        <xsd:annotation>\r\n" + 
			"            <xsd:documentation>Represents a set of customers, grouped togethter in a so called \"Customer Cluster\". Each customer cluster must have one master customer. A customer cluster itself lack's a separated defined identity attribute, it can only be identified by it's members.</xsd:documentation>\r\n" + 
			"        </xsd:annotation>\r\n" + 
			"        <xsd:sequence>\r\n" + 
			"            <xsd:element name=\"MasterCustomer\" type=\"Customer\">\r\n" + 
			"                <xsd:annotation>\r\n" + 
			"                    <xsd:documentation>Denotes the stated customer as the \"Master Customer\" of this customer cluster.</xsd:documentation>\r\n" + 
			"                </xsd:annotation>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"MemberCustomer\" type=\"Customer\">\r\n" + 
			"                <xsd:annotation>\r\n" + 
			"                    <xsd:documentation>Each \"Member Customer\" is member of the customer cluster, but not master.</xsd:documentation>\r\n" + 
			"                </xsd:annotation>\r\n" + 
			"            </xsd:element>\r\n" + 
			"        </xsd:sequence>\r\n" + 
			"    </xsd:complexType>\r\n" + 
			"    <xsd:complexType name=\"AdditionalFieldStringValue\">\r\n" + 
			"        <xsd:attribute default=\"false\" name=\"setToNull\" type=\"xsd:boolean\"/>\r\n" + 
			"        <xsd:attribute name=\"value\" use=\"required\">\r\n" + 
			"            <xsd:simpleType>\r\n" + 
			"                <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                    <xsd:minLength value=\"0\"/>\r\n" + 
			"                    <xsd:maxLength value=\"50\"/>\r\n" + 
			"                </xsd:restriction>\r\n" + 
			"            </xsd:simpleType>\r\n" + 
			"        </xsd:attribute>\r\n" + 
			"    </xsd:complexType>\r\n" + 
			"    <xsd:complexType name=\"AdditionalFieldChoiceValue\">\r\n" + 
			"        <xsd:attribute default=\"false\" name=\"setToNull\" type=\"xsd:boolean\"/>\r\n" + 
			"        <xsd:attribute name=\"value\" use=\"required\">\r\n" + 
			"            <xsd:simpleType>\r\n" + 
			"                <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                    <xsd:minLength value=\"1\"/>\r\n" + 
			"                    <xsd:maxLength value=\"50\"/>\r\n" + 
			"                </xsd:restriction>\r\n" + 
			"            </xsd:simpleType>\r\n" + 
			"        </xsd:attribute>\r\n" + 
			"    </xsd:complexType>\r\n" + 
			"    <xsd:complexType name=\"AdditionalFieldDoubleValue\">\r\n" + 
			"        <xsd:attribute default=\"false\" name=\"setToNull\" type=\"xsd:boolean\">\r\n" + 
			"            <xsd:annotation>\r\n" + 
			"                <xsd:documentation>Please note, that \"setToNull\" on an AdditionalFieldsDoubleValue doesn't acutall set the value to NULL. It sets the value to 0.0.</xsd:documentation>\r\n" + 
			"            </xsd:annotation>\r\n" + 
			"        </xsd:attribute>\r\n" + 
			"        <xsd:attribute name=\"value\" use=\"required\">\r\n" + 
			"            <xsd:annotation>\r\n" + 
			"                <xsd:documentation>Please note, that any double value within an additional field in 4Vending will be rounded to two decimals. To avoid any unpreditcted results, please use only double values with finite precision and a maximum of two decimals.</xsd:documentation>\r\n" + 
			"            </xsd:annotation>\r\n" + 
			"            <xsd:simpleType>\r\n" + 
			"                <xsd:restriction base=\"xsd:double\"/>\r\n" + 
			"            </xsd:simpleType>\r\n" + 
			"        </xsd:attribute>\r\n" + 
			"    </xsd:complexType>\r\n" + 
			"    <xsd:complexType name=\"AdditionalFields\">\r\n" + 
			"        <xsd:annotation>\r\n" + 
			"            <xsd:documentation>This elements defines Additional Fieleds. For instance, Additional Fields can be attached to Customers, Vendingmachins or VirtualVendingmachines.\r\n" + 
			"\r\n" + 
			"Additional fields are comprised by a maximum of 6 different values (Code 1 til Code 6).</xsd:documentation>\r\n" + 
			"        </xsd:annotation>\r\n" + 
			"        <xsd:sequence>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Code1\" type=\"AdditionalFieldStringValue\">\r\n" + 
			"                <xsd:annotation>\r\n" + 
			"                    <xsd:documentation>The field Code1 is an additional field which can be sticked to several application objects. For instance, Additional Fields can be attached to Customers, Vendingmachins or VirtualVendingmachines.\r\n" + 
			"\r\n" + 
			"Code 1 is a String with a maximum length of 50 characters. It is freely editable by the user.\r\n" + 
			"\r\n" + 
			"If the attribute \"setToNull\" is set to true, then the value will be ignored (although it must be stated) and the value in the database will be set to what is known as NULL (=the empty value).</xsd:documentation>\r\n" + 
			"                </xsd:annotation>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Code2\" type=\"AdditionalFieldStringValue\">\r\n" + 
			"                <xsd:annotation>\r\n" + 
			"                    <xsd:documentation>The field Code2 is an additional field which can be sticked to several application objects. For instance, Additional Fields can be attached to Customers, Vendingmachins or VirtualVendingmachines.\r\n" + 
			"\r\n" + 
			"Code 2 is a String with a maximum length of 50 characters. It is freely editable by the user.\r\n" + 
			"\r\n" + 
			"If the attribute \"setToNull\" is set to true, then the value will be ignored (although it must be stated) and the value in the database will be set to what is known as NULL (=the empty value).</xsd:documentation>\r\n" + 
			"                </xsd:annotation>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Code3\" type=\"AdditionalFieldChoiceValue\">\r\n" + 
			"                <xsd:annotation>\r\n" + 
			"                    <xsd:documentation>The field Code3 is an additional field which can be sticked to several application objects. For instance, Additional Fields can be attached to Customers, Vendingmachins or VirtualVendingmachines.\r\n" + 
			"\r\n" + 
			"Code 3 is represented to the user as a value of a select box. These values are maintained centrally and are strings with a maximum length of 50 characters.\r\n" + 
			"\r\n" + 
			"If the attribute \"setToNull\" is set to true, then the value will be ignored (although it must be stated) and the value in the database will be set to what is known as NULL (=the empty value).</xsd:documentation>\r\n" + 
			"                </xsd:annotation>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Code4\" type=\"AdditionalFieldChoiceValue\">\r\n" + 
			"                <xsd:annotation>\r\n" + 
			"                    <xsd:documentation>The field Code4 is an additional field which can be sticked to several application objects. For instance, Additional Fields can be attached to Customers, Vendingmachins or VirtualVendingmachines.\r\n" + 
			"\r\n" + 
			"Code 4 is represented to the user as a value of a select box. These values are maintained centrally and are strings with a maximum length of 50 characters.\r\n" + 
			"\r\n" + 
			"If the attribute \"setToNull\" is set to true, then the value will be ignored (although it must be stated) and the value in the database will be set to what is known as NULL (=the empty value).</xsd:documentation>\r\n" + 
			"                </xsd:annotation>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Code5\" type=\"AdditionalFieldDoubleValue\">\r\n" + 
			"                <xsd:annotation>\r\n" + 
			"                    <xsd:documentation>The field Code5 is an additional field which can be sticked to several application objects. For instance, Additional Fields can be attached to Customers, Vendingmachins or VirtualVendingmachines.\r\n" + 
			"\r\n" + 
			"Code 5 is a double value. It is freely and directly editable by the user.\r\n" + 
			"\r\n" + 
			"If the attribute \"setToNull\" is set to true, then the value will be ignored (although it must be stated) and the value in the database will be set to what is known as NULL (=the empty value).</xsd:documentation>\r\n" + 
			"                </xsd:annotation>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"Code6\" type=\"AdditionalFieldDoubleValue\">\r\n" + 
			"                <xsd:annotation>\r\n" + 
			"                    <xsd:documentation>The field Code6 is an additional field which can be sticked to several application objects. For instance, Additional Fields can be attached to Customers, Vendingmachins or VirtualVendingmachines.\r\n" + 
			"\r\n" + 
			"Code 6 is a double value. It is freely and directly editable by the user.\r\n" + 
			"\r\n" + 
			"If the attribute \"setToNull\" is set to true, then the value will be ignored (although it must be stated) and the value in the database will be set to what is known as NULL (=the empty value).</xsd:documentation>\r\n" + 
			"                </xsd:annotation>\r\n" + 
			"            </xsd:element>\r\n" + 
			"        </xsd:sequence>\r\n" + 
			"    </xsd:complexType>\r\n" + 
			"    <xsd:simpleType name=\"UpdateMode\">\r\n" + 
			"        <xsd:annotation>\r\n" + 
			"            <xsd:documentation>The UpdateMode specifies the behaviour of the Sales Price List Update. See values for details</xsd:documentation>\r\n" + 
			"        </xsd:annotation>\r\n" + 
			"        <xsd:restriction base=\"xsd:string\">\r\n" + 
			"            <xsd:enumeration value=\"REPLACE\">\r\n" + 
			"                <xsd:annotation>\r\n" + 
			"                    <xsd:documentation>\"REPLACE\"-Mode deletes all existing Sales Price List entries from the database and writes all stated new values into the database.</xsd:documentation>\r\n" + 
			"                </xsd:annotation>\r\n" + 
			"            </xsd:enumeration>\r\n" + 
			"            <xsd:enumeration value=\"ADD_OR_UPDATE\">\r\n" + 
			"                <xsd:annotation>\r\n" + 
			"                    <xsd:documentation>\"UPDATE\"-Mode doesn't modify the existing Sales Price List entries in the database and add or updates all stated in the database.\r\n" + 
			"\r\n" + 
			"Update means, that for existing Sales Prices the sales Price and Price Lines are updated.</xsd:documentation>\r\n" + 
			"                </xsd:annotation>\r\n" + 
			"            </xsd:enumeration>\r\n" + 
			"        </xsd:restriction>\r\n" + 
			"    </xsd:simpleType>\r\n" + 
			"    <xsd:complexType name=\"SalesPrice\">\r\n" + 
			"        <xsd:annotation>\r\n" + 
			"            <xsd:documentation>SalesPrice defines a sales price for exactly one article, the article has to be denominated either by it's ERPCode, Base- or SalesArticleNumber. Furthermore the value of the sales price can be specified, if not the price is taken from the default sales price from the article list. Additionaly an arbitrary count of PriceLines can be specified.</xsd:documentation>\r\n" + 
			"        </xsd:annotation>\r\n" + 
			"        <xsd:sequence>\r\n" + 
			"            <xsd:choice>\r\n" + 
			"                <xsd:annotation>\r\n" + 
			"                    <xsd:documentation>The element choosen is used to reference the article for the salesprice</xsd:documentation>\r\n" + 
			"                </xsd:annotation>\r\n" + 
			"                <xsd:element name=\"ERPCode\">\r\n" + 
			"                    <xsd:simpleType>\r\n" + 
			"                        <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                            <xsd:minLength value=\"1\"/>\r\n" + 
			"                            <xsd:maxLength value=\"50\"/>\r\n" + 
			"                        </xsd:restriction>\r\n" + 
			"                    </xsd:simpleType>\r\n" + 
			"                </xsd:element>\r\n" + 
			"                <xsd:element name=\"SalesProductID\">\r\n" + 
			"                    <xsd:simpleType>\r\n" + 
			"                        <xsd:restriction base=\"xsd:int\">\r\n" + 
			"                            <xsd:minInclusive value=\"1\"/>\r\n" + 
			"                            <xsd:maxInclusive value=\"2147483646\"/>\r\n" + 
			"                        </xsd:restriction>\r\n" + 
			"                    </xsd:simpleType>\r\n" + 
			"                </xsd:element>\r\n" + 
			"                <xsd:element name=\"BaseProductID\">\r\n" + 
			"                    <xsd:simpleType>\r\n" + 
			"                        <xsd:restriction base=\"xsd:int\">\r\n" + 
			"                            <xsd:minInclusive value=\"0\"/>\r\n" + 
			"                            <xsd:maxInclusive value=\"2147483646\"/>\r\n" + 
			"                        </xsd:restriction>\r\n" + 
			"                    </xsd:simpleType>\r\n" + 
			"                </xsd:element>\r\n" + 
			"            </xsd:choice>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"SalesPriceValue\">\r\n" + 
			"                <xsd:annotation>\r\n" + 
			"                    <xsd:documentation>The desired sales price value. If omitted, the sales price is taken from the article list's default sales price.</xsd:documentation>\r\n" + 
			"                </xsd:annotation>\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:double\">\r\n" + 
			"                        <xsd:minInclusive value=\"0\"/>\r\n" + 
			"                        <xsd:maxInclusive value=\"1999999\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:element minOccurs=\"0\" name=\"PriceLines\" type=\"PriceLines\"/>\r\n" + 
			"        </xsd:sequence>\r\n" + 
			"    </xsd:complexType>\r\n" + 
			"    <xsd:simpleType name=\"PriceLine\">\r\n" + 
			"        <xsd:restriction base=\"xsd:int\">\r\n" + 
			"            <xsd:minInclusive value=\"0\"/>\r\n" + 
			"            <xsd:maxInclusive value=\"999999\"/>\r\n" + 
			"        </xsd:restriction>\r\n" + 
			"    </xsd:simpleType>\r\n" + 
			"    <xsd:complexType name=\"PriceLines\">\r\n" + 
			"        <xsd:sequence>\r\n" + 
			"            <xsd:element maxOccurs=\"unbounded\" minOccurs=\"1\" name=\"PriceLine\" type=\"PriceLine\"/>\r\n" + 
			"        </xsd:sequence>\r\n" + 
			"    </xsd:complexType>\r\n" + 
			"    <xsd:simpleType name=\"PriceLineUpdateMode\">\r\n" + 
			"        <xsd:restriction base=\"xsd:string\">\r\n" + 
			"            <xsd:enumeration value=\"REPLACE\"/>\r\n" + 
			"            <xsd:enumeration value=\"ADD\"/>\r\n" + 
			"        </xsd:restriction>\r\n" + 
			"    </xsd:simpleType>\r\n" + 
			"    <xsd:complexType name=\"SalesPriceList\">\r\n" + 
			"        <xsd:sequence>\r\n" + 
			"            <xsd:element maxOccurs=\"unbounded\" name=\"SalesPrice\" type=\"SalesPrice\"/>\r\n" + 
			"        </xsd:sequence>\r\n" + 
			"        <xsd:attribute name=\"updateMode\" type=\"UpdateMode\" use=\"required\"/>\r\n" + 
			"        <xsd:attribute default=\"ADD\" name=\"priceLineUpdateMode\" type=\"PriceLineUpdateMode\"/>\r\n" + 
			"    </xsd:complexType>\r\n" + 
			"    <xsd:simpleType name=\"AutoGenerateId\">\r\n" + 
			"        <xsd:restriction base=\"xsd:string\">\r\n" + 
			"            <xsd:enumeration value=\"true\"/>\r\n" + 
			"        </xsd:restriction>\r\n" + 
			"    </xsd:simpleType>\r\n" + 
			"    <xsd:simpleType name=\"UpdateLegacyIdNull\">\r\n" + 
			"        <xsd:restriction base=\"xsd:string\">\r\n" + 
			"            <xsd:enumeration value=\"NULL\"/>\r\n" + 
			"        </xsd:restriction>\r\n" + 
			"    </xsd:simpleType>\r\n" + 
			"    <xsd:complexType name=\"UpdateLegacyId\">\r\n" + 
			"        <xsd:annotation>\r\n" + 
			"            <xsd:documentation>This element acts as a command for updating VVM LegacyId values prior to all other import actions.</xsd:documentation>\r\n" + 
			"        </xsd:annotation>\r\n" + 
			"        <xsd:sequence>\r\n" + 
			"            <xsd:element name=\"OldValue\">\r\n" + 
			"                <xsd:annotation>\r\n" + 
			"                    <xsd:documentation>The old value used to identify the VirtualVendingmachine</xsd:documentation>\r\n" + 
			"                </xsd:annotation>\r\n" + 
			"                <xsd:simpleType>\r\n" + 
			"                    <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                        <xsd:minLength value=\"1\"/>\r\n" + 
			"                        <xsd:maxLength value=\"255\"/>\r\n" + 
			"                    </xsd:restriction>\r\n" + 
			"                </xsd:simpleType>\r\n" + 
			"            </xsd:element>\r\n" + 
			"            <xsd:choice>\r\n" + 
			"                <xsd:element minOccurs=\"1\" name=\"newValue\">\r\n" + 
			"                    <xsd:annotation>\r\n" + 
			"                        <xsd:documentation>The new value ought to be set.</xsd:documentation>\r\n" + 
			"                    </xsd:annotation>\r\n" + 
			"                    <xsd:simpleType>\r\n" + 
			"                        <xsd:restriction base=\"xsd:string\">\r\n" + 
			"                            <xsd:minLength value=\"1\"/>\r\n" + 
			"                            <xsd:maxLength value=\"255\"/>\r\n" + 
			"                        </xsd:restriction>\r\n" + 
			"                    </xsd:simpleType>\r\n" + 
			"                </xsd:element>\r\n" + 
			"                <xsd:element name=\"newValueNull\" type=\"UpdateLegacyIdNull\">\r\n" + 
			"                    <xsd:annotation>\r\n" + 
			"                        <xsd:documentation>If this element is present, the new value will be NULL</xsd:documentation>\r\n" + 
			"                    </xsd:annotation>\r\n" + 
			"                </xsd:element>\r\n" + 
			"            </xsd:choice>\r\n" + 
			"        </xsd:sequence>\r\n" + 
			"    </xsd:complexType>\r\n" + 
			"</xsd:schema>\r\n" + 
			"";
	
	public VendidataCustomersMarshaller() throws JAXBException {
		super();
	}

	public String marshal(XMLCustomers xmlCustomers) throws JAXBException, SAXException {
		getMarshaller().setProperty(Marshaller.JAXB_SCHEMA_LOCATION, 
				"http://www.vendidata.com/XML/Schema/Customers http://www.vendidata.com/XML/Schema/Customers/customers.xsd");
		ObjectFactory objectFactory = new ObjectFactory();
		return marshal(xsdCustomers, objectFactory.createCustomers(xmlCustomers));
	}

	@Override
	protected Class<XMLCustomers> getClazz() {
		return XMLCustomers.class;
	}
}
