/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2015 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
package com.lp.server.finanz.bl.sepa;

import javax.xml.bind.JAXBException;

import org.xml.sax.SAXException;

import com.lp.server.schema.iso20022.camt053V02.CADocument;

public class SepaXmlUnmarshallerCamt053V02 extends SepaXmlUnmarshaller {

	private String V02part1 = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\r\n" + 
			"<!--Generated by SWIFTStandards Workstation (build:R6.1.0.2) on 2009 Jan 08 17:30:53-->\r\n" + 
			"<xs:schema xmlns=\"urn:iso:std:iso:20022:tech:xsd:camt.053.001.02\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" elementFormDefault=\"qualified\" targetNamespace=\"urn:iso:std:iso:20022:tech:xsd:camt.053.001.02\">\r\n" + 
			"    <xs:element name=\"Document\" type=\"Document\"/>\r\n" + 
			"    <xs:complexType name=\"AccountIdentification4Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"IBAN\" type=\"IBAN2007Identifier\"/>\r\n" + 
			"                <xs:element name=\"Othr\" type=\"GenericAccountIdentification1\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"AccountInterest2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tp\" type=\"InterestType1Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Rate\" type=\"Rate3\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"FrToDt\" type=\"DateTimePeriodDetails\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Rsn\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"AccountSchemeName1Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Cd\" type=\"ExternalAccountIdentification1Code\"/>\r\n" + 
			"                <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"AccountStatement2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Id\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ElctrncSeqNb\" type=\"Number\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"LglSeqNb\" type=\"Number\"/>\r\n" + 
			"            <xs:element name=\"CreDtTm\" type=\"ISODateTime\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"FrToDt\" type=\"DateTimePeriodDetails\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CpyDplctInd\" type=\"CopyDuplicate1Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RptgSrc\" type=\"ReportingSource1Choice\"/>\r\n" + 
			"            <xs:element name=\"Acct\" type=\"CashAccount20\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RltdAcct\" type=\"CashAccount16\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Intrst\" type=\"AccountInterest2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"1\" name=\"Bal\" type=\"CashBalance3\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TxsSummry\" type=\"TotalTransactions2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Ntry\" type=\"ReportEntry2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AddtlStmtInf\" type=\"Max500Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"ActiveOrHistoricCurrencyAndAmount_SimpleType\">\r\n" + 
			"        <xs:restriction base=\"xs:decimal\">\r\n" + 
			"            <xs:minInclusive value=\"0\"/>\r\n" + 
			"            <xs:fractionDigits value=\"5\"/>\r\n" + 
			"            <xs:totalDigits value=\"18\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"ActiveOrHistoricCurrencyAndAmount\">\r\n" + 
			"        <xs:simpleContent>\r\n" + 
			"            <xs:extension base=\"ActiveOrHistoricCurrencyAndAmount_SimpleType\">\r\n" + 
			"                <xs:attribute name=\"Ccy\" type=\"ActiveOrHistoricCurrencyCode\" use=\"required\"/>\r\n" + 
			"            </xs:extension>\r\n" + 
			"        </xs:simpleContent>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"ActiveOrHistoricCurrencyCode\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:pattern value=\"[A-Z]{3,3}\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"AddressType2Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"ADDR\"/>\r\n" + 
			"            <xs:enumeration value=\"PBOX\"/>\r\n" + 
			"            <xs:enumeration value=\"HOME\"/>\r\n" + 
			"            <xs:enumeration value=\"BIZZ\"/>\r\n" + 
			"            <xs:enumeration value=\"MLTO\"/>\r\n" + 
			"            <xs:enumeration value=\"DLVY\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"AlternateSecurityIdentification2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Tp\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element name=\"Id\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"AmountAndCurrencyExchange3\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"InstdAmt\" type=\"AmountAndCurrencyExchangeDetails3\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TxAmt\" type=\"AmountAndCurrencyExchangeDetails3\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CntrValAmt\" type=\"AmountAndCurrencyExchangeDetails3\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AnncdPstngAmt\" type=\"AmountAndCurrencyExchangeDetails3\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"PrtryAmt\" type=\"AmountAndCurrencyExchangeDetails4\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"AmountAndCurrencyExchangeDetails3\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Amt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CcyXchg\" type=\"CurrencyExchange5\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"AmountAndCurrencyExchangeDetails4\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Tp\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element name=\"Amt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CcyXchg\" type=\"CurrencyExchange5\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"AmountRangeBoundary1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"BdryAmt\" type=\"ImpliedCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element name=\"Incl\" type=\"YesNoIndicator\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"AnyBICIdentifier\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:pattern value=\"[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"BICIdentifier\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:pattern value=\"[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"BalanceSubType1Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Cd\" type=\"ExternalBalanceSubType1Code\"/>\r\n" + 
			"                <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"BalanceType12\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"CdOrPrtry\" type=\"BalanceType5Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SubTp\" type=\"BalanceSubType1Choice\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"BalanceType12Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"XPCD\"/>\r\n" + 
			"            <xs:enumeration value=\"OPAV\"/>\r\n" + 
			"            <xs:enumeration value=\"ITAV\"/>\r\n" + 
			"            <xs:enumeration value=\"CLAV\"/>\r\n" + 
			"            <xs:enumeration value=\"FWAV\"/>\r\n" + 
			"            <xs:enumeration value=\"CLBD\"/>\r\n" + 
			"            <xs:enumeration value=\"ITBD\"/>\r\n" + 
			"            <xs:enumeration value=\"OPBD\"/>\r\n" + 
			"            <xs:enumeration value=\"PRCD\"/>\r\n" + 
			"            <xs:enumeration value=\"INFO\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"BalanceType5Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Cd\" type=\"BalanceType12Code\"/>\r\n" + 
			"                <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"BankToCustomerStatementV02\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"GrpHdr\" type=\"GroupHeader42\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"1\" name=\"Stmt\" type=\"AccountStatement2\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"BankTransactionCodeStructure4\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Domn\" type=\"BankTransactionCodeStructure5\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Prtry\" type=\"ProprietaryBankTransactionCodeStructure1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"BankTransactionCodeStructure5\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"ExternalBankTransactionDomain1Code\"/>\r\n" + 
			"            <xs:element name=\"Fmly\" type=\"BankTransactionCodeStructure6\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"BankTransactionCodeStructure6\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"ExternalBankTransactionFamily1Code\"/>\r\n" + 
			"            <xs:element name=\"SubFmlyCd\" type=\"ExternalBankTransactionSubFamily1Code\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"BaseOneRate\">\r\n" + 
			"        <xs:restriction base=\"xs:decimal\">\r\n" + 
			"            <xs:fractionDigits value=\"10\"/>\r\n" + 
			"            <xs:totalDigits value=\"11\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"BatchInformation2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"MsgId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PmtInfId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"NbOfTxs\" type=\"Max15NumericText\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TtlAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CdtDbtInd\" type=\"CreditDebitCode\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"BranchAndFinancialInstitutionIdentification4\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"FinInstnId\" type=\"FinancialInstitutionIdentification7\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"BrnchId\" type=\"BranchData2\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"BranchData2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Id\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Nm\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PstlAdr\" type=\"PostalAddress6\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"CashAccount16\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Id\" type=\"AccountIdentification4Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tp\" type=\"CashAccountType2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Ccy\" type=\"ActiveOrHistoricCurrencyCode\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Nm\" type=\"Max70Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"CashAccount20\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Id\" type=\"AccountIdentification4Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tp\" type=\"CashAccountType2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Ccy\" type=\"ActiveOrHistoricCurrencyCode\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Nm\" type=\"Max70Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Ownr\" type=\"PartyIdentification32\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Svcr\" type=\"BranchAndFinancialInstitutionIdentification4\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"CashAccountType2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Cd\" type=\"CashAccountType4Code\"/>\r\n" + 
			"                <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"CashAccountType4Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"CASH\"/>\r\n" + 
			"            <xs:enumeration value=\"CHAR\"/>\r\n" + 
			"            <xs:enumeration value=\"COMM\"/>\r\n" + 
			"            <xs:enumeration value=\"TAXE\"/>\r\n" + 
			"            <xs:enumeration value=\"CISH\"/>\r\n" + 
			"            <xs:enumeration value=\"TRAS\"/>\r\n" + 
			"            <xs:enumeration value=\"SACC\"/>\r\n" + 
			"            <xs:enumeration value=\"CACC\"/>\r\n" + 
			"            <xs:enumeration value=\"SVGS\"/>\r\n" + 
			"            <xs:enumeration value=\"ONDP\"/>\r\n" + 
			"            <xs:enumeration value=\"MGLD\"/>\r\n" + 
			"            <xs:enumeration value=\"NREX\"/>\r\n" + 
			"            <xs:enumeration value=\"MOMA\"/>\r\n" + 
			"            <xs:enumeration value=\"LOAN\"/>\r\n" + 
			"            <xs:enumeration value=\"SLRY\"/>\r\n" + 
			"            <xs:enumeration value=\"ODFT\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"CashBalance3\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Tp\" type=\"BalanceType12\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CdtLine\" type=\"CreditLine2\"/>\r\n" + 
			"            <xs:element name=\"Amt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element name=\"CdtDbtInd\" type=\"CreditDebitCode\"/>\r\n" + 
			"            <xs:element name=\"Dt\" type=\"DateAndDateTimeChoice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Avlbty\" type=\"CashBalanceAvailability2\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"CashBalanceAvailability2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Dt\" type=\"CashBalanceAvailabilityDate1\"/>\r\n" + 
			"            <xs:element name=\"Amt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element name=\"CdtDbtInd\" type=\"CreditDebitCode\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"CashBalanceAvailabilityDate1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"NbOfDays\" type=\"Max15PlusSignedNumericText\"/>\r\n" + 
			"                <xs:element name=\"ActlDt\" type=\"ISODate\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"ChargeBearerType1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"DEBT\"/>\r\n" + 
			"            <xs:enumeration value=\"CRED\"/>\r\n" + 
			"            <xs:enumeration value=\"SHAR\"/>\r\n" + 
			"            <xs:enumeration value=\"SLEV\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ChargeType1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"BRKF\"/>\r\n" + 
			"            <xs:enumeration value=\"COMM\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"ChargeType2Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Cd\" type=\"ChargeType1Code\"/>\r\n" + 
			"                <xs:element name=\"Prtry\" type=\"GenericIdentification3\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ChargesInformation6\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TtlChrgsAndTaxAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element name=\"Amt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CdtDbtInd\" type=\"CreditDebitCode\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tp\" type=\"ChargeType2Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Rate\" type=\"PercentageRate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Br\" type=\"ChargeBearerType1Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Pty\" type=\"BranchAndFinancialInstitutionIdentification4\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tax\" type=\"TaxCharges2\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ClearingSystemIdentification2Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Cd\" type=\"ExternalClearingSystemIdentification1Code\"/>\r\n" + 
			"                <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n";
	private String V02part2 = 
			"    <xs:complexType name=\"ClearingSystemMemberIdentification2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ClrSysId\" type=\"ClearingSystemIdentification2Choice\"/>\r\n" + 
			"            <xs:element name=\"MmbId\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ContactDetails2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"NmPrfx\" type=\"NamePrefix1Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Nm\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PhneNb\" type=\"PhoneNumber\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"MobNb\" type=\"PhoneNumber\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"FaxNb\" type=\"PhoneNumber\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"EmailAdr\" type=\"Max2048Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Othr\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"CopyDuplicate1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"CODU\"/>\r\n" + 
			"            <xs:enumeration value=\"COPY\"/>\r\n" + 
			"            <xs:enumeration value=\"DUPL\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"CorporateAction1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Cd\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Nb\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"CountryCode\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:pattern value=\"[A-Z]{2,2}\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"CreditDebitCode\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"CRDT\"/>\r\n" + 
			"            <xs:enumeration value=\"DBIT\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"CreditLine2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Incl\" type=\"TrueFalseIndicator\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Amt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"CreditorReferenceInformation2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tp\" type=\"CreditorReferenceType2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Ref\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"CreditorReferenceType1Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Cd\" type=\"DocumentType3Code\"/>\r\n" + 
			"                <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"CreditorReferenceType2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"CdOrPrtry\" type=\"CreditorReferenceType1Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Issr\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"CurrencyAndAmountRange2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Amt\" type=\"ImpliedCurrencyAmountRangeChoice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CdtDbtInd\" type=\"CreditDebitCode\"/>\r\n" + 
			"            <xs:element name=\"Ccy\" type=\"ActiveOrHistoricCurrencyCode\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"CurrencyExchange5\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"SrcCcy\" type=\"ActiveOrHistoricCurrencyCode\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TrgtCcy\" type=\"ActiveOrHistoricCurrencyCode\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"UnitCcy\" type=\"ActiveOrHistoricCurrencyCode\"/>\r\n" + 
			"            <xs:element name=\"XchgRate\" type=\"BaseOneRate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CtrctId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"QtnDt\" type=\"ISODateTime\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"DateAndDateTimeChoice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Dt\" type=\"ISODate\"/>\r\n" + 
			"                <xs:element name=\"DtTm\" type=\"ISODateTime\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"DateAndPlaceOfBirth\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"BirthDt\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PrvcOfBirth\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element name=\"CityOfBirth\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element name=\"CtryOfBirth\" type=\"CountryCode\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"DatePeriodDetails\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"FrDt\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element name=\"ToDt\" type=\"ISODate\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"DateTimePeriodDetails\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"FrDtTm\" type=\"ISODateTime\"/>\r\n" + 
			"            <xs:element name=\"ToDtTm\" type=\"ISODateTime\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"DecimalNumber\">\r\n" + 
			"        <xs:restriction base=\"xs:decimal\">\r\n" + 
			"            <xs:fractionDigits value=\"17\"/>\r\n" + 
			"            <xs:totalDigits value=\"18\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"Document\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"BkToCstmrStmt\" type=\"BankToCustomerStatementV02\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"DocumentAdjustment1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Amt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CdtDbtInd\" type=\"CreditDebitCode\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Rsn\" type=\"Max4Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AddtlInf\" type=\"Max140Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"DocumentType3Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"RADM\"/>\r\n" + 
			"            <xs:enumeration value=\"RPIN\"/>\r\n" + 
			"            <xs:enumeration value=\"FXDR\"/>\r\n" + 
			"            <xs:enumeration value=\"DISP\"/>\r\n" + 
			"            <xs:enumeration value=\"PUOR\"/>\r\n" + 
			"            <xs:enumeration value=\"SCOR\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"DocumentType5Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"MSIN\"/>\r\n" + 
			"            <xs:enumeration value=\"CNFA\"/>\r\n" + 
			"            <xs:enumeration value=\"DNFA\"/>\r\n" + 
			"            <xs:enumeration value=\"CINV\"/>\r\n" + 
			"            <xs:enumeration value=\"CREN\"/>\r\n" + 
			"            <xs:enumeration value=\"DEBN\"/>\r\n" + 
			"            <xs:enumeration value=\"HIRI\"/>\r\n" + 
			"            <xs:enumeration value=\"SBIN\"/>\r\n" + 
			"            <xs:enumeration value=\"CMCN\"/>\r\n" + 
			"            <xs:enumeration value=\"SOAC\"/>\r\n" + 
			"            <xs:enumeration value=\"DISP\"/>\r\n" + 
			"            <xs:enumeration value=\"BOLD\"/>\r\n" + 
			"            <xs:enumeration value=\"VCHR\"/>\r\n" + 
			"            <xs:enumeration value=\"AROI\"/>\r\n" + 
			"            <xs:enumeration value=\"TSUT\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"EntryDetails1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Btch\" type=\"BatchInformation2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"TxDtls\" type=\"EntryTransaction2\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"EntryStatus2Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"BOOK\"/>\r\n" + 
			"            <xs:enumeration value=\"PDNG\"/>\r\n" + 
			"            <xs:enumeration value=\"INFO\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"EntryTransaction2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Refs\" type=\"TransactionReferences2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AmtDtls\" type=\"AmountAndCurrencyExchange3\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Avlbty\" type=\"CashBalanceAvailability2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"BkTxCd\" type=\"BankTransactionCodeStructure4\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Chrgs\" type=\"ChargesInformation6\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Intrst\" type=\"TransactionInterest2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RltdPties\" type=\"TransactionParty2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RltdAgts\" type=\"TransactionAgents2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Purp\" type=\"Purpose2Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"10\" minOccurs=\"0\" name=\"RltdRmtInf\" type=\"RemittanceLocation2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RmtInf\" type=\"RemittanceInformation5\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RltdDts\" type=\"TransactionDates2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RltdPric\" type=\"TransactionPrice2Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"RltdQties\" type=\"TransactionQuantities1Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"FinInstrmId\" type=\"SecurityIdentification4Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tax\" type=\"TaxInformation3\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RtrInf\" type=\"ReturnReasonInformation10\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CorpActn\" type=\"CorporateAction1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SfkpgAcct\" type=\"CashAccount16\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AddtlTxInf\" type=\"Max500Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"ExternalAccountIdentification1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalBalanceSubType1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalBankTransactionDomain1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalBankTransactionFamily1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalBankTransactionSubFamily1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalClearingSystemIdentification1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"5\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalFinancialInstitutionIdentification1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalOrganisationIdentification1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalPersonIdentification1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalPurpose1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalReportingSource1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalReturnReason1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ExternalTechnicalInputChannel1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"FinancialIdentificationSchemeName1Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Cd\" type=\"ExternalFinancialInstitutionIdentification1Code\"/>\r\n" + 
			"                <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"FinancialInstitutionIdentification7\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"BIC\" type=\"BICIdentifier\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ClrSysMmbId\" type=\"ClearingSystemMemberIdentification2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Nm\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PstlAdr\" type=\"PostalAddress6\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Othr\" type=\"GenericFinancialIdentification1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"FinancialInstrumentQuantityChoice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Unit\" type=\"DecimalNumber\"/>\r\n" + 
			"                <xs:element name=\"FaceAmt\" type=\"ImpliedCurrencyAndAmount\"/>\r\n" + 
			"                <xs:element name=\"AmtsdVal\" type=\"ImpliedCurrencyAndAmount\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"FromToAmountRange\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"FrAmt\" type=\"AmountRangeBoundary1\"/>\r\n" + 
			"            <xs:element name=\"ToAmt\" type=\"AmountRangeBoundary1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"GenericAccountIdentification1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Id\" type=\"Max34Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SchmeNm\" type=\"AccountSchemeName1Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Issr\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"GenericFinancialIdentification1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Id\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SchmeNm\" type=\"FinancialIdentificationSchemeName1Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Issr\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"GenericIdentification3\">\r\n";
	private String V02part3 = 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Id\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Issr\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"GenericOrganisationIdentification1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Id\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SchmeNm\" type=\"OrganisationIdentificationSchemeName1Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Issr\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"GenericPersonIdentification1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Id\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SchmeNm\" type=\"PersonIdentificationSchemeName1Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Issr\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"GroupHeader42\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"MsgId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element name=\"CreDtTm\" type=\"ISODateTime\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"MsgRcpt\" type=\"PartyIdentification32\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"MsgPgntn\" type=\"Pagination\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AddtlInf\" type=\"Max500Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"IBAN2007Identifier\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:pattern value=\"[A-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ISINIdentifier\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:pattern value=\"[A-Z0-9]{12,12}\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ISODate\">\r\n" + 
			"        <xs:restriction base=\"xs:date\"/>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"ISODateTime\">\r\n" + 
			"        <xs:restriction base=\"xs:dateTime\"/>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"ImpliedCurrencyAmountRangeChoice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"FrAmt\" type=\"AmountRangeBoundary1\"/>\r\n" + 
			"                <xs:element name=\"ToAmt\" type=\"AmountRangeBoundary1\"/>\r\n" + 
			"                <xs:element name=\"FrToAmt\" type=\"FromToAmountRange\"/>\r\n" + 
			"                <xs:element name=\"EQAmt\" type=\"ImpliedCurrencyAndAmount\"/>\r\n" + 
			"                <xs:element name=\"NEQAmt\" type=\"ImpliedCurrencyAndAmount\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"ImpliedCurrencyAndAmount\">\r\n" + 
			"        <xs:restriction base=\"xs:decimal\">\r\n" + 
			"            <xs:minInclusive value=\"0\"/>\r\n" + 
			"            <xs:fractionDigits value=\"5\"/>\r\n" + 
			"            <xs:totalDigits value=\"18\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"InterestType1Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Cd\" type=\"InterestType1Code\"/>\r\n" + 
			"                <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"InterestType1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"INDY\"/>\r\n" + 
			"            <xs:enumeration value=\"OVRN\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max105Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"105\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max140Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"140\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max15NumericText\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:pattern value=\"[0-9]{1,15}\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max15PlusSignedNumericText\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:pattern value=\"[+]{0,1}[0-9]{1,15}\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max16Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"16\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max2048Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"2048\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max34Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"34\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max35Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"35\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max4Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"4\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max500Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"500\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max5NumericText\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:pattern value=\"[0-9]{1,5}\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Max70Text\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:minLength value=\"1\"/>\r\n" + 
			"            <xs:maxLength value=\"70\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"MessageIdentification2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"MsgNmId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"MsgId\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"NameAndAddress10\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Nm\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element name=\"Adr\" type=\"PostalAddress6\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"NamePrefix1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"DOCT\"/>\r\n" + 
			"            <xs:enumeration value=\"MIST\"/>\r\n" + 
			"            <xs:enumeration value=\"MISS\"/>\r\n" + 
			"            <xs:enumeration value=\"MADM\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"Number\">\r\n" + 
			"        <xs:restriction base=\"xs:decimal\">\r\n" + 
			"            <xs:fractionDigits value=\"0\"/>\r\n" + 
			"            <xs:totalDigits value=\"18\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"NumberAndSumOfTransactions1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"NbOfNtries\" type=\"Max15NumericText\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Sum\" type=\"DecimalNumber\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"NumberAndSumOfTransactions2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"NbOfNtries\" type=\"Max15NumericText\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Sum\" type=\"DecimalNumber\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TtlNetNtryAmt\" type=\"DecimalNumber\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CdtDbtInd\" type=\"CreditDebitCode\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"OrganisationIdentification4\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"BICOrBEI\" type=\"AnyBICIdentifier\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Othr\" type=\"GenericOrganisationIdentification1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"OrganisationIdentificationSchemeName1Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Cd\" type=\"ExternalOrganisationIdentification1Code\"/>\r\n" + 
			"                <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"Pagination\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"PgNb\" type=\"Max5NumericText\"/>\r\n" + 
			"            <xs:element name=\"LastPgInd\" type=\"YesNoIndicator\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"Party6Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"OrgId\" type=\"OrganisationIdentification4\"/>\r\n" + 
			"                <xs:element name=\"PrvtId\" type=\"PersonIdentification5\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"PartyIdentification32\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Nm\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PstlAdr\" type=\"PostalAddress6\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Id\" type=\"Party6Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CtryOfRes\" type=\"CountryCode\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CtctDtls\" type=\"ContactDetails2\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"PercentageRate\">\r\n" + 
			"        <xs:restriction base=\"xs:decimal\">\r\n" + 
			"            <xs:fractionDigits value=\"10\"/>\r\n" + 
			"            <xs:totalDigits value=\"11\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"PersonIdentification5\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"DtAndPlcOfBirth\" type=\"DateAndPlaceOfBirth\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Othr\" type=\"GenericPersonIdentification1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"PersonIdentificationSchemeName1Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Cd\" type=\"ExternalPersonIdentification1Code\"/>\r\n" + 
			"                <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"PhoneNumber\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:pattern value=\"\\+[0-9]{1,3}-[0-9()+\\-]{1,30}\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"PostalAddress6\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AdrTp\" type=\"AddressType2Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Dept\" type=\"Max70Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SubDept\" type=\"Max70Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"StrtNm\" type=\"Max70Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"BldgNb\" type=\"Max16Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PstCd\" type=\"Max16Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TwnNm\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CtrySubDvsn\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Ctry\" type=\"CountryCode\"/>\r\n" + 
			"            <xs:element maxOccurs=\"7\" minOccurs=\"0\" name=\"AdrLine\" type=\"Max70Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ProprietaryAgent2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Tp\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element name=\"Agt\" type=\"BranchAndFinancialInstitutionIdentification4\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ProprietaryBankTransactionCodeStructure1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Cd\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Issr\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ProprietaryDate2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Tp\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element name=\"Dt\" type=\"DateAndDateTimeChoice\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ProprietaryParty2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Tp\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element name=\"Pty\" type=\"PartyIdentification32\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ProprietaryPrice2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Tp\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element name=\"Pric\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ProprietaryQuantity1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Tp\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element name=\"Qty\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ProprietaryReference1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Tp\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element name=\"Ref\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"Purpose2Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Cd\" type=\"ExternalPurpose1Code\"/>\r\n" + 
			"                <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"Rate3\">\r\n" + 
			"        <xs:sequence>\r\n";
	private String V02part4 = 
			"            <xs:element name=\"Tp\" type=\"RateType4Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"VldtyRg\" type=\"CurrencyAndAmountRange2\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"RateType4Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Pctg\" type=\"PercentageRate\"/>\r\n" + 
			"                <xs:element name=\"Othr\" type=\"Max35Text\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ReferredDocumentInformation3\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tp\" type=\"ReferredDocumentType2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Nb\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RltdDt\" type=\"ISODate\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ReferredDocumentType1Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Cd\" type=\"DocumentType5Code\"/>\r\n" + 
			"                <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ReferredDocumentType2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"CdOrPrtry\" type=\"ReferredDocumentType1Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Issr\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"RemittanceAmount1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"DuePyblAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"DscntApldAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CdtNoteAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TaxAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"AdjstmntAmtAndRsn\" type=\"DocumentAdjustment1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RmtdAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"RemittanceInformation5\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Ustrd\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Strd\" type=\"StructuredRemittanceInformation7\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"RemittanceLocation2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RmtId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RmtLctnMtd\" type=\"RemittanceLocationMethod2Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RmtLctnElctrncAdr\" type=\"Max2048Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RmtLctnPstlAdr\" type=\"NameAndAddress10\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"RemittanceLocationMethod2Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"FAXI\"/>\r\n" + 
			"            <xs:enumeration value=\"EDIC\"/>\r\n" + 
			"            <xs:enumeration value=\"URID\"/>\r\n" + 
			"            <xs:enumeration value=\"EMAL\"/>\r\n" + 
			"            <xs:enumeration value=\"POST\"/>\r\n" + 
			"            <xs:enumeration value=\"SMSM\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"ReportEntry2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"NtryRef\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element name=\"Amt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element name=\"CdtDbtInd\" type=\"CreditDebitCode\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RvslInd\" type=\"TrueFalseIndicator\"/>\r\n" + 
			"            <xs:element name=\"Sts\" type=\"EntryStatus2Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"BookgDt\" type=\"DateAndDateTimeChoice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ValDt\" type=\"DateAndDateTimeChoice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AcctSvcrRef\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Avlbty\" type=\"CashBalanceAvailability2\"/>\r\n" + 
			"            <xs:element name=\"BkTxCd\" type=\"BankTransactionCodeStructure4\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ComssnWvrInd\" type=\"YesNoIndicator\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AddtlInfInd\" type=\"MessageIdentification2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AmtDtls\" type=\"AmountAndCurrencyExchange3\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Chrgs\" type=\"ChargesInformation6\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TechInptChanl\" type=\"TechnicalInputChannel1Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Intrst\" type=\"TransactionInterest2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"NtryDtls\" type=\"EntryDetails1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AddtlNtryInf\" type=\"Max500Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ReportingSource1Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Cd\" type=\"ExternalReportingSource1Code\"/>\r\n" + 
			"                <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ReturnReason5Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Cd\" type=\"ExternalReturnReason1Code\"/>\r\n" + 
			"                <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"ReturnReasonInformation10\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"OrgnlBkTxCd\" type=\"BankTransactionCodeStructure4\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Orgtr\" type=\"PartyIdentification32\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Rsn\" type=\"ReturnReason5Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"AddtlInf\" type=\"Max105Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"SecurityIdentification4Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"ISIN\" type=\"ISINIdentifier\"/>\r\n" + 
			"                <xs:element name=\"Prtry\" type=\"AlternateSecurityIdentification2\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"StructuredRemittanceInformation7\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"RfrdDocInf\" type=\"ReferredDocumentInformation3\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RfrdDocAmt\" type=\"RemittanceAmount1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CdtrRefInf\" type=\"CreditorReferenceInformation2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Invcr\" type=\"PartyIdentification32\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Invcee\" type=\"PartyIdentification32\"/>\r\n" + 
			"            <xs:element maxOccurs=\"3\" minOccurs=\"0\" name=\"AddtlRmtInf\" type=\"Max140Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxAmount1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Rate\" type=\"PercentageRate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TaxblBaseAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TtlAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Dtls\" type=\"TaxRecordDetails1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxAuthorisation1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Titl\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Nm\" type=\"Max140Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxCharges2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Id\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Rate\" type=\"PercentageRate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Amt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxInformation3\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Cdtr\" type=\"TaxParty1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Dbtr\" type=\"TaxParty2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AdmstnZn\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RefNb\" type=\"Max140Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Mtd\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TtlTaxblBaseAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TtlTaxAmt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Dt\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SeqNb\" type=\"Number\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Rcrd\" type=\"TaxRecord1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxParty1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TaxId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RegnId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TaxTp\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxParty2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TaxId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RegnId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TaxTp\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Authstn\" type=\"TaxAuthorisation1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxPeriod1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Yr\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tp\" type=\"TaxRecordPeriod1Code\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"FrToDt\" type=\"DatePeriodDetails\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxRecord1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tp\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Ctgy\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CtgyDtls\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"DbtrSts\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CertId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"FrmsCd\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Prd\" type=\"TaxPeriod1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TaxAmt\" type=\"TaxAmount1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AddtlInf\" type=\"Max140Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TaxRecordDetails1\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Prd\" type=\"TaxPeriod1\"/>\r\n" + 
			"            <xs:element name=\"Amt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"TaxRecordPeriod1Code\">\r\n" + 
			"        <xs:restriction base=\"xs:string\">\r\n" + 
			"            <xs:enumeration value=\"MM01\"/>\r\n" + 
			"            <xs:enumeration value=\"MM02\"/>\r\n" + 
			"            <xs:enumeration value=\"MM03\"/>\r\n" + 
			"            <xs:enumeration value=\"MM04\"/>\r\n" + 
			"            <xs:enumeration value=\"MM05\"/>\r\n" + 
			"            <xs:enumeration value=\"MM06\"/>\r\n" + 
			"            <xs:enumeration value=\"MM07\"/>\r\n" + 
			"            <xs:enumeration value=\"MM08\"/>\r\n" + 
			"            <xs:enumeration value=\"MM09\"/>\r\n" + 
			"            <xs:enumeration value=\"MM10\"/>\r\n" + 
			"            <xs:enumeration value=\"MM11\"/>\r\n" + 
			"            <xs:enumeration value=\"MM12\"/>\r\n" + 
			"            <xs:enumeration value=\"QTR1\"/>\r\n" + 
			"            <xs:enumeration value=\"QTR2\"/>\r\n" + 
			"            <xs:enumeration value=\"QTR3\"/>\r\n" + 
			"            <xs:enumeration value=\"QTR4\"/>\r\n" + 
			"            <xs:enumeration value=\"HLF1\"/>\r\n" + 
			"            <xs:enumeration value=\"HLF2\"/>\r\n" + 
			"        </xs:restriction>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:complexType name=\"TechnicalInputChannel1Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Cd\" type=\"ExternalTechnicalInputChannel1Code\"/>\r\n" + 
			"                <xs:element name=\"Prtry\" type=\"Max35Text\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TotalTransactions2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TtlNtries\" type=\"NumberAndSumOfTransactions2\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TtlCdtNtries\" type=\"NumberAndSumOfTransactions1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TtlDbtNtries\" type=\"NumberAndSumOfTransactions1\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"TtlNtriesPerBkTxCd\" type=\"TotalsPerBankTransactionCode2\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TotalsPerBankTransactionCode2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"NbOfNtries\" type=\"Max15NumericText\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Sum\" type=\"DecimalNumber\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TtlNetNtryAmt\" type=\"DecimalNumber\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CdtDbtInd\" type=\"CreditDebitCode\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"FcstInd\" type=\"TrueFalseIndicator\"/>\r\n" + 
			"            <xs:element name=\"BkTxCd\" type=\"BankTransactionCodeStructure4\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Avlbty\" type=\"CashBalanceAvailability2\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TransactionAgents2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"DbtrAgt\" type=\"BranchAndFinancialInstitutionIdentification4\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CdtrAgt\" type=\"BranchAndFinancialInstitutionIdentification4\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"IntrmyAgt1\" type=\"BranchAndFinancialInstitutionIdentification4\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"IntrmyAgt2\" type=\"BranchAndFinancialInstitutionIdentification4\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"IntrmyAgt3\" type=\"BranchAndFinancialInstitutionIdentification4\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"RcvgAgt\" type=\"BranchAndFinancialInstitutionIdentification4\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"DlvrgAgt\" type=\"BranchAndFinancialInstitutionIdentification4\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"IssgAgt\" type=\"BranchAndFinancialInstitutionIdentification4\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SttlmPlc\" type=\"BranchAndFinancialInstitutionIdentification4\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Prtry\" type=\"ProprietaryAgent2\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TransactionDates2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AccptncDtTm\" type=\"ISODateTime\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TradActvtyCtrctlSttlmDt\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TradDt\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"IntrBkSttlmDt\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"StartDt\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"EndDt\" type=\"ISODate\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TxDtTm\" type=\"ISODateTime\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Prtry\" type=\"ProprietaryDate2\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TransactionInterest2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element name=\"Amt\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"            <xs:element name=\"CdtDbtInd\" type=\"CreditDebitCode\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Tp\" type=\"InterestType1Choice\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Rate\" type=\"Rate3\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"FrToDt\" type=\"DateTimePeriodDetails\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Rsn\" type=\"Max35Text\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TransactionParty2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"InitgPty\" type=\"PartyIdentification32\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Dbtr\" type=\"PartyIdentification32\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"DbtrAcct\" type=\"CashAccount16\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"UltmtDbtr\" type=\"PartyIdentification32\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Cdtr\" type=\"PartyIdentification32\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"CdtrAcct\" type=\"CashAccount16\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"UltmtCdtr\" type=\"PartyIdentification32\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TradgPty\" type=\"PartyIdentification32\"/>\r\n" + 
			"            <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Prtry\" type=\"ProprietaryParty2\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TransactionPrice2Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"DealPric\" type=\"ActiveOrHistoricCurrencyAndAmount\"/>\r\n" + 
			"                <xs:element maxOccurs=\"unbounded\" minOccurs=\"1\" name=\"Prtry\" type=\"ProprietaryPrice2\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TransactionQuantities1Choice\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:choice>\r\n" + 
			"                <xs:element name=\"Qty\" type=\"FinancialInstrumentQuantityChoice\"/>\r\n" + 
			"                <xs:element name=\"Prtry\" type=\"ProprietaryQuantity1\"/>\r\n" + 
			"            </xs:choice>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:complexType name=\"TransactionReferences2\">\r\n" + 
			"        <xs:sequence>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"MsgId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"AcctSvcrRef\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"PmtInfId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"InstrId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"EndToEndId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TxId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"MndtId\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ChqNb\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ClrSysRef\" type=\"Max35Text\"/>\r\n" + 
			"            <xs:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Prtry\" type=\"ProprietaryReference1\"/>\r\n" + 
			"        </xs:sequence>\r\n" + 
			"    </xs:complexType>\r\n" + 
			"    <xs:simpleType name=\"TrueFalseIndicator\">\r\n" + 
			"        <xs:restriction base=\"xs:boolean\"/>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"    <xs:simpleType name=\"YesNoIndicator\">\r\n" + 
			"        <xs:restriction base=\"xs:boolean\"/>\r\n" + 
			"    </xs:simpleType>\r\n" + 
			"</xs:schema>\r\n" + 
			"";

	private String xsdSchemaV02ISO = V02part1 + V02part2 + V02part3 + V02part4;
	
	public SepaXmlUnmarshallerCamt053V02() {
	}

	@Override
	public Object unmarshal(String xmlContent) throws JAXBException, SAXException {
		Object sepaStmt = unmarshal(xsdSchemaV02ISO, xmlContent, CADocument.class);
		
		return sepaStmt;
	}

}
