/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2014 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.04 at 12:27:27 PM MEZ 
//


package com.lp.server.schema.opentrans.cc.dispatchnotification;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for _XML_XML_DISPATCHNOTIFICATION_ITEM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_XML_XML_DISPATCHNOTIFICATION_ITEM">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CC_ROW_ID" minOccurs="0"/>
 *         &lt;element ref="{}LINE_ITEM_ID"/>
 *         &lt;element ref="{}ARTICLE_ID"/>
 *         &lt;element ref="{}QUANTITY"/>
 *         &lt;element ref="{}CC_PRICE" minOccurs="0"/>
 *         &lt;element ref="{}ORDER_UNIT" minOccurs="0"/>
 *         &lt;element ref="{}CC_ORDER_UNIT"/>
 *         &lt;element ref="{}DELIVERY_COMPLETED" minOccurs="0"/>
 *         &lt;element ref="{}DELIVERY_DATE" minOccurs="0"/>
 *         &lt;element ref="{}ORDER_REFERENCE"/>
 *         &lt;element ref="{}SUPPLIER_ORDER_REFERENCE" minOccurs="0"/>
 *         &lt;element ref="{}LOGISTIC_DETAILS" minOccurs="0"/>
 *         &lt;element ref="{}PACKAGE_INFO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}REMARK" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}CC_CUSTOMS_INFO" minOccurs="0"/>
 *         &lt;element ref="{}CC_ORIGIN_COUNTRY" minOccurs="0"/>
 *         &lt;element ref="{}CC_SERIAL_NUMBER" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}ComIbmMrmNamespaceInfo77"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_XML_XML_DISPATCHNOTIFICATION_ITEM", propOrder = {
    "ccrowid",
    "lineitemid",
    "articleid",
    "quantity",
    "ccprice",
    "orderunit",
    "ccorderunit",
    "deliverycompleted",
    "deliverydate",
    "orderreference",
    "supplierorderreference",
    "logisticdetails",
    "packageinfo",
    "remark",
    "cccustomsinfo",
    "ccorigincountry",
    "ccserialnumber"
})
public class XMLXMLDISPATCHNOTIFICATIONITEM {

    @XmlElement(name = "CC_ROW_ID")
    protected String ccrowid;
    @XmlElement(name = "LINE_ITEM_ID", required = true)
    protected String lineitemid;
    @XmlElement(name = "ARTICLE_ID", required = true)
    protected XMLXMLARTICLEID articleid;
    @XmlElement(name = "QUANTITY", required = true)
    protected BigDecimal quantity;
    @XmlElement(name = "CC_PRICE")
    protected BigDecimal ccprice;
    @XmlElement(name = "ORDER_UNIT")
    protected String orderunit;
    @XmlElement(name = "CC_ORDER_UNIT", required = true)
    protected String ccorderunit;
    @XmlElement(name = "DELIVERY_COMPLETED")
    protected String deliverycompleted;
    @XmlElement(name = "DELIVERY_DATE")
    protected XMLXMLDELIVERYDATE deliverydate;
    @XmlElement(name = "ORDER_REFERENCE", required = true)
    protected XMLXMLORDERREFERENCE orderreference;
    @XmlElement(name = "SUPPLIER_ORDER_REFERENCE")
    protected XMLXMLSUPPLIERORDERREFERENCE supplierorderreference;
    @XmlElement(name = "LOGISTIC_DETAILS")
    protected XMLXMLLOGISTICDETAILS logisticdetails;
    @XmlElement(name = "PACKAGE_INFO")
    protected List<XMLXMLPACKAGEINFO> packageinfo;
    @XmlElement(name = "REMARK")
    protected List<XMLXMLREMARK> remark;
    @XmlElement(name = "CC_CUSTOMS_INFO")
    protected XMLXMLCCCUSTOMSINFO cccustomsinfo;
    @XmlElement(name = "CC_ORIGIN_COUNTRY")
    protected String ccorigincountry;
    @XmlElement(name = "CC_SERIAL_NUMBER")
    protected String ccserialnumber;
    @XmlAttribute(name = "xsi_schemaLocation")
    protected String xsiSchemaLocation;
    @XmlAttribute(name = "xmlns_xsd")
    protected String xmlnsXsd;

    /**
     * Gets the value of the ccrowid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCROWID() {
        return ccrowid;
    }

    /**
     * Sets the value of the ccrowid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCROWID(String value) {
        this.ccrowid = value;
    }

    /**
     * Gets the value of the lineitemid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLINEITEMID() {
        return lineitemid;
    }

    /**
     * Sets the value of the lineitemid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLINEITEMID(String value) {
        this.lineitemid = value;
    }

    /**
     * Gets the value of the articleid property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLARTICLEID }
     *     
     */
    public XMLXMLARTICLEID getARTICLEID() {
        return articleid;
    }

    /**
     * Sets the value of the articleid property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLARTICLEID }
     *     
     */
    public void setARTICLEID(XMLXMLARTICLEID value) {
        this.articleid = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQUANTITY() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQUANTITY(BigDecimal value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the ccprice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCCPRICE() {
        return ccprice;
    }

    /**
     * Sets the value of the ccprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCCPRICE(BigDecimal value) {
        this.ccprice = value;
    }

    /**
     * Gets the value of the orderunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDERUNIT() {
        return orderunit;
    }

    /**
     * Sets the value of the orderunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDERUNIT(String value) {
        this.orderunit = value;
    }

    /**
     * Gets the value of the ccorderunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCORDERUNIT() {
        return ccorderunit;
    }

    /**
     * Sets the value of the ccorderunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCORDERUNIT(String value) {
        this.ccorderunit = value;
    }

    /**
     * Gets the value of the deliverycompleted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDELIVERYCOMPLETED() {
        return deliverycompleted;
    }

    /**
     * Sets the value of the deliverycompleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDELIVERYCOMPLETED(String value) {
        this.deliverycompleted = value;
    }

    /**
     * Gets the value of the deliverydate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLDELIVERYDATE }
     *     
     */
    public XMLXMLDELIVERYDATE getDELIVERYDATE() {
        return deliverydate;
    }

    /**
     * Sets the value of the deliverydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLDELIVERYDATE }
     *     
     */
    public void setDELIVERYDATE(XMLXMLDELIVERYDATE value) {
        this.deliverydate = value;
    }

    /**
     * Gets the value of the orderreference property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLORDERREFERENCE }
     *     
     */
    public XMLXMLORDERREFERENCE getORDERREFERENCE() {
        return orderreference;
    }

    /**
     * Sets the value of the orderreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLORDERREFERENCE }
     *     
     */
    public void setORDERREFERENCE(XMLXMLORDERREFERENCE value) {
        this.orderreference = value;
    }

    /**
     * Gets the value of the supplierorderreference property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLSUPPLIERORDERREFERENCE }
     *     
     */
    public XMLXMLSUPPLIERORDERREFERENCE getSUPPLIERORDERREFERENCE() {
        return supplierorderreference;
    }

    /**
     * Sets the value of the supplierorderreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLSUPPLIERORDERREFERENCE }
     *     
     */
    public void setSUPPLIERORDERREFERENCE(XMLXMLSUPPLIERORDERREFERENCE value) {
        this.supplierorderreference = value;
    }

    /**
     * Gets the value of the logisticdetails property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLLOGISTICDETAILS }
     *     
     */
    public XMLXMLLOGISTICDETAILS getLOGISTICDETAILS() {
        return logisticdetails;
    }

    /**
     * Sets the value of the logisticdetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLLOGISTICDETAILS }
     *     
     */
    public void setLOGISTICDETAILS(XMLXMLLOGISTICDETAILS value) {
        this.logisticdetails = value;
    }

    /**
     * Gets the value of the packageinfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packageinfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPACKAGEINFO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLXMLPACKAGEINFO }
     * 
     * 
     */
    public List<XMLXMLPACKAGEINFO> getPACKAGEINFO() {
        if (packageinfo == null) {
            packageinfo = new ArrayList<XMLXMLPACKAGEINFO>();
        }
        return this.packageinfo;
    }

    /**
     * Gets the value of the remark property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remark property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getREMARK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLXMLREMARK }
     * 
     * 
     */
    public List<XMLXMLREMARK> getREMARK() {
        if (remark == null) {
            remark = new ArrayList<XMLXMLREMARK>();
        }
        return this.remark;
    }

    /**
     * Gets the value of the cccustomsinfo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLCCCUSTOMSINFO }
     *     
     */
    public XMLXMLCCCUSTOMSINFO getCCCUSTOMSINFO() {
        return cccustomsinfo;
    }

    /**
     * Sets the value of the cccustomsinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLCCCUSTOMSINFO }
     *     
     */
    public void setCCCUSTOMSINFO(XMLXMLCCCUSTOMSINFO value) {
        this.cccustomsinfo = value;
    }

    /**
     * Gets the value of the ccorigincountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCORIGINCOUNTRY() {
        return ccorigincountry;
    }

    /**
     * Sets the value of the ccorigincountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCORIGINCOUNTRY(String value) {
        this.ccorigincountry = value;
    }

    /**
     * Gets the value of the ccserialnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCSERIALNUMBER() {
        return ccserialnumber;
    }

    /**
     * Sets the value of the ccserialnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCSERIALNUMBER(String value) {
        this.ccserialnumber = value;
    }

    /**
     * Gets the value of the xsiSchemaLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsiSchemaLocation() {
        if (xsiSchemaLocation == null) {
            return "openTRANS_DISPATCHNOTIFICATION_1_0.mxsd";
        } else {
            return xsiSchemaLocation;
        }
    }

    /**
     * Sets the value of the xsiSchemaLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsiSchemaLocation(String value) {
        this.xsiSchemaLocation = value;
    }

    /**
     * Gets the value of the xmlnsXsd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsXsd() {
        if (xmlnsXsd == null) {
            return "http://www.w3.org/2001/XMLSchema";
        } else {
            return xmlnsXsd;
        }
    }

    /**
     * Sets the value of the xmlnsXsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsXsd(String value) {
        this.xmlnsXsd = value;
    }

}
