/*******************************************************************************
 * HELIUM V, Open Source ERP software for sustained success
 * at small and medium-sized enterprises.
 * Copyright (C) 2004 - 2015 HELIUM V IT-Solutions GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published 
 * by the Free Software Foundation, either version 3 of theLicense, or 
 * (at your option) any later version.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, 
 * the terms of the AGPL are supplemented with the following terms:
 * 
 * "HELIUM V" and "HELIUM 5" are registered trademarks of 
 * HELIUM V IT-Solutions GmbH. The licensing of the program under the 
 * AGPL does not imply a trademark license. Therefore any rights, title and
 * interest in our trademarks remain entirely with us. If you want to propagate
 * modified versions of the Program under the name "HELIUM V" or "HELIUM 5",
 * you may only do so if you have a written permission by HELIUM V IT-Solutions 
 * GmbH (to acquire a permission please contact HELIUM V IT-Solutions
 * at trademark@heliumv.com).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact: developers@heliumv.com
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.04 at 12:27:27 PM MEZ 
//


package com.lp.server.schema.opentrans.cc.dispatchnotification;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for _XML_XML_ORDER_ITEM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_XML_XML_ORDER_ITEM">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CC_ROW_ID" minOccurs="0"/>
 *         &lt;element ref="{}LINE_ITEM_ID"/>
 *         &lt;element ref="{}ARTICLE_ID"/>
 *         &lt;element ref="{}QUANTITY"/>
 *         &lt;element ref="{}ORDER_UNIT" minOccurs="0"/>
 *         &lt;element ref="{}CC_ORDER_UNIT"/>
 *         &lt;element ref="{}ARTICLE_PRICE" minOccurs="0"/>
 *         &lt;element ref="{}DELIVERY_DATE" minOccurs="0"/>
 *         &lt;element ref="{}SHIPMENT_PARTIES" minOccurs="0"/>
 *         &lt;element ref="{}ACCOUNTING_INFO" minOccurs="0"/>
 *         &lt;element ref="{}REMARK" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}CC_CUSTOMS_INFO" minOccurs="0"/>
 *         &lt;element ref="{}CC_ORIGIN_COUNTRY" minOccurs="0"/>
 *         &lt;element ref="{}CC_BUYER_EMAIL" minOccurs="0"/>
 *         &lt;element ref="{}CC_DISPONENT_EMAIL" minOccurs="0"/>
 *         &lt;element ref="{}CC_DELIVERY_NOTIF_DEACTIVATION" minOccurs="0"/>
 *         &lt;element ref="{}CC_CREDITNOTE_DEACTIVATION" minOccurs="0"/>
 *         &lt;element ref="{}CC_ORDER_SPLIT_ENABLED" minOccurs="0"/>
 *         &lt;element ref="{}CC_DRAWING_NR" minOccurs="0"/>
 *         &lt;element ref="{}CC_DRAWING_NR_DATE" minOccurs="0"/>
 *         &lt;element ref="{}CC_INDEX_NR" minOccurs="0"/>
 *         &lt;element ref="{}CC_PRICECHG_ALLOW" minOccurs="0"/>
 *         &lt;element ref="{}CC_RECIPIENT_NR" minOccurs="0"/>
 *         &lt;element ref="{}CC_PARENT_POS_ID" minOccurs="0"/>
 *         &lt;element ref="{}CC_DELIVERY_COMPLETED" minOccurs="0"/>
 *         &lt;element ref="{}CC_COMPLAINT_ENABLED" minOccurs="0"/>
 *         &lt;element ref="{}CC_ORDER_PROV" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}CC_BOM_ITEM_LIST"/>
 *         &lt;element ref="{}ORDER_POS_TEXT_LIST"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}ComIbmMrmNamespaceInfo154"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_XML_XML_ORDER_ITEM", propOrder = {
    "ccrowid",
    "lineitemid",
    "articleid",
    "quantity",
    "orderunit",
    "ccorderunit",
    "articleprice",
    "deliverydate",
    "shipmentparties",
    "accountinginfo",
    "remark",
    "cccustomsinfo",
    "ccorigincountry",
    "ccbuyeremail",
    "ccdisponentemail",
    "ccdeliverynotifdeactivation",
    "cccreditnotedeactivation",
    "ccordersplitenabled",
    "ccdrawingnr",
    "ccdrawingnrdate",
    "ccindexnr",
    "ccpricechgallow",
    "ccrecipientnr",
    "ccparentposid",
    "ccdeliverycompleted",
    "cccomplaintenabled",
    "ccorderprov",
    "ccbomitemlist",
    "orderpostextlist"
})
public class XMLXMLORDERITEM {

    @XmlElement(name = "CC_ROW_ID")
    protected String ccrowid;
    @XmlElement(name = "LINE_ITEM_ID", required = true)
    protected String lineitemid;
    @XmlElement(name = "ARTICLE_ID", required = true)
    protected XMLXMLARTICLEID articleid;
    @XmlElement(name = "QUANTITY", required = true)
    protected BigDecimal quantity;
    @XmlElement(name = "ORDER_UNIT")
    protected String orderunit;
    @XmlElement(name = "CC_ORDER_UNIT", required = true)
    protected String ccorderunit;
    @XmlElement(name = "ARTICLE_PRICE")
    protected XMLXMLARTICLEPRICE articleprice;
    @XmlElement(name = "DELIVERY_DATE")
    protected XMLXMLDELIVERYDATE deliverydate;
    @XmlElement(name = "SHIPMENT_PARTIES")
    protected XMLXMLSHIPMENTPARTIES shipmentparties;
    @XmlElement(name = "ACCOUNTING_INFO")
    protected XMLXMLACCOUNTINGINFO accountinginfo;
    @XmlElement(name = "REMARK")
    protected List<XMLXMLREMARK> remark;
    @XmlElement(name = "CC_CUSTOMS_INFO")
    protected XMLXMLCCCUSTOMSINFO cccustomsinfo;
    @XmlElement(name = "CC_ORIGIN_COUNTRY")
    protected String ccorigincountry;
    @XmlElement(name = "CC_BUYER_EMAIL")
    protected String ccbuyeremail;
    @XmlElement(name = "CC_DISPONENT_EMAIL")
    protected String ccdisponentemail;
    @XmlElement(name = "CC_DELIVERY_NOTIF_DEACTIVATION")
    protected String ccdeliverynotifdeactivation;
    @XmlElement(name = "CC_CREDITNOTE_DEACTIVATION")
    protected String cccreditnotedeactivation;
    @XmlElement(name = "CC_ORDER_SPLIT_ENABLED")
    protected BigInteger ccordersplitenabled;
    @XmlElement(name = "CC_DRAWING_NR")
    protected String ccdrawingnr;
    @XmlElement(name = "CC_DRAWING_NR_DATE")
    protected String ccdrawingnrdate;
    @XmlElement(name = "CC_INDEX_NR")
    protected String ccindexnr;
    @XmlElement(name = "CC_PRICECHG_ALLOW")
    protected String ccpricechgallow;
    @XmlElement(name = "CC_RECIPIENT_NR")
    protected String ccrecipientnr;
    @XmlElement(name = "CC_PARENT_POS_ID")
    protected String ccparentposid;
    @XmlElement(name = "CC_DELIVERY_COMPLETED")
    protected String ccdeliverycompleted;
    @XmlElement(name = "CC_COMPLAINT_ENABLED")
    protected BigInteger cccomplaintenabled;
    @XmlElement(name = "CC_ORDER_PROV")
    protected List<XMLXMLCCORDERPROV> ccorderprov;
    @XmlElement(name = "CC_BOM_ITEM_LIST", required = true)
    protected XMLXMLCCBOMITEMLIST ccbomitemlist;
    @XmlElement(name = "ORDER_POS_TEXT_LIST", required = true)
    protected XMLXMLORDERPOSTEXTLIST orderpostextlist;
    @XmlAttribute(name = "xsi_schemaLocation")
    protected String xsiSchemaLocation;
    @XmlAttribute(name = "xmlns_xsd")
    protected String xmlnsXsd;

    /**
     * Gets the value of the ccrowid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCROWID() {
        return ccrowid;
    }

    /**
     * Sets the value of the ccrowid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCROWID(String value) {
        this.ccrowid = value;
    }

    /**
     * Gets the value of the lineitemid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLINEITEMID() {
        return lineitemid;
    }

    /**
     * Sets the value of the lineitemid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLINEITEMID(String value) {
        this.lineitemid = value;
    }

    /**
     * Gets the value of the articleid property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLARTICLEID }
     *     
     */
    public XMLXMLARTICLEID getARTICLEID() {
        return articleid;
    }

    /**
     * Sets the value of the articleid property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLARTICLEID }
     *     
     */
    public void setARTICLEID(XMLXMLARTICLEID value) {
        this.articleid = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQUANTITY() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQUANTITY(BigDecimal value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the orderunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDERUNIT() {
        return orderunit;
    }

    /**
     * Sets the value of the orderunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDERUNIT(String value) {
        this.orderunit = value;
    }

    /**
     * Gets the value of the ccorderunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCORDERUNIT() {
        return ccorderunit;
    }

    /**
     * Sets the value of the ccorderunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCORDERUNIT(String value) {
        this.ccorderunit = value;
    }

    /**
     * Gets the value of the articleprice property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLARTICLEPRICE }
     *     
     */
    public XMLXMLARTICLEPRICE getARTICLEPRICE() {
        return articleprice;
    }

    /**
     * Sets the value of the articleprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLARTICLEPRICE }
     *     
     */
    public void setARTICLEPRICE(XMLXMLARTICLEPRICE value) {
        this.articleprice = value;
    }

    /**
     * Gets the value of the deliverydate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLDELIVERYDATE }
     *     
     */
    public XMLXMLDELIVERYDATE getDELIVERYDATE() {
        return deliverydate;
    }

    /**
     * Sets the value of the deliverydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLDELIVERYDATE }
     *     
     */
    public void setDELIVERYDATE(XMLXMLDELIVERYDATE value) {
        this.deliverydate = value;
    }

    /**
     * Gets the value of the shipmentparties property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLSHIPMENTPARTIES }
     *     
     */
    public XMLXMLSHIPMENTPARTIES getSHIPMENTPARTIES() {
        return shipmentparties;
    }

    /**
     * Sets the value of the shipmentparties property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLSHIPMENTPARTIES }
     *     
     */
    public void setSHIPMENTPARTIES(XMLXMLSHIPMENTPARTIES value) {
        this.shipmentparties = value;
    }

    /**
     * Gets the value of the accountinginfo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLACCOUNTINGINFO }
     *     
     */
    public XMLXMLACCOUNTINGINFO getACCOUNTINGINFO() {
        return accountinginfo;
    }

    /**
     * Sets the value of the accountinginfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLACCOUNTINGINFO }
     *     
     */
    public void setACCOUNTINGINFO(XMLXMLACCOUNTINGINFO value) {
        this.accountinginfo = value;
    }

    /**
     * Gets the value of the remark property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remark property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getREMARK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLXMLREMARK }
     * 
     * 
     */
    public List<XMLXMLREMARK> getREMARK() {
        if (remark == null) {
            remark = new ArrayList<XMLXMLREMARK>();
        }
        return this.remark;
    }

    /**
     * Gets the value of the cccustomsinfo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLCCCUSTOMSINFO }
     *     
     */
    public XMLXMLCCCUSTOMSINFO getCCCUSTOMSINFO() {
        return cccustomsinfo;
    }

    /**
     * Sets the value of the cccustomsinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLCCCUSTOMSINFO }
     *     
     */
    public void setCCCUSTOMSINFO(XMLXMLCCCUSTOMSINFO value) {
        this.cccustomsinfo = value;
    }

    /**
     * Gets the value of the ccorigincountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCORIGINCOUNTRY() {
        return ccorigincountry;
    }

    /**
     * Sets the value of the ccorigincountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCORIGINCOUNTRY(String value) {
        this.ccorigincountry = value;
    }

    /**
     * Gets the value of the ccbuyeremail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCBUYEREMAIL() {
        return ccbuyeremail;
    }

    /**
     * Sets the value of the ccbuyeremail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCBUYEREMAIL(String value) {
        this.ccbuyeremail = value;
    }

    /**
     * Gets the value of the ccdisponentemail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCDISPONENTEMAIL() {
        return ccdisponentemail;
    }

    /**
     * Sets the value of the ccdisponentemail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCDISPONENTEMAIL(String value) {
        this.ccdisponentemail = value;
    }

    /**
     * Gets the value of the ccdeliverynotifdeactivation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCDELIVERYNOTIFDEACTIVATION() {
        return ccdeliverynotifdeactivation;
    }

    /**
     * Sets the value of the ccdeliverynotifdeactivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCDELIVERYNOTIFDEACTIVATION(String value) {
        this.ccdeliverynotifdeactivation = value;
    }

    /**
     * Gets the value of the cccreditnotedeactivation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCCREDITNOTEDEACTIVATION() {
        return cccreditnotedeactivation;
    }

    /**
     * Sets the value of the cccreditnotedeactivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCCREDITNOTEDEACTIVATION(String value) {
        this.cccreditnotedeactivation = value;
    }

    /**
     * Gets the value of the ccordersplitenabled property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCCORDERSPLITENABLED() {
        return ccordersplitenabled;
    }

    /**
     * Sets the value of the ccordersplitenabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCCORDERSPLITENABLED(BigInteger value) {
        this.ccordersplitenabled = value;
    }

    /**
     * Gets the value of the ccdrawingnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCDRAWINGNR() {
        return ccdrawingnr;
    }

    /**
     * Sets the value of the ccdrawingnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCDRAWINGNR(String value) {
        this.ccdrawingnr = value;
    }

    /**
     * Gets the value of the ccdrawingnrdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCDRAWINGNRDATE() {
        return ccdrawingnrdate;
    }

    /**
     * Sets the value of the ccdrawingnrdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCDRAWINGNRDATE(String value) {
        this.ccdrawingnrdate = value;
    }

    /**
     * Gets the value of the ccindexnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCINDEXNR() {
        return ccindexnr;
    }

    /**
     * Sets the value of the ccindexnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCINDEXNR(String value) {
        this.ccindexnr = value;
    }

    /**
     * Gets the value of the ccpricechgallow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCPRICECHGALLOW() {
        return ccpricechgallow;
    }

    /**
     * Sets the value of the ccpricechgallow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCPRICECHGALLOW(String value) {
        this.ccpricechgallow = value;
    }

    /**
     * Gets the value of the ccrecipientnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCRECIPIENTNR() {
        return ccrecipientnr;
    }

    /**
     * Sets the value of the ccrecipientnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCRECIPIENTNR(String value) {
        this.ccrecipientnr = value;
    }

    /**
     * Gets the value of the ccparentposid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCPARENTPOSID() {
        return ccparentposid;
    }

    /**
     * Sets the value of the ccparentposid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCPARENTPOSID(String value) {
        this.ccparentposid = value;
    }

    /**
     * Gets the value of the ccdeliverycompleted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCDELIVERYCOMPLETED() {
        return ccdeliverycompleted;
    }

    /**
     * Sets the value of the ccdeliverycompleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCDELIVERYCOMPLETED(String value) {
        this.ccdeliverycompleted = value;
    }

    /**
     * Gets the value of the cccomplaintenabled property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCCCOMPLAINTENABLED() {
        return cccomplaintenabled;
    }

    /**
     * Sets the value of the cccomplaintenabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCCCOMPLAINTENABLED(BigInteger value) {
        this.cccomplaintenabled = value;
    }

    /**
     * Gets the value of the ccorderprov property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ccorderprov property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCCORDERPROV().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLXMLCCORDERPROV }
     * 
     * 
     */
    public List<XMLXMLCCORDERPROV> getCCORDERPROV() {
        if (ccorderprov == null) {
            ccorderprov = new ArrayList<XMLXMLCCORDERPROV>();
        }
        return this.ccorderprov;
    }

    /**
     * Gets the value of the ccbomitemlist property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLCCBOMITEMLIST }
     *     
     */
    public XMLXMLCCBOMITEMLIST getCCBOMITEMLIST() {
        return ccbomitemlist;
    }

    /**
     * Sets the value of the ccbomitemlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLCCBOMITEMLIST }
     *     
     */
    public void setCCBOMITEMLIST(XMLXMLCCBOMITEMLIST value) {
        this.ccbomitemlist = value;
    }

    /**
     * Gets the value of the orderpostextlist property.
     * 
     * @return
     *     possible object is
     *     {@link XMLXMLORDERPOSTEXTLIST }
     *     
     */
    public XMLXMLORDERPOSTEXTLIST getORDERPOSTEXTLIST() {
        return orderpostextlist;
    }

    /**
     * Sets the value of the orderpostextlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLXMLORDERPOSTEXTLIST }
     *     
     */
    public void setORDERPOSTEXTLIST(XMLXMLORDERPOSTEXTLIST value) {
        this.orderpostextlist = value;
    }

    /**
     * Gets the value of the xsiSchemaLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsiSchemaLocation() {
        if (xsiSchemaLocation == null) {
            return "openbase_1_0.mxsd";
        } else {
            return xsiSchemaLocation;
        }
    }

    /**
     * Sets the value of the xsiSchemaLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsiSchemaLocation(String value) {
        this.xsiSchemaLocation = value;
    }

    /**
     * Gets the value of the xmlnsXsd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsXsd() {
        if (xmlnsXsd == null) {
            return "http://www.w3.org/2001/XMLSchema";
        } else {
            return xmlnsXsd;
        }
    }

    /**
     * Sets the value of the xmlnsXsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsXsd(String value) {
        this.xmlnsXsd = value;
    }

}
